CONFIG_PSRAM_HEAP_SIZE=0x40000

CONFIG_ARCS_AP_CORE=y

CONFIG_LISA_WIFI=y
CONFIG_WIFI_LWIP_DIFF_CORE=y
CONFIG_LOG_BACKEND_IPC_WRITER=y
CONFIG_CONSOLE_UART_NAME="uart1"
CONFIG_PRINTF_LOG_REDIRECT=y

# 双核WiFi要手动选择当前核心运行WIFI还是LWIP
CONFIG_WIFI=y
