/**
 ****************************************************************************************
 *
 * Don't modify this file. It is automatically generated by a script.
 *
 * Author: KeHuatao
 *
 * Copyright (C) ListenAI 2025
 *
 ****************************************************************************************
 */
#include <stdio.h>
#include <stdint.h>
#include <string.h>
#include <lwip/opt.h>
#include <lwip/pbuf.h>
#include <lwip/netif.h>
#include "ls_err.h"
#include "ls_wifi_type.h"
#include "net_al.h"
#include "ipc_master.h"
#include "mrpc.h"
#include "mrpc_server.h"
#include "mrpc_s2m_test_api_msg.h"

void mrpc_s2m_echo_req(void *msg, struct mrpc_resp_msg *resp_msg)
{
    mrpc_s2m_echo_req_req_t *req;
    mrpc_s2m_echo_req_resp_t *resp;

    req = (mrpc_s2m_echo_req_req_t*)msg;
    resp = (mrpc_s2m_echo_req_resp_t*)resp_msg;
    resp_msg->len = sizeof(mrpc_s2m_echo_req_resp_t);
    resp_msg->status = s2m_echo_req(req->mrpc_ep, &req->echo_req, &resp->echo_resp);
}


mrpc_msg_handler_t mrpc_msg_s2m_test_handlers[] =
{
    mrpc_s2m_echo_req,  /*MRPC_MSG_ID_S2M_ECHO_REQ*/
    NULL
};