/**
 ****************************************************************************************
 *
 * Don't modify this file. It is automatically generated by a script.
 *
 * Author: KeHuatao
 *
 * Copyright (C) ListenAI 2025
 *
 ****************************************************************************************
 */
#include <stdint.h>
#include <string.h>
#include "ls_err.h"
#include "ls_wifi_type.h"
#include "ipc_msg.h"
#include "ipc_slave.h"
#include "mrpc.h"
#include "mrpc_client.h"
#include "mrpc_s2m_test_api_msg.h"
#include "mrpc_s2m_test_api_server.h"

ls_err_t s2m_echo_req(struct ipc_ep * mrpc_ep, struct cfg_ipc_echo * echo_req, struct cfg_ipc_echo_resp * echo_resp)
{
    mrpc_s2m_echo_req_req_t req;
    mrpc_s2m_echo_req_resp_t resp;

    if (sizeof(mrpc_s2m_echo_req_req_t) > IPC_MSG_BUFFER_SIZE)
        return LS_FAIL;

    req.hdr.id = MRPC_MSG_ID_S2M_ECHO_REQ;
    req.mrpc_ep = mrpc_ep;
    req.echo_req = *echo_req;
    if (mrpc_msg_send_from(mrpc_ep, &req, sizeof(mrpc_s2m_echo_req_req_t), &resp))
        return LS_FAIL;
    *echo_resp = resp.echo_resp;

    return resp.hdr.status;
}

