#ifndef _VIDEO_CONFIG_H_
#define _VIDEO_CONFIG_H_

#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <stdbool.h>


/*********************** MALLOC ***********************************/
#define MALLOC_FROM_ADDR_ENABLE     1

#if MALLOC_FROM_ADDR_ENABLE
#define MALLOC_ADDR                 0x28000000
#define MALLOC_SIZE                 (4*1024*1024)
#else       // malloc form heap
#define MALLOC_ADDR_ALIGN_BYTE      4   // __dtsibute__ ((aligned(4)))
#define MALLOC_SIZE                 (256*1024)
#endif


/*********************** CACHE ***********************************/
#define DCACHE_ENABLE               0
#define ICACHE_ENABLE               0


/*********************** LOG ***********************************/
#define UART_ENABLE                 1
#define SEGGER_RTT_ENABLE           1

#if (UART_ENABLE && SEGGER_RTT_ENABLE)
#include "log_print.h"
#include "SEGGER_RTT.h"
#define VIDEO_LOG(format, ...)   do { \
        CLOG(format, ##__VA_ARGS__); \
        SEGGER_RTT_printf(0, format, ##__VA_ARGS__); \
    } while(0)
#elif UART_ENABLE
#include "log_print.h"
#define VIDEO_LOG(format, ...)   CLOG(format, ##__VA_ARGS__)
#elif SEGGER_RTT_ENABLE
#include "SEGGER_RTT.h"
#define VIDEO_LOG(format, ...)   SEGGER_RTT_printf(0, format, ##__VA_ARGS__)
#else
#define VIDEO_LOG(format, ...)
#endif


/*********************** DELAY ***********************************/
#include "systick.h"
#if  (IC_BOARD==0)  // FPGA
#define DELAY_US(_dat)  SysTick_Delay_Us((_dat) / 24)
#define DELAY_MS(_dat)  SysTick_Delay_Us((_dat) * 1000 / 24)
#else    // SOC
#define DELAY_US(_dat)  SysTick_Delay_Us(_dat)
#define DELAY_MS(_dat)  SysTick_Delay_Ms(_dat)
#endif


/*********************** SW_I2C ***********************************/
#define QSPI_IN_I2C_INDEX           0
#define DVP_I2C_INDEX               1


/*********************** CAMERA ***********************************/
#define CONFIG_OV5640_SUPPORT       1
#define CONFIG_OV9655_SUPPORT       0
#define CONFIG_GC0308_SUPPORT       0
#define CONFIG_GC0328_SUPPORT       0
#define CONFIG_GC0310_SUPPORT       0
#define CONFIG_GC032A_SUPPORT       0
#define CONFIG_BF3901_SUPPORT       0
#define CONFIG_SC030IOT_SUPPORT     0


/*********************** LCD ***********************************/
#define CONFIG_ST7789_SUPPORT       0
#define CONFIG_SPD2010_SUPPORT      0
#define CONFIG_AXS15231B_SUPPORT    1


/*********************** PIN ***********************************/
#include "IOMuxManager.h"
#include "pin_str.h"

#define ARCSD_SOC_BOARD_PIN         0x1
#define ARCSD_SCAN_PEN_BOARD_PIN    0x2
#define ARCSD_FPGA_ECO_BOARD_PIN    0x3

#define CONFIG_BOARD_PIN            ARCSD_SOC_BOARD_PIN

#if (CONFIG_BOARD_PIN == ARCSD_FPGA_ECO_BOARD_PIN)
#define PIN_QSPI_IN_MCLK        {CSK_IOMUX_PAD_A, 26, CSK_IOMUX_FUNC_ALTER29, CSK_IOMUX_FUNC_DEFAULT}
#define PIN_QSPI_IN_PCLK        {CSK_IOMUX_PAD_B,  1, CSK_IOMUX_FUNC_ALTER29, CSK_IOMUX_FUNC_DEFAULT}
#define PIN_QSPI_IN_D0          {CSK_IOMUX_PAD_A, 29, CSK_IOMUX_FUNC_ALTER29, CSK_IOMUX_FUNC_DEFAULT}
#define PIN_QSPI_IN_D1          {CSK_IOMUX_PAD_A, 28, CSK_IOMUX_FUNC_ALTER29, CSK_IOMUX_FUNC_DEFAULT}
#define PIN_QSPI_IN_D2          {CSK_IOMUX_PAD_A, 31, CSK_IOMUX_FUNC_ALTER29, CSK_IOMUX_FUNC_DEFAULT}
#define PIN_QSPI_IN_D3          {CSK_IOMUX_PAD_B,  0, CSK_IOMUX_FUNC_ALTER29, CSK_IOMUX_FUNC_DEFAULT}
#define PIN_QSPI_IN_PWDN        {CSK_IOMUX_PAD_A, 18, PIN_PAD_NULL, CSK_IOMUX_FUNC_DEFAULT}
#define PIN_QSPI_IN_SCL         {CSK_IOMUX_PAD_A,  4, PIN_PAD_NULL, CSK_IOMUX_FUNC_DEFAULT}
#define PIN_QSPI_IN_SDA         {CSK_IOMUX_PAD_A,  5, PIN_PAD_NULL, CSK_IOMUX_FUNC_DEFAULT}

#define PIN_QSPI_OUT_CS         {CSK_IOMUX_PAD_B,  5, PIN_PAD_NULL, CSK_IOMUX_FUNC_DEFAULT}
#define PIN_QSPI_OUT_CLK        {CSK_IOMUX_PAD_B,  3, CSK_IOMUX_FUNC_ALTER30, CSK_IOMUX_FUNC_DEFAULT}
#define PIN_QSPI_OUT_D0         {CSK_IOMUX_PAD_B,  7, CSK_IOMUX_FUNC_ALTER30, CSK_IOMUX_FUNC_DEFAULT}
#define PIN_QSPI_OUT_D1         {CSK_IOMUX_PAD_B,  6, CSK_IOMUX_FUNC_ALTER30, CSK_IOMUX_FUNC_DEFAULT}
#define PIN_QSPI_OUT_D2         {CSK_IOMUX_PAD_B,  4, CSK_IOMUX_FUNC_ALTER30, CSK_IOMUX_FUNC_DEFAULT}
#define PIN_QSPI_OUT_D3         {CSK_IOMUX_PAD_B,  2, CSK_IOMUX_FUNC_ALTER30, CSK_IOMUX_FUNC_DEFAULT}
#define PIN_QSPI_OUT_DC         {PIN_PAD_NULL, PIN_PAD_NULL, PIN_PAD_NULL, PIN_PAD_NULL}
#define PIN_QSPI_OUT_RST        {CSK_IOMUX_PAD_A, 19, PIN_PAD_NULL, CSK_IOMUX_FUNC_DEFAULT}
#define PIN_QSPI_OUT_BL         {CSK_IOMUX_PAD_A, 20, PIN_PAD_NULL, CSK_IOMUX_FUNC_DEFAULT}

#define PIN_DVP_MCLK            {CSK_IOMUX_PAD_A, 25, CSK_IOMUX_FUNC_ALTER16, CSK_IOMUX_FUNC_DEFAULT}
#define PIN_DVP_PCLK            {CSK_IOMUX_PAD_A, 12, CSK_IOMUX_FUNC_ALTER16, CSK_IOMUX_FUNC_DEFAULT}
#define PIN_DVP_VS              {CSK_IOMUX_PAD_A, 11, CSK_IOMUX_FUNC_ALTER16, CSK_IOMUX_FUNC_DEFAULT}
#define PIN_DVP_HS              {CSK_IOMUX_PAD_A, 10, CSK_IOMUX_FUNC_ALTER16, CSK_IOMUX_FUNC_DEFAULT}
#define PIN_DVP_D0              {CSK_IOMUX_PAD_A, 21, CSK_IOMUX_FUNC_ALTER16, CSK_IOMUX_FUNC_DEFAULT}
#define PIN_DVP_D1              {CSK_IOMUX_PAD_A, 22, CSK_IOMUX_FUNC_ALTER16, CSK_IOMUX_FUNC_DEFAULT}
#define PIN_DVP_D2              {CSK_IOMUX_PAD_A, 23, CSK_IOMUX_FUNC_ALTER16, CSK_IOMUX_FUNC_DEFAULT}
#define PIN_DVP_D3              {CSK_IOMUX_PAD_A, 24, CSK_IOMUX_FUNC_ALTER16, CSK_IOMUX_FUNC_DEFAULT}
#define PIN_DVP_D4              {CSK_IOMUX_PAD_A, 13, CSK_IOMUX_FUNC_ALTER16, CSK_IOMUX_FUNC_DEFAULT}
#define PIN_DVP_D5              {CSK_IOMUX_PAD_A, 14, CSK_IOMUX_FUNC_ALTER16, CSK_IOMUX_FUNC_DEFAULT}
#define PIN_DVP_D6              {CSK_IOMUX_PAD_A, 15, CSK_IOMUX_FUNC_ALTER16, CSK_IOMUX_FUNC_DEFAULT}
#define PIN_DVP_D7              {CSK_IOMUX_PAD_A, 16, CSK_IOMUX_FUNC_ALTER16, CSK_IOMUX_FUNC_DEFAULT}
#define PIN_DVP_D8              {PIN_PAD_NULL, PIN_PAD_NULL, PIN_PAD_NULL, PIN_PAD_NULL}
#define PIN_DVP_D9              {PIN_PAD_NULL, PIN_PAD_NULL, PIN_PAD_NULL, PIN_PAD_NULL}
#define PIN_DVP_D10             {PIN_PAD_NULL, PIN_PAD_NULL, PIN_PAD_NULL, PIN_PAD_NULL}
#define PIN_DVP_D11             {PIN_PAD_NULL, PIN_PAD_NULL, PIN_PAD_NULL, PIN_PAD_NULL}
#define PIN_DVP_RST             {CSK_IOMUX_PAD_B,  8, PIN_PAD_NULL, CSK_IOMUX_FUNC_DEFAULT}
#define PIN_DVP_PWDN            {CSK_IOMUX_PAD_A, 17, PIN_PAD_NULL, CSK_IOMUX_FUNC_DEFAULT}
#define PIN_DVP_SCL             {CSK_IOMUX_PAD_A,  4, PIN_PAD_NULL, CSK_IOMUX_FUNC_DEFAULT}
#define PIN_DVP_SDA             {CSK_IOMUX_PAD_A,  5, PIN_PAD_NULL, CSK_IOMUX_FUNC_DEFAULT}

#define PIN_RGB_CLK             {PIN_PAD_NULL, PIN_PAD_NULL, PIN_PAD_NULL, PIN_PAD_NULL}
#define PIN_RGB_VS              {PIN_PAD_NULL, PIN_PAD_NULL, PIN_PAD_NULL, PIN_PAD_NULL}
#define PIN_RGB_HS              {PIN_PAD_NULL, PIN_PAD_NULL, PIN_PAD_NULL, PIN_PAD_NULL}
#define PIN_RGB_DE              {PIN_PAD_NULL, PIN_PAD_NULL, PIN_PAD_NULL, PIN_PAD_NULL}
#define PIN_RGB_R0              {PIN_PAD_NULL, PIN_PAD_NULL, PIN_PAD_NULL, PIN_PAD_NULL}
#define PIN_RGB_R1              {PIN_PAD_NULL, PIN_PAD_NULL, PIN_PAD_NULL, PIN_PAD_NULL}
#define PIN_RGB_R2              {PIN_PAD_NULL, PIN_PAD_NULL, PIN_PAD_NULL, PIN_PAD_NULL}
#define PIN_RGB_R3              {PIN_PAD_NULL, PIN_PAD_NULL, PIN_PAD_NULL, PIN_PAD_NULL}
#define PIN_RGB_R4              {PIN_PAD_NULL, PIN_PAD_NULL, PIN_PAD_NULL, PIN_PAD_NULL}
#define PIN_RGB_R5              {PIN_PAD_NULL, PIN_PAD_NULL, PIN_PAD_NULL, PIN_PAD_NULL}
#define PIN_RGB_R6              {PIN_PAD_NULL, PIN_PAD_NULL, PIN_PAD_NULL, PIN_PAD_NULL}
#define PIN_RGB_R7              {PIN_PAD_NULL, PIN_PAD_NULL, PIN_PAD_NULL, PIN_PAD_NULL}
#define PIN_RGB_G0              {PIN_PAD_NULL, PIN_PAD_NULL, PIN_PAD_NULL, PIN_PAD_NULL}
#define PIN_RGB_G1              {PIN_PAD_NULL, PIN_PAD_NULL, PIN_PAD_NULL, PIN_PAD_NULL}
#define PIN_RGB_G2              {PIN_PAD_NULL, PIN_PAD_NULL, PIN_PAD_NULL, PIN_PAD_NULL}
#define PIN_RGB_G3              {PIN_PAD_NULL, PIN_PAD_NULL, PIN_PAD_NULL, PIN_PAD_NULL}
#define PIN_RGB_G4              {PIN_PAD_NULL, PIN_PAD_NULL, PIN_PAD_NULL, PIN_PAD_NULL}
#define PIN_RGB_G5              {PIN_PAD_NULL, PIN_PAD_NULL, PIN_PAD_NULL, PIN_PAD_NULL}
#define PIN_RGB_G6              {PIN_PAD_NULL, PIN_PAD_NULL, PIN_PAD_NULL, PIN_PAD_NULL}
#define PIN_RGB_G7              {PIN_PAD_NULL, PIN_PAD_NULL, PIN_PAD_NULL, PIN_PAD_NULL}
#define PIN_RGB_B0              {PIN_PAD_NULL, PIN_PAD_NULL, PIN_PAD_NULL, PIN_PAD_NULL}
#define PIN_RGB_B1              {PIN_PAD_NULL, PIN_PAD_NULL, PIN_PAD_NULL, PIN_PAD_NULL}
#define PIN_RGB_B2              {PIN_PAD_NULL, PIN_PAD_NULL, PIN_PAD_NULL, PIN_PAD_NULL}
#define PIN_RGB_B3              {PIN_PAD_NULL, PIN_PAD_NULL, PIN_PAD_NULL, PIN_PAD_NULL}
#define PIN_RGB_B4              {PIN_PAD_NULL, PIN_PAD_NULL, PIN_PAD_NULL, PIN_PAD_NULL}
#define PIN_RGB_B5              {PIN_PAD_NULL, PIN_PAD_NULL, PIN_PAD_NULL, PIN_PAD_NULL}
#define PIN_RGB_B6              {PIN_PAD_NULL, PIN_PAD_NULL, PIN_PAD_NULL, PIN_PAD_NULL}
#define PIN_RGB_B7              {PIN_PAD_NULL, PIN_PAD_NULL, PIN_PAD_NULL, PIN_PAD_NULL}
#define PIN_RGB_RST             {PIN_PAD_NULL, PIN_PAD_NULL, PIN_PAD_NULL, PIN_PAD_NULL}
#define PIN_RGB_BL              {PIN_PAD_NULL, PIN_PAD_NULL, PIN_PAD_NULL, PIN_PAD_NULL}
#endif

#if (CONFIG_BOARD_PIN == ARCSD_SCAN_PEN_BOARD_PIN)
#define PIN_QSPI_IN_MCLK        {CSK_IOMUX_PAD_A, 26, CSK_IOMUX_FUNC_ALTER16, CSK_IOMUX_FUNC_DEFAULT}
#define PIN_QSPI_IN_PCLK        {CSK_IOMUX_PAD_A, 22, CSK_IOMUX_FUNC_ALTER29, CSK_IOMUX_FUNC_DEFAULT}
#define PIN_QSPI_IN_D0          {CSK_IOMUX_PAD_A, 25, CSK_IOMUX_FUNC_ALTER29, CSK_IOMUX_FUNC_DEFAULT}
#define PIN_QSPI_IN_D1          {CSK_IOMUX_PAD_A, 24, CSK_IOMUX_FUNC_ALTER29, CSK_IOMUX_FUNC_DEFAULT}
#define PIN_QSPI_IN_D2          {CSK_IOMUX_PAD_A, 21, CSK_IOMUX_FUNC_ALTER29, CSK_IOMUX_FUNC_DEFAULT}
#define PIN_QSPI_IN_D3          {CSK_IOMUX_PAD_A, 20, CSK_IOMUX_FUNC_ALTER29, CSK_IOMUX_FUNC_DEFAULT}
#define PIN_QSPI_IN_PWDN        {CSK_IOMUX_PAD_B,  4, PIN_PAD_NULL, CSK_IOMUX_FUNC_DEFAULT}
#define PIN_QSPI_IN_SCL         {CSK_IOMUX_PAD_A, 10, PIN_PAD_NULL, CSK_IOMUX_FUNC_DEFAULT}
#define PIN_QSPI_IN_SDA         {CSK_IOMUX_PAD_A, 11, PIN_PAD_NULL, CSK_IOMUX_FUNC_DEFAULT}

#define PIN_QSPI_OUT_CS         {CSK_IOMUX_PAD_A, 19, PIN_PAD_NULL, CSK_IOMUX_FUNC_DEFAULT}
#define PIN_QSPI_OUT_CLK        {CSK_IOMUX_PAD_A, 17, CSK_IOMUX_FUNC_ALTER30, CSK_IOMUX_FUNC_DEFAULT}
#define PIN_QSPI_OUT_D0         {CSK_IOMUX_PAD_A, 15, CSK_IOMUX_FUNC_ALTER30, CSK_IOMUX_FUNC_DEFAULT}
#define PIN_QSPI_OUT_D1         {CSK_IOMUX_PAD_A, 14, CSK_IOMUX_FUNC_ALTER30, CSK_IOMUX_FUNC_DEFAULT}
#define PIN_QSPI_OUT_D2         {CSK_IOMUX_PAD_A, 18, CSK_IOMUX_FUNC_ALTER30, CSK_IOMUX_FUNC_DEFAULT}
#define PIN_QSPI_OUT_D3         {CSK_IOMUX_PAD_A, 16, CSK_IOMUX_FUNC_ALTER30, CSK_IOMUX_FUNC_DEFAULT}
#define PIN_QSPI_OUT_DC         {PIN_PAD_NULL, PIN_PAD_NULL, PIN_PAD_NULL, PIN_PAD_NULL}
#define PIN_QSPI_OUT_RST        {CSK_IOMUX_PAD_A, 12, PIN_PAD_NULL, CSK_IOMUX_FUNC_DEFAULT}
#define PIN_QSPI_OUT_BL         {CSK_IOMUX_PAD_A, 13, PIN_PAD_NULL, CSK_IOMUX_FUNC_DEFAULT}

#define PIN_DVP_MCLK            {PIN_PAD_NULL, PIN_PAD_NULL, PIN_PAD_NULL, PIN_PAD_NULL}
#define PIN_DVP_PCLK            {PIN_PAD_NULL, PIN_PAD_NULL, PIN_PAD_NULL, PIN_PAD_NULL}
#define PIN_DVP_VS              {PIN_PAD_NULL, PIN_PAD_NULL, PIN_PAD_NULL, PIN_PAD_NULL}
#define PIN_DVP_HS              {PIN_PAD_NULL, PIN_PAD_NULL, PIN_PAD_NULL, PIN_PAD_NULL}
#define PIN_DVP_D0              {PIN_PAD_NULL, PIN_PAD_NULL, PIN_PAD_NULL, PIN_PAD_NULL}
#define PIN_DVP_D1              {PIN_PAD_NULL, PIN_PAD_NULL, PIN_PAD_NULL, PIN_PAD_NULL}
#define PIN_DVP_D2              {PIN_PAD_NULL, PIN_PAD_NULL, PIN_PAD_NULL, PIN_PAD_NULL}
#define PIN_DVP_D3              {PIN_PAD_NULL, PIN_PAD_NULL, PIN_PAD_NULL, PIN_PAD_NULL}
#define PIN_DVP_D4              {PIN_PAD_NULL, PIN_PAD_NULL, PIN_PAD_NULL, PIN_PAD_NULL}
#define PIN_DVP_D5              {PIN_PAD_NULL, PIN_PAD_NULL, PIN_PAD_NULL, PIN_PAD_NULL}
#define PIN_DVP_D6              {PIN_PAD_NULL, PIN_PAD_NULL, PIN_PAD_NULL, PIN_PAD_NULL}
#define PIN_DVP_D7              {PIN_PAD_NULL, PIN_PAD_NULL, PIN_PAD_NULL, PIN_PAD_NULL}
#define PIN_DVP_D8              {PIN_PAD_NULL, PIN_PAD_NULL, PIN_PAD_NULL, PIN_PAD_NULL}
#define PIN_DVP_D9              {PIN_PAD_NULL, PIN_PAD_NULL, PIN_PAD_NULL, PIN_PAD_NULL}
#define PIN_DVP_D10             {PIN_PAD_NULL, PIN_PAD_NULL, PIN_PAD_NULL, PIN_PAD_NULL}
#define PIN_DVP_D11             {PIN_PAD_NULL, PIN_PAD_NULL, PIN_PAD_NULL, PIN_PAD_NULL}
#define PIN_DVP_RST             {PIN_PAD_NULL, PIN_PAD_NULL, PIN_PAD_NULL, PIN_PAD_NULL}
#define PIN_DVP_PWDN            {PIN_PAD_NULL, PIN_PAD_NULL, PIN_PAD_NULL, PIN_PAD_NULL}
#define PIN_DVP_SCL             {PIN_PAD_NULL, PIN_PAD_NULL, PIN_PAD_NULL, PIN_PAD_NULL}
#define PIN_DVP_SDA             {PIN_PAD_NULL, PIN_PAD_NULL, PIN_PAD_NULL, PIN_PAD_NULL}

#define PIN_RGB_CLK             {PIN_PAD_NULL, PIN_PAD_NULL, PIN_PAD_NULL, PIN_PAD_NULL}
#define PIN_RGB_VS              {PIN_PAD_NULL, PIN_PAD_NULL, PIN_PAD_NULL, PIN_PAD_NULL}
#define PIN_RGB_HS              {PIN_PAD_NULL, PIN_PAD_NULL, PIN_PAD_NULL, PIN_PAD_NULL}
#define PIN_RGB_DE              {PIN_PAD_NULL, PIN_PAD_NULL, PIN_PAD_NULL, PIN_PAD_NULL}
#define PIN_RGB_R0              {PIN_PAD_NULL, PIN_PAD_NULL, PIN_PAD_NULL, PIN_PAD_NULL}
#define PIN_RGB_R1              {PIN_PAD_NULL, PIN_PAD_NULL, PIN_PAD_NULL, PIN_PAD_NULL}
#define PIN_RGB_R2              {PIN_PAD_NULL, PIN_PAD_NULL, PIN_PAD_NULL, PIN_PAD_NULL}
#define PIN_RGB_R3              {PIN_PAD_NULL, PIN_PAD_NULL, PIN_PAD_NULL, PIN_PAD_NULL}
#define PIN_RGB_R4              {PIN_PAD_NULL, PIN_PAD_NULL, PIN_PAD_NULL, PIN_PAD_NULL}
#define PIN_RGB_R5              {PIN_PAD_NULL, PIN_PAD_NULL, PIN_PAD_NULL, PIN_PAD_NULL}
#define PIN_RGB_R6              {PIN_PAD_NULL, PIN_PAD_NULL, PIN_PAD_NULL, PIN_PAD_NULL}
#define PIN_RGB_R7              {PIN_PAD_NULL, PIN_PAD_NULL, PIN_PAD_NULL, PIN_PAD_NULL}
#define PIN_RGB_G0              {PIN_PAD_NULL, PIN_PAD_NULL, PIN_PAD_NULL, PIN_PAD_NULL}
#define PIN_RGB_G1              {PIN_PAD_NULL, PIN_PAD_NULL, PIN_PAD_NULL, PIN_PAD_NULL}
#define PIN_RGB_G2              {PIN_PAD_NULL, PIN_PAD_NULL, PIN_PAD_NULL, PIN_PAD_NULL}
#define PIN_RGB_G3              {PIN_PAD_NULL, PIN_PAD_NULL, PIN_PAD_NULL, PIN_PAD_NULL}
#define PIN_RGB_G4              {PIN_PAD_NULL, PIN_PAD_NULL, PIN_PAD_NULL, PIN_PAD_NULL}
#define PIN_RGB_G5              {PIN_PAD_NULL, PIN_PAD_NULL, PIN_PAD_NULL, PIN_PAD_NULL}
#define PIN_RGB_G6              {PIN_PAD_NULL, PIN_PAD_NULL, PIN_PAD_NULL, PIN_PAD_NULL}
#define PIN_RGB_G7              {PIN_PAD_NULL, PIN_PAD_NULL, PIN_PAD_NULL, PIN_PAD_NULL}
#define PIN_RGB_B0              {PIN_PAD_NULL, PIN_PAD_NULL, PIN_PAD_NULL, PIN_PAD_NULL}
#define PIN_RGB_B1              {PIN_PAD_NULL, PIN_PAD_NULL, PIN_PAD_NULL, PIN_PAD_NULL}
#define PIN_RGB_B2              {PIN_PAD_NULL, PIN_PAD_NULL, PIN_PAD_NULL, PIN_PAD_NULL}
#define PIN_RGB_B3              {PIN_PAD_NULL, PIN_PAD_NULL, PIN_PAD_NULL, PIN_PAD_NULL}
#define PIN_RGB_B4              {PIN_PAD_NULL, PIN_PAD_NULL, PIN_PAD_NULL, PIN_PAD_NULL}
#define PIN_RGB_B5              {PIN_PAD_NULL, PIN_PAD_NULL, PIN_PAD_NULL, PIN_PAD_NULL}
#define PIN_RGB_B6              {PIN_PAD_NULL, PIN_PAD_NULL, PIN_PAD_NULL, PIN_PAD_NULL}
#define PIN_RGB_B7              {PIN_PAD_NULL, PIN_PAD_NULL, PIN_PAD_NULL, PIN_PAD_NULL}
#define PIN_RGB_RST             {PIN_PAD_NULL, PIN_PAD_NULL, PIN_PAD_NULL, PIN_PAD_NULL}
#define PIN_RGB_BL              {PIN_PAD_NULL, PIN_PAD_NULL, PIN_PAD_NULL, PIN_PAD_NULL}
#endif

#if (CONFIG_BOARD_PIN == ARCSD_SOC_BOARD_PIN)
#define PIN_QSPI_IN_MCLK        {CSK_IOMUX_PAD_A, 26, CSK_IOMUX_FUNC_ALTER29, CSK_IOMUX_FUNC_DEFAULT}
#define PIN_QSPI_IN_PCLK        {CSK_IOMUX_PAD_A, 10, CSK_IOMUX_FUNC_ALTER29, CSK_IOMUX_FUNC_DEFAULT}
#define PIN_QSPI_IN_D0          {CSK_IOMUX_PAD_A, 14, CSK_IOMUX_FUNC_ALTER29, CSK_IOMUX_FUNC_DEFAULT}
#define PIN_QSPI_IN_D1          {CSK_IOMUX_PAD_A, 15, CSK_IOMUX_FUNC_ALTER29, CSK_IOMUX_FUNC_DEFAULT}
#define PIN_QSPI_IN_D2          {CSK_IOMUX_PAD_A, 12, CSK_IOMUX_FUNC_ALTER29, CSK_IOMUX_FUNC_DEFAULT}
#define PIN_QSPI_IN_D3          {CSK_IOMUX_PAD_A, 13, CSK_IOMUX_FUNC_ALTER29, CSK_IOMUX_FUNC_DEFAULT}
#define PIN_QSPI_IN_PWDN        {CSK_IOMUX_PAD_A, 11, PIN_PAD_NULL, CSK_IOMUX_FUNC_DEFAULT}
#define PIN_QSPI_IN_SCL         {CSK_IOMUX_PAD_A,  2, PIN_PAD_NULL, CSK_IOMUX_FUNC_DEFAULT}
#define PIN_QSPI_IN_SDA         {CSK_IOMUX_PAD_A,  3, PIN_PAD_NULL, CSK_IOMUX_FUNC_DEFAULT}

#define PIN_QSPI_OUT_CS         {CSK_IOMUX_PAD_A, 21, PIN_PAD_NULL, CSK_IOMUX_FUNC_DEFAULT}
#define PIN_QSPI_OUT_CLK        {CSK_IOMUX_PAD_A, 22, CSK_IOMUX_FUNC_ALTER30, CSK_IOMUX_FUNC_DEFAULT}
#define PIN_QSPI_OUT_D0         {CSK_IOMUX_PAD_A, 23, CSK_IOMUX_FUNC_ALTER30, CSK_IOMUX_FUNC_DEFAULT}
#define PIN_QSPI_OUT_D1         {CSK_IOMUX_PAD_A, 24, CSK_IOMUX_FUNC_ALTER30, CSK_IOMUX_FUNC_DEFAULT}
#define PIN_QSPI_OUT_D2         {CSK_IOMUX_PAD_A, 25, CSK_IOMUX_FUNC_ALTER30, CSK_IOMUX_FUNC_DEFAULT}
#define PIN_QSPI_OUT_D3         {CSK_IOMUX_PAD_A, 26, CSK_IOMUX_FUNC_ALTER30, CSK_IOMUX_FUNC_DEFAULT}
#define PIN_QSPI_OUT_DC         {PIN_PAD_NULL, PIN_PAD_NULL, PIN_PAD_NULL, PIN_PAD_NULL}
#define PIN_QSPI_OUT_RST        {CSK_IOMUX_PAD_B,  8, PIN_PAD_NULL, CSK_IOMUX_FUNC_DEFAULT}
#define PIN_QSPI_OUT_BL         {CSK_IOMUX_PAD_B,  0, PIN_PAD_NULL, CSK_IOMUX_FUNC_DEFAULT}

#define PIN_DVP_MCLK            {CSK_IOMUX_PAD_A, 25, PIN_PAD_NULL, CSK_IOMUX_FUNC_DEFAULT}
#define PIN_DVP_PCLK            {CSK_IOMUX_PAD_A, 12, CSK_IOMUX_FUNC_ALTER16, CSK_IOMUX_FUNC_DEFAULT}
#define PIN_DVP_VS              {CSK_IOMUX_PAD_A, 11, CSK_IOMUX_FUNC_ALTER16, CSK_IOMUX_FUNC_DEFAULT}
#define PIN_DVP_HS              {CSK_IOMUX_PAD_A, 10, CSK_IOMUX_FUNC_ALTER16, CSK_IOMUX_FUNC_DEFAULT}
#define PIN_DVP_D0              {CSK_IOMUX_PAD_A, 13, CSK_IOMUX_FUNC_ALTER16, CSK_IOMUX_FUNC_DEFAULT}
#define PIN_DVP_D1              {CSK_IOMUX_PAD_A, 14, CSK_IOMUX_FUNC_ALTER16, CSK_IOMUX_FUNC_DEFAULT}
#define PIN_DVP_D2              {CSK_IOMUX_PAD_A, 15, CSK_IOMUX_FUNC_ALTER16, CSK_IOMUX_FUNC_DEFAULT}
#define PIN_DVP_D3              {CSK_IOMUX_PAD_A, 16, CSK_IOMUX_FUNC_ALTER16, CSK_IOMUX_FUNC_DEFAULT}
#define PIN_DVP_D4              {CSK_IOMUX_PAD_A, 17, CSK_IOMUX_FUNC_ALTER16, CSK_IOMUX_FUNC_DEFAULT}
#define PIN_DVP_D5              {CSK_IOMUX_PAD_A, 18, CSK_IOMUX_FUNC_ALTER16, CSK_IOMUX_FUNC_DEFAULT}
#define PIN_DVP_D6              {CSK_IOMUX_PAD_A, 19, CSK_IOMUX_FUNC_ALTER16, CSK_IOMUX_FUNC_DEFAULT}
#define PIN_DVP_D7              {CSK_IOMUX_PAD_A, 20, CSK_IOMUX_FUNC_ALTER16, CSK_IOMUX_FUNC_DEFAULT}
#define PIN_DVP_RST             {CSK_IOMUX_PAD_A, 27, PIN_PAD_NULL, CSK_IOMUX_FUNC_DEFAULT}
#define PIN_DVP_PWDN            {CSK_IOMUX_PAD_B,  9, PIN_PAD_NULL, CSK_IOMUX_FUNC_DEFAULT}
#define PIN_DVP_SCL             {CSK_IOMUX_PAD_A,  6, PIN_PAD_NULL, CSK_IOMUX_FUNC_DEFAULT}
#define PIN_DVP_SDA             {CSK_IOMUX_PAD_A,  7, PIN_PAD_NULL, CSK_IOMUX_FUNC_DEFAULT}

#define PIN_RGB_CLK             {CSK_IOMUX_PAD_A,  6, CSK_IOMUX_FUNC_ALTER31, CSK_IOMUX_FUNC_DEFAULT}
#define PIN_RGB_VS              {CSK_IOMUX_PAD_A,  5, CSK_IOMUX_FUNC_ALTER31, CSK_IOMUX_FUNC_DEFAULT}
#define PIN_RGB_HS              {CSK_IOMUX_PAD_A,  4, CSK_IOMUX_FUNC_ALTER31, CSK_IOMUX_FUNC_DEFAULT}
#define PIN_RGB_DE              {CSK_IOMUX_PAD_A,  7, CSK_IOMUX_FUNC_ALTER31, CSK_IOMUX_FUNC_DEFAULT}
#define PIN_RGB_R0              {CSK_IOMUX_PAD_B,  0, CSK_IOMUX_FUNC_ALTER31, CSK_IOMUX_FUNC_DEFAULT}
#define PIN_RGB_R1              {CSK_IOMUX_PAD_B,  1, CSK_IOMUX_FUNC_ALTER31, CSK_IOMUX_FUNC_DEFAULT}
#define PIN_RGB_R2              {CSK_IOMUX_PAD_A,  8, CSK_IOMUX_FUNC_ALTER31, CSK_IOMUX_FUNC_ALTER1}
#define PIN_RGB_R3              {CSK_IOMUX_PAD_A,  9, CSK_IOMUX_FUNC_ALTER31, CSK_IOMUX_FUNC_ALTER1}
#define PIN_RGB_R4              {CSK_IOMUX_PAD_A, 10, CSK_IOMUX_FUNC_ALTER31, CSK_IOMUX_FUNC_DEFAULT}
#define PIN_RGB_R5              {CSK_IOMUX_PAD_A, 11, CSK_IOMUX_FUNC_ALTER31, CSK_IOMUX_FUNC_DEFAULT}
#define PIN_RGB_R6              {CSK_IOMUX_PAD_A, 12, CSK_IOMUX_FUNC_ALTER31, CSK_IOMUX_FUNC_DEFAULT}
#define PIN_RGB_R7              {CSK_IOMUX_PAD_A, 13, CSK_IOMUX_FUNC_ALTER31, CSK_IOMUX_FUNC_DEFAULT}
#define PIN_RGB_G0              {CSK_IOMUX_PAD_B,  2, CSK_IOMUX_FUNC_ALTER31, CSK_IOMUX_FUNC_DEFAULT}
#define PIN_RGB_G1              {CSK_IOMUX_PAD_B,  3, CSK_IOMUX_FUNC_ALTER31, CSK_IOMUX_FUNC_DEFAULT}
#define PIN_RGB_G2              {CSK_IOMUX_PAD_A, 14, CSK_IOMUX_FUNC_ALTER31, CSK_IOMUX_FUNC_DEFAULT}
#define PIN_RGB_G3              {CSK_IOMUX_PAD_A, 15, CSK_IOMUX_FUNC_ALTER31, CSK_IOMUX_FUNC_DEFAULT}
#define PIN_RGB_G4              {CSK_IOMUX_PAD_A, 16, CSK_IOMUX_FUNC_ALTER31, CSK_IOMUX_FUNC_DEFAULT}
#define PIN_RGB_G5              {CSK_IOMUX_PAD_A, 17, CSK_IOMUX_FUNC_ALTER31, CSK_IOMUX_FUNC_DEFAULT}
#define PIN_RGB_G6              {CSK_IOMUX_PAD_A, 18, CSK_IOMUX_FUNC_ALTER31, CSK_IOMUX_FUNC_DEFAULT}
#define PIN_RGB_G7              {CSK_IOMUX_PAD_A, 19, CSK_IOMUX_FUNC_ALTER31, CSK_IOMUX_FUNC_DEFAULT}
#define PIN_RGB_B0              {CSK_IOMUX_PAD_B,  4, CSK_IOMUX_FUNC_ALTER31, CSK_IOMUX_FUNC_DEFAULT}
#define PIN_RGB_B1              {CSK_IOMUX_PAD_B,  5, CSK_IOMUX_FUNC_ALTER31, CSK_IOMUX_FUNC_DEFAULT}
#define PIN_RGB_B2              {CSK_IOMUX_PAD_A, 20, CSK_IOMUX_FUNC_ALTER31, CSK_IOMUX_FUNC_DEFAULT}
#define PIN_RGB_B3              {CSK_IOMUX_PAD_A, 21, CSK_IOMUX_FUNC_ALTER31, CSK_IOMUX_FUNC_DEFAULT}
#define PIN_RGB_B4              {CSK_IOMUX_PAD_A, 22, CSK_IOMUX_FUNC_ALTER31, CSK_IOMUX_FUNC_DEFAULT}
#define PIN_RGB_B5              {CSK_IOMUX_PAD_A, 23, CSK_IOMUX_FUNC_ALTER31, CSK_IOMUX_FUNC_DEFAULT}
#define PIN_RGB_B6              {CSK_IOMUX_PAD_A, 24, CSK_IOMUX_FUNC_ALTER31, CSK_IOMUX_FUNC_DEFAULT}
#define PIN_RGB_B7              {CSK_IOMUX_PAD_A, 25, CSK_IOMUX_FUNC_ALTER31, CSK_IOMUX_FUNC_DEFAULT}
#define PIN_RGB_RST             {CSK_IOMUX_PAD_B,  9, PIN_PAD_NULL, CSK_IOMUX_FUNC_DEFAULT}
#define PIN_RGB_BL              {CSK_IOMUX_PAD_B,  8, PIN_PAD_NULL, CSK_IOMUX_FUNC_DEFAULT}
#endif


#endif
