#ifndef _RGB_CASE_CONFIG_H_
#define _RGB_CASE_CONFIG_H_

#include <stdio.h>
#include <string.h>
#include <stdlib.h>

#include "Driver_RGB.h"
#include "Driver_GPDMA.h"
#include "csk_driver.h"

#define TEST_RGB_OUT_CLK_HZ        24000000
#define TEST_RGB_LCD_WIDTH          800
#define TEST_RGB_LCD_HEIGHT         480
//#define TEST_RGB_MALLOC_LINE        80          // 800x80x4=256000 Byte

#define TEST_RGB_GPDMA_CH          gp_dma_ch1
#define TEST_RGB_PSRAM_ADDR        (0x28000000)

RGB_InitTypeDef rgb_cfg_case0001 = {
    .frms               = RGB_FRAME_CONTINUE,       // RGB_FRAME_ONCE
    .wires              = RGB_OUTPUT_WIRES_24,
    .sync               = RGB_SYNC_MODE_SYNC_DE,
    .de_continue        = true,
    .format_in          = RGB_INPUT_FORMAT_RGB888,
    .format_out         = RGB_OUTPUT_FORMAT_RGB888,
    .out_lsb            = false,
    .VSPolarity         = RGB_POLARITY_POSITIVE,
    .HSPolarity         = RGB_POLARITY_POSITIVE,
    .DEPolarity         = RGB_POLARITY_NEGATIVE,
    .CLKPolarity        = RGB_POLARITY_NEGATIVE,
    .clk_hz             = TEST_RGB_OUT_CLK_HZ,
    .img_width          = TEST_RGB_LCD_WIDTH,
    .img_height         = TEST_RGB_LCD_HEIGHT,
    .v_pulse_width      = 1,
    .h_pulse_width      = 1,
    .v_front_blanking   = 22,
    .h_front_blanking   = 210,
    .v_back_blanking    = 7,
    .h_back_blanking    = 7,
};

RGB_InitTypeDef rgb_cfg_case0101 = {
    .frms               = RGB_FRAME_CONTINUE,
    .wires              = RGB_OUTPUT_WIRES_24,
    .sync               = RGB_SYNC_MODE_SYNC_DE,
    .de_continue        = true,
    .format_in          = RGB_INPUT_FORMAT_RGB888,
    .format_out         = RGB_OUTPUT_FORMAT_RGB888,
    .out_lsb            = false,
    .VSPolarity         = RGB_POLARITY_POSITIVE,
    .HSPolarity         = RGB_POLARITY_POSITIVE,
    .DEPolarity         = RGB_POLARITY_NEGATIVE,
    .CLKPolarity        = RGB_POLARITY_NEGATIVE,
    .clk_hz             = TEST_RGB_OUT_CLK_HZ,
    .img_width          = TEST_RGB_LCD_WIDTH,
    .img_height         = TEST_RGB_LCD_HEIGHT,
    .v_pulse_width      = 1,
    .h_pulse_width      = 1,
    .v_front_blanking   = 22,
    .h_front_blanking   = 210,
    .v_back_blanking    = 7,
    .h_back_blanking    = 7,
};

RGB_InitTypeDef rgb_cfg_case0102 = {
    .frms               = RGB_FRAME_CONTINUE,
    .wires              = RGB_OUTPUT_WIRES_24,
    .sync               = RGB_SYNC_MODE_SYNC_DE,
    .de_continue        = true,
    .format_in          = RGB_INPUT_FORMAT_RGB888,
    .format_out         = RGB_OUTPUT_FORMAT_RGB666,
    .out_lsb            = false,
    .VSPolarity         = RGB_POLARITY_POSITIVE,
    .HSPolarity         = RGB_POLARITY_POSITIVE,
    .DEPolarity         = RGB_POLARITY_NEGATIVE,
    .CLKPolarity        = RGB_POLARITY_NEGATIVE,
    .clk_hz             = TEST_RGB_OUT_CLK_HZ,
    .img_width          = TEST_RGB_LCD_WIDTH,
    .img_height         = TEST_RGB_LCD_HEIGHT,
    .v_pulse_width      = 1,
    .h_pulse_width      = 1,
    .v_front_blanking   = 22,
    .h_front_blanking   = 210,
    .v_back_blanking    = 7,
    .h_back_blanking    = 7,
};

RGB_InitTypeDef rgb_cfg_case0103 = {
    .frms               = RGB_FRAME_CONTINUE,
    .wires              = RGB_OUTPUT_WIRES_24,
    .sync               = RGB_SYNC_MODE_SYNC_DE,
    .de_continue        = true,
    .format_in          = RGB_INPUT_FORMAT_RGB888,
    .format_out         = RGB_OUTPUT_FORMAT_BGR888,
    .out_lsb            = false,
    .VSPolarity         = RGB_POLARITY_POSITIVE,
    .HSPolarity         = RGB_POLARITY_POSITIVE,
    .DEPolarity         = RGB_POLARITY_NEGATIVE,
    .CLKPolarity        = RGB_POLARITY_NEGATIVE,
    .clk_hz             = TEST_RGB_OUT_CLK_HZ,
    .img_width          = TEST_RGB_LCD_WIDTH,
    .img_height         = TEST_RGB_LCD_HEIGHT,
    .v_pulse_width      = 1,
    .h_pulse_width      = 1,
    .v_front_blanking   = 22,
    .h_front_blanking   = 210,
    .v_back_blanking    = 7,
    .h_back_blanking    = 7,
};

RGB_InitTypeDef rgb_cfg_case0104 = {
    .frms               = RGB_FRAME_CONTINUE,
    .wires              = RGB_OUTPUT_WIRES_24,
    .sync               = RGB_SYNC_MODE_SYNC_DE,
    .de_continue        = true,
    .format_in          = RGB_INPUT_FORMAT_RGB888,
    .format_out         = RGB_OUTPUT_FORMAT_BGR666,
    .out_lsb            = false,
    .VSPolarity         = RGB_POLARITY_POSITIVE,
    .HSPolarity         = RGB_POLARITY_POSITIVE,
    .DEPolarity         = RGB_POLARITY_NEGATIVE,
    .CLKPolarity        = RGB_POLARITY_NEGATIVE,
    .clk_hz             = TEST_RGB_OUT_CLK_HZ,
    .img_width          = TEST_RGB_LCD_WIDTH,
    .img_height         = TEST_RGB_LCD_HEIGHT,
    .v_pulse_width      = 1,
    .h_pulse_width      = 1,
    .v_front_blanking   = 22,
    .h_front_blanking   = 210,
    .v_back_blanking    = 7,
    .h_back_blanking    = 7,
};

RGB_InitTypeDef rgb_cfg_case0105 = {
    .frms               = RGB_FRAME_CONTINUE,
    .wires              = RGB_OUTPUT_WIRES_24,
    .sync               = RGB_SYNC_MODE_SYNC_DE,
    .de_continue        = true,
    .format_in          = RGB_INPUT_FORMAT_XRGB8888,
    .format_out         = RGB_OUTPUT_FORMAT_RGB888,
    .out_lsb            = false,
    .VSPolarity         = RGB_POLARITY_POSITIVE,
    .HSPolarity         = RGB_POLARITY_POSITIVE,
    .DEPolarity         = RGB_POLARITY_NEGATIVE,
    .CLKPolarity        = RGB_POLARITY_NEGATIVE,
    .clk_hz             = TEST_RGB_OUT_CLK_HZ,
    .img_width          = TEST_RGB_LCD_WIDTH,
    .img_height         = TEST_RGB_LCD_HEIGHT,
    .v_pulse_width      = 1,
    .h_pulse_width      = 1,
    .v_front_blanking   = 22,
    .h_front_blanking   = 210,
    .v_back_blanking    = 7,
    .h_back_blanking    = 7,
};

RGB_InitTypeDef rgb_cfg_case0106 = {
    .frms               = RGB_FRAME_CONTINUE,
    .wires              = RGB_OUTPUT_WIRES_24,
    .sync               = RGB_SYNC_MODE_SYNC_DE,
    .de_continue        = true,
    .format_in          = RGB_INPUT_FORMAT_XRGB8888,
    .format_out         = RGB_OUTPUT_FORMAT_RGB666,
    .out_lsb            = false,
    .VSPolarity         = RGB_POLARITY_POSITIVE,
    .HSPolarity         = RGB_POLARITY_POSITIVE,
    .DEPolarity         = RGB_POLARITY_NEGATIVE,
    .CLKPolarity        = RGB_POLARITY_NEGATIVE,
    .clk_hz             = TEST_RGB_OUT_CLK_HZ,
    .img_width          = TEST_RGB_LCD_WIDTH,
    .img_height         = TEST_RGB_LCD_HEIGHT,
    .v_pulse_width      = 1,
    .h_pulse_width      = 1,
    .v_front_blanking   = 22,
    .h_front_blanking   = 210,
    .v_back_blanking    = 7,
    .h_back_blanking    = 7,
};

RGB_InitTypeDef rgb_cfg_case0107 = {
    .frms               = RGB_FRAME_CONTINUE,
    .wires              = RGB_OUTPUT_WIRES_24,
    .sync               = RGB_SYNC_MODE_SYNC_DE,
    .de_continue        = true,
    .format_in          = RGB_INPUT_FORMAT_XRGB8888,
    .format_out         = RGB_OUTPUT_FORMAT_BGR888,
    .out_lsb            = false,
    .VSPolarity         = RGB_POLARITY_POSITIVE,
    .HSPolarity         = RGB_POLARITY_POSITIVE,
    .DEPolarity         = RGB_POLARITY_NEGATIVE,
    .CLKPolarity        = RGB_POLARITY_NEGATIVE,
    .clk_hz             = TEST_RGB_OUT_CLK_HZ,
    .img_width          = TEST_RGB_LCD_WIDTH,
    .img_height         = TEST_RGB_LCD_HEIGHT,
    .v_pulse_width      = 1,
    .h_pulse_width      = 1,
    .v_front_blanking   = 22,
    .h_front_blanking   = 210,
    .v_back_blanking    = 7,
    .h_back_blanking    = 7,
};

RGB_InitTypeDef rgb_cfg_case0108 = {
    .frms               = RGB_FRAME_CONTINUE,
    .wires              = RGB_OUTPUT_WIRES_24,
    .sync               = RGB_SYNC_MODE_SYNC_DE,
    .de_continue        = true,
    .format_in          = RGB_INPUT_FORMAT_XRGB8888,
    .format_out         = RGB_OUTPUT_FORMAT_BGR666,
    .out_lsb            = false,
    .VSPolarity         = RGB_POLARITY_POSITIVE,
    .HSPolarity         = RGB_POLARITY_POSITIVE,
    .DEPolarity         = RGB_POLARITY_NEGATIVE,
    .CLKPolarity        = RGB_POLARITY_NEGATIVE,
    .clk_hz             = TEST_RGB_OUT_CLK_HZ,
    .img_width          = TEST_RGB_LCD_WIDTH,
    .img_height         = TEST_RGB_LCD_HEIGHT,
    .v_pulse_width      = 1,
    .h_pulse_width      = 1,
    .v_front_blanking   = 22,
    .h_front_blanking   = 210,
    .v_back_blanking    = 7,
    .h_back_blanking    = 7,
};

RGB_InitTypeDef rgb_cfg_case0109 = {
    .frms               = RGB_FRAME_CONTINUE,
    .wires              = RGB_OUTPUT_WIRES_24,
    .sync               = RGB_SYNC_MODE_SYNC_DE,
    .de_continue        = true,
    .format_in          = RGB_INPUT_FORMAT_RGB565,
    .format_out         = RGB_OUTPUT_FORMAT_RGB565,
    .out_lsb            = false,
    .VSPolarity         = RGB_POLARITY_POSITIVE,
    .HSPolarity         = RGB_POLARITY_POSITIVE,
    .DEPolarity         = RGB_POLARITY_NEGATIVE,
    .CLKPolarity        = RGB_POLARITY_NEGATIVE,
    .clk_hz             = TEST_RGB_OUT_CLK_HZ,
    .img_width          = TEST_RGB_LCD_WIDTH,
    .img_height         = TEST_RGB_LCD_HEIGHT,
    .v_pulse_width      = 1,
    .h_pulse_width      = 1,
    .v_front_blanking   = 22,
    .h_front_blanking   = 210,
    .v_back_blanking    = 7,
    .h_back_blanking    = 7,
};

RGB_InitTypeDef rgb_cfg_case0110 = {
    .frms               = RGB_FRAME_CONTINUE,
    .wires              = RGB_OUTPUT_WIRES_24,
    .sync               = RGB_SYNC_MODE_SYNC_DE,
    .de_continue        = true,
    .format_in          = RGB_INPUT_FORMAT_RGB565,
    .format_out         = RGB_OUTPUT_FORMAT_BGR565,
    .out_lsb            = false,
    .VSPolarity         = RGB_POLARITY_POSITIVE,
    .HSPolarity         = RGB_POLARITY_POSITIVE,
    .DEPolarity         = RGB_POLARITY_NEGATIVE,
    .CLKPolarity        = RGB_POLARITY_NEGATIVE,
    .clk_hz             = TEST_RGB_OUT_CLK_HZ,
    .img_width          = TEST_RGB_LCD_WIDTH,
    .img_height         = TEST_RGB_LCD_HEIGHT,
    .v_pulse_width      = 1,
    .h_pulse_width      = 1,
    .v_front_blanking   = 22,
    .h_front_blanking   = 210,
    .v_back_blanking    = 7,
    .h_back_blanking    = 7,
};

RGB_InitTypeDef rgb_cfg_case0201 = {
    .frms               = RGB_FRAME_CONTINUE,
    .wires              = RGB_OUTPUT_WIRES_24,
    .sync               = RGB_SYNC_MODE_SYNC,
    .de_continue        = true,
    .format_in          = RGB_INPUT_FORMAT_RGB888,
    .format_out         = RGB_OUTPUT_FORMAT_RGB888,
    .out_lsb            = false,
    .VSPolarity         = RGB_POLARITY_POSITIVE,
    .HSPolarity         = RGB_POLARITY_POSITIVE,
    .DEPolarity         = RGB_POLARITY_NEGATIVE,
    .CLKPolarity        = RGB_POLARITY_NEGATIVE,
    .clk_hz             = TEST_RGB_OUT_CLK_HZ,
    .img_width          = TEST_RGB_LCD_WIDTH,
    .img_height         = TEST_RGB_LCD_HEIGHT,
    .v_pulse_width      = 1,
    .h_pulse_width      = 1,
    .v_front_blanking   = 22,
    .h_front_blanking   = 210,
    .v_back_blanking    = 7,
    .h_back_blanking    = 7,
};

RGB_InitTypeDef rgb_cfg_case0202 = {
    .frms               = RGB_FRAME_CONTINUE,
    .wires              = RGB_OUTPUT_WIRES_24,
    .sync               = RGB_SYNC_MODE_SYNC,
    .de_continue        = true,
    .format_in          = RGB_INPUT_FORMAT_RGB565,
    .format_out         = RGB_OUTPUT_FORMAT_RGB565,
    .out_lsb            = false,
    .VSPolarity         = RGB_POLARITY_POSITIVE,
    .HSPolarity         = RGB_POLARITY_POSITIVE,
    .DEPolarity         = RGB_POLARITY_NEGATIVE,
    .CLKPolarity        = RGB_POLARITY_NEGATIVE,
    .clk_hz             = TEST_RGB_OUT_CLK_HZ,
    .img_width          = TEST_RGB_LCD_WIDTH,
    .img_height         = TEST_RGB_LCD_HEIGHT,
    .v_pulse_width      = 1,
    .h_pulse_width      = 1,
    .v_front_blanking   = 22,
    .h_front_blanking   = 210,
    .v_back_blanking    = 7,
    .h_back_blanking    = 7,
};

RGB_InitTypeDef rgb_cfg_case0301 = {
    .frms               = RGB_FRAME_CONTINUE,
    .wires              = RGB_OUTPUT_WIRES_8,
    .sync               = RGB_SYNC_MODE_SYNC_DE,
    .de_continue        = true,
    .format_in          = RGB_INPUT_FORMAT_RGB888,
    .format_out         = RGB_OUTPUT_FORMAT_RGB888,
    .out_lsb            = false,
    .VSPolarity         = RGB_POLARITY_POSITIVE,
    .HSPolarity         = RGB_POLARITY_POSITIVE,
    .DEPolarity         = RGB_POLARITY_NEGATIVE,
    .CLKPolarity        = RGB_POLARITY_NEGATIVE,
    .clk_hz             = TEST_RGB_OUT_CLK_HZ,
    .img_width          = TEST_RGB_LCD_WIDTH,
    .img_height         = TEST_RGB_LCD_HEIGHT,
    .v_pulse_width      = 1,
    .h_pulse_width      = 1,
    .v_front_blanking   = 22,
    .h_front_blanking   = 210,
    .v_back_blanking    = 7,
    .h_back_blanking    = 7,
};

RGB_InitTypeDef rgb_cfg_case0302 = {
    .frms               = RGB_FRAME_CONTINUE,
    .wires              = RGB_OUTPUT_WIRES_8,
    .sync               = RGB_SYNC_MODE_SYNC_DE,
    .de_continue        = true,
    .format_in          = RGB_INPUT_FORMAT_RGB565,
    .format_out         = RGB_OUTPUT_FORMAT_RGB565,
    .out_lsb            = false,
    .VSPolarity         = RGB_POLARITY_POSITIVE,
    .HSPolarity         = RGB_POLARITY_POSITIVE,
    .DEPolarity         = RGB_POLARITY_NEGATIVE,
    .CLKPolarity        = RGB_POLARITY_NEGATIVE,
    .clk_hz             = TEST_RGB_OUT_CLK_HZ,
    .img_width          = TEST_RGB_LCD_WIDTH,
    .img_height         = TEST_RGB_LCD_HEIGHT,
    .v_pulse_width      = 1,
    .h_pulse_width      = 1,
    .v_front_blanking   = 22,
    .h_front_blanking   = 210,
    .v_back_blanking    = 7,
    .h_back_blanking    = 7,
};

RGB_InitTypeDef rgb_cfg_case0401 = {
    .frms               = RGB_FRAME_CONTINUE,
    .wires              = RGB_OUTPUT_WIRES_24,
    .sync               = RGB_SYNC_MODE_SYNC_DE,
    .de_continue        = true,
    .format_in          = RGB_INPUT_FORMAT_RGB888,
    .format_out         = RGB_OUTPUT_FORMAT_RGB666,
    .out_lsb            = true,
    .VSPolarity         = RGB_POLARITY_POSITIVE,
    .HSPolarity         = RGB_POLARITY_POSITIVE,
    .DEPolarity         = RGB_POLARITY_NEGATIVE,
    .CLKPolarity        = RGB_POLARITY_NEGATIVE,
    .clk_hz             = TEST_RGB_OUT_CLK_HZ,
    .img_width          = TEST_RGB_LCD_WIDTH,
    .img_height         = TEST_RGB_LCD_HEIGHT,
    .v_pulse_width      = 1,
    .h_pulse_width      = 1,
    .v_front_blanking   = 22,
    .h_front_blanking   = 210,
    .v_back_blanking    = 7,
    .h_back_blanking    = 7,
};

RGB_InitTypeDef rgb_cfg_case0402 = {
    .frms               = RGB_FRAME_CONTINUE,
    .wires              = RGB_OUTPUT_WIRES_24,
    .sync               = RGB_SYNC_MODE_SYNC_DE,
    .de_continue        = true,
    .format_in          = RGB_INPUT_FORMAT_RGB565,
    .format_out         = RGB_OUTPUT_FORMAT_RGB565,
    .out_lsb            = true,
    .VSPolarity         = RGB_POLARITY_POSITIVE,
    .HSPolarity         = RGB_POLARITY_POSITIVE,
    .DEPolarity         = RGB_POLARITY_NEGATIVE,
    .CLKPolarity        = RGB_POLARITY_NEGATIVE,
    .clk_hz             = TEST_RGB_OUT_CLK_HZ,
    .img_width          = TEST_RGB_LCD_WIDTH,
    .img_height         = TEST_RGB_LCD_HEIGHT,
    .v_pulse_width      = 1,
    .h_pulse_width      = 1,
    .v_front_blanking   = 22,
    .h_front_blanking   = 210,
    .v_back_blanking    = 7,
    .h_back_blanking    = 7,
};

RGB_InitTypeDef rgb_cfg_case0501 = {
    .frms               = RGB_FRAME_CONTINUE,
    .wires              = RGB_OUTPUT_WIRES_24,
    .sync               = RGB_SYNC_MODE_SYNC_DE,
    .de_continue        = true,
    .format_in          = RGB_INPUT_FORMAT_RGB888,
    .format_out         = RGB_OUTPUT_FORMAT_RGB888,
    .out_lsb            = false,
    .VSPolarity         = RGB_POLARITY_NEGATIVE,
    .HSPolarity         = RGB_POLARITY_NEGATIVE,
    .DEPolarity         = RGB_POLARITY_POSITIVE,
    .CLKPolarity        = RGB_POLARITY_POSITIVE,
    .clk_hz             = TEST_RGB_OUT_CLK_HZ,
    .img_width          = TEST_RGB_LCD_WIDTH,
    .img_height         = TEST_RGB_LCD_HEIGHT,
    .v_pulse_width      = 1,
    .h_pulse_width      = 1,
    .v_front_blanking   = 22,
    .h_front_blanking   = 210,
    .v_back_blanking    = 7,
    .h_back_blanking    = 7,
};

typedef struct
{
    uint8_t index;
    uint16_t id;
    uint8_t *name;
    RGB_InitTypeDef *pcfg;
    int32_t ret;
}rgb_CaseTypeDef;

rgb_CaseTypeDef rgb_case_tab[] = {
    { 0, 0x0101, NULL, &rgb_cfg_case0101, FAILURE},
    { 1, 0x0102, NULL, &rgb_cfg_case0102, FAILURE},
    { 2, 0x0103, NULL, &rgb_cfg_case0103, FAILURE},
    { 3, 0x0104, NULL, &rgb_cfg_case0104, FAILURE},
    { 4, 0x0105, NULL, &rgb_cfg_case0105, FAILURE},
    { 5, 0x0106, NULL, &rgb_cfg_case0106, FAILURE},
    { 6, 0x0107, NULL, &rgb_cfg_case0107, FAILURE},
    { 7, 0x0108, NULL, &rgb_cfg_case0108, FAILURE},
    { 8, 0x0109, NULL, &rgb_cfg_case0109, FAILURE},
    { 9, 0x0110, NULL, &rgb_cfg_case0110, FAILURE},
    {10, 0x0201, NULL, &rgb_cfg_case0201, FAILURE},
    {11, 0x0202, NULL, &rgb_cfg_case0202, FAILURE},
    {14, 0x0301, NULL, &rgb_cfg_case0301, FAILURE},
    {15, 0x0302, NULL, &rgb_cfg_case0302, FAILURE},
    {16, 0x0401, NULL, &rgb_cfg_case0401, FAILURE},
    {17, 0x0402, NULL, &rgb_cfg_case0402, FAILURE},
    {18, 0x0501, NULL, &rgb_cfg_case0501, FAILURE},
};

#endif

