CONFIG_PSRAM_HEAP_SIZE=0x40000

CONFIG_ARCS_AP_CORE=y

# AP 核内存布局（双核分区，避免踩踏 CP SRAM）
CONFIG_MEM_SRAM_BASE=0x2002B400
CONFIG_MEM_SRAM_SIZE=0x0001A000
CONFIG_MEM_WFRAM_BASE=0x2001E400
CONFIG_MEM_WFRAM_SIZE=0x0000D000
CONFIG_MEM_LUNA_SHARED_BASE=0x20045400
CONFIG_MEM_LUNA_SHARED_SIZE=0x00008C00
CONFIG_MEM_IPC_BASE=0x2004E000

CONFIG_LISA_WIFI=y
CONFIG_WIFI_LWIP_DIFF_CORE=y

# 双核WiFi要手动选择当前核心运行WIFI还是LWIP
CONFIG_WIFI=y

# 射频板型配置
CONFIG_ARCS_HAL_WCND_RF_BOARD_VER=1

CONFIG_CONSOLE_UART_NAME="uart1"
