CONFIG_BOARD_ARCS_MINI_DOLL_V2=y

CONFIG_LISA_DISPLAY_COMPOSITE=y
CONFIG_LISA_DISPLAY_TE_SYNC=n
CONFIG_LISA_DISPLAY_PANEL_ST7789P3=n
CONFIG_LISA_DISPLAY_PANEL_GC9D01N=y
CONFIG_LV_DRIVER_ROTATE_NORMAL=y

CONFIG_CLOUD_PRODUCT_ID_DEFAULT="dc735585-6dbb-425b-9685-5155e96d52fb"
CONFIG_CLOUD_SECRET_ID_DEFAULT="35752bbc-0957-4c5b-8dbb-3c767b9b204a"

CONFIG_AUDIO_DEFAULT_MIC_GAIN_A_DB=30
CONFIG_AUDIO_DEFAULT_MIC_GAIN_D_DB=0
CONFIG_AUDIO_DEFAULT_REF_GAIN_A_DB=22
CONFIG_AUDIO_DEFAULT_REF_GAIN_D_DB=0
CONFIG_AUDIO_DEFAULT_SPK_GAIN_A_DB=0
CONFIG_AUDIO_DEFAULT_SPK_GAIN_D_DB=-19
