#ifndef __MRPC_FLASH_IF_API_SERVER_H__
#define __MRPC_FLASH_IF_API_SERVER_H__

#include "mrpc_server.h"

typedef enum
{
    MRPC_MSG_ID_FLASH_IF_START = MRPC_SERVICE_TYPE_FLASH_IF << 24,
    MRPC_MSG_ID_FLASH_IF_INIT,
    MRPC_MSG_ID_FLASH_IF_READ,
    MRPC_MSG_ID_FLASH_IF_WRITE,
    MRPC_MSG_ID_FLASH_IF_ERASE,
    MRPC_MSG_ID_FLASH_IF_WRITE_PROTECTION_SET,
    MRPC_MSG_ID_FLASH_IF_SECURITY_READ,
    MRPC_MSG_ID_FLASH_IF_SECURITY_WRITE,
    MRPC_MSG_ID_FLASH_IF_SECURITY_ERASE,
    MRPC_MSG_ID_FLASH_IF_CHECK_SECURITY_SUPPORT,
    MRPC_MSG_ID_FLASH_IF_MAX
} ipc_msg_id_flash_if_t;

extern mrpc_msg_handler_t mrpc_msg_flash_if_handlers[MRPC_MSG_ID_FLASH_IF_MAX - MRPC_MSG_ID_FLASH_IF_START];

#endif