/*
 * Copyright (c) 2025, LISTENAI
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#include "audio_adc_init.h"
#include "arcs_ap.h"

/**
 * @brief ADC GPIO 引脚配置
 *
 * 配置 MIC 引脚为差分输入模式
 */
int audio_adc_gpio_init(void)
{
    /* MIC0 使用 GPIOA_30 (INP) + GPIOA_31 (INN) - 差分输入 */
    /* MIC1 使用 GPIOA_28 (INP) + GPIOA_29 (INN) - 差分输入 */

    /* GPIOA_28 配置 - MIC1_INP */
    IP_CMN_IOMUX->REG_PAD_GPIOA_28.bit.PAD_GPIOA_28_OEN_FRC = 0x1;
    IP_CMN_IOMUX->REG_PAD_GPIOA_28.bit.PAD_GPIOA_28_OEN_REG = 0x1;
    IP_CMN_IOMUX->REG_PAD_GPIOA_28.bit.PAD_GPIOA_28_IE_FRC = 0x1;
    IP_CMN_IOMUX->REG_PAD_GPIOA_28.bit.PAD_GPIOA_28_IE_REG = 0x0;
    IP_CMN_IOMUX->REG_PAD_GPIOA_28.bit.PAD_GPIOA_28_PULL_FRC = 0x1;
    IP_CMN_IOMUX->REG_PAD_GPIOA_28.bit.PAD_GPIOA_28_PULL_UP = 0x0;
    IP_CMN_IOMUX->REG_PAD_GPIOA_28.bit.PAD_GPIOA_28_PULL_DN = 0x0;

    /* GPIOA_29 配置 - MIC1_INN */
    IP_CMN_IOMUX->REG_PAD_GPIOA_29.bit.PAD_GPIOA_29_OEN_FRC = 0x1;
    IP_CMN_IOMUX->REG_PAD_GPIOA_29.bit.PAD_GPIOA_29_OEN_REG = 0x1;
    IP_CMN_IOMUX->REG_PAD_GPIOA_29.bit.PAD_GPIOA_29_IE_FRC = 0x1;
    IP_CMN_IOMUX->REG_PAD_GPIOA_29.bit.PAD_GPIOA_29_IE_REG = 0x0;
    IP_CMN_IOMUX->REG_PAD_GPIOA_29.bit.PAD_GPIOA_29_PULL_FRC = 0x1;
    IP_CMN_IOMUX->REG_PAD_GPIOA_29.bit.PAD_GPIOA_29_PULL_UP = 0x0;
    IP_CMN_IOMUX->REG_PAD_GPIOA_29.bit.PAD_GPIOA_29_PULL_DN = 0x0;

    /* GPIOA_30 配置 - MIC0_INP */
    IP_CMN_IOMUX->REG_PAD_GPIOA_30.bit.PAD_GPIOA_30_OEN_FRC = 0x1;
    IP_CMN_IOMUX->REG_PAD_GPIOA_30.bit.PAD_GPIOA_30_OEN_REG = 0x1;
    IP_CMN_IOMUX->REG_PAD_GPIOA_30.bit.PAD_GPIOA_30_IE_FRC = 0x1;
    IP_CMN_IOMUX->REG_PAD_GPIOA_30.bit.PAD_GPIOA_30_IE_REG = 0x0;
    IP_CMN_IOMUX->REG_PAD_GPIOA_30.bit.PAD_GPIOA_30_PULL_FRC = 0x1;
    IP_CMN_IOMUX->REG_PAD_GPIOA_30.bit.PAD_GPIOA_30_PULL_UP = 0x0;
    IP_CMN_IOMUX->REG_PAD_GPIOA_30.bit.PAD_GPIOA_30_PULL_DN = 0x0;

    /* GPIOA_31 配置 - MIC0_INN */
    IP_CMN_IOMUX->REG_PAD_GPIOA_31.bit.PAD_GPIOA_31_OEN_FRC = 0x1;
    IP_CMN_IOMUX->REG_PAD_GPIOA_31.bit.PAD_GPIOA_31_OEN_REG = 0x1;
    IP_CMN_IOMUX->REG_PAD_GPIOA_31.bit.PAD_GPIOA_31_IE_FRC = 0x1;
    IP_CMN_IOMUX->REG_PAD_GPIOA_31.bit.PAD_GPIOA_31_IE_REG = 0x0;
    IP_CMN_IOMUX->REG_PAD_GPIOA_31.bit.PAD_GPIOA_31_PULL_FRC = 0x1;
    IP_CMN_IOMUX->REG_PAD_GPIOA_31.bit.PAD_GPIOA_31_PULL_UP = 0x0;
    IP_CMN_IOMUX->REG_PAD_GPIOA_31.bit.PAD_GPIOA_31_PULL_DN = 0x0;

    /* 功能选择 - MIC 功能 (FSEL=21) */
    IP_CMN_IOMUX->REG_PAD_GPIOA_30.bit.PAD_GPIOA_30_FSEL = 21; /* MIC0_INP */
    IP_CMN_IOMUX->REG_PAD_GPIOA_31.bit.PAD_GPIOA_31_FSEL = 21; /* MIC0_INN */
    IP_CMN_IOMUX->REG_PAD_GPIOA_28.bit.PAD_GPIOA_28_FSEL = 21; /* MIC1_INP */
    IP_CMN_IOMUX->REG_PAD_GPIOA_29.bit.PAD_GPIOA_29_FSEL = 21; /* MIC1_INN */

    return 0;
}

/**
 * @brief ADC 平台初始化
 */
int audio_adc_platform_init(void)
{
    /* 配置 GPIO 引脚 */
    audio_adc_gpio_init();

    /* ADC/PDM 时钟和电源在 HAL 层初始化时自动配置 */
    /* 配置 LDOVA 电压等级（根据 Kconfig 配置） */
#if defined(CONFIG_LISA_AUDIO_RECORD_LDOVA_1V68)
    IP_AON_CTRL->REG_AON_TUNE1.bit.TUNE_LDOVA = 0x8;
#elif defined(CONFIG_LISA_AUDIO_RECORD_LDOVA_1V785)
    IP_AON_CTRL->REG_AON_TUNE1.bit.TUNE_LDOVA = 0xf;
#elif defined(CONFIG_LISA_AUDIO_RECORD_LDOVA_1V8)
    IP_AON_CTRL->REG_AON_TUNE1.bit.TUNE_LDOVA = 0x0;
#elif defined(CONFIG_LISA_AUDIO_RECORD_LDOVA_1V815)
    IP_AON_CTRL->REG_AON_TUNE1.bit.TUNE_LDOVA = 0x1;
#elif defined(CONFIG_LISA_AUDIO_RECORD_LDOVA_1V905)
    IP_AON_CTRL->REG_AON_TUNE1.bit.TUNE_LDOVA = 0x7;
#else
    /* 默认使用 1.8V (0x0) */
    IP_AON_CTRL->REG_AON_TUNE1.bit.TUNE_LDOVA = 0x7;
#endif
    return 0;
}
