add_subdirectory(aacdec)
add_subdirectory(cjson)
add_subdirectory(collections-c)
add_subdirectory(coreHTTP)
add_subdirectory(coresntp)
add_subdirectory(coreMQTT)
add_subdirectory(coreMQTT-Agent)
add_subdirectory(cpputest)
add_subdirectory(cpr)
add_subdirectory(crc32)
add_subdirectory(csk_sqlite3)
add_subdirectory(EasyFlash)
add_subdirectory(easylogger)
add_subdirectory(fff)
add_subdirectory(flexlayout)
add_subdirectory(freertos)
add_subdirectory(FreeRTOS-CPP11)
add_subdirectory(freetype)
add_subdirectory(fs)
add_subdirectory(giflib)
add_subdirectory(googletest)
add_subdirectory(heap)
add_subdirectory(http_ssl)
add_subdirectory(httpclient)
add_subdirectory(ijg)
add_subdirectory(libjpeg-turbo)
add_subdirectory(letter-shell)
add_subdirectory(libcurl)
add_subdirectory(libico)
add_subdirectory(libid3tag)
add_subdirectory(libmad)
add_subdirectory(libpng)
add_subdirectory(libxml2)
add_subdirectory(lisa_player)
add_subdirectory(ltlsf)
add_subdirectory(lvgl)
add_subdirectory(lvgl8)
add_subdirectory(mac_manager)
add_subdirectory(mbedtls)
add_subdirectory(mempool)
add_subdirectory(mp3dec)
add_subdirectory(nopoll)
add_subdirectory(resample)
add_subdirectory(rtos_al)
add_subdirectory(speexdsp)
add_subdirectory(tinyusb)
add_subdirectory(uchardet)
add_subdirectory(unity)
add_subdirectory(wifi_manager)
add_subdirectory(zlib)
add_subdirectory(quirc)
add_subdirectory(cAT)
add_subdirectory(4g_module)
