# 项目可根据需要在此文件中设置对应的配置

# mbedtls
CONFIG_LWIP=n
CONFIG_SDK_MODULE_MBEDTLS=y
CONFIG_CUSTOM_MBEDTLS_CFG_FILE=y
CONFIG_MBEDTLS_CFG_FILE="config-tls-generic.h"

# ecdsa
CONFIG_MBEDTLS_ECP_C=y
CONFIG_MBEDTLS_ECDSA_C=y
CONFIG_MBEDTLS_ECDH_C=y
CONFIG_MBEDTLS_KEY_EXCHANGE_ECDH_ECDSA_ENABLED=y

# Elliptic curve
CONFIG_MBEDTLS_ECP_ALL_ENABLED=y

# message digest
CONFIG_MD_C=y
CONFIG_MBEDTLS_HASH_ALL_ENABLED=y

# entropy
CONFIG_MBEDTLS_MAC_SHA256_ENABLED=y
CONFIG_MBEDTLS_MAC_SHA384_ENABLED=y
CONFIG_MBEDTLS_MAC_SHA512_ENABLED=y

# hardware acceleration
CONFIG_MBEDTLS_HARDWARE_ENTROPY=y
CONFIG_MBEDTLS_HARDWARE_MPI_MODULAR_EXPONENTIATION=y
