# ============================================
# LISA Flash Dual-Core Example - CP Core
# (Master Core - Runs Flash Operations)
# ============================================

# Core Configuration
CONFIG_ARCS_CP_CORE=y
CONFIG_BOOT=n

# LISA Device Framework
CONFIG_LISA_DEVICE=y
CONFIG_LISA_FLASH=y
CONFIG_LISA_FLASH_ARCS_HALT_REMOTE_CORE=y

#IPC Configuration for Dual-Core
CONFIG_ARCS_HAL_IPC_MASTER=y

# Flash memory base address for CP core
CONFIG_MEM_FLASH_BASE=0x30080000

# HAL Configuration
CONFIG_LOG_MODE_ASYNC=n
CONFIG_EASYLOGGER_LOG_MODE_ASYNC=n
CONFIG_ARCS_HAL_EXT_RAM_SECTION=".ramcode"

# redefine memory config for CP core
CONFIG_MEM_SRAM_BASE=0x20030000
CONFIG_MEM_SRAM_SIZE=0x00020000
CONFIG_MEM_PSRAM_BASE=0x28100000
CONFIG_MEM_PSRAM_SIZE=0x00100000