
#ifndef _LS_RTOS_H_
#define _LS_RTOS_H_


#include "rtos_al.h"


enum
{
    LS_TCPIP_PRIORITY = RTOS_TASK_PRIORITY(9),
    LS_IPC_MSG_TASK_PRIORITY  = RTOS_TASK_PRIORITY(7),
    LS_IPC_RX_TASK_PRIORITY = RTOS_TASK_PRIORITY(9),
    LS_IPC_TXCFM_TASK_PRIORITY = RTOS_TASK_PRIORITY(9),
    LS_IPC_TX_TASK_PRIORITY = RTOS_TASK_PRIORITY(8),
    LS_IPC_RXCFM_TASK_PRIORITY = RTOS_TASK_PRIORITY(8),
    LS_MRPC_SERV_TASK_PRIORITY = RTOS_TASK_PRIORITY(9),
    LS_IPC_DBG_TASK_PRIORITY = RTOS_TASK_PRIORITY(1),
    LS_HALT_PEER_TASK_PRIORITY = RTOS_TASK_PRIORITY(10),
};

enum
{
    LS_TCPIP_STACK_SIZE = 2048,
    LS_IPC_MSG_TASK_STACK_SIZE  = 2048,
    LS_IPC_RX_DATA_TASK_STACK_SIZE = 2048,
    LS_IPC_TX_CFM_TASK_STACK_SIZE = 2048,
    LS_IPC_TX_TASK_STACK_SIZE = 2048,
    LS_IPC_RXCFM_TASK_STACK_SIZE = 2048,
    LS_MRPC_SERV_TASK_STACK_SIZE  = 2048,
    LS_IPC_DBG_TASK_STACK_SIZE  = 2048,
    LS_HALT_PEER_TASK_STACK_SIZE = 2048,
};

/// @}

#endif
