# 项目可根据需要在此文件中设置对应的配置
CONFIG_MEM_CONFIG=y
CONFIG_BACK_TRACE=y
CONFIG_FREERTOS_STATIC_ALLOCATION_ENABLE=1
CONFIG_FREERTOS_CPP11=y

CONFIG_LINK_OPTION_NONE_SPECS=y


# 文件系统配置
CONFIG_FILE_SYSTEM=y
CONFIG_FATFS_FILESYSTEM=y

# DISK驱动使能
CONFIG_DISK_DRIVER=y
CONFIG_DISK_DRIVER_SDMMC=y


# 抽象文件系统
CONFIG_LSFS=y
CONFIG_LSFS_FAT=y
CONFIG_LSFS_REGISTER_VFS=y

# 虚拟文件系统
CONFIG_LVFS=y
CONFIG_LVFS_POSIX_API=y
CONFIG_LVFS_POSIX_API_ALIAS=y

