CONFIG_BOOT=n
CONFIG_ARCS_AP_CORE=y

CONFIG_BACK_TRACE=y
CONFIG_MAIN_TASK_STACK_SIZE=2048
CONFIG_HEAP_SIZE=0x8000
CONFIG_PSRAM_INIT=y

CONFIG_ARCS_HAL_IPC=y
CONFIG_ARCS_HAL_IPC_AUTO_INIT=y
CONFIG_ARCS_HAL_PM=y
CONFIG_ARCS_HAL_VRTC=y
CONFIG_ARCS_HAL_PM_DEBUG=y
CONFIG_ARCS_HAL_PM_UART_WAKEUP=n
CONFIG_PM_SNAPSHOT_PSRAM_SIZE=0x10000

CONFIG_MEM_FLASH_BASE=0x30000000
CONFIG_MEM_FLASH_SIZE=0x00100000
CONFIG_MEM_PSRAM_BASE=0x28000000
CONFIG_MEM_PSRAM_SIZE=0x00400000
CONFIG_MEM_WFRAM_SIZE=0
CONFIG_MEM_WIFI_CALIBRATION_SIZE=0
CONFIG_MEM_WIFI_TRACE_SIZE=0
CONFIG_MEM_LUNA_SHARED_SIZE=0
CONFIG_MEM_IPC_ISOLATED=y
CONFIG_MEM_APRAM_SIZE=0

CONFIG_CONSOLE_UART_NAME="uart1"
CONFIG_CONSOLE_UART_BAUDRATE=115200
CONFIG_SYSLOG_UART_DEVICE_UART1=y
CONFIG_SYSLOG_UART_PORT=1
CONFIG_SYSLOG_UART_BAUDRATE=115200
CONFIG_PRINTF_LOG_REDIRECT=y

CONFIG_LOG_MODE_ASYNC=n
CONFIG_EASYLOGGER_LOG_MODE_ASYNC=n
CONFIG_EASYLOGGER_LINE_BUF_SIZE=512
