/**
 ****************************************************************************************
 *
 * Don't modify this file. It is automatically generated by a script.
 *
 * Author: KeHuatao
 *
 * Copyright (C) ListenAI 2025
 *
 ****************************************************************************************
 */
#include <stdio.h>
#include <stdint.h>
#include <string.h>
#include "ls_err.h"
#include "ipc.h"
#include "mrpc.h"
#include "mrpc_bt_s2m_api_msg.h"
#include "mrpc_bt_s2m_api_server.h"

static void mrpc_cp_btos_malloc_api(void *msg, struct mrpc_resp_msg *resp_msg, uint32_t resp_buf_len)
{
    mrpc_cp_btos_malloc_api_req_t *req;
    mrpc_cp_btos_malloc_api_resp_t *resp;

    req = (mrpc_cp_btos_malloc_api_req_t*)msg;
    resp = (mrpc_cp_btos_malloc_api_resp_t*)resp_msg;
    memset(resp, 0, sizeof(mrpc_cp_btos_malloc_api_resp_t));
    resp_msg->len = sizeof(mrpc_cp_btos_malloc_api_resp_t);
    resp_msg->status = cp_btos_malloc_api(&resp->buffer_ptr, req->size);
}

static void mrpc_cp_btos_free_api(void *msg, struct mrpc_resp_msg *resp_msg, uint32_t resp_buf_len)
{
    mrpc_cp_btos_free_api_req_t *req;
    mrpc_cp_btos_free_api_resp_t *resp;

    req = (mrpc_cp_btos_free_api_req_t*)msg;
    resp = (mrpc_cp_btos_free_api_resp_t*)resp_msg;
    memset(resp, 0, sizeof(mrpc_cp_btos_free_api_resp_t));
    resp_msg->len = sizeof(mrpc_cp_btos_free_api_resp_t);
    resp_msg->status = cp_btos_free_api(&req->ptr);
}


mrpc_msg_handler_t mrpc_msg_bt_s2m_handlers[MRPC_MSG_ID_BT_S2M_MAX - MRPC_MSG_ID_BT_S2M_START] =
{
    mrpc_cp_btos_malloc_api,  /*MRPC_MSG_ID_CP_BTOS_MALLOC_API*/
    mrpc_cp_btos_free_api,  /*MRPC_MSG_ID_CP_BTOS_FREE_API*/
    NULL
};
