/* AUTOGENERATED FILE. DO NOT EDIT. */

/*=======Test Runner Used To Run Each Test Below=====*/
#define RUN_TEST(TestFunc, TestLineNum)                                                                                \
    {                                                                                                                  \
        Unity.CurrentTestName = #TestFunc;                                                                             \
        Unity.CurrentTestLineNumber = TestLineNum;                                                                     \
        Unity.NumberOfTests++;                                                                                         \
        if (TEST_PROTECT()) {                                                                                          \
            setUp();                                                                                                   \
            TestFunc();                                                                                                \
        }                                                                                                              \
        if (TEST_PROTECT()) {                                                                                          \
            tearDown();                                                                                                \
        }                                                                                                              \
        UnityConcludeTest();                                                                                           \
    }

/*=======Automagically Detected Files To Include=====*/
#include "unity.h"
#include <setjmp.h>
#include <sys/stat.h>

#include "user_fs.h"
#include "lisa_sdmmc.h"
#include "IOMuxManager.h"

void setUp(void)
{
}

void tearDown(void)
{
}

/*=======Test Reset Option=====*/
void resetTest(void);
void resetTest(void)
{
    tearDown();
    setUp();
}

#include <stdio.h>
#include <string.h>
#include <errno.h>

void test_stat_check_if_dir(void)
{
    struct stat sb;
    int rc;

    remove("/SD:/test_stat_check_if_dir");
    mkdir("/SD:/test_stat_check_if_dir", 0755);

    rc = stat("/SD:/test_stat_check_if_dir", &sb);
    TEST_ASSERT_EQUAL_INT(0, rc);
    printf("sb.st_mode: 0x%X, sb.st_size: %d\n", sb.st_mode, sb.st_size);

    TEST_ASSERT_TRUE(S_ISDIR(sb.st_mode));

    remove("/SD:/test_stat_check_if_dir");
}

void test_stat_dir_size(void)
{
    struct stat sb;
    int rc;

    remove("/SD:/test_stat_dir_size");
    mkdir("/SD:/test_stat_dir_size", 0755);

    rc = stat("/SD:/test_stat_dir_size", &sb);

    TEST_ASSERT_EQUAL(0, sb.st_size);

    remove("/SD:/test_stat_dir_size");
}


void test_mkdir_func(void)
{
    int ret = 0;

    ret = mkdir("/SD:/test_mkdir_func", 0755);
    TEST_ASSERT_EQUAL_INT(0, ret);

    remove("/SD:/test_mkdir_func");
}

void test_mkdir_with_exist_dir_name(void)
{
    int ret = 0;

    remove("/SD:/test_mkdir_with_exist_dir_name");
    mkdir("/SD:/test_mkdir_with_exist_dir_name", 0755);

    ret = mkdir("/SD:/test_mkdir_with_exist_dir_name", 0755);
    TEST_ASSERT_EQUAL_INT(-EEXIST, ret);

    remove("/SD:/test_mkdir_with_exist_dir_name");
}

void test_stat_not_exist_folder(void)
{
    struct stat sb;
    int rc;

    rc = stat("/SD:/test_stat_not_exist_folder", &sb);
    TEST_ASSERT_EQUAL_INT(-ENOENT, rc);
}

void test_stat_file_size(void)
{
    const char *filename = "/SD:/test_stat_file_size.txt";
    const char *test_data = "hello, world!";
    size_t data_len = strlen(test_data);
    FILE *fp;
    struct stat sb;
    int ret;

    remove(filename); 
    fp = fopen(filename, "w");
    TEST_ASSERT_NOT_NULL(fp);
    fwrite(test_data, 1, data_len, fp);
    fclose(fp);

    ret = stat(filename, &sb);
    TEST_ASSERT_EQUAL_INT(0, ret);

    TEST_ASSERT_EQUAL(data_len, sb.st_size);

    remove(filename);
}

void test_stat_root_path_is_a_dir(void)
{
    struct stat sb;
    int rc;

    rc = stat("/SD:/", &sb);

    TEST_ASSERT_EQUAL_INT(0, rc);
    TEST_ASSERT_TRUE(S_ISDIR(sb.st_mode));
}


/*=======MAIN=====*/
int main(void)
{
    /* Configure SDMMC pins (same as lisa_disk test) */
    IOMuxManager_PinConfigure(CSK_IOMUX_PAD_A, 6, CSK_IOMUX_FUNC_ALTER15); /* CLK */
    IOMuxManager_PinConfigure(CSK_IOMUX_PAD_A, 7, CSK_IOMUX_FUNC_ALTER15); /* CMD */
    IOMuxManager_PinConfigure(CSK_IOMUX_PAD_A, 5, CSK_IOMUX_FUNC_ALTER15); /* DAT0 */
    IOMuxManager_PinConfigure(CSK_IOMUX_PAD_A, 4, CSK_IOMUX_FUNC_ALTER15); /* DAT1 */
    IOMuxManager_PinConfigure(CSK_IOMUX_PAD_A, 9, CSK_IOMUX_FUNC_ALTER15); /* DAT2 */
    IOMuxManager_PinConfigure(CSK_IOMUX_PAD_A, 8, CSK_IOMUX_FUNC_ALTER15); /* DAT3 */

    user_fs_init();

    printf("user fs init complete\n");

    UnityBegin("test/stat_func/test_stat.c");
    RUN_TEST(test_mkdir_func, __LINE__);
    RUN_TEST(test_mkdir_with_exist_dir_name, __LINE__);
    RUN_TEST(test_stat_check_if_dir, __LINE__);
    RUN_TEST(test_stat_not_exist_folder, __LINE__);
    RUN_TEST(test_stat_dir_size, __LINE__);
    RUN_TEST(test_stat_file_size, __LINE__);
    RUN_TEST(test_stat_root_path_is_a_dir, __LINE__);

    return (UnityEnd());
}
