CONFIG_LOG=y
CONFIG_PRINTF_LOG_REDIRECT=y
CONFIG_ARCS_AP_CORE=y
CONFIG_THINKER_LIB=y
CONFIG_MAIN_TASK_STACK_SIZE=4096
CONFIG_HEAP_SIZE=0x8000
CONFIG_PSRAM_HEAP_SIZE=0x200000
CONFIG_MEM_FLASH_SIZE=0x00300000
CONFIG_THINKER_RESNET18_MODEL_ADDR=0x30300000
CONFIG_THINKER_RESNET18_MODEL_SIZE=0x1FD1E0
CONFIG_THINKER_RESNET18_PSRAM_POOL_SIZE=0x10000
CONFIG_THINKER_RESNET18_SHARE_POOL_SIZE=0x58000
