CONFIG_LOG=n
CONFIG_PRINTF_LOG_REDIRECT=n
CONFIG_ARCS_AP_CORE=y
CONFIG_FREERTOS_STACK_HW_CHECK=n
CONFIG_MODULE_FREERTOS=n

CONFIG_LISA_DEVICE=n
CONFIG_LISA_OS=n

CONFIG_CONSOLE=n

CONFIG_CONSOLE_UART_BACKEND=n

CONFIG_VADDR_REMAP_SAMPLE_BOOT_VARIANT_NAME="AP"
CONFIG_VADDR_REMAP_SAMPLE_FW_FLASH_OFFSET=0x20000
