CONFIG_LOG=y
CONFIG_PRINTF_LOG_REDIRECT=n
CONFIG_ARCS_AP_CORE=y
CONFIG_FREERTOS_STACK_HW_CHECK=n

CONFIG_VADDR_REMAP_SAMPLE_BOOT_VARIANT_NAME="CP"
CONFIG_VADDR_REMAP_SAMPLE_FW_FLASH_OFFSET=0x20000
CONFIG_VADDR_REMAP_SAMPLE_BOOT_FW_IN_CP=y
