#ifndef TEST_USB_CONFIG_H
#define TEST_USB_CONFIG_H
#include <stdio.h>
#define CONFIG_USB_PRINTF(...) printf(__VA_ARGS__)
#define CONFIG_USB_DBG_LEVEL USB_DBG_ERROR
#define CONFIG_USB_MUSB_EP_NUM 8
#define CONFIG_USBDEV_MAX_BUS 1
#define CONFIG_USBDEV_EP_NUM 8
#define CONFIG_USBDEV_REQUEST_BUFFER_LEN 512
#define CONFIG_USB_ALIGN_SIZE 4
#define CONFIG_CHERRYUSB_DEVICE_MUSB_LISA 1
#define USB_NOCACHE_RAM_SECTION
#endif
