#pragma once

#include "IOMuxManager.h"

#define LISA_CP_LOG_UART_RX_PORT        CSK_IOMUX_PAD_A
#define LISA_CP_LOG_UART_RX_PIN         2
#define LISA_CP_LOG_UART_RX_FUNC        CSK_IOMUX_FUNC_ALTER2

#define LISA_CP_LOG_UART_TX_PORT        CSK_IOMUX_PAD_A
#define LISA_CP_LOG_UART_TX_PIN         3
#define LISA_CP_LOG_UART_TX_FUNC        CSK_IOMUX_FUNC_ALTER2

#define LISA_EMMC_PORT                 CSK_IOMUX_PAD_A
#define LISA_EMMC_CLK_PIN              6
#define LISA_EMMC_CLK_FUNC             CSK_IOMUX_FUNC_ALTER15
#define LISA_EMMC_CMD_PIN              7
#define LISA_EMMC_CMD_FUNC             CSK_IOMUX_FUNC_ALTER15
#define LISA_EMMC_D0_PIN               5
#define LISA_EMMC_D0_FUNC              CSK_IOMUX_FUNC_ALTER15
#define LISA_EMMC_D1_PIN               4
#define LISA_EMMC_D1_FUNC              CSK_IOMUX_FUNC_ALTER15
#define LISA_EMMC_D2_PIN               9
#define LISA_EMMC_D2_FUNC              CSK_IOMUX_FUNC_ALTER15
#define LISA_EMMC_D3_PIN               8
#define LISA_EMMC_D3_FUNC              CSK_IOMUX_FUNC_ALTER15

#define LISA_AP_LOG_UART_TX_PORT        CSK_IOMUX_PAD_B
#define LISA_AP_LOG_UART_TX_PIN         2
#define LISA_AP_LOG_UART_TX_FUNC        CSK_IOMUX_FUNC_ALTER3

#define LISA_DISPLAY_SPI_DEV            SPI1()
#define LISA_DISPLAY_SPI_CS_PORT        CSK_IOMUX_PAD_A
#define LISA_DISPLAY_SPI_CS_PIN         13
#define LISA_DISPLAY_SPI_CS_FUNC        CSK_IOMUX_FUNC_DEFAULT

#define LISA_DISPLAY_SPI_SDA_PORT       CSK_IOMUX_PAD_A
#define LISA_DISPLAY_SPI_SDA_PIN        15
#define LISA_DISPLAY_SPI_SDA_FUNC       CSK_IOMUX_FUNC_ALTER6

#define LISA_DISPLAY_SPI_DC_PORT        CSK_IOMUX_PAD_A
#define LISA_DISPLAY_SPI_DC_PIN         19
#define LISA_DISPLAY_SPI_DC_FUNC        CSK_IOMUX_FUNC_DEFAULT

#define LISA_DISPLAY_SPI_CLK_PORT       CSK_IOMUX_PAD_A
#define LISA_DISPLAY_SPI_CLK_PIN        17
#define LISA_DISPLAY_SPI_CLK_FUNC       CSK_IOMUX_FUNC_ALTER6

#define LISA_DISPLAY_BUSY_PORT          CSK_IOMUX_PAD_A
#define LISA_DISPLAY_BUSY_PIN           14
#define LISA_DISPLAY_BUSY_FUNC          CSK_IOMUX_FUNC_DEFAULT

#define LISA_DISPLAY_RESET_PORT         CSK_IOMUX_PAD_A
#define LISA_DISPLAY_RESET_PIN          10
#define LISA_DISPLAY_RESET_FUNC         CSK_IOMUX_FUNC_DEFAULT

#define LISA_CAMERA_SPI                 SPI0()
#define LISA_CAMERA_SPI_CS_PORT         CSK_IOMUX_PAD_A
#define LISA_CAMERA_SPI_CS_PIN          22
#define LISA_CAMERA_SPI_CS_FUNC         CSK_IOMUX_FUNC_DEFAULT

#define LISA_CAMERA_SPI_CLK_PORT        CSK_IOMUX_PAD_A
#define LISA_CAMERA_SPI_CLK_PIN         25
#define LISA_CAMERA_SPI_CLK_FUNC        CSK_IOMUX_FUNC_ALTER5

#define LISA_CAMERA_SPI_DO_PORT         CSK_IOMUX_PAD_A
#define LISA_CAMERA_SPI_DO_PIN          24
#define LISA_CAMERA_SPI_DO_FUNC         CSK_IOMUX_FUNC_ALTER5

#define LISA_CAMERA_I2C_SDA_PORT         CSK_IOMUX_PAD_B
#define LISA_CAMERA_I2C_SDA_PIN          0
#define LISA_CAMERA_I2C_SDA_FUNC         CSK_IOMUX_FUNC_ALTER8

#define LISA_CAMERA_I2C_SCL_PORT        CSK_IOMUX_PAD_B
#define LISA_CAMERA_I2C_SCL_PIN         1
#define LISA_CAMERA_I2C_SCL_FUNC        CSK_IOMUX_FUNC_ALTER8

#define LISA_CAMERA_MCLK_PORT           CSK_IOMUX_PAD_A
#define LISA_CAMERA_MCLK_PIN            26
#define LISA_CAMERA_MCLK_FUNC           CSK_IOMUX_FUNC_ALTER16

#define LISA_CAMERA_LED_PORT             CSK_IOMUX_PAD_A
#define LISA_CAMERA_LED_PIN              23
#define LISA_CAMERA_LED_FUNC             CSK_IOMUX_FUNC_DEFAULT

#define LISA_KEY1_PORT                   CSK_IOMUX_PAD_A
#define LISA_KEY1_PIN                    27
#define LISA_KEY1_FUNC                   CSK_IOMUX_FUNC_DEFAULT

#define LISA_KEY2_PORT                   CSK_IOMUX_PAD_A
#define LISA_KEY2_PIN                    12
#define LISA_KEY2_FUNC                   CSK_IOMUX_FUNC_DEFAULT

#define LISA_KEY3_PORT                   CSK_IOMUX_PAD_A
#define LISA_KEY3_PIN                    16
#define LISA_KEY3_FUNC                   CSK_IOMUX_FUNC_DEFAULT

#define LISA_KEY_PWR_PORT                CSK_IOMUX_PAD_B
#define LISA_KEY_PWR_PIN                 3
#define LISA_KEY_PWR_FUNC                CSK_IOMUX_FUNC_DEFAULT

#define LISA_KEY_VOICE_PORT               CSK_IOMUX_PAD_B
#define LISA_KEY_VOICE_PIN                4
#define LISA_KEY_VOICE_FUNC               CSK_IOMUX_FUNC_DEFAULT

#define LISA_LED_G_PORT                   CSK_IOMUX_PAD_A
#define LISA_LED_G_PIN                    20
#define LISA_LED_G_FUNC                   CSK_IOMUX_FUNC_DEFAULT

#define LISA_LED_B_PORT                   CSK_IOMUX_PAD_A
#define LISA_LED_B_PIN                    21
#define LISA_LED_B_FUNC                   CSK_IOMUX_FUNC_DEFAULT

#define LISA_BATT_ADC_AON_PORT           CSK_IOMUX_PAD_B
#define LISA_BATT_ADC_AON_PIN            6
#define LISA_BATT_ADC_AON_FUNC           CSK_AON_IOMUX_FUNC_ALTER3

#define LISA_KEY_ADC_AON_PORT            CSK_IOMUX_PAD_B
#define LISA_KEY_ADC_AON_PIN             7
#define LISA_KEY_ADC_AON_FUNC            CSK_AON_IOMUX_FUNC_ALTER3

typedef struct{
    uint8_t pad;
    uint8_t pin_num;
    uint32_t pin_cfg;
} board_iomux_config_t;

static const board_iomux_config_t board_iomux_config[] = {
#ifdef CONFIG_ARCS_CP_CORE
    {LISA_CP_LOG_UART_RX_PORT,LISA_CP_LOG_UART_RX_PIN,LISA_CP_LOG_UART_RX_FUNC},
    {LISA_CP_LOG_UART_TX_PORT,LISA_CP_LOG_UART_TX_PIN,LISA_CP_LOG_UART_TX_FUNC},
    {LISA_EMMC_PORT,LISA_EMMC_CLK_PIN,LISA_EMMC_CLK_FUNC},
    {LISA_EMMC_PORT,LISA_EMMC_CMD_PIN,LISA_EMMC_CMD_FUNC},
    {LISA_EMMC_PORT,LISA_EMMC_D0_PIN,LISA_EMMC_D0_FUNC},
    {LISA_EMMC_PORT,LISA_EMMC_D1_PIN,LISA_EMMC_D1_FUNC},
    {LISA_EMMC_PORT,LISA_EMMC_D2_PIN,LISA_EMMC_D2_FUNC},
    {LISA_EMMC_PORT,LISA_EMMC_D3_PIN,LISA_EMMC_D3_FUNC},
    {LISA_CAMERA_MCLK_PORT,LISA_CAMERA_MCLK_PIN,LISA_CAMERA_MCLK_FUNC},
    {LISA_CAMERA_LED_PORT,LISA_CAMERA_LED_PIN,LISA_CAMERA_LED_FUNC},

    {LISA_KEY_PWR_PORT,LISA_KEY_PWR_PIN,LISA_KEY_PWR_FUNC},
    {LISA_KEY_VOICE_PORT,LISA_KEY_VOICE_PIN,LISA_KEY_VOICE_FUNC},
    {LISA_KEY3_PORT,LISA_KEY3_PIN,LISA_KEY3_FUNC},
    {LISA_KEY2_PORT,LISA_KEY2_PIN,LISA_KEY2_FUNC},
    {LISA_KEY1_PORT,LISA_KEY1_PIN,LISA_KEY1_FUNC},
    {LISA_LED_G_PORT,LISA_LED_G_PIN,LISA_LED_G_FUNC},
    {LISA_LED_B_PORT,LISA_LED_B_PIN,LISA_LED_B_FUNC},
#elif(CONFIG_ARCS_AP_CORE)
    {LISA_AP_LOG_UART_TX_PORT,LISA_AP_LOG_UART_TX_PIN,LISA_AP_LOG_UART_TX_FUNC},
#endif
#ifdef CONFIG_LISA_DISPLAY
    {LISA_DISPLAY_SPI_CS_PORT,LISA_DISPLAY_SPI_CS_PIN,LISA_DISPLAY_SPI_CS_FUNC},
    {LISA_DISPLAY_SPI_SDA_PORT,LISA_DISPLAY_SPI_SDA_PIN,LISA_DISPLAY_SPI_SDA_FUNC},
    {LISA_DISPLAY_SPI_DC_PORT,LISA_DISPLAY_SPI_DC_PIN,LISA_DISPLAY_SPI_DC_FUNC},
    {LISA_DISPLAY_SPI_CLK_PORT,LISA_DISPLAY_SPI_CLK_PIN,LISA_DISPLAY_SPI_CLK_FUNC},
    {LISA_DISPLAY_BUSY_PORT,LISA_DISPLAY_BUSY_PIN,LISA_DISPLAY_BUSY_FUNC},
    {LISA_DISPLAY_RESET_PORT,LISA_DISPLAY_RESET_PIN,LISA_DISPLAY_RESET_FUNC},
#endif
#ifdef CONFIG_COMPONENT_CAMERA
    {LISA_CAMERA_SPI_CS_PORT,LISA_CAMERA_SPI_CS_PIN,LISA_CAMERA_SPI_CS_FUNC},
    {LISA_CAMERA_SPI_CLK_PORT,LISA_CAMERA_SPI_CLK_PIN,LISA_CAMERA_SPI_CLK_FUNC},
    {LISA_CAMERA_SPI_DO_PORT,LISA_CAMERA_SPI_DO_PIN,LISA_CAMERA_SPI_DO_FUNC},
    {LISA_CAMERA_I2C_SDA_PORT,LISA_CAMERA_I2C_SDA_PIN,LISA_CAMERA_I2C_SDA_FUNC},
    {LISA_CAMERA_I2C_SCL_PORT,LISA_CAMERA_I2C_SCL_PIN,LISA_CAMERA_I2C_SCL_FUNC},
#endif

};

static const board_iomux_config_t board_iomux_aon_config[] = {
#ifdef CONFIG_ARCS_CP_CORE
    {LISA_BATT_ADC_AON_PORT,LISA_BATT_ADC_AON_PIN,LISA_BATT_ADC_AON_FUNC},
    {LISA_KEY_ADC_AON_PORT,LISA_KEY_ADC_AON_PIN,LISA_KEY_ADC_AON_FUNC},   
#endif
};
