#ifndef __ARCS_MEMAP_HEADER__
#define __ARCS_MEMAP_HEADER__

#if CONFIG_MEM_CONFIG

/* sram */
#define MEM_SRAM_BASE   CONFIG_MEM_SRAM_BASE
#define MEM_SRAM_SIZE   CONFIG_MEM_SRAM_SIZE

/* psram */
#define MEM_PSRAM_BASE  CONFIG_MEM_PSRAM_BASE
#define MEM_PSRAM_SIZE  CONFIG_MEM_PSRAM_SIZE

/* luna */
#define MEM_LUNA_BASE  CONFIG_MEM_LUNA_BASE
#define MEM_LUNA_SIZE  CONFIG_MEM_LUNA_SIZE

/* BT */
#define MEM_BTRAM_BASE  CONFIG_MEM_BTRAM_BASE
#define MEM_BTRAM_SIZE  CONFIG_MEM_BTRAM_SIZE

/* flash */
#if CONFIG_BOOT
#define MEM_FLASH_BASE  (CONFIG_MEM_FLASH_BASE + CONFIG_BOOT_FLASH_SIZE)
#define MEM_FLASH_SIZE  (CONFIG_MEM_FLASH_SIZE - CONFIG_BOOT_FLASH_SIZE)
#else
#define MEM_FLASH_BASE  CONFIG_MEM_FLASH_BASE
#define MEM_FLASH_SIZE  CONFIG_MEM_FLASH_SIZE
#endif

#if CONFIG_MEM_WFRAM_ISOLATED
/* wifi */
#define MEM_WFRAM_BASE  CONFIG_MEM_WFRAM_BASE
#define MEM_WFRAM_SIZE  CONFIG_MEM_WFRAM_SIZE
#endif

/* ilm */
#define MEM_ILM_BASE    CONFIG_MEM_ILM_BASE
#define MEM_ILM_SIZE    CONFIG_MEM_ILM_SIZE

/* dlm */
#define MEM_DLM_BASE    CONFIG_MEM_DLM_BASE
#define MEM_DLM_SIZE    CONFIG_MEM_DLM_SIZE

#if CONFIG_MEM_IPC_ISOLATED
/* ipc */
#define MEM_IPC_BASE    CONFIG_MEM_IPC_BASE
#define MEM_IPC_SIZE    CONFIG_MEM_IPC_SIZE
#endif

#define MEM_WIFI_CALIBRATION_SIZE CONFIG_MEM_WIFI_CALIBRATION_SIZE
#define MEM_WIFI_TRACE_SIZE       CONFIG_MEM_WIFI_TRACE_SIZE

#define MEM_INTERRUPT_STACK_SIZE  CONFIG_MEM_INTERRUPT_STACK_SIZE

#else

#define MEM_SRAM_BASE   0x20050000
#define MEM_SRAM_SIZE   (384 * 1024)

#define MEM_PSRAM_BASE  0x28000000
#define MEM_PSRAM_SIZE  (8 * 1024 * 1024)

#if CONFIG_BOOT
#define MEM_FLASH_BASE  (0x30000000 + CONFIG_BOOT_FLASH_SIZE)
#define MEM_FLASH_SIZE  (8 * 1024 * 1024 - CONFIG_BOOT_FLASH_SIZE)
#else
#define MEM_FLASH_BASE  0x30000000
#define MEM_FLASH_SIZE  (8 * 1024 * 1024)
#define MEM_FLASH_EX_BASE  0x31000000
#define MEM_FLASH_EX_SIZE  (__MB__(16)) //外部flash大小, 目前
#endif

#define MEM_WFRAM_BASE  0x20000000
#define MEM_WFRAM_SIZE  (256 * 1024)

#define MEM_ILM_BASE    0x00080000
#define MEM_ILM_SIZE    (16 * 1024)

#define MEM_DLM_BASE    0x00100000
#define MEM_DLM_SIZE    (8 * 1024)

#define MEM_WIFI_CALIBRATION_SIZE (16 * 1024)
#define MEM_WIFI_TRACE_SIZE       (8 * 1024)

#define MEM_INTERRUPT_STACK_SIZE  (4 * 1024)
#endif

#endif//__ARCS_MEMAP_HEADER__
