//  ----------------------------------------------------------------------
//  File Name   : GenCFold/aon_wdt_reg_arcs.h
//  Description : C header file generated by Python script.
//  Script Ver  £ºLS.AUTO_REG.2024.03.01
//  Create Time : 2024-06-20 11:17:02
//  Comments    : 
//  ----------------------------------------------------------------------

#ifndef __AON_WDT_REGFILE_H__
#define __AON_WDT_REGFILE_H__

#include <stdint.h>

#define AON_WDT_AON_WDTTIMER_CTRL_OFFSET            0x000
#define AON_WDT_AON_WDTTIMER_CTRL_LOAD_PROTECTED_Pos    8
#define AON_WDT_AON_WDTTIMER_CTRL_LOAD_PROTECTED_Msk    0x100
#define AON_WDT_AON_WDTTIMER_CTRL_STOP_PROTECTED_Pos    7
#define AON_WDT_AON_WDTTIMER_CTRL_STOP_PROTECTED_Msk    0x80
#define AON_WDT_AON_WDTTIMER_CTRL_START_PROTECTED_Pos    6
#define AON_WDT_AON_WDTTIMER_CTRL_START_PROTECTED_Msk    0x40
#define AON_WDT_AON_WDTTIMER_CTRL_WDENABLED_Pos     5
#define AON_WDT_AON_WDTTIMER_CTRL_WDENABLED_Msk     0x20
#define AON_WDT_AON_WDTTIMER_CTRL_RELOAD_Pos        4
#define AON_WDT_AON_WDTTIMER_CTRL_RELOAD_Msk        0x10
#define AON_WDT_AON_WDTTIMER_CTRL_WDT_MODE_Pos      3
#define AON_WDT_AON_WDTTIMER_CTRL_WDT_MODE_Msk      0x8
#define AON_WDT_AON_WDTTIMER_CTRL_STOP_Pos          2
#define AON_WDT_AON_WDTTIMER_CTRL_STOP_Msk          0x4
#define AON_WDT_AON_WDTTIMER_CTRL_WDT_INT_MASK_Pos    1
#define AON_WDT_AON_WDTTIMER_CTRL_WDT_INT_MASK_Msk    0x2
#define AON_WDT_AON_WDTTIMER_CTRL_START_Pos         0
#define AON_WDT_AON_WDTTIMER_CTRL_START_Msk         0x1

#define AON_WDT_STOP_PROTECT_OFFSET                 0x004
#define AON_WDT_STOP_PROTECT_STOP_LOCK_Pos          0
#define AON_WDT_STOP_PROTECT_STOP_LOCK_Msk          0x1

#define AON_WDT_OTHER_PROTECT_OFFSET                0x008
#define AON_WDT_OTHER_PROTECT_START_LOAD_LOCK_Pos    0
#define AON_WDT_OTHER_PROTECT_START_LOAD_LOCK_Msk    0x1

#define AON_WDT_RESET_PMU_EN_OFFSET                 0x00C
#define AON_WDT_RESET_PMU_EN_WDT_RESET_PMU_EN_Pos    0
#define AON_WDT_RESET_PMU_EN_WDT_RESET_PMU_EN_Msk    0x1

#define AON_WDT_AONWDTTIMER_LOADVAL_OFFSET          0x010
#define AON_WDT_AONWDTTIMER_LOADVAL_LOADVAL_Pos     0
#define AON_WDT_AONWDTTIMER_LOADVAL_LOADVAL_Msk     0xffffff

#define AON_WDT_AON_WDT_IRQ_CLR_OFFSET              0x014
#define AON_WDT_AON_WDT_IRQ_CLR_AONWDT_CLR_Pos      0
#define AON_WDT_AON_WDT_IRQ_CLR_AONWDT_CLR_Msk      0x1

#define AON_WDT_AON_WDT_IRQ_CAUSE_OFFSET            0x018
#define AON_WDT_AON_WDT_IRQ_CAUSE_WDT_RESET_OCURRED_Pos    17
#define AON_WDT_AON_WDT_IRQ_CAUSE_WDT_RESET_OCURRED_Msk    0x20000
#define AON_WDT_AON_WDT_IRQ_CAUSE_WDT_WAKEUP_STATUS_Pos    16
#define AON_WDT_AON_WDT_IRQ_CAUSE_WDT_WAKEUP_STATUS_Msk    0x10000
#define AON_WDT_AON_WDT_IRQ_CAUSE_AONWDT_IRQ_CAUSE_Pos    0
#define AON_WDT_AON_WDT_IRQ_CAUSE_AONWDT_IRQ_CAUSE_Msk    0x1

struct AON_WDT_REG_AON_WDTTIMER_CTRL_BITS
{
    volatile uint32_t START                         : 1; // bit 0~0
    volatile uint32_t WDT_INT_MASK                  : 1; // bit 1~1
    volatile uint32_t STOP                          : 1; // bit 2~2
    volatile uint32_t WDT_MODE                      : 1; // bit 3~3
    volatile uint32_t RELOAD                        : 1; // bit 4~4
    volatile uint32_t WDENABLED                     : 1; // bit 5~5
    volatile uint32_t START_PROTECTED               : 1; // bit 6~6
    volatile uint32_t STOP_PROTECTED                : 1; // bit 7~7
    volatile uint32_t LOAD_PROTECTED                : 1; // bit 8~8
    volatile uint32_t RESV_9_31                     : 23; // bit 9~31
};

union AON_WDT_REG_AON_WDTTIMER_CTRL {
    volatile uint32_t                               all;
    struct AON_WDT_REG_AON_WDTTIMER_CTRL_BITS       bit;
};

struct AON_WDT_REG_STOP_PROTECT_BITS
{
    volatile uint32_t STOP_LOCK                     : 1; // bit 0~0
    volatile uint32_t RESV_1_31                     : 31; // bit 1~31
};

union AON_WDT_REG_STOP_PROTECT {
    volatile uint32_t                               all;
    struct AON_WDT_REG_STOP_PROTECT_BITS            bit;
};

struct AON_WDT_REG_OTHER_PROTECT_BITS
{
    volatile uint32_t START_LOAD_LOCK               : 1; // bit 0~0
    volatile uint32_t RESV_1_31                     : 31; // bit 1~31
};

union AON_WDT_REG_OTHER_PROTECT {
    volatile uint32_t                               all;
    struct AON_WDT_REG_OTHER_PROTECT_BITS           bit;
};

struct AON_WDT_REG_RESET_PMU_EN_BITS
{
    volatile uint32_t WDT_RESET_PMU_EN              : 1; // bit 0~0
    volatile uint32_t RESV_1_31                     : 31; // bit 1~31
};

union AON_WDT_REG_RESET_PMU_EN {
    volatile uint32_t                               all;
    struct AON_WDT_REG_RESET_PMU_EN_BITS            bit;
};

struct AON_WDT_REG_AONWDTTIMER_LOADVAL_BITS
{
    volatile uint32_t LOADVAL                       : 24; // bit 0~23
    volatile uint32_t RESV_24_31                    : 8; // bit 24~31
};

union AON_WDT_REG_AONWDTTIMER_LOADVAL {
    volatile uint32_t                               all;
    struct AON_WDT_REG_AONWDTTIMER_LOADVAL_BITS     bit;
};

struct AON_WDT_REG_AON_WDT_IRQ_CLR_BITS
{
    volatile uint32_t AONWDT_CLR                    : 1; // bit 0~0
    volatile uint32_t RESV_1_31                     : 31; // bit 1~31
};

union AON_WDT_REG_AON_WDT_IRQ_CLR {
    volatile uint32_t                               all;
    struct AON_WDT_REG_AON_WDT_IRQ_CLR_BITS         bit;
};

struct AON_WDT_REG_AON_WDT_IRQ_CAUSE_BITS
{
    volatile uint32_t AONWDT_IRQ_CAUSE              : 1; // bit 0~0
    volatile uint32_t RESV_1_15                     : 15; // bit 1~15
    volatile uint32_t WDT_WAKEUP_STATUS             : 1; // bit 16~16
    volatile uint32_t WDT_RESET_OCURRED             : 1; // bit 17~17
    volatile uint32_t RESV_18_31                    : 14; // bit 18~31
};

union AON_WDT_REG_AON_WDT_IRQ_CAUSE {
    volatile uint32_t                               all;
    struct AON_WDT_REG_AON_WDT_IRQ_CAUSE_BITS       bit;
};

typedef struct
{
    union AON_WDT_REG_AON_WDTTIMER_CTRL             REG_AON_WDTTIMER_CTRL; // 0x000
    union AON_WDT_REG_STOP_PROTECT                  REG_STOP_PROTECT; // 0x004
    union AON_WDT_REG_OTHER_PROTECT                 REG_OTHER_PROTECT; // 0x008
    union AON_WDT_REG_RESET_PMU_EN                  REG_RESET_PMU_EN; // 0x00C
    union AON_WDT_REG_AONWDTTIMER_LOADVAL           REG_AONWDTTIMER_LOADVAL; // 0x010
    union AON_WDT_REG_AON_WDT_IRQ_CLR               REG_AON_WDT_IRQ_CLR; // 0x014
    union AON_WDT_REG_AON_WDT_IRQ_CAUSE             REG_AON_WDT_IRQ_CAUSE; // 0x018
} AON_WDT_RegDef;


#endif // __AON_WDT_REGFILE_H__

