//  ----------------------------------------------------------------------
//  File Name   : GenCFold/crypto_aes_reg_arcs.h
//  Description : C header file generated by Python script.
//  Script Ver  £ºLS.AUTO_REG.2024.03.01
//  Create Time : 2024-06-20 11:17:02
//  Comments    : 
//  ----------------------------------------------------------------------

#ifndef __CRYPTO_AES_REGFILE_H__
#define __CRYPTO_AES_REGFILE_H__

#include <stdint.h>

#define CRYPTO_AES_AES_MSG_CFG_OFFSET               0x000
#define CRYPTO_AES_AES_MSG_CFG_AES_KEY_SIZE_Pos     12
#define CRYPTO_AES_AES_MSG_CFG_AES_KEY_SIZE_Msk     0x3000
#define CRYPTO_AES_AES_MSG_CFG_AES_MAC_LEN_Pos      8
#define CRYPTO_AES_AES_MSG_CFG_AES_MAC_LEN_Msk      0xf00
#define CRYPTO_AES_AES_MSG_CFG_AES_ALG_MODE_Pos     4
#define CRYPTO_AES_AES_MSG_CFG_AES_ALG_MODE_Msk     0xf0
#define CRYPTO_AES_AES_MSG_CFG_AES_ENCRYPT_Pos      3
#define CRYPTO_AES_AES_MSG_CFG_AES_ENCRYPT_Msk      0x8
#define CRYPTO_AES_AES_MSG_CFG_AES_MSG_BEGIN_Pos    2
#define CRYPTO_AES_AES_MSG_CFG_AES_MSG_BEGIN_Msk    0x4
#define CRYPTO_AES_AES_MSG_CFG_AES_MSG_END_Pos      1
#define CRYPTO_AES_AES_MSG_CFG_AES_MSG_END_Msk      0x2
#define CRYPTO_AES_AES_MSG_CFG_AES_GO_Pos           0
#define CRYPTO_AES_AES_MSG_CFG_AES_GO_Msk           0x1

#define CRYPTO_AES_AES_CTX_CFG_OFFSET               0x004
#define CRYPTO_AES_AES_CTX_CFG_AES_CTX_INDEX_Pos    4
#define CRYPTO_AES_AES_CTX_CFG_AES_CTX_INDEX_Msk    0xfff0
#define CRYPTO_AES_AES_CTX_CFG_AES_INV_KEY_STR_Pos    3
#define CRYPTO_AES_AES_CTX_CFG_AES_INV_KEY_STR_Msk    0x8
#define CRYPTO_AES_AES_CTX_CFG_AES_INV_KEY_RET_Pos    2
#define CRYPTO_AES_AES_CTX_CFG_AES_INV_KEY_RET_Msk    0x4
#define CRYPTO_AES_AES_CTX_CFG_AES_CTX_STR_Pos      1
#define CRYPTO_AES_AES_CTX_CFG_AES_CTX_STR_Msk      0x2
#define CRYPTO_AES_AES_CTX_CFG_AES_CTX_RET_Pos      0
#define CRYPTO_AES_AES_CTX_CFG_AES_CTX_RET_Msk      0x1

#define CRYPTO_AES_AES_MSG_TOTAL_BYTES_OFFSET       0x008
#define CRYPTO_AES_AES_MSG_TOTAL_BYTES_TOTAL_BYTES_Pos    0
#define CRYPTO_AES_AES_MSG_TOTAL_BYTES_TOTAL_BYTES_Msk    0xfffffff

#define CRYPTO_AES_AES_MSG_AAD_BYTES_OFFSET         0x00C
#define CRYPTO_AES_AES_MSG_AAD_BYTES_AAD_LEN_Pos    16
#define CRYPTO_AES_AES_MSG_AAD_BYTES_AAD_LEN_Msk    0xffff0000
#define CRYPTO_AES_AES_MSG_AAD_BYTES_MSG_LEN_Pos    0
#define CRYPTO_AES_AES_MSG_AAD_BYTES_MSG_LEN_Msk    0xffff

#define CRYPTO_AES_GCM_MODE_AAD_INFO_OFFSET         0x010
#define CRYPTO_AES_GCM_MODE_AAD_INFO_AAD_LEN_TOT_Pos    0
#define CRYPTO_AES_GCM_MODE_AAD_INFO_AAD_LEN_TOT_Msk    0xfffffff

#define CRYPTO_AES_AES_CTX_KEY_MODE_SEL_OFFSET      0x014
#define CRYPTO_AES_AES_CTX_KEY_MODE_SEL_KEY_SEL_Pos    0
#define CRYPTO_AES_AES_CTX_KEY_MODE_SEL_KEY_SEL_Msk    0x7

#define CRYPTO_AES_AES_CTX_KEY_0_OFFSET             0x020
#define CRYPTO_AES_AES_CTX_KEY_0_KEY_0_Pos          0
#define CRYPTO_AES_AES_CTX_KEY_0_KEY_0_Msk          0xffffffff

#define CRYPTO_AES_AES_CTX_KEY_1_OFFSET             0x024
#define CRYPTO_AES_AES_CTX_KEY_1_KEY_1_Pos          0
#define CRYPTO_AES_AES_CTX_KEY_1_KEY_1_Msk          0xffffffff

#define CRYPTO_AES_AES_CTX_KEY_2_OFFSET             0x028
#define CRYPTO_AES_AES_CTX_KEY_2_KEY_2_Pos          0
#define CRYPTO_AES_AES_CTX_KEY_2_KEY_2_Msk          0xffffffff

#define CRYPTO_AES_AES_CTX_KEY_3_OFFSET             0x02C
#define CRYPTO_AES_AES_CTX_KEY_3_KEY_3_Pos          0
#define CRYPTO_AES_AES_CTX_KEY_3_KEY_3_Msk          0xffffffff

#define CRYPTO_AES_AES_CTX_KEY_4_OFFSET             0x030
#define CRYPTO_AES_AES_CTX_KEY_4_KEY_4_Pos          0
#define CRYPTO_AES_AES_CTX_KEY_4_KEY_4_Msk          0xffffffff

#define CRYPTO_AES_AES_CTX_KEY_5_OFFSET             0x034
#define CRYPTO_AES_AES_CTX_KEY_5_KEY_5_Pos          0
#define CRYPTO_AES_AES_CTX_KEY_5_KEY_5_Msk          0xffffffff

#define CRYPTO_AES_AES_CTX_KEY_6_OFFSET             0x038
#define CRYPTO_AES_AES_CTX_KEY_6_KEY_6_Pos          0
#define CRYPTO_AES_AES_CTX_KEY_6_KEY_6_Msk          0xffffffff

#define CRYPTO_AES_AES_CTX_KEY_7_OFFSET             0x03C
#define CRYPTO_AES_AES_CTX_KEY_7_KEY_7_Pos          0
#define CRYPTO_AES_AES_CTX_KEY_7_KEY_7_Msk          0xffffffff

#define CRYPTO_AES_AES_CTX_CBC_KEY_0_OFFSET         0x040
#define CRYPTO_AES_AES_CTX_CBC_KEY_0_CBC_KEY_0_Pos    0
#define CRYPTO_AES_AES_CTX_CBC_KEY_0_CBC_KEY_0_Msk    0xffffffff

#define CRYPTO_AES_AES_CTX_CBC_KEY_1_OFFSET         0x044
#define CRYPTO_AES_AES_CTX_CBC_KEY_1_CBC_KEY_1_Pos    0
#define CRYPTO_AES_AES_CTX_CBC_KEY_1_CBC_KEY_1_Msk    0xffffffff

#define CRYPTO_AES_AES_CTX_CBC_KEY_2_OFFSET         0x048
#define CRYPTO_AES_AES_CTX_CBC_KEY_2_CBC_KEY_2_Pos    0
#define CRYPTO_AES_AES_CTX_CBC_KEY_2_CBC_KEY_2_Msk    0xffffffff

#define CRYPTO_AES_AES_CTX_CBC_KEY_3_OFFSET         0x04C
#define CRYPTO_AES_AES_CTX_CBC_KEY_3_CBC_KEY_3_Pos    0
#define CRYPTO_AES_AES_CTX_CBC_KEY_3_CBC_KEY_3_Msk    0xffffffff

#define CRYPTO_AES_AES_CTX_CTR_0_OFFSET             0x050
#define CRYPTO_AES_AES_CTX_CTR_0_CCM_CTR_0_Pos      0
#define CRYPTO_AES_AES_CTX_CTR_0_CCM_CTR_0_Msk      0xffffffff

#define CRYPTO_AES_AES_CTX_CTR_1_OFFSET             0x054
#define CRYPTO_AES_AES_CTX_CTR_1_CCM_CTR_1_Pos      0
#define CRYPTO_AES_AES_CTX_CTR_1_CCM_CTR_1_Msk      0xffffffff

#define CRYPTO_AES_AES_CTX_CTR_2_OFFSET             0x058
#define CRYPTO_AES_AES_CTX_CTR_2_CCM_CTR_2_Pos      0
#define CRYPTO_AES_AES_CTX_CTR_2_CCM_CTR_2_Msk      0xffffffff

#define CRYPTO_AES_AES_CTX_CTR_3_OFFSET             0x05C
#define CRYPTO_AES_AES_CTX_CTR_3_CCM_CTR_3_Pos      0
#define CRYPTO_AES_AES_CTX_CTR_3_CCM_CTR_3_Msk      0xffffffff

#define CRYPTO_AES_AES_CTX_IV_0_OFFSET              0x060
#define CRYPTO_AES_AES_CTX_IV_0_CCM_IV_0_Pos        0
#define CRYPTO_AES_AES_CTX_IV_0_CCM_IV_0_Msk        0xffffffff

#define CRYPTO_AES_AES_CTX_IV_1_OFFSET              0x064
#define CRYPTO_AES_AES_CTX_IV_1_CCM_IV_1_Pos        0
#define CRYPTO_AES_AES_CTX_IV_1_CCM_IV_1_Msk        0xffffffff

#define CRYPTO_AES_AES_CTX_IV_2_OFFSET              0x068
#define CRYPTO_AES_AES_CTX_IV_2_CCM_IV_2_Pos        0
#define CRYPTO_AES_AES_CTX_IV_2_CCM_IV_2_Msk        0xffffffff

#define CRYPTO_AES_AES_CTX_IV_3_OFFSET              0x06C
#define CRYPTO_AES_AES_CTX_IV_3_CCM_IV_3_Pos        0
#define CRYPTO_AES_AES_CTX_IV_3_CCM_IV_3_Msk        0xffffffff

#define CRYPTO_AES_AES_CTX_MAC_0_OFFSET             0x070
#define CRYPTO_AES_AES_CTX_MAC_0_CCM_MAC_0_Pos      0
#define CRYPTO_AES_AES_CTX_MAC_0_CCM_MAC_0_Msk      0xffffffff

#define CRYPTO_AES_AES_CTX_MAC_1_OFFSET             0x074
#define CRYPTO_AES_AES_CTX_MAC_1_CCM_MAC_1_Pos      0
#define CRYPTO_AES_AES_CTX_MAC_1_CCM_MAC_1_Msk      0xffffffff

#define CRYPTO_AES_AES_CTX_MAC_2_OFFSET             0x078
#define CRYPTO_AES_AES_CTX_MAC_2_CCM_MAC_2_Pos      0
#define CRYPTO_AES_AES_CTX_MAC_2_CCM_MAC_2_Msk      0xffffffff

#define CRYPTO_AES_AES_CTX_MAC_3_OFFSET             0x07C
#define CRYPTO_AES_AES_CTX_MAC_3_CCM_MAC_3_Pos      0
#define CRYPTO_AES_AES_CTX_MAC_3_CCM_MAC_3_Msk      0xffffffff

#define CRYPTO_AES_AES_INGRESS_FIFO_OFFSET          0x080
#define CRYPTO_AES_AES_INGRESS_FIFO_INGRESS_FIFO_DATA_Pos    0
#define CRYPTO_AES_AES_INGRESS_FIFO_INGRESS_FIFO_DATA_Msk    0xffffffff

#define CRYPTO_AES_AES_INGRESS_FIFO_STATUS_REG_OFFSET    0x084
#define CRYPTO_AES_AES_INGRESS_FIFO_STATUS_REG_INGRESS_FIFO_FULL_Pos    1
#define CRYPTO_AES_AES_INGRESS_FIFO_STATUS_REG_INGRESS_FIFO_FULL_Msk    0x2
#define CRYPTO_AES_AES_INGRESS_FIFO_STATUS_REG_INGRESS_FIFO_EMPTY_Pos    0
#define CRYPTO_AES_AES_INGRESS_FIFO_STATUS_REG_INGRESS_FIFO_EMPTY_Msk    0x1

#define CRYPTO_AES_AES_ENGRESS_FIFO_OFFSET          0x088
#define CRYPTO_AES_AES_ENGRESS_FIFO_ENGRESS_FIFO_DATA_Pos    0
#define CRYPTO_AES_AES_ENGRESS_FIFO_ENGRESS_FIFO_DATA_Msk    0xffffffff

#define CRYPTO_AES_AES_ENGRESS_FIFO_STATUS_REG_OFFSET    0x08C
#define CRYPTO_AES_AES_ENGRESS_FIFO_STATUS_REG_ENGRESS_FIFO_FULL_Pos    1
#define CRYPTO_AES_AES_ENGRESS_FIFO_STATUS_REG_ENGRESS_FIFO_FULL_Msk    0x2
#define CRYPTO_AES_AES_ENGRESS_FIFO_STATUS_REG_ENGRESS_FIFO_EMPTY_Pos    0
#define CRYPTO_AES_AES_ENGRESS_FIFO_STATUS_REG_ENGRESS_FIFO_EMPTY_Msk    0x1

#define CRYPTO_AES_AES_INGRESS_DMA_TOTAL_NUM_REG_OFFSET    0x090
#define CRYPTO_AES_AES_INGRESS_DMA_TOTAL_NUM_REG_INGRESS_DMA_DATA_NUMBER_Pos    0
#define CRYPTO_AES_AES_INGRESS_DMA_TOTAL_NUM_REG_INGRESS_DMA_DATA_NUMBER_Msk    0xffffffff

#define CRYPTO_AES_AES_INGRESS_DMA_BST_TYPE_REG_OFFSET    0x094
#define CRYPTO_AES_AES_INGRESS_DMA_BST_TYPE_REG_PLAINTEXT_REQ_Pos    31
#define CRYPTO_AES_AES_INGRESS_DMA_BST_TYPE_REG_PLAINTEXT_REQ_Msk    0x80000000
#define CRYPTO_AES_AES_INGRESS_DMA_BST_TYPE_REG_DMA_EN_Pos    30
#define CRYPTO_AES_AES_INGRESS_DMA_BST_TYPE_REG_DMA_EN_Msk    0x40000000
#define CRYPTO_AES_AES_INGRESS_DMA_BST_TYPE_REG_DST_MSIZE_Pos    3
#define CRYPTO_AES_AES_INGRESS_DMA_BST_TYPE_REG_DST_MSIZE_Msk    0x38
#define CRYPTO_AES_AES_INGRESS_DMA_BST_TYPE_REG_DEST_TR_WIDTH_Pos    0
#define CRYPTO_AES_AES_INGRESS_DMA_BST_TYPE_REG_DEST_TR_WIDTH_Msk    0x7

#define CRYPTO_AES_AES_ENGRESS_DMA_TOTAL_NUM_REG_OFFSET    0x098
#define CRYPTO_AES_AES_ENGRESS_DMA_TOTAL_NUM_REG_ENGRESS_DMA_DATA_NUMBER_Pos    0
#define CRYPTO_AES_AES_ENGRESS_DMA_TOTAL_NUM_REG_ENGRESS_DMA_DATA_NUMBER_Msk    0xffffffff

#define CRYPTO_AES_AES_ENGRESS_DMA_BST_TYPE_REG_OFFSET    0x09C
#define CRYPTO_AES_AES_ENGRESS_DMA_BST_TYPE_REG_PLAINTEXT_REQ_Pos    31
#define CRYPTO_AES_AES_ENGRESS_DMA_BST_TYPE_REG_PLAINTEXT_REQ_Msk    0x80000000
#define CRYPTO_AES_AES_ENGRESS_DMA_BST_TYPE_REG_DMA_EN_Pos    30
#define CRYPTO_AES_AES_ENGRESS_DMA_BST_TYPE_REG_DMA_EN_Msk    0x40000000
#define CRYPTO_AES_AES_ENGRESS_DMA_BST_TYPE_REG_SURC_MSIZE_Pos    3
#define CRYPTO_AES_AES_ENGRESS_DMA_BST_TYPE_REG_SURC_MSIZE_Msk    0x38
#define CRYPTO_AES_AES_ENGRESS_DMA_BST_TYPE_REG_SURC_TR_WIDTH_Pos    0
#define CRYPTO_AES_AES_ENGRESS_DMA_BST_TYPE_REG_SURC_TR_WIDTH_Msk    0x7

#define CRYPTO_AES_AES_DONE_STAT_REG_OFFSET         0x0A0
#define CRYPTO_AES_AES_DONE_STAT_REG_AES_MAC_VALID_Pos    1
#define CRYPTO_AES_AES_DONE_STAT_REG_AES_MAC_VALID_Msk    0x2
#define CRYPTO_AES_AES_DONE_STAT_REG_AES_DONE_Pos    0
#define CRYPTO_AES_AES_DONE_STAT_REG_AES_DONE_Msk    0x1

#define CRYPTO_AES_AES_INGRESS_DMA_DONE_REG_OFFSET    0x0A4
#define CRYPTO_AES_AES_INGRESS_DMA_DONE_REG_INGRESS_DMA_DONE_Pos    0
#define CRYPTO_AES_AES_INGRESS_DMA_DONE_REG_INGRESS_DMA_DONE_Msk    0x1

#define CRYPTO_AES_AES_ENGRESS_DMA_DONE_REG_OFFSET    0x0A8
#define CRYPTO_AES_AES_ENGRESS_DMA_DONE_REG_ENGRESS_DMA_DONE_Pos    0
#define CRYPTO_AES_AES_ENGRESS_DMA_DONE_REG_ENGRESS_DMA_DONE_Msk    0x1

struct CRYPTO_AES_REG_AES_MSG_CFG_BITS
{
    volatile uint32_t AES_GO                        : 1; // bit 0~0
    volatile uint32_t AES_MSG_END                   : 1; // bit 1~1
    volatile uint32_t AES_MSG_BEGIN                 : 1; // bit 2~2
    volatile uint32_t AES_ENCRYPT                   : 1; // bit 3~3
    volatile uint32_t AES_ALG_MODE                  : 4; // bit 4~7
    volatile uint32_t AES_MAC_LEN                   : 4; // bit 8~11
    volatile uint32_t AES_KEY_SIZE                  : 2; // bit 12~13
    volatile uint32_t RESV_14_31                    : 18; // bit 14~31
};

union CRYPTO_AES_REG_AES_MSG_CFG {
    volatile uint32_t                               all;
    struct CRYPTO_AES_REG_AES_MSG_CFG_BITS          bit;
};

struct CRYPTO_AES_REG_AES_CTX_CFG_BITS
{
    volatile uint32_t AES_CTX_RET                   : 1; // bit 0~0
    volatile uint32_t AES_CTX_STR                   : 1; // bit 1~1
    volatile uint32_t AES_INV_KEY_RET               : 1; // bit 2~2
    volatile uint32_t AES_INV_KEY_STR               : 1; // bit 3~3
    volatile uint32_t AES_CTX_INDEX                 : 12; // bit 4~15
    volatile uint32_t RESV_16_31                    : 16; // bit 16~31
};

union CRYPTO_AES_REG_AES_CTX_CFG {
    volatile uint32_t                               all;
    struct CRYPTO_AES_REG_AES_CTX_CFG_BITS          bit;
};

struct CRYPTO_AES_REG_AES_MSG_TOTAL_BYTES_BITS
{
    volatile uint32_t TOTAL_BYTES                   : 28; // bit 0~27
    volatile uint32_t RESV_28_31                    : 4; // bit 28~31
};

union CRYPTO_AES_REG_AES_MSG_TOTAL_BYTES {
    volatile uint32_t                               all;
    struct CRYPTO_AES_REG_AES_MSG_TOTAL_BYTES_BITS    bit;
};

struct CRYPTO_AES_REG_AES_MSG_AAD_BYTES_BITS
{
    volatile uint32_t MSG_LEN                       : 16; // bit 0~15
    volatile uint32_t AAD_LEN                       : 16; // bit 16~31
};

union CRYPTO_AES_REG_AES_MSG_AAD_BYTES {
    volatile uint32_t                               all;
    struct CRYPTO_AES_REG_AES_MSG_AAD_BYTES_BITS    bit;
};

struct CRYPTO_AES_REG_GCM_MODE_AAD_INFO_BITS
{
    volatile uint32_t AAD_LEN_TOT                   : 28; // bit 0~27
    volatile uint32_t RESV_28_31                    : 4; // bit 28~31
};

union CRYPTO_AES_REG_GCM_MODE_AAD_INFO {
    volatile uint32_t                               all;
    struct CRYPTO_AES_REG_GCM_MODE_AAD_INFO_BITS    bit;
};

struct CRYPTO_AES_REG_AES_CTX_KEY_MODE_SEL_BITS
{
    volatile uint32_t KEY_SEL                       : 3; // bit 0~2
    volatile uint32_t RESV_3_31                     : 29; // bit 3~31
};

union CRYPTO_AES_REG_AES_CTX_KEY_MODE_SEL {
    volatile uint32_t                               all;
    struct CRYPTO_AES_REG_AES_CTX_KEY_MODE_SEL_BITS    bit;
};

struct CRYPTO_AES_REG_AES_CTX_KEY_0_BITS
{
    volatile uint32_t KEY_0                         : 32; // bit 0~31
};

union CRYPTO_AES_REG_AES_CTX_KEY_0 {
    volatile uint32_t                               all;
    struct CRYPTO_AES_REG_AES_CTX_KEY_0_BITS        bit;
};

struct CRYPTO_AES_REG_AES_CTX_KEY_1_BITS
{
    volatile uint32_t KEY_1                         : 32; // bit 0~31
};

union CRYPTO_AES_REG_AES_CTX_KEY_1 {
    volatile uint32_t                               all;
    struct CRYPTO_AES_REG_AES_CTX_KEY_1_BITS        bit;
};

struct CRYPTO_AES_REG_AES_CTX_KEY_2_BITS
{
    volatile uint32_t KEY_2                         : 32; // bit 0~31
};

union CRYPTO_AES_REG_AES_CTX_KEY_2 {
    volatile uint32_t                               all;
    struct CRYPTO_AES_REG_AES_CTX_KEY_2_BITS        bit;
};

struct CRYPTO_AES_REG_AES_CTX_KEY_3_BITS
{
    volatile uint32_t KEY_3                         : 32; // bit 0~31
};

union CRYPTO_AES_REG_AES_CTX_KEY_3 {
    volatile uint32_t                               all;
    struct CRYPTO_AES_REG_AES_CTX_KEY_3_BITS        bit;
};

struct CRYPTO_AES_REG_AES_CTX_KEY_4_BITS
{
    volatile uint32_t KEY_4                         : 32; // bit 0~31
};

union CRYPTO_AES_REG_AES_CTX_KEY_4 {
    volatile uint32_t                               all;
    struct CRYPTO_AES_REG_AES_CTX_KEY_4_BITS        bit;
};

struct CRYPTO_AES_REG_AES_CTX_KEY_5_BITS
{
    volatile uint32_t KEY_5                         : 32; // bit 0~31
};

union CRYPTO_AES_REG_AES_CTX_KEY_5 {
    volatile uint32_t                               all;
    struct CRYPTO_AES_REG_AES_CTX_KEY_5_BITS        bit;
};

struct CRYPTO_AES_REG_AES_CTX_KEY_6_BITS
{
    volatile uint32_t KEY_6                         : 32; // bit 0~31
};

union CRYPTO_AES_REG_AES_CTX_KEY_6 {
    volatile uint32_t                               all;
    struct CRYPTO_AES_REG_AES_CTX_KEY_6_BITS        bit;
};

struct CRYPTO_AES_REG_AES_CTX_KEY_7_BITS
{
    volatile uint32_t KEY_7                         : 32; // bit 0~31
};

union CRYPTO_AES_REG_AES_CTX_KEY_7 {
    volatile uint32_t                               all;
    struct CRYPTO_AES_REG_AES_CTX_KEY_7_BITS        bit;
};

struct CRYPTO_AES_REG_AES_CTX_CBC_KEY_0_BITS
{
    volatile uint32_t CBC_KEY_0                     : 32; // bit 0~31
};

union CRYPTO_AES_REG_AES_CTX_CBC_KEY_0 {
    volatile uint32_t                               all;
    struct CRYPTO_AES_REG_AES_CTX_CBC_KEY_0_BITS    bit;
};

struct CRYPTO_AES_REG_AES_CTX_CBC_KEY_1_BITS
{
    volatile uint32_t CBC_KEY_1                     : 32; // bit 0~31
};

union CRYPTO_AES_REG_AES_CTX_CBC_KEY_1 {
    volatile uint32_t                               all;
    struct CRYPTO_AES_REG_AES_CTX_CBC_KEY_1_BITS    bit;
};

struct CRYPTO_AES_REG_AES_CTX_CBC_KEY_2_BITS
{
    volatile uint32_t CBC_KEY_2                     : 32; // bit 0~31
};

union CRYPTO_AES_REG_AES_CTX_CBC_KEY_2 {
    volatile uint32_t                               all;
    struct CRYPTO_AES_REG_AES_CTX_CBC_KEY_2_BITS    bit;
};

struct CRYPTO_AES_REG_AES_CTX_CBC_KEY_3_BITS
{
    volatile uint32_t CBC_KEY_3                     : 32; // bit 0~31
};

union CRYPTO_AES_REG_AES_CTX_CBC_KEY_3 {
    volatile uint32_t                               all;
    struct CRYPTO_AES_REG_AES_CTX_CBC_KEY_3_BITS    bit;
};

struct CRYPTO_AES_REG_AES_CTX_CTR_0_BITS
{
    volatile uint32_t CCM_CTR_0                     : 32; // bit 0~31
};

union CRYPTO_AES_REG_AES_CTX_CTR_0 {
    volatile uint32_t                               all;
    struct CRYPTO_AES_REG_AES_CTX_CTR_0_BITS        bit;
};

struct CRYPTO_AES_REG_AES_CTX_CTR_1_BITS
{
    volatile uint32_t CCM_CTR_1                     : 32; // bit 0~31
};

union CRYPTO_AES_REG_AES_CTX_CTR_1 {
    volatile uint32_t                               all;
    struct CRYPTO_AES_REG_AES_CTX_CTR_1_BITS        bit;
};

struct CRYPTO_AES_REG_AES_CTX_CTR_2_BITS
{
    volatile uint32_t CCM_CTR_2                     : 32; // bit 0~31
};

union CRYPTO_AES_REG_AES_CTX_CTR_2 {
    volatile uint32_t                               all;
    struct CRYPTO_AES_REG_AES_CTX_CTR_2_BITS        bit;
};

struct CRYPTO_AES_REG_AES_CTX_CTR_3_BITS
{
    volatile uint32_t CCM_CTR_3                     : 32; // bit 0~31
};

union CRYPTO_AES_REG_AES_CTX_CTR_3 {
    volatile uint32_t                               all;
    struct CRYPTO_AES_REG_AES_CTX_CTR_3_BITS        bit;
};

struct CRYPTO_AES_REG_AES_CTX_IV_0_BITS
{
    volatile uint32_t CCM_IV_0                      : 32; // bit 0~31
};

union CRYPTO_AES_REG_AES_CTX_IV_0 {
    volatile uint32_t                               all;
    struct CRYPTO_AES_REG_AES_CTX_IV_0_BITS         bit;
};

struct CRYPTO_AES_REG_AES_CTX_IV_1_BITS
{
    volatile uint32_t CCM_IV_1                      : 32; // bit 0~31
};

union CRYPTO_AES_REG_AES_CTX_IV_1 {
    volatile uint32_t                               all;
    struct CRYPTO_AES_REG_AES_CTX_IV_1_BITS         bit;
};

struct CRYPTO_AES_REG_AES_CTX_IV_2_BITS
{
    volatile uint32_t CCM_IV_2                      : 32; // bit 0~31
};

union CRYPTO_AES_REG_AES_CTX_IV_2 {
    volatile uint32_t                               all;
    struct CRYPTO_AES_REG_AES_CTX_IV_2_BITS         bit;
};

struct CRYPTO_AES_REG_AES_CTX_IV_3_BITS
{
    volatile uint32_t CCM_IV_3                      : 32; // bit 0~31
};

union CRYPTO_AES_REG_AES_CTX_IV_3 {
    volatile uint32_t                               all;
    struct CRYPTO_AES_REG_AES_CTX_IV_3_BITS         bit;
};

struct CRYPTO_AES_REG_AES_CTX_MAC_0_BITS
{
    volatile uint32_t CCM_MAC_0                     : 32; // bit 0~31
};

union CRYPTO_AES_REG_AES_CTX_MAC_0 {
    volatile uint32_t                               all;
    struct CRYPTO_AES_REG_AES_CTX_MAC_0_BITS        bit;
};

struct CRYPTO_AES_REG_AES_CTX_MAC_1_BITS
{
    volatile uint32_t CCM_MAC_1                     : 32; // bit 0~31
};

union CRYPTO_AES_REG_AES_CTX_MAC_1 {
    volatile uint32_t                               all;
    struct CRYPTO_AES_REG_AES_CTX_MAC_1_BITS        bit;
};

struct CRYPTO_AES_REG_AES_CTX_MAC_2_BITS
{
    volatile uint32_t CCM_MAC_2                     : 32; // bit 0~31
};

union CRYPTO_AES_REG_AES_CTX_MAC_2 {
    volatile uint32_t                               all;
    struct CRYPTO_AES_REG_AES_CTX_MAC_2_BITS        bit;
};

struct CRYPTO_AES_REG_AES_CTX_MAC_3_BITS
{
    volatile uint32_t CCM_MAC_3                     : 32; // bit 0~31
};

union CRYPTO_AES_REG_AES_CTX_MAC_3 {
    volatile uint32_t                               all;
    struct CRYPTO_AES_REG_AES_CTX_MAC_3_BITS        bit;
};

struct CRYPTO_AES_REG_AES_INGRESS_FIFO_BITS
{
    volatile uint32_t INGRESS_FIFO_DATA             : 32; // bit 0~31
};

union CRYPTO_AES_REG_AES_INGRESS_FIFO {
    volatile uint32_t                               all;
    struct CRYPTO_AES_REG_AES_INGRESS_FIFO_BITS     bit;
};

struct CRYPTO_AES_REG_AES_INGRESS_FIFO_STATUS_REG_BITS
{
    volatile uint32_t INGRESS_FIFO_EMPTY            : 1; // bit 0~0
    volatile uint32_t INGRESS_FIFO_FULL             : 1; // bit 1~1
    volatile uint32_t RESV_2_31                     : 30; // bit 2~31
};

union CRYPTO_AES_REG_AES_INGRESS_FIFO_STATUS_REG {
    volatile uint32_t                               all;
    struct CRYPTO_AES_REG_AES_INGRESS_FIFO_STATUS_REG_BITS    bit;
};

struct CRYPTO_AES_REG_AES_ENGRESS_FIFO_BITS
{
    volatile uint32_t ENGRESS_FIFO_DATA             : 32; // bit 0~31
};

union CRYPTO_AES_REG_AES_ENGRESS_FIFO {
    volatile uint32_t                               all;
    struct CRYPTO_AES_REG_AES_ENGRESS_FIFO_BITS     bit;
};

struct CRYPTO_AES_REG_AES_ENGRESS_FIFO_STATUS_REG_BITS
{
    volatile uint32_t ENGRESS_FIFO_EMPTY            : 1; // bit 0~0
    volatile uint32_t ENGRESS_FIFO_FULL             : 1; // bit 1~1
    volatile uint32_t RESV_2_31                     : 30; // bit 2~31
};

union CRYPTO_AES_REG_AES_ENGRESS_FIFO_STATUS_REG {
    volatile uint32_t                               all;
    struct CRYPTO_AES_REG_AES_ENGRESS_FIFO_STATUS_REG_BITS    bit;
};

struct CRYPTO_AES_REG_AES_INGRESS_DMA_TOTAL_NUM_REG_BITS
{
    volatile uint32_t INGRESS_DMA_DATA_NUMBER       : 32; // bit 0~31
};

union CRYPTO_AES_REG_AES_INGRESS_DMA_TOTAL_NUM_REG {
    volatile uint32_t                               all;
    struct CRYPTO_AES_REG_AES_INGRESS_DMA_TOTAL_NUM_REG_BITS    bit;
};

struct CRYPTO_AES_REG_AES_INGRESS_DMA_BST_TYPE_REG_BITS
{
    volatile uint32_t DEST_TR_WIDTH                 : 3; // bit 0~2
    volatile uint32_t DST_MSIZE                     : 3; // bit 3~5
    volatile uint32_t RESV_6_29                     : 24; // bit 6~29
    volatile uint32_t DMA_EN                        : 1; // bit 30~30
    volatile uint32_t PLAINTEXT_REQ                 : 1; // bit 31~31
};

union CRYPTO_AES_REG_AES_INGRESS_DMA_BST_TYPE_REG {
    volatile uint32_t                               all;
    struct CRYPTO_AES_REG_AES_INGRESS_DMA_BST_TYPE_REG_BITS    bit;
};

struct CRYPTO_AES_REG_AES_ENGRESS_DMA_TOTAL_NUM_REG_BITS
{
    volatile uint32_t ENGRESS_DMA_DATA_NUMBER       : 32; // bit 0~31
};

union CRYPTO_AES_REG_AES_ENGRESS_DMA_TOTAL_NUM_REG {
    volatile uint32_t                               all;
    struct CRYPTO_AES_REG_AES_ENGRESS_DMA_TOTAL_NUM_REG_BITS    bit;
};

struct CRYPTO_AES_REG_AES_ENGRESS_DMA_BST_TYPE_REG_BITS
{
    volatile uint32_t SURC_TR_WIDTH                 : 3; // bit 0~2
    volatile uint32_t SURC_MSIZE                    : 3; // bit 3~5
    volatile uint32_t RESV_6_29                     : 24; // bit 6~29
    volatile uint32_t DMA_EN                        : 1; // bit 30~30
    volatile uint32_t PLAINTEXT_REQ                 : 1; // bit 31~31
};

union CRYPTO_AES_REG_AES_ENGRESS_DMA_BST_TYPE_REG {
    volatile uint32_t                               all;
    struct CRYPTO_AES_REG_AES_ENGRESS_DMA_BST_TYPE_REG_BITS    bit;
};

struct CRYPTO_AES_REG_AES_DONE_STAT_REG_BITS
{
    volatile uint32_t AES_DONE                      : 1; // bit 0~0
    volatile uint32_t AES_MAC_VALID                 : 1; // bit 1~1
    volatile uint32_t RESV_2_31                     : 30; // bit 2~31
};

union CRYPTO_AES_REG_AES_DONE_STAT_REG {
    volatile uint32_t                               all;
    struct CRYPTO_AES_REG_AES_DONE_STAT_REG_BITS    bit;
};

struct CRYPTO_AES_REG_AES_INGRESS_DMA_DONE_REG_BITS
{
    volatile uint32_t INGRESS_DMA_DONE              : 1; // bit 0~0
    volatile uint32_t RESV_1_31                     : 31; // bit 1~31
};

union CRYPTO_AES_REG_AES_INGRESS_DMA_DONE_REG {
    volatile uint32_t                               all;
    struct CRYPTO_AES_REG_AES_INGRESS_DMA_DONE_REG_BITS    bit;
};

struct CRYPTO_AES_REG_AES_ENGRESS_DMA_DONE_REG_BITS
{
    volatile uint32_t ENGRESS_DMA_DONE              : 1; // bit 0~0
    volatile uint32_t RESV_1_31                     : 31; // bit 1~31
};

union CRYPTO_AES_REG_AES_ENGRESS_DMA_DONE_REG {
    volatile uint32_t                               all;
    struct CRYPTO_AES_REG_AES_ENGRESS_DMA_DONE_REG_BITS    bit;
};

typedef struct
{
    union CRYPTO_AES_REG_AES_MSG_CFG                REG_AES_MSG_CFG; // 0x000
    union CRYPTO_AES_REG_AES_CTX_CFG                REG_AES_CTX_CFG; // 0x004
    union CRYPTO_AES_REG_AES_MSG_TOTAL_BYTES        REG_AES_MSG_TOTAL_BYTES; // 0x008
    union CRYPTO_AES_REG_AES_MSG_AAD_BYTES          REG_AES_MSG_AAD_BYTES; // 0x00C
    union CRYPTO_AES_REG_GCM_MODE_AAD_INFO          REG_GCM_MODE_AAD_INFO; // 0x010
    union CRYPTO_AES_REG_AES_CTX_KEY_MODE_SEL       REG_AES_CTX_KEY_MODE_SEL; // 0x014
    volatile uint32_t                               REG_RESV_0X18_0X1C[2];
    union CRYPTO_AES_REG_AES_CTX_KEY_0              REG_AES_CTX_KEY_0; // 0x020
    union CRYPTO_AES_REG_AES_CTX_KEY_1              REG_AES_CTX_KEY_1; // 0x024
    union CRYPTO_AES_REG_AES_CTX_KEY_2              REG_AES_CTX_KEY_2; // 0x028
    union CRYPTO_AES_REG_AES_CTX_KEY_3              REG_AES_CTX_KEY_3; // 0x02C
    union CRYPTO_AES_REG_AES_CTX_KEY_4              REG_AES_CTX_KEY_4; // 0x030
    union CRYPTO_AES_REG_AES_CTX_KEY_5              REG_AES_CTX_KEY_5; // 0x034
    union CRYPTO_AES_REG_AES_CTX_KEY_6              REG_AES_CTX_KEY_6; // 0x038
    union CRYPTO_AES_REG_AES_CTX_KEY_7              REG_AES_CTX_KEY_7; // 0x03C
    union CRYPTO_AES_REG_AES_CTX_CBC_KEY_0          REG_AES_CTX_CBC_KEY_0; // 0x040
    union CRYPTO_AES_REG_AES_CTX_CBC_KEY_1          REG_AES_CTX_CBC_KEY_1; // 0x044
    union CRYPTO_AES_REG_AES_CTX_CBC_KEY_2          REG_AES_CTX_CBC_KEY_2; // 0x048
    union CRYPTO_AES_REG_AES_CTX_CBC_KEY_3          REG_AES_CTX_CBC_KEY_3; // 0x04C
    union CRYPTO_AES_REG_AES_CTX_CTR_0              REG_AES_CTX_CTR_0; // 0x050
    union CRYPTO_AES_REG_AES_CTX_CTR_1              REG_AES_CTX_CTR_1; // 0x054
    union CRYPTO_AES_REG_AES_CTX_CTR_2              REG_AES_CTX_CTR_2; // 0x058
    union CRYPTO_AES_REG_AES_CTX_CTR_3              REG_AES_CTX_CTR_3; // 0x05C
    union CRYPTO_AES_REG_AES_CTX_IV_0               REG_AES_CTX_IV_0; // 0x060
    union CRYPTO_AES_REG_AES_CTX_IV_1               REG_AES_CTX_IV_1; // 0x064
    union CRYPTO_AES_REG_AES_CTX_IV_2               REG_AES_CTX_IV_2; // 0x068
    union CRYPTO_AES_REG_AES_CTX_IV_3               REG_AES_CTX_IV_3; // 0x06C
    union CRYPTO_AES_REG_AES_CTX_MAC_0              REG_AES_CTX_MAC_0; // 0x070
    union CRYPTO_AES_REG_AES_CTX_MAC_1              REG_AES_CTX_MAC_1; // 0x074
    union CRYPTO_AES_REG_AES_CTX_MAC_2              REG_AES_CTX_MAC_2; // 0x078
    union CRYPTO_AES_REG_AES_CTX_MAC_3              REG_AES_CTX_MAC_3; // 0x07C
    union CRYPTO_AES_REG_AES_INGRESS_FIFO           REG_AES_INGRESS_FIFO; // 0x080
    union CRYPTO_AES_REG_AES_INGRESS_FIFO_STATUS_REG    REG_AES_INGRESS_FIFO_STATUS_REG; // 0x084
    union CRYPTO_AES_REG_AES_ENGRESS_FIFO           REG_AES_ENGRESS_FIFO; // 0x088
    union CRYPTO_AES_REG_AES_ENGRESS_FIFO_STATUS_REG    REG_AES_ENGRESS_FIFO_STATUS_REG; // 0x08C
    union CRYPTO_AES_REG_AES_INGRESS_DMA_TOTAL_NUM_REG    REG_AES_INGRESS_DMA_TOTAL_NUM_REG; // 0x090
    union CRYPTO_AES_REG_AES_INGRESS_DMA_BST_TYPE_REG    REG_AES_INGRESS_DMA_BST_TYPE_REG; // 0x094
    union CRYPTO_AES_REG_AES_ENGRESS_DMA_TOTAL_NUM_REG    REG_AES_ENGRESS_DMA_TOTAL_NUM_REG; // 0x098
    union CRYPTO_AES_REG_AES_ENGRESS_DMA_BST_TYPE_REG    REG_AES_ENGRESS_DMA_BST_TYPE_REG; // 0x09C
    union CRYPTO_AES_REG_AES_DONE_STAT_REG          REG_AES_DONE_STAT_REG; // 0x0A0
    union CRYPTO_AES_REG_AES_INGRESS_DMA_DONE_REG    REG_AES_INGRESS_DMA_DONE_REG; // 0x0A4
    union CRYPTO_AES_REG_AES_ENGRESS_DMA_DONE_REG    REG_AES_ENGRESS_DMA_DONE_REG; // 0x0A8
} CRYPTO_AES_RegDef;


#endif // __CRYPTO_AES_REGFILE_H__

