//  ----------------------------------------------------------------------
//  File Name   : GenCFold/flashc_reg_arcs.h
//  Description : C header file generated by Python script.
//  Script Ver  £ºLS.AUTO_REG.2024.03.01
//  Create Time : 2024-06-20 11:17:02
//  Comments    : 
//  ----------------------------------------------------------------------

#ifndef __FLASHC_REGFILE_H__
#define __FLASHC_REGFILE_H__

#include <stdint.h>

#define FLASHC_IDREV_OFFSET                         0x000
#define FLASHC_IDREV_ID_Pos                         12
#define FLASHC_IDREV_ID_Msk                         0xfffff000
#define FLASHC_IDREV_REVMAJOR_Pos                   4
#define FLASHC_IDREV_REVMAJOR_Msk                   0xff0
#define FLASHC_IDREV_REVMINOR_Pos                   0
#define FLASHC_IDREV_REVMINOR_Msk                   0xf

#define FLASHC_TRANSFMT_OFFSET                      0x010
#define FLASHC_TRANSFMT_FAST_MD_Pos                 31
#define FLASHC_TRANSFMT_FAST_MD_Msk                 0x80000000
#define FLASHC_TRANSFMT_ADDRLEN_Pos                 16
#define FLASHC_TRANSFMT_ADDRLEN_Msk                 0x30000
#define FLASHC_TRANSFMT_DATALEN_Pos                 8
#define FLASHC_TRANSFMT_DATALEN_Msk                 0x1f00
#define FLASHC_TRANSFMT_DATAMERGE_Pos               7
#define FLASHC_TRANSFMT_DATAMERGE_Msk               0x80
#define FLASHC_TRANSFMT_MOSIBIDIR_Pos               4
#define FLASHC_TRANSFMT_MOSIBIDIR_Msk               0x10
#define FLASHC_TRANSFMT_LSB_Pos                     3
#define FLASHC_TRANSFMT_LSB_Msk                     0x8
#define FLASHC_TRANSFMT_SLVMODE_Pos                 2
#define FLASHC_TRANSFMT_SLVMODE_Msk                 0x4
#define FLASHC_TRANSFMT_CPOL_Pos                    1
#define FLASHC_TRANSFMT_CPOL_Msk                    0x2
#define FLASHC_TRANSFMT_CPHA_Pos                    0
#define FLASHC_TRANSFMT_CPHA_Msk                    0x1

#define FLASHC_DIRECTIO_OFFSET                      0x014
#define FLASHC_DIRECTIO_DIRECTIOEN_Pos              24
#define FLASHC_DIRECTIO_DIRECTIOEN_Msk              0x1000000
#define FLASHC_DIRECTIO_HOLD_OE_Pos                 21
#define FLASHC_DIRECTIO_HOLD_OE_Msk                 0x200000
#define FLASHC_DIRECTIO_WP_OE_Pos                   20
#define FLASHC_DIRECTIO_WP_OE_Msk                   0x100000
#define FLASHC_DIRECTIO_MISO_OE_Pos                 19
#define FLASHC_DIRECTIO_MISO_OE_Msk                 0x80000
#define FLASHC_DIRECTIO_MOSI_OE_Pos                 18
#define FLASHC_DIRECTIO_MOSI_OE_Msk                 0x40000
#define FLASHC_DIRECTIO_SCLK_OE_Pos                 17
#define FLASHC_DIRECTIO_SCLK_OE_Msk                 0x20000
#define FLASHC_DIRECTIO_CS_OE_Pos                   16
#define FLASHC_DIRECTIO_CS_OE_Msk                   0x10000
#define FLASHC_DIRECTIO_HOLD_O_Pos                  13
#define FLASHC_DIRECTIO_HOLD_O_Msk                  0x2000
#define FLASHC_DIRECTIO_WP_O_Pos                    12
#define FLASHC_DIRECTIO_WP_O_Msk                    0x1000
#define FLASHC_DIRECTIO_MISO_O_Pos                  11
#define FLASHC_DIRECTIO_MISO_O_Msk                  0x800
#define FLASHC_DIRECTIO_MOSI_O_Pos                  10
#define FLASHC_DIRECTIO_MOSI_O_Msk                  0x400
#define FLASHC_DIRECTIO_SCLK_O_Pos                  9
#define FLASHC_DIRECTIO_SCLK_O_Msk                  0x200
#define FLASHC_DIRECTIO_CS_O_Pos                    8
#define FLASHC_DIRECTIO_CS_O_Msk                    0x100
#define FLASHC_DIRECTIO_HOLD_I_Pos                  5
#define FLASHC_DIRECTIO_HOLD_I_Msk                  0x20
#define FLASHC_DIRECTIO_WP_I_Pos                    4
#define FLASHC_DIRECTIO_WP_I_Msk                    0x10
#define FLASHC_DIRECTIO_MISO_I_Pos                  3
#define FLASHC_DIRECTIO_MISO_I_Msk                  0x8
#define FLASHC_DIRECTIO_MOSI_I_Pos                  2
#define FLASHC_DIRECTIO_MOSI_I_Msk                  0x4
#define FLASHC_DIRECTIO_SCLK_I_Pos                  1
#define FLASHC_DIRECTIO_SCLK_I_Msk                  0x2
#define FLASHC_DIRECTIO_CS_I_Pos                    0
#define FLASHC_DIRECTIO_CS_I_Msk                    0x1

#define FLASHC_TRANSCTRL_OFFSET                     0x020
#define FLASHC_TRANSCTRL_CMDEN_Pos                  30
#define FLASHC_TRANSCTRL_CMDEN_Msk                  0x40000000
#define FLASHC_TRANSCTRL_ADDREN_Pos                 29
#define FLASHC_TRANSCTRL_ADDREN_Msk                 0x20000000
#define FLASHC_TRANSCTRL_ADDRFMT_Pos                28
#define FLASHC_TRANSCTRL_ADDRFMT_Msk                0x10000000
#define FLASHC_TRANSCTRL_TRANSMODE_Pos              24
#define FLASHC_TRANSCTRL_TRANSMODE_Msk              0xf000000
#define FLASHC_TRANSCTRL_DUALQUAD_Pos               22
#define FLASHC_TRANSCTRL_DUALQUAD_Msk               0xc00000
#define FLASHC_TRANSCTRL_TOKENEN_Pos                21
#define FLASHC_TRANSCTRL_TOKENEN_Msk                0x200000
#define FLASHC_TRANSCTRL_WRTRANCNT_Pos              12
#define FLASHC_TRANSCTRL_WRTRANCNT_Msk              0x1ff000
#define FLASHC_TRANSCTRL_TOKENVALUE_Pos             11
#define FLASHC_TRANSCTRL_TOKENVALUE_Msk             0x800
#define FLASHC_TRANSCTRL_DUMMYCNT_Pos               9
#define FLASHC_TRANSCTRL_DUMMYCNT_Msk               0x600
#define FLASHC_TRANSCTRL_RDTRANCNT_Pos              0
#define FLASHC_TRANSCTRL_RDTRANCNT_Msk              0x1ff

#define FLASHC_CMD_OFFSET                           0x024
#define FLASHC_CMD_CMD_Pos                          0
#define FLASHC_CMD_CMD_Msk                          0xff

#define FLASHC_ADDR_OFFSET                          0x028
#define FLASHC_ADDR_ADDR_Pos                        0
#define FLASHC_ADDR_ADDR_Msk                        0xffffffff

#define FLASHC_DATA_OFFSET                          0x02C
#define FLASHC_DATA_DATA_Pos                        0
#define FLASHC_DATA_DATA_Msk                        0xffffffff

#define FLASHC_CTRL_OFFSET                          0x030
#define FLASHC_CTRL_TXTHRES_Pos                     16
#define FLASHC_CTRL_TXTHRES_Msk                     0x1f0000
#define FLASHC_CTRL_RXTHRES_Pos                     8
#define FLASHC_CTRL_RXTHRES_Msk                     0x1f00
#define FLASHC_CTRL_TXDMAEN_Pos                     4
#define FLASHC_CTRL_TXDMAEN_Msk                     0x10
#define FLASHC_CTRL_RXDMAEN_Pos                     3
#define FLASHC_CTRL_RXDMAEN_Msk                     0x8
#define FLASHC_CTRL_TXFIFORST_Pos                   2
#define FLASHC_CTRL_TXFIFORST_Msk                   0x4
#define FLASHC_CTRL_RXFIFORST_Pos                   1
#define FLASHC_CTRL_RXFIFORST_Msk                   0x2
#define FLASHC_CTRL_SPIRST_Pos                      0
#define FLASHC_CTRL_SPIRST_Msk                      0x1

#define FLASHC_STATUS_OFFSET                        0x034
#define FLASHC_STATUS_TXFULL_Pos                    23
#define FLASHC_STATUS_TXFULL_Msk                    0x800000
#define FLASHC_STATUS_TXEMPTY_Pos                   22
#define FLASHC_STATUS_TXEMPTY_Msk                   0x400000
#define FLASHC_STATUS_TXNUM_Pos                     16
#define FLASHC_STATUS_TXNUM_Msk                     0x1f0000
#define FLASHC_STATUS_RXFULL_Pos                    15
#define FLASHC_STATUS_RXFULL_Msk                    0x8000
#define FLASHC_STATUS_RXEMPTY_Pos                   14
#define FLASHC_STATUS_RXEMPTY_Msk                   0x4000
#define FLASHC_STATUS_RXNUM_Pos                     8
#define FLASHC_STATUS_RXNUM_Msk                     0x1f00
#define FLASHC_STATUS_SPIACTIVE_Pos                 0
#define FLASHC_STATUS_SPIACTIVE_Msk                 0x1

#define FLASHC_INTREN_OFFSET                        0x038
#define FLASHC_INTREN_SLVCMDEN_Pos                  5
#define FLASHC_INTREN_SLVCMDEN_Msk                  0x20
#define FLASHC_INTREN_ENDINTEN_Pos                  4
#define FLASHC_INTREN_ENDINTEN_Msk                  0x10
#define FLASHC_INTREN_TXFIFOINTEN_Pos               3
#define FLASHC_INTREN_TXFIFOINTEN_Msk               0x8
#define FLASHC_INTREN_RXFIFOINTEN_Pos               2
#define FLASHC_INTREN_RXFIFOINTEN_Msk               0x4
#define FLASHC_INTREN_TXFIFOURINTEN_Pos             1
#define FLASHC_INTREN_TXFIFOURINTEN_Msk             0x2
#define FLASHC_INTREN_RXFIFOORINTEN_Pos             0
#define FLASHC_INTREN_RXFIFOORINTEN_Msk             0x1

#define FLASHC_INTRST_OFFSET                        0x03C
#define FLASHC_INTRST_SLVCMDINT_Pos                 5
#define FLASHC_INTRST_SLVCMDINT_Msk                 0x20
#define FLASHC_INTRST_ENDINT_Pos                    4
#define FLASHC_INTRST_ENDINT_Msk                    0x10
#define FLASHC_INTRST_TXFIFOINT_Pos                 3
#define FLASHC_INTRST_TXFIFOINT_Msk                 0x8
#define FLASHC_INTRST_RXFIFOINT_Pos                 2
#define FLASHC_INTRST_RXFIFOINT_Msk                 0x4
#define FLASHC_INTRST_TXFIFOURINT_Pos               1
#define FLASHC_INTRST_TXFIFOURINT_Msk               0x2
#define FLASHC_INTRST_RXFIFOORINT_Pos               0
#define FLASHC_INTRST_RXFIFOORINT_Msk               0x1

#define FLASHC_TIMING_OFFSET                        0x040
#define FLASHC_TIMING_CS2SCLK_Pos                   12
#define FLASHC_TIMING_CS2SCLK_Msk                   0x3000
#define FLASHC_TIMING_CSHT_Pos                      8
#define FLASHC_TIMING_CSHT_Msk                      0xf00
#define FLASHC_TIMING_SCLK_DIV_Pos                  0
#define FLASHC_TIMING_SCLK_DIV_Msk                  0xff

#define FLASHC_MEMCTRL_OFFSET                       0x050
#define FLASHC_MEMCTRL_MEMCTRLCHG_Pos               8
#define FLASHC_MEMCTRL_MEMCTRLCHG_Msk               0x100
#define FLASHC_MEMCTRL_MEMRDCMD_Pos                 0
#define FLASHC_MEMCTRL_MEMRDCMD_Msk                 0xf

#define FLASHC_CS_ADDR_OFFSET                       0x054
#define FLASHC_CS_ADDR_CS0_MEM_ADDR_H_Pos           16
#define FLASHC_CS_ADDR_CS0_MEM_ADDR_H_Msk           0xffff0000
#define FLASHC_CS_ADDR_CS0_MEM_ADDR_L_Pos           0
#define FLASHC_CS_ADDR_CS0_MEM_ADDR_L_Msk           0xffff

#define FLASHC_CS_2_CTRL_OFFSET                     0x058
#define FLASHC_CS_2_CTRL_ADDR_RANGE_ENALBE_Pos      16
#define FLASHC_CS_2_CTRL_ADDR_RANGE_ENALBE_Msk      0xffff0000
#define FLASHC_CS_2_CTRL_CS1_MODE_SEL_Pos           2
#define FLASHC_CS_2_CTRL_CS1_MODE_SEL_Msk           0xc
#define FLASHC_CS_2_CTRL_CS0_MODE_SEL_Pos           0
#define FLASHC_CS_2_CTRL_CS0_MODE_SEL_Msk           0x3

#define FLASHC_SLVST_OFFSET                         0x060
#define FLASHC_SLVST_UNDERRUN_Pos                   18
#define FLASHC_SLVST_UNDERRUN_Msk                   0x40000
#define FLASHC_SLVST_OVERRUN_Pos                    17
#define FLASHC_SLVST_OVERRUN_Msk                    0x20000
#define FLASHC_SLVST_READY_Pos                      16
#define FLASHC_SLVST_READY_Msk                      0x10000
#define FLASHC_SLVST_USR_STATUS_Pos                 0
#define FLASHC_SLVST_USR_STATUS_Msk                 0xffff

#define FLASHC_SLVDATACNT_OFFSET                    0x064
#define FLASHC_SLVDATACNT_WCNT_CLR_Pos              31
#define FLASHC_SLVDATACNT_WCNT_CLR_Msk              0x80000000
#define FLASHC_SLVDATACNT_WCNT_Pos                  16
#define FLASHC_SLVDATACNT_WCNT_Msk                  0x3ff0000
#define FLASHC_SLVDATACNT_RCNT_CLR_Pos              15
#define FLASHC_SLVDATACNT_RCNT_CLR_Msk              0x8000
#define FLASHC_SLVDATACNT_RCNT_Pos                  0
#define FLASHC_SLVDATACNT_RCNT_Msk                  0x3ff

#define FLASHC_CONFIG_OFFSET                        0x07C
#define FLASHC_CONFIG_SLAVE_Pos                     14
#define FLASHC_CONFIG_SLAVE_Msk                     0x4000
#define FLASHC_CONFIG_EILMMEM_Pos                   13
#define FLASHC_CONFIG_EILMMEM_Msk                   0x2000
#define FLASHC_CONFIG_AHBMEM_Pos                    12
#define FLASHC_CONFIG_AHBMEM_Msk                    0x1000
#define FLASHC_CONFIG_DIRECTIO_Pos                  11
#define FLASHC_CONFIG_DIRECTIO_Msk                  0x800
#define FLASHC_CONFIG_QUADSPI_Pos                   9
#define FLASHC_CONFIG_QUADSPI_Msk                   0x200
#define FLASHC_CONFIG_DUALSPI_Pos                   8
#define FLASHC_CONFIG_DUALSPI_Msk                   0x100
#define FLASHC_CONFIG_TXFIFOSIZE_Pos                4
#define FLASHC_CONFIG_TXFIFOSIZE_Msk                0x30
#define FLASHC_CONFIG_RXFIFOSIZE_Pos                0
#define FLASHC_CONFIG_RXFIFOSIZE_Msk                0x3

#define FLASHC_USER_CONFIG_OFFSET                   0x080
#define FLASHC_USER_CONFIG_KEY_PROTECTION_Pos       24
#define FLASHC_USER_CONFIG_KEY_PROTECTION_Msk       0xff000000
#define FLASHC_USER_CONFIG_CRYPTO_EN_Pos            9
#define FLASHC_USER_CONFIG_CRYPTO_EN_Msk            0x200
#define FLASHC_USER_CONFIG_APPCLK_EN_Pos            8
#define FLASHC_USER_CONFIG_APPCLK_EN_Msk            0x100
#define FLASHC_USER_CONFIG_SPI_PRGM_IN_PROC_Pos     7
#define FLASHC_USER_CONFIG_SPI_PRGM_IN_PROC_Msk     0x80
#define FLASHC_USER_CONFIG_SPI_CLOCK_INV_SEL_Pos    6
#define FLASHC_USER_CONFIG_SPI_CLOCK_INV_SEL_Msk    0x40
#define FLASHC_USER_CONFIG_MEM_DM_EN_Pos            5
#define FLASHC_USER_CONFIG_MEM_DM_EN_Msk            0x20
#define FLASHC_USER_CONFIG_REG_DM_EN_Pos            4
#define FLASHC_USER_CONFIG_REG_DM_EN_Msk            0x10
#define FLASHC_USER_CONFIG_MEM_DTR_EN_Pos           3
#define FLASHC_USER_CONFIG_MEM_DTR_EN_Msk           0x8
#define FLASHC_USER_CONFIG_INV_CLK_SEL_Pos          2
#define FLASHC_USER_CONFIG_INV_CLK_SEL_Msk          0x4
#define FLASHC_USER_CONFIG_QPI_EN_Pos               1
#define FLASHC_USER_CONFIG_QPI_EN_Msk               0x2
#define FLASHC_USER_CONFIG_TOKEN_EN_Pos             0
#define FLASHC_USER_CONFIG_TOKEN_EN_Msk             0x1

#define FLASHC_USER_TOKEN_OFFSET                    0x084
#define FLASHC_USER_TOKEN_TOKEN_VALUE_Pos           0
#define FLASHC_USER_TOKEN_TOKEN_VALUE_Msk           0xff

#define FLASHC_USER_MEM_READ_OP_OFFSET              0x088
#define FLASHC_USER_MEM_READ_OP_MEM_LEN_Pos         16
#define FLASHC_USER_MEM_READ_OP_MEM_LEN_Msk         0x30000
#define FLASHC_USER_MEM_READ_OP_MEM_OP_Pos          0
#define FLASHC_USER_MEM_READ_OP_MEM_OP_Msk          0xff

#define FLASHC_USER_MEM_READ_TRANS_OFFSET           0x08C
#define FLASHC_USER_MEM_READ_TRANS_MEM_TRANS_Pos    0
#define FLASHC_USER_MEM_READ_TRANS_MEM_TRANS_Msk    0x7fffffff

#define FLASHC_USER_DUMMY_COUNT_OFFSET              0x090
#define FLASHC_USER_DUMMY_COUNT_MEM_DM_CNT_Pos      8
#define FLASHC_USER_DUMMY_COUNT_MEM_DM_CNT_Msk      0xf00
#define FLASHC_USER_DUMMY_COUNT_REG_DM_CNT_Pos      0
#define FLASHC_USER_DUMMY_COUNT_REG_DM_CNT_Msk      0xf

#define FLASHC_USER_APPEND_CLOCK_PATTERN_OFFSET     0x094
#define FLASHC_USER_APPEND_CLOCK_PATTERN_APPCLK_PAT_Pos    0
#define FLASHC_USER_APPEND_CLOCK_PATTERN_APPCLK_PAT_Msk    0xffff

struct FLASHC_REG_IDREV_BITS
{
    volatile uint32_t REVMINOR                      : 4; // bit 0~3
    volatile uint32_t REVMAJOR                      : 8; // bit 4~11
    volatile uint32_t ID                            : 20; // bit 12~31
};

union FLASHC_REG_IDREV {
    volatile uint32_t                               all;
    struct FLASHC_REG_IDREV_BITS                    bit;
};

struct FLASHC_REG_TRANSFMT_BITS
{
    volatile uint32_t CPHA                          : 1; // bit 0~0
    volatile uint32_t CPOL                          : 1; // bit 1~1
    volatile uint32_t SLVMODE                       : 1; // bit 2~2
    volatile uint32_t LSB                           : 1; // bit 3~3
    volatile uint32_t MOSIBIDIR                     : 1; // bit 4~4
    volatile uint32_t RESV_5_6                      : 2; // bit 5~6
    volatile uint32_t DATAMERGE                     : 1; // bit 7~7
    volatile uint32_t DATALEN                       : 5; // bit 8~12
    volatile uint32_t RESV_13_15                    : 3; // bit 13~15
    volatile uint32_t ADDRLEN                       : 2; // bit 16~17
    volatile uint32_t RESV_18_30                    : 13; // bit 18~30
    volatile uint32_t FAST_MD                       : 1; // bit 31~31
};

union FLASHC_REG_TRANSFMT {
    volatile uint32_t                               all;
    struct FLASHC_REG_TRANSFMT_BITS                 bit;
};

struct FLASHC_REG_DIRECTIO_BITS
{
    volatile uint32_t CS_I                          : 1; // bit 0~0
    volatile uint32_t SCLK_I                        : 1; // bit 1~1
    volatile uint32_t MOSI_I                        : 1; // bit 2~2
    volatile uint32_t MISO_I                        : 1; // bit 3~3
    volatile uint32_t WP_I                          : 1; // bit 4~4
    volatile uint32_t HOLD_I                        : 1; // bit 5~5
    volatile uint32_t RESV_6_7                      : 2; // bit 6~7
    volatile uint32_t CS_O                          : 1; // bit 8~8
    volatile uint32_t SCLK_O                        : 1; // bit 9~9
    volatile uint32_t MOSI_O                        : 1; // bit 10~10
    volatile uint32_t MISO_O                        : 1; // bit 11~11
    volatile uint32_t WP_O                          : 1; // bit 12~12
    volatile uint32_t HOLD_O                        : 1; // bit 13~13
    volatile uint32_t RESV_14_15                    : 2; // bit 14~15
    volatile uint32_t CS_OE                         : 1; // bit 16~16
    volatile uint32_t SCLK_OE                       : 1; // bit 17~17
    volatile uint32_t MOSI_OE                       : 1; // bit 18~18
    volatile uint32_t MISO_OE                       : 1; // bit 19~19
    volatile uint32_t WP_OE                         : 1; // bit 20~20
    volatile uint32_t HOLD_OE                       : 1; // bit 21~21
    volatile uint32_t RESV_22_23                    : 2; // bit 22~23
    volatile uint32_t DIRECTIOEN                    : 1; // bit 24~24
    volatile uint32_t RESV_25_31                    : 7; // bit 25~31
};

union FLASHC_REG_DIRECTIO {
    volatile uint32_t                               all;
    struct FLASHC_REG_DIRECTIO_BITS                 bit;
};

struct FLASHC_REG_TRANSCTRL_BITS
{
    volatile uint32_t RDTRANCNT                     : 9; // bit 0~8
    volatile uint32_t DUMMYCNT                      : 2; // bit 9~10
    volatile uint32_t TOKENVALUE                    : 1; // bit 11~11
    volatile uint32_t WRTRANCNT                     : 9; // bit 12~20
    volatile uint32_t TOKENEN                       : 1; // bit 21~21
    volatile uint32_t DUALQUAD                      : 2; // bit 22~23
    volatile uint32_t TRANSMODE                     : 4; // bit 24~27
    volatile uint32_t ADDRFMT                       : 1; // bit 28~28
    volatile uint32_t ADDREN                        : 1; // bit 29~29
    volatile uint32_t CMDEN                         : 1; // bit 30~30
    volatile uint32_t RESV_31_31                    : 1; // bit 31~31
};

union FLASHC_REG_TRANSCTRL {
    volatile uint32_t                               all;
    struct FLASHC_REG_TRANSCTRL_BITS                bit;
};

struct FLASHC_REG_CMD_BITS
{
    volatile uint32_t CMD                           : 8; // bit 0~7
    volatile uint32_t RESV_8_31                     : 24; // bit 8~31
};

union FLASHC_REG_CMD {
    volatile uint32_t                               all;
    struct FLASHC_REG_CMD_BITS                      bit;
};

struct FLASHC_REG_ADDR_BITS
{
    volatile uint32_t ADDR                          : 32; // bit 0~31
};

union FLASHC_REG_ADDR {
    volatile uint32_t                               all;
    struct FLASHC_REG_ADDR_BITS                     bit;
};

struct FLASHC_REG_DATA_BITS
{
    volatile uint32_t DATA                          : 32; // bit 0~31
};

union FLASHC_REG_DATA {
    volatile uint32_t                               all;
    struct FLASHC_REG_DATA_BITS                     bit;
};

struct FLASHC_REG_CTRL_BITS
{
    volatile uint32_t SPIRST                        : 1; // bit 0~0
    volatile uint32_t RXFIFORST                     : 1; // bit 1~1
    volatile uint32_t TXFIFORST                     : 1; // bit 2~2
    volatile uint32_t RXDMAEN                       : 1; // bit 3~3
    volatile uint32_t TXDMAEN                       : 1; // bit 4~4
    volatile uint32_t RESV_5_7                      : 3; // bit 5~7
    volatile uint32_t RXTHRES                       : 5; // bit 8~12
    volatile uint32_t RESV_13_15                    : 3; // bit 13~15
    volatile uint32_t TXTHRES                       : 5; // bit 16~20
    volatile uint32_t RESV_21_31                    : 11; // bit 21~31
};

union FLASHC_REG_CTRL {
    volatile uint32_t                               all;
    struct FLASHC_REG_CTRL_BITS                     bit;
};

struct FLASHC_REG_STATUS_BITS
{
    volatile uint32_t SPIACTIVE                     : 1; // bit 0~0
    volatile uint32_t RESV_1_7                      : 7; // bit 1~7
    volatile uint32_t RXNUM                         : 5; // bit 8~12
    volatile uint32_t RESV_13_13                    : 1; // bit 13~13
    volatile uint32_t RXEMPTY                       : 1; // bit 14~14
    volatile uint32_t RXFULL                        : 1; // bit 15~15
    volatile uint32_t TXNUM                         : 5; // bit 16~20
    volatile uint32_t RESV_21_21                    : 1; // bit 21~21
    volatile uint32_t TXEMPTY                       : 1; // bit 22~22
    volatile uint32_t TXFULL                        : 1; // bit 23~23
    volatile uint32_t RESV_24_31                    : 8; // bit 24~31
};

union FLASHC_REG_STATUS {
    volatile uint32_t                               all;
    struct FLASHC_REG_STATUS_BITS                   bit;
};

struct FLASHC_REG_INTREN_BITS
{
    volatile uint32_t RXFIFOORINTEN                 : 1; // bit 0~0
    volatile uint32_t TXFIFOURINTEN                 : 1; // bit 1~1
    volatile uint32_t RXFIFOINTEN                   : 1; // bit 2~2
    volatile uint32_t TXFIFOINTEN                   : 1; // bit 3~3
    volatile uint32_t ENDINTEN                      : 1; // bit 4~4
    volatile uint32_t SLVCMDEN                      : 1; // bit 5~5
    volatile uint32_t RESV_6_31                     : 26; // bit 6~31
};

union FLASHC_REG_INTREN {
    volatile uint32_t                               all;
    struct FLASHC_REG_INTREN_BITS                   bit;
};

struct FLASHC_REG_INTRST_BITS
{
    volatile uint32_t RXFIFOORINT                   : 1; // bit 0~0
    volatile uint32_t TXFIFOURINT                   : 1; // bit 1~1
    volatile uint32_t RXFIFOINT                     : 1; // bit 2~2
    volatile uint32_t TXFIFOINT                     : 1; // bit 3~3
    volatile uint32_t ENDINT                        : 1; // bit 4~4
    volatile uint32_t SLVCMDINT                     : 1; // bit 5~5
    volatile uint32_t RESV_6_31                     : 26; // bit 6~31
};

union FLASHC_REG_INTRST {
    volatile uint32_t                               all;
    struct FLASHC_REG_INTRST_BITS                   bit;
};

struct FLASHC_REG_TIMING_BITS
{
    volatile uint32_t SCLK_DIV                      : 8; // bit 0~7
    volatile uint32_t CSHT                          : 4; // bit 8~11
    volatile uint32_t CS2SCLK                       : 2; // bit 12~13
    volatile uint32_t RESV_14_31                    : 18; // bit 14~31
};

union FLASHC_REG_TIMING {
    volatile uint32_t                               all;
    struct FLASHC_REG_TIMING_BITS                   bit;
};

struct FLASHC_REG_MEMCTRL_BITS
{
    volatile uint32_t MEMRDCMD                      : 4; // bit 0~3
    volatile uint32_t RESV_4_7                      : 4; // bit 4~7
    volatile uint32_t MEMCTRLCHG                    : 1; // bit 8~8
    volatile uint32_t RESV_9_31                     : 23; // bit 9~31
};

union FLASHC_REG_MEMCTRL {
    volatile uint32_t                               all;
    struct FLASHC_REG_MEMCTRL_BITS                  bit;
};

struct FLASHC_REG_CS_ADDR_BITS
{
    volatile uint32_t CS0_MEM_ADDR_L                : 16; // bit 0~15
    volatile uint32_t CS0_MEM_ADDR_H                : 16; // bit 16~31
};

union FLASHC_REG_CS_ADDR {
    volatile uint32_t                               all;
    struct FLASHC_REG_CS_ADDR_BITS                  bit;
};

struct FLASHC_REG_CS_2_CTRL_BITS
{
    volatile uint32_t CS0_MODE_SEL                  : 2; // bit 0~1
    volatile uint32_t CS1_MODE_SEL                  : 2; // bit 2~3
    volatile uint32_t RESV_4_15                     : 12; // bit 4~15
    volatile uint32_t ADDR_RANGE_ENALBE             : 16; // bit 16~31
};

union FLASHC_REG_CS_2_CTRL {
    volatile uint32_t                               all;
    struct FLASHC_REG_CS_2_CTRL_BITS                bit;
};

struct FLASHC_REG_SLVST_BITS
{
    volatile uint32_t USR_STATUS                    : 16; // bit 0~15
    volatile uint32_t READY                         : 1; // bit 16~16
    volatile uint32_t OVERRUN                       : 1; // bit 17~17
    volatile uint32_t UNDERRUN                      : 1; // bit 18~18
    volatile uint32_t RESV_19_31                    : 13; // bit 19~31
};

union FLASHC_REG_SLVST {
    volatile uint32_t                               all;
    struct FLASHC_REG_SLVST_BITS                    bit;
};

struct FLASHC_REG_SLVDATACNT_BITS
{
    volatile uint32_t RCNT                          : 10; // bit 0~9
    volatile uint32_t RESV_10_14                    : 5; // bit 10~14
    volatile uint32_t RCNT_CLR                      : 1; // bit 15~15
    volatile uint32_t WCNT                          : 10; // bit 16~25
    volatile uint32_t RESV_26_30                    : 5; // bit 26~30
    volatile uint32_t WCNT_CLR                      : 1; // bit 31~31
};

union FLASHC_REG_SLVDATACNT {
    volatile uint32_t                               all;
    struct FLASHC_REG_SLVDATACNT_BITS               bit;
};

struct FLASHC_REG_CONFIG_BITS
{
    volatile uint32_t RXFIFOSIZE                    : 2; // bit 0~1
    volatile uint32_t RESV_2_3                      : 2; // bit 2~3
    volatile uint32_t TXFIFOSIZE                    : 2; // bit 4~5
    volatile uint32_t RESV_6_7                      : 2; // bit 6~7
    volatile uint32_t DUALSPI                       : 1; // bit 8~8
    volatile uint32_t QUADSPI                       : 1; // bit 9~9
    volatile uint32_t RESV_10_10                    : 1; // bit 10~10
    volatile uint32_t DIRECTIO                      : 1; // bit 11~11
    volatile uint32_t AHBMEM                        : 1; // bit 12~12
    volatile uint32_t EILMMEM                       : 1; // bit 13~13
    volatile uint32_t SLAVE                         : 1; // bit 14~14
    volatile uint32_t RESV_15_31                    : 17; // bit 15~31
};

union FLASHC_REG_CONFIG {
    volatile uint32_t                               all;
    struct FLASHC_REG_CONFIG_BITS                   bit;
};

struct FLASHC_REG_USER_CONFIG_BITS
{
    volatile uint32_t TOKEN_EN                      : 1; // bit 0~0
    volatile uint32_t QPI_EN                        : 1; // bit 1~1
    volatile uint32_t INV_CLK_SEL                   : 1; // bit 2~2
    volatile uint32_t MEM_DTR_EN                    : 1; // bit 3~3
    volatile uint32_t REG_DM_EN                     : 1; // bit 4~4
    volatile uint32_t MEM_DM_EN                     : 1; // bit 5~5
    volatile uint32_t SPI_CLOCK_INV_SEL             : 1; // bit 6~6
    volatile uint32_t SPI_PRGM_IN_PROC              : 1; // bit 7~7
    volatile uint32_t APPCLK_EN                     : 1; // bit 8~8
    volatile uint32_t CRYPTO_EN                     : 1; // bit 9~9
    volatile uint32_t RESV_10_23                    : 14; // bit 10~23
    volatile uint32_t KEY_PROTECTION                : 8; // bit 24~31
};

union FLASHC_REG_USER_CONFIG {
    volatile uint32_t                               all;
    struct FLASHC_REG_USER_CONFIG_BITS              bit;
};

struct FLASHC_REG_USER_TOKEN_BITS
{
    volatile uint32_t TOKEN_VALUE                   : 8; // bit 0~7
    volatile uint32_t RESV_8_31                     : 24; // bit 8~31
};

union FLASHC_REG_USER_TOKEN {
    volatile uint32_t                               all;
    struct FLASHC_REG_USER_TOKEN_BITS               bit;
};

struct FLASHC_REG_USER_MEM_READ_OP_BITS
{
    volatile uint32_t MEM_OP                        : 8; // bit 0~7
    volatile uint32_t RESV_8_15                     : 8; // bit 8~15
    volatile uint32_t MEM_LEN                       : 2; // bit 16~17
    volatile uint32_t RESV_18_31                    : 14; // bit 18~31
};

union FLASHC_REG_USER_MEM_READ_OP {
    volatile uint32_t                               all;
    struct FLASHC_REG_USER_MEM_READ_OP_BITS         bit;
};

struct FLASHC_REG_USER_MEM_READ_TRANS_BITS
{
    volatile uint32_t MEM_TRANS                     : 31; // bit 0~30
    volatile uint32_t RESV_31_31                    : 1; // bit 31~31
};

union FLASHC_REG_USER_MEM_READ_TRANS {
    volatile uint32_t                               all;
    struct FLASHC_REG_USER_MEM_READ_TRANS_BITS      bit;
};

struct FLASHC_REG_USER_DUMMY_COUNT_BITS
{
    volatile uint32_t REG_DM_CNT                    : 4; // bit 0~3
    volatile uint32_t RESV_4_7                      : 4; // bit 4~7
    volatile uint32_t MEM_DM_CNT                    : 4; // bit 8~11
    volatile uint32_t RESV_12_31                    : 20; // bit 12~31
};

union FLASHC_REG_USER_DUMMY_COUNT {
    volatile uint32_t                               all;
    struct FLASHC_REG_USER_DUMMY_COUNT_BITS         bit;
};

struct FLASHC_REG_USER_APPEND_CLOCK_PATTERN_BITS
{
    volatile uint32_t APPCLK_PAT                    : 16; // bit 0~15
    volatile uint32_t RESV_16_31                    : 16; // bit 16~31
};

union FLASHC_REG_USER_APPEND_CLOCK_PATTERN {
    volatile uint32_t                               all;
    struct FLASHC_REG_USER_APPEND_CLOCK_PATTERN_BITS    bit;
};

typedef struct
{
    union FLASHC_REG_IDREV                          REG_IDREV;   // 0x000
    volatile uint32_t                               REG_RESV_0X4_0XC[3];
    union FLASHC_REG_TRANSFMT                       REG_TRANSFMT; // 0x010
    union FLASHC_REG_DIRECTIO                       REG_DIRECTIO; // 0x014
    volatile uint32_t                               REG_RESV_0X18_0X1C[2];
    union FLASHC_REG_TRANSCTRL                      REG_TRANSCTRL; // 0x020
    union FLASHC_REG_CMD                            REG_CMD;     // 0x024
    union FLASHC_REG_ADDR                           REG_ADDR;    // 0x028
    union FLASHC_REG_DATA                           REG_DATA;    // 0x02C
    union FLASHC_REG_CTRL                           REG_CTRL;    // 0x030
    union FLASHC_REG_STATUS                         REG_STATUS;  // 0x034
    union FLASHC_REG_INTREN                         REG_INTREN;  // 0x038
    union FLASHC_REG_INTRST                         REG_INTRST;  // 0x03C
    union FLASHC_REG_TIMING                         REG_TIMING;  // 0x040
    volatile uint32_t                               REG_RESV_0X44_0X4C[3];
    union FLASHC_REG_MEMCTRL                        REG_MEMCTRL; // 0x050
    union FLASHC_REG_CS_ADDR                        REG_CS_ADDR; // 0x054
    union FLASHC_REG_CS_2_CTRL                      REG_CS_2_CTRL; // 0x058
    volatile uint32_t                               REG_RESV_0X5C_0X5C[1];
    union FLASHC_REG_SLVST                          REG_SLVST;   // 0x060
    union FLASHC_REG_SLVDATACNT                     REG_SLVDATACNT; // 0x064
    volatile uint32_t                               REG_RESV_0X68_0X78[5];
    union FLASHC_REG_CONFIG                         REG_CONFIG;  // 0x07C
    union FLASHC_REG_USER_CONFIG                    REG_USER_CONFIG; // 0x080
    union FLASHC_REG_USER_TOKEN                     REG_USER_TOKEN; // 0x084
    union FLASHC_REG_USER_MEM_READ_OP               REG_USER_MEM_READ_OP; // 0x088
    union FLASHC_REG_USER_MEM_READ_TRANS            REG_USER_MEM_READ_TRANS; // 0x08C
    union FLASHC_REG_USER_DUMMY_COUNT               REG_USER_DUMMY_COUNT; // 0x090
    union FLASHC_REG_USER_APPEND_CLOCK_PATTERN      REG_USER_APPEND_CLOCK_PATTERN; // 0x094
} FLASHC_RegDef;


#endif // __FLASHC_REGFILE_H__

