//  ----------------------------------------------------------------------
//  File Name   : GenCFold/ir_reg_arcs.h
//  Description : C header file generated by Python script.
//  Script Ver  £ºLS.AUTO_REG.2024.03.01
//  Create Time : 2024-06-20 11:17:02
//  Comments    : 
//  ----------------------------------------------------------------------

#ifndef __IR_REGFILE_H__
#define __IR_REGFILE_H__

#include <stdint.h>

#define IR_IR_CTRL_OFFSET                           0x000
#define IR_IR_CTRL_SW_HW_MODE_Pos                   31
#define IR_IR_CTRL_SW_HW_MODE_Msk                   0x80000000
#define IR_IR_CTRL_IR_BIT_CYCLE_Pos                 24
#define IR_IR_CTRL_IR_BIT_CYCLE_Msk                 0x7f000000
#define IR_IR_CTRL_TXRX_MODE_Pos                    23
#define IR_IR_CTRL_TXRX_MODE_Msk                    0x800000
#define IR_IR_CTRL_BIT_TIME_2_Pos                   16
#define IR_IR_CTRL_BIT_TIME_2_Msk                   0x7f0000
#define IR_IR_CTRL_TX_REPEAT_MODE_Pos               15
#define IR_IR_CTRL_TX_REPEAT_MODE_Msk               0x8000
#define IR_IR_CTRL_BIT_TIME_1_Pos                   8
#define IR_IR_CTRL_BIT_TIME_1_Msk                   0x7f00
#define IR_IR_CTRL_IR_DATACODE_VERIFY_Pos           7
#define IR_IR_CTRL_IR_DATACODE_VERIFY_Msk           0x80
#define IR_IR_CTRL_IR_USERCODE_VERIFY_Pos           6
#define IR_IR_CTRL_IR_USERCODE_VERIFY_Msk           0x40
#define IR_IR_CTRL_IR_INT_VERIFY_EN_Pos             5
#define IR_IR_CTRL_IR_INT_VERIFY_EN_Msk             0x20
#define IR_IR_CTRL_IR_INT_EN_Pos                    4
#define IR_IR_CTRL_IR_INT_EN_Msk                    0x10
#define IR_IR_CTRL_IR_END_DETECT_EN_Pos             3
#define IR_IR_CTRL_IR_END_DETECT_EN_Msk             0x8
#define IR_IR_CTRL_IR_MODE_Pos                      1
#define IR_IR_CTRL_IR_MODE_Msk                      0x6
#define IR_IR_CTRL_IR_EN_Pos                        0
#define IR_IR_CTRL_IR_EN_Msk                        0x1

#define IR_IR_TX_CONFIG_OFFSET                      0x004
#define IR_IR_TX_CONFIG_CARRIER_CNT_CLR_Pos         3
#define IR_IR_TX_CONFIG_CARRIER_CNT_CLR_Msk         0x8
#define IR_IR_TX_CONFIG_IR_DEBUG_SEL_Pos            2
#define IR_IR_TX_CONFIG_IR_DEBUG_SEL_Msk            0x4
#define IR_IR_TX_CONFIG_IR_TX_POL_Pos               1
#define IR_IR_TX_CONFIG_IR_TX_POL_Msk               0x2
#define IR_IR_TX_CONFIG_TX_START_Pos                0
#define IR_IR_TX_CONFIG_TX_START_Msk                0x1

#define IR_IR_CARRY_CONFIG_OFFSET                   0x008
#define IR_IR_CARRY_CONFIG_IR_RX_IN_POL_Pos         28
#define IR_IR_CARRY_CONFIG_IR_RX_IN_POL_Msk         0x10000000
#define IR_IR_CARRY_CONFIG_RX_CR_DUTY_FIX_Pos       27
#define IR_IR_CARRY_CONFIG_RX_CR_DUTY_FIX_Msk       0x8000000
#define IR_IR_CARRY_CONFIG_RX_CR_HI_TH_Pos          18
#define IR_IR_CARRY_CONFIG_RX_CR_HI_TH_Msk          0x7fc0000
#define IR_IR_CARRY_CONFIG_IR_CARRY_HIGH_Pos        9
#define IR_IR_CARRY_CONFIG_IR_CARRY_HIGH_Msk        0x3fe00
#define IR_IR_CARRY_CONFIG_IR_CARRY_LOW_Pos         0
#define IR_IR_CARRY_CONFIG_IR_CARRY_LOW_Msk         0x1ff

#define IR_IR_TIME_1_OFFSET                         0x00C
#define IR_IR_TIME_1_IR_RX_POL_Pos                  31
#define IR_IR_TIME_1_IR_RX_POL_Msk                  0x80000000
#define IR_IR_TIME_1_RX_CR_EN_Pos                   30
#define IR_IR_TIME_1_RX_CR_EN_Msk                   0x40000000
#define IR_IR_TIME_1_RX_CR_DET_TH_Pos               21
#define IR_IR_TIME_1_RX_CR_DET_TH_Msk               0x3fe00000
#define IR_IR_TIME_1_RX_CR_LOS_TH_Pos               12
#define IR_IR_TIME_1_RX_CR_LOS_TH_Msk               0x1ff000
#define IR_IR_TIME_1_IR_TIME_S1_Pos                 0
#define IR_IR_TIME_1_IR_TIME_S1_Msk                 0xfff

#define IR_IR_TIME_2_OFFSET                         0x010
#define IR_IR_TIME_2_RX_CR_FILTER_Pos               27
#define IR_IR_TIME_2_RX_CR_FILTER_Msk               0x78000000
#define IR_IR_TIME_2_RX_CR_START_Pos                26
#define IR_IR_TIME_2_RX_CR_START_Msk                0x4000000
#define IR_IR_TIME_2_CARRIER_DIVID_Pos              16
#define IR_IR_TIME_2_CARRIER_DIVID_Msk              0x3ff0000
#define IR_IR_TIME_2_RX_CR_EXP_Pos                  12
#define IR_IR_TIME_2_RX_CR_EXP_Msk                  0xf000
#define IR_IR_TIME_2_IR_TIME_S2_Pos                 0
#define IR_IR_TIME_2_IR_TIME_S2_Msk                 0xfff

#define IR_IR_TIME_3_OFFSET                         0x014
#define IR_IR_TIME_3_IR_TIME_S3_Pos                 0
#define IR_IR_TIME_3_IR_TIME_S3_Msk                 0xfff

#define IR_IR_TIME_4_OFFSET                         0x018
#define IR_IR_TIME_4_IR_TIME_S4_Pos                 0
#define IR_IR_TIME_4_IR_TIME_S4_Msk                 0xfff

#define IR_IR_TIME_5_OFFSET                         0x01C
#define IR_IR_TIME_5_IR_TIME_S5_Pos                 0
#define IR_IR_TIME_5_IR_TIME_S5_Msk                 0xfff

#define IR_IR_RX_CODE_OFFSET                        0x020
#define IR_IR_RX_CODE_IR_RX_DATACODE_Pos            16
#define IR_IR_RX_CODE_IR_RX_DATACODE_Msk            0xffff0000
#define IR_IR_RX_CODE_IR_RX_USERCODE_Pos            0
#define IR_IR_RX_CODE_IR_RX_USERCODE_Msk            0xffff

#define IR_IR_TX_CODE_OFFSET                        0x024
#define IR_IR_TX_CODE_IR_TX_DATACODE_Pos            16
#define IR_IR_TX_CODE_IR_TX_DATACODE_Msk            0xffff0000
#define IR_IR_TX_CODE_IR_TX_USERCODE_Pos            0
#define IR_IR_TX_CODE_IR_TX_USERCODE_Msk            0xffff

#define IR_IR_FSM_OFFSET                            0x028
#define IR_IR_FSM_IR_RX_FIFO_WRCLR_DONE_Pos         21
#define IR_IR_FSM_IR_RX_FIFO_WRCLR_DONE_Msk         0x200000
#define IR_IR_FSM_IR_TX_FIFO_RDCLR_DONE_Pos         20
#define IR_IR_FSM_IR_TX_FIFO_RDCLR_DONE_Msk         0x100000
#define IR_IR_FSM_IR_RX_DMA_DONE_Pos                19
#define IR_IR_FSM_IR_RX_DMA_DONE_Msk                0x80000
#define IR_IR_FSM_IR_TX_DMA_DONE_Pos                18
#define IR_IR_FSM_IR_TX_DMA_DONE_Msk                0x40000
#define IR_IR_FSM_IR_RX_FIFO_USEDW_Pos              14
#define IR_IR_FSM_IR_RX_FIFO_USEDW_Msk              0x3c000
#define IR_IR_FSM_IR_RX_FIFO_FULL_Pos               13
#define IR_IR_FSM_IR_RX_FIFO_FULL_Msk               0x2000
#define IR_IR_FSM_IR_RX_FIFO_EMPTY_Pos              12
#define IR_IR_FSM_IR_RX_FIFO_EMPTY_Msk              0x1000
#define IR_IR_FSM_IR_TX_FIFO_USEDW_Pos              8
#define IR_IR_FSM_IR_TX_FIFO_USEDW_Msk              0xf00
#define IR_IR_FSM_IR_TX_FIFO_FULL_Pos               7
#define IR_IR_FSM_IR_TX_FIFO_FULL_Msk               0x80
#define IR_IR_FSM_IR_TX_FIFO_EMPTY_Pos              6
#define IR_IR_FSM_IR_TX_FIFO_EMPTY_Msk              0x40
#define IR_IR_FSM_IR_TX_REPEAT_Pos                  5
#define IR_IR_FSM_IR_TX_REPEAT_Msk                  0x20
#define IR_IR_FSM_IR_TRANSMIT_OK_Pos                4
#define IR_IR_FSM_IR_TRANSMIT_OK_Msk                0x10
#define IR_IR_FSM_IR_REPEAT_Pos                     3
#define IR_IR_FSM_IR_REPEAT_Msk                     0x8
#define IR_IR_FSM_IR_DATACODE_VERIFY_Pos            2
#define IR_IR_FSM_IR_DATACODE_VERIFY_Msk            0x4
#define IR_IR_FSM_IR_USERCODE_VERIFY_Pos            1
#define IR_IR_FSM_IR_USERCODE_VERIFY_Msk            0x2
#define IR_IR_FSM_IR_RECEIVED_OK_Pos                0
#define IR_IR_FSM_IR_RECEIVED_OK_Msk                0x1

#define IR_IR_TX_FIFO_OFFSET                        0x02C
#define IR_IR_TX_FIFO_TXDATA_HI_LO_Pos              15
#define IR_IR_TX_FIFO_TXDATA_HI_LO_Msk              0x8000
#define IR_IR_TX_FIFO_TX_DATA_LEN_Pos               0
#define IR_IR_TX_FIFO_TX_DATA_LEN_Msk               0x7fff

#define IR_IR_RX_FIFO_OFFSET                        0x030
#define IR_IR_RX_FIFO_RXDATA_HI_LO_Pos              15
#define IR_IR_RX_FIFO_RXDATA_HI_LO_Msk              0x8000
#define IR_IR_RX_FIFO_RX_DATA_LEN_Pos               0
#define IR_IR_RX_FIFO_RX_DATA_LEN_Msk               0x7fff

#define IR_IR_DMA_CONFIG_OFFSET                     0x034
#define IR_IR_DMA_CONFIG_RX_DMA_THRES_SEL_Pos       6
#define IR_IR_DMA_CONFIG_RX_DMA_THRES_SEL_Msk       0x3c0
#define IR_IR_DMA_CONFIG_TX_DMA_THRES_SEL_Pos       2
#define IR_IR_DMA_CONFIG_TX_DMA_THRES_SEL_Msk       0x3c
#define IR_IR_DMA_CONFIG_RX_DMA_ENABLE_Pos          1
#define IR_IR_DMA_CONFIG_RX_DMA_ENABLE_Msk          0x2
#define IR_IR_DMA_CONFIG_TX_DMA_ENABLE_Pos          0
#define IR_IR_DMA_CONFIG_TX_DMA_ENABLE_Msk          0x1

#define IR_IR_FIFO_CONFIG_OFFSET                    0x038
#define IR_IR_FIFO_CONFIG_RX_FIFO_WR_CLR_Pos        3
#define IR_IR_FIFO_CONFIG_RX_FIFO_WR_CLR_Msk        0x8
#define IR_IR_FIFO_CONFIG_RX_FIFO_RD_CLR_Pos        2
#define IR_IR_FIFO_CONFIG_RX_FIFO_RD_CLR_Msk        0x4
#define IR_IR_FIFO_CONFIG_TX_FIFO_WR_CLR_Pos        1
#define IR_IR_FIFO_CONFIG_TX_FIFO_WR_CLR_Msk        0x2
#define IR_IR_FIFO_CONFIG_TX_FIFO_RD_CLR_Pos        0
#define IR_IR_FIFO_CONFIG_TX_FIFO_RD_CLR_Msk        0x1

#define IR_IR_CLEAR_STATUS_OFFSET                   0x03C
#define IR_IR_CLEAR_STATUS_IR_INT_CLR_Pos           6
#define IR_IR_CLEAR_STATUS_IR_INT_CLR_Msk           0x40
#define IR_IR_CLEAR_STATUS_IR_RX_DMA_DONE_CLR_Pos    5
#define IR_IR_CLEAR_STATUS_IR_RX_DMA_DONE_CLR_Msk    0x20
#define IR_IR_CLEAR_STATUS_IR_TX_DMA_DONE_CLR_Pos    4
#define IR_IR_CLEAR_STATUS_IR_TX_DMA_DONE_CLR_Msk    0x10
#define IR_IR_CLEAR_STATUS_IR_TX_REPEAT_CLR_Pos     3
#define IR_IR_CLEAR_STATUS_IR_TX_REPEAT_CLR_Msk     0x8
#define IR_IR_CLEAR_STATUS_IR_TRANSMIT_OK_CLR_Pos    2
#define IR_IR_CLEAR_STATUS_IR_TRANSMIT_OK_CLR_Msk    0x4
#define IR_IR_CLEAR_STATUS_IR_REPEAT_CLR_Pos        1
#define IR_IR_CLEAR_STATUS_IR_REPEAT_CLR_Msk        0x2
#define IR_IR_CLEAR_STATUS_IR_RECEIVED_OK_CLR_Pos    0
#define IR_IR_CLEAR_STATUS_IR_RECEIVED_OK_CLR_Msk    0x1

#define IR_IR_IDLE_THRES_OFFSET                     0x040
#define IR_IR_IDLE_THRES_THRES_Pos                  0
#define IR_IR_IDLE_THRES_THRES_Msk                  0x7fff

#define IR_IR_ANA_OFFSET                            0x044
#define IR_IR_ANA_IR_ANA_TX_TEST_EN_Pos             12
#define IR_IR_ANA_IR_ANA_TX_TEST_EN_Msk             0x1000
#define IR_IR_ANA_IR_INTEGRATOR_VREF_SEL_Pos        10
#define IR_IR_ANA_IR_INTEGRATOR_VREF_SEL_Msk        0xc00
#define IR_IR_ANA_IR_RX_SEL_Pos                     9
#define IR_IR_ANA_IR_RX_SEL_Msk                     0x200
#define IR_IR_ANA_IR_TX_CURRENT_SEL_Pos             7
#define IR_IR_ANA_IR_TX_CURRENT_SEL_Msk             0x180
#define IR_IR_ANA_IR_ANA_CR_DEC_EN_Pos              6
#define IR_IR_ANA_IR_ANA_CR_DEC_EN_Msk              0x40
#define IR_IR_ANA_IR_ANA_IN_EN_Pos                  5
#define IR_IR_ANA_IR_ANA_IN_EN_Msk                  0x20
#define IR_IR_ANA_IR_ANA_OUT_EN_Pos                 4
#define IR_IR_ANA_IR_ANA_OUT_EN_Msk                 0x10
#define IR_IR_ANA_IR_ANA_TRIM_Pos                   0
#define IR_IR_ANA_IR_ANA_TRIM_Msk                   0xf

struct IR_REG_IR_CTRL_BITS
{
    volatile uint32_t IR_EN                         : 1; // bit 0~0
    volatile uint32_t IR_MODE                       : 2; // bit 1~2
    volatile uint32_t IR_END_DETECT_EN              : 1; // bit 3~3
    volatile uint32_t IR_INT_EN                     : 1; // bit 4~4
    volatile uint32_t IR_INT_VERIFY_EN              : 1; // bit 5~5
    volatile uint32_t IR_USERCODE_VERIFY            : 1; // bit 6~6
    volatile uint32_t IR_DATACODE_VERIFY            : 1; // bit 7~7
    volatile uint32_t BIT_TIME_1                    : 7; // bit 8~14
    volatile uint32_t TX_REPEAT_MODE                : 1; // bit 15~15
    volatile uint32_t BIT_TIME_2                    : 7; // bit 16~22
    volatile uint32_t TXRX_MODE                     : 1; // bit 23~23
    volatile uint32_t IR_BIT_CYCLE                  : 7; // bit 24~30
    volatile uint32_t SW_HW_MODE                    : 1; // bit 31~31
};

union IR_REG_IR_CTRL {
    volatile uint32_t                               all;
    struct IR_REG_IR_CTRL_BITS                      bit;
};

struct IR_REG_IR_TX_CONFIG_BITS
{
    volatile uint32_t TX_START                      : 1; // bit 0~0
    volatile uint32_t IR_TX_POL                     : 1; // bit 1~1
    volatile uint32_t IR_DEBUG_SEL                  : 1; // bit 2~2
    volatile uint32_t CARRIER_CNT_CLR               : 1; // bit 3~3
    volatile uint32_t RESV_4_31                     : 28; // bit 4~31
};

union IR_REG_IR_TX_CONFIG {
    volatile uint32_t                               all;
    struct IR_REG_IR_TX_CONFIG_BITS                 bit;
};

struct IR_REG_IR_CARRY_CONFIG_BITS
{
    volatile uint32_t IR_CARRY_LOW                  : 9; // bit 0~8
    volatile uint32_t IR_CARRY_HIGH                 : 9; // bit 9~17
    volatile uint32_t RX_CR_HI_TH                   : 9; // bit 18~26
    volatile uint32_t RX_CR_DUTY_FIX                : 1; // bit 27~27
    volatile uint32_t IR_RX_IN_POL                  : 1; // bit 28~28
    volatile uint32_t RESV_29_31                    : 3; // bit 29~31
};

union IR_REG_IR_CARRY_CONFIG {
    volatile uint32_t                               all;
    struct IR_REG_IR_CARRY_CONFIG_BITS              bit;
};

struct IR_REG_IR_TIME_1_BITS
{
    volatile uint32_t IR_TIME_S1                    : 12; // bit 0~11
    volatile uint32_t RX_CR_LOS_TH                  : 9; // bit 12~20
    volatile uint32_t RX_CR_DET_TH                  : 9; // bit 21~29
    volatile uint32_t RX_CR_EN                      : 1; // bit 30~30
    volatile uint32_t IR_RX_POL                     : 1; // bit 31~31
};

union IR_REG_IR_TIME_1 {
    volatile uint32_t                               all;
    struct IR_REG_IR_TIME_1_BITS                    bit;
};

struct IR_REG_IR_TIME_2_BITS
{
    volatile uint32_t IR_TIME_S2                    : 12; // bit 0~11
    volatile uint32_t RX_CR_EXP                     : 4; // bit 12~15
    volatile uint32_t CARRIER_DIVID                 : 10; // bit 16~25
    volatile uint32_t RX_CR_START                   : 1; // bit 26~26
    volatile uint32_t RX_CR_FILTER                  : 4; // bit 27~30
    volatile uint32_t RESV_31_31                    : 1; // bit 31~31
};

union IR_REG_IR_TIME_2 {
    volatile uint32_t                               all;
    struct IR_REG_IR_TIME_2_BITS                    bit;
};

struct IR_REG_IR_TIME_3_BITS
{
    volatile uint32_t IR_TIME_S3                    : 12; // bit 0~11
    volatile uint32_t RESV_12_31                    : 20; // bit 12~31
};

union IR_REG_IR_TIME_3 {
    volatile uint32_t                               all;
    struct IR_REG_IR_TIME_3_BITS                    bit;
};

struct IR_REG_IR_TIME_4_BITS
{
    volatile uint32_t IR_TIME_S4                    : 12; // bit 0~11
    volatile uint32_t RESV_12_31                    : 20; // bit 12~31
};

union IR_REG_IR_TIME_4 {
    volatile uint32_t                               all;
    struct IR_REG_IR_TIME_4_BITS                    bit;
};

struct IR_REG_IR_TIME_5_BITS
{
    volatile uint32_t IR_TIME_S5                    : 12; // bit 0~11
    volatile uint32_t RESV_12_31                    : 20; // bit 12~31
};

union IR_REG_IR_TIME_5 {
    volatile uint32_t                               all;
    struct IR_REG_IR_TIME_5_BITS                    bit;
};

struct IR_REG_IR_RX_CODE_BITS
{
    volatile uint32_t IR_RX_USERCODE                : 16; // bit 0~15
    volatile uint32_t IR_RX_DATACODE                : 16; // bit 16~31
};

union IR_REG_IR_RX_CODE {
    volatile uint32_t                               all;
    struct IR_REG_IR_RX_CODE_BITS                   bit;
};

struct IR_REG_IR_TX_CODE_BITS
{
    volatile uint32_t IR_TX_USERCODE                : 16; // bit 0~15
    volatile uint32_t IR_TX_DATACODE                : 16; // bit 16~31
};

union IR_REG_IR_TX_CODE {
    volatile uint32_t                               all;
    struct IR_REG_IR_TX_CODE_BITS                   bit;
};

struct IR_REG_IR_FSM_BITS
{
    volatile uint32_t IR_RECEIVED_OK                : 1; // bit 0~0
    volatile uint32_t IR_USERCODE_VERIFY            : 1; // bit 1~1
    volatile uint32_t IR_DATACODE_VERIFY            : 1; // bit 2~2
    volatile uint32_t IR_REPEAT                     : 1; // bit 3~3
    volatile uint32_t IR_TRANSMIT_OK                : 1; // bit 4~4
    volatile uint32_t IR_TX_REPEAT                  : 1; // bit 5~5
    volatile uint32_t IR_TX_FIFO_EMPTY              : 1; // bit 6~6
    volatile uint32_t IR_TX_FIFO_FULL               : 1; // bit 7~7
    volatile uint32_t IR_TX_FIFO_USEDW              : 4; // bit 8~11
    volatile uint32_t IR_RX_FIFO_EMPTY              : 1; // bit 12~12
    volatile uint32_t IR_RX_FIFO_FULL               : 1; // bit 13~13
    volatile uint32_t IR_RX_FIFO_USEDW              : 4; // bit 14~17
    volatile uint32_t IR_TX_DMA_DONE                : 1; // bit 18~18
    volatile uint32_t IR_RX_DMA_DONE                : 1; // bit 19~19
    volatile uint32_t IR_TX_FIFO_RDCLR_DONE         : 1; // bit 20~20
    volatile uint32_t IR_RX_FIFO_WRCLR_DONE         : 1; // bit 21~21
    volatile uint32_t RESV_22_31                    : 10; // bit 22~31
};

union IR_REG_IR_FSM {
    volatile uint32_t                               all;
    struct IR_REG_IR_FSM_BITS                       bit;
};

struct IR_REG_IR_TX_FIFO_BITS
{
    volatile uint32_t TX_DATA_LEN                   : 15; // bit 0~14
    volatile uint32_t TXDATA_HI_LO                  : 1; // bit 15~15
    volatile uint32_t RESV_16_31                    : 16; // bit 16~31
};

union IR_REG_IR_TX_FIFO {
    volatile uint32_t                               all;
    struct IR_REG_IR_TX_FIFO_BITS                   bit;
};

struct IR_REG_IR_RX_FIFO_BITS
{
    volatile uint32_t RX_DATA_LEN                   : 15; // bit 0~14
    volatile uint32_t RXDATA_HI_LO                  : 1; // bit 15~15
    volatile uint32_t RESV_16_31                    : 16; // bit 16~31
};

union IR_REG_IR_RX_FIFO {
    volatile uint32_t                               all;
    struct IR_REG_IR_RX_FIFO_BITS                   bit;
};

struct IR_REG_IR_DMA_CONFIG_BITS
{
    volatile uint32_t TX_DMA_ENABLE                 : 1; // bit 0~0
    volatile uint32_t RX_DMA_ENABLE                 : 1; // bit 1~1
    volatile uint32_t TX_DMA_THRES_SEL              : 4; // bit 2~5
    volatile uint32_t RX_DMA_THRES_SEL              : 4; // bit 6~9
    volatile uint32_t RESV_10_31                    : 22; // bit 10~31
};

union IR_REG_IR_DMA_CONFIG {
    volatile uint32_t                               all;
    struct IR_REG_IR_DMA_CONFIG_BITS                bit;
};

struct IR_REG_IR_FIFO_CONFIG_BITS
{
    volatile uint32_t TX_FIFO_RD_CLR                : 1; // bit 0~0
    volatile uint32_t TX_FIFO_WR_CLR                : 1; // bit 1~1
    volatile uint32_t RX_FIFO_RD_CLR                : 1; // bit 2~2
    volatile uint32_t RX_FIFO_WR_CLR                : 1; // bit 3~3
    volatile uint32_t RESV_4_31                     : 28; // bit 4~31
};

union IR_REG_IR_FIFO_CONFIG {
    volatile uint32_t                               all;
    struct IR_REG_IR_FIFO_CONFIG_BITS               bit;
};

struct IR_REG_IR_CLEAR_STATUS_BITS
{
    volatile uint32_t IR_RECEIVED_OK_CLR            : 1; // bit 0~0
    volatile uint32_t IR_REPEAT_CLR                 : 1; // bit 1~1
    volatile uint32_t IR_TRANSMIT_OK_CLR            : 1; // bit 2~2
    volatile uint32_t IR_TX_REPEAT_CLR              : 1; // bit 3~3
    volatile uint32_t IR_TX_DMA_DONE_CLR            : 1; // bit 4~4
    volatile uint32_t IR_RX_DMA_DONE_CLR            : 1; // bit 5~5
    volatile uint32_t IR_INT_CLR                    : 1; // bit 6~6
    volatile uint32_t RESV_7_31                     : 25; // bit 7~31
};

union IR_REG_IR_CLEAR_STATUS {
    volatile uint32_t                               all;
    struct IR_REG_IR_CLEAR_STATUS_BITS              bit;
};

struct IR_REG_IR_IDLE_THRES_BITS
{
    volatile uint32_t THRES                         : 15; // bit 0~14
    volatile uint32_t RESV_15_31                    : 17; // bit 15~31
};

union IR_REG_IR_IDLE_THRES {
    volatile uint32_t                               all;
    struct IR_REG_IR_IDLE_THRES_BITS                bit;
};

struct IR_REG_IR_ANA_BITS
{
    volatile uint32_t IR_ANA_TRIM                   : 4; // bit 0~3
    volatile uint32_t IR_ANA_OUT_EN                 : 1; // bit 4~4
    volatile uint32_t IR_ANA_IN_EN                  : 1; // bit 5~5
    volatile uint32_t IR_ANA_CR_DEC_EN              : 1; // bit 6~6
    volatile uint32_t IR_TX_CURRENT_SEL             : 2; // bit 7~8
    volatile uint32_t IR_RX_SEL                     : 1; // bit 9~9
    volatile uint32_t IR_INTEGRATOR_VREF_SEL        : 2; // bit 10~11
    volatile uint32_t IR_ANA_TX_TEST_EN             : 1; // bit 12~12
    volatile uint32_t RESV_13_31                    : 19; // bit 13~31
};

union IR_REG_IR_ANA {
    volatile uint32_t                               all;
    struct IR_REG_IR_ANA_BITS                       bit;
};

typedef struct
{
    union IR_REG_IR_CTRL                            REG_IR_CTRL; // 0x000
    union IR_REG_IR_TX_CONFIG                       REG_IR_TX_CONFIG; // 0x004
    union IR_REG_IR_CARRY_CONFIG                    REG_IR_CARRY_CONFIG; // 0x008
    union IR_REG_IR_TIME_1                          REG_IR_TIME_1; // 0x00C
    union IR_REG_IR_TIME_2                          REG_IR_TIME_2; // 0x010
    union IR_REG_IR_TIME_3                          REG_IR_TIME_3; // 0x014
    union IR_REG_IR_TIME_4                          REG_IR_TIME_4; // 0x018
    union IR_REG_IR_TIME_5                          REG_IR_TIME_5; // 0x01C
    union IR_REG_IR_RX_CODE                         REG_IR_RX_CODE; // 0x020
    union IR_REG_IR_TX_CODE                         REG_IR_TX_CODE; // 0x024
    union IR_REG_IR_FSM                             REG_IR_FSM;  // 0x028
    union IR_REG_IR_TX_FIFO                         REG_IR_TX_FIFO; // 0x02C
    union IR_REG_IR_RX_FIFO                         REG_IR_RX_FIFO; // 0x030
    union IR_REG_IR_DMA_CONFIG                      REG_IR_DMA_CONFIG; // 0x034
    union IR_REG_IR_FIFO_CONFIG                     REG_IR_FIFO_CONFIG; // 0x038
    union IR_REG_IR_CLEAR_STATUS                    REG_IR_CLEAR_STATUS; // 0x03C
    union IR_REG_IR_IDLE_THRES                      REG_IR_IDLE_THRES; // 0x040
    union IR_REG_IR_ANA                             REG_IR_ANA;  // 0x044
} IR_RegDef;


#endif // __IR_REGFILE_H__

