//  ----------------------------------------------------------------------
//  File Name   : GenCFold/jpeg_reg_arcs.h
//  Description : C header file generated by Python script.
//  Script Ver  £ºLS.AUTO_REG.2024.03.01
//  Create Time : 2024-06-20 11:17:02
//  Comments    : 
//  ----------------------------------------------------------------------

#ifndef __JPEG_REGFILE_H__
#define __JPEG_REGFILE_H__

#include <stdint.h>

#define JPEG_RSV_OFFSET                             0x000

#define JPEG_CONTRL_OFFSET                          0x004
#define JPEG_CONTRL_ENC_MIRROR_EN_Pos               4
#define JPEG_CONTRL_ENC_MIRROR_EN_Msk               0x10
#define JPEG_CONTRL_DEC_OU_FORMAT_Pos               3
#define JPEG_CONTRL_DEC_OU_FORMAT_Msk               0x8
#define JPEG_CONTRL_DEC_IN_FORMAT_Pos               1
#define JPEG_CONTRL_DEC_IN_FORMAT_Msk               0x6
#define JPEG_CONTRL_MODE_Pos                        0
#define JPEG_CONTRL_MODE_Msk                        0x1

#define JPEG_PIXEL_DMA_START_OFFSET                 0x008
#define JPEG_PIXEL_DMA_START_PDMA_START_Pos         0
#define JPEG_PIXEL_DMA_START_PDMA_START_Msk         0x1

#define JPEG_ECS_DMA_START_OFFSET                   0x00C
#define JPEG_ECS_DMA_START_EDMA_START_Pos           0
#define JPEG_ECS_DMA_START_EDMA_START_Msk           0x1

#define JPEG_PIXEL_DMA_TRANSFER_SIZE_OFFSET         0x010
#define JPEG_PIXEL_DMA_TRANSFER_SIZE_PDMA_SIZE_Pos    0
#define JPEG_PIXEL_DMA_TRANSFER_SIZE_PDMA_SIZE_Msk    0xffffff

#define JPEG_ECS_DMA_TRANSFER_SIZE_OFFSET           0x014
#define JPEG_ECS_DMA_TRANSFER_SIZE_EDMA_SIZE_Pos    0
#define JPEG_ECS_DMA_TRANSFER_SIZE_EDMA_SIZE_Msk    0xfffff

#define JPEG_SOURCE_DATA_LENGTH_OFFSET              0x018
#define JPEG_SOURCE_DATA_LENGTH_SRC_LEN_Pos         0
#define JPEG_SOURCE_DATA_LENGTH_SRC_LEN_Msk         0xffffff

#define JPEG_RESULT_DATA_LENGTH_OFFSET              0x01C
#define JPEG_RESULT_DATA_LENGTH_RESULT_LEN_Pos      0
#define JPEG_RESULT_DATA_LENGTH_RESULT_LEN_Msk      0xffffff

#define JPEG_DEC_DUMMY_OFFSET                       0x020
#define JPEG_DEC_DUMMY_DUMMY_BYTE_Pos               0
#define JPEG_DEC_DUMMY_DUMMY_BYTE_Msk               0x3

#define JPEG_INT_ST_CLR_OFFSET                      0x040
#define JPEG_INT_ST_CLR_EDMA_DONE_Pos               3
#define JPEG_INT_ST_CLR_EDMA_DONE_Msk               0x8
#define JPEG_INT_ST_CLR_PDMA_DONE_Pos               2
#define JPEG_INT_ST_CLR_PDMA_DONE_Msk               0x4
#define JPEG_INT_ST_CLR_CODEC_DONE_Pos              0
#define JPEG_INT_ST_CLR_CODEC_DONE_Msk              0x1

#define JPEG_INT_MASK_OFFSET                        0x044
#define JPEG_INT_MASK_EDMA_DONE_MASK_Pos            3
#define JPEG_INT_MASK_EDMA_DONE_MASK_Msk            0x8
#define JPEG_INT_MASK_PDMA_DONE_MASK_Pos            2
#define JPEG_INT_MASK_PDMA_DONE_MASK_Msk            0x4
#define JPEG_INT_MASK_CODEC_DONE_MASK_Pos           0
#define JPEG_INT_MASK_CODEC_DONE_MASK_Msk           0x1

#define JPEG_SCALING_CTRL_OFFSET                    0x060
#define JPEG_SCALING_CTRL_FIX_BUG_Pos               3
#define JPEG_SCALING_CTRL_FIX_BUG_Msk               0x8
#define JPEG_SCALING_CTRL_FAKE_MODE_Pos             2
#define JPEG_SCALING_CTRL_FAKE_MODE_Msk             0x4
#define JPEG_SCALING_CTRL_SCALING_EN_Pos            1
#define JPEG_SCALING_CTRL_SCALING_EN_Msk            0x2
#define JPEG_SCALING_CTRL_SCALING_MODE_Pos          0
#define JPEG_SCALING_CTRL_SCALING_MODE_Msk          0x1

#define JPEG_ENC_PDMA_START_OFFSET                  0x064
#define JPEG_ENC_PDMA_START_ARCS_PDMA_START_Pos     0
#define JPEG_ENC_PDMA_START_ARCS_PDMA_START_Msk     0x1

#define JPEG_ENC_PIC_SIZE_OFFSET                    0x068
#define JPEG_ENC_PIC_SIZE_ARCS_ENC_WIDTH_Pos        16
#define JPEG_ENC_PIC_SIZE_ARCS_ENC_WIDTH_Msk        0xfff0000
#define JPEG_ENC_PIC_SIZE_CFG_P_WBUF_BURST_THD_Pos    12
#define JPEG_ENC_PIC_SIZE_CFG_P_WBUF_BURST_THD_Msk    0xf000
#define JPEG_ENC_PIC_SIZE_ARCS_ENC_HEIGHT_Pos       0
#define JPEG_ENC_PIC_SIZE_ARCS_ENC_HEIGHT_Msk       0x7ff

#define JPEG_DEC_PIC_SIZE_OFFSET                    0x06C
#define JPEG_DEC_PIC_SIZE_ARCS_DEC_WIDTH_Pos        16
#define JPEG_DEC_PIC_SIZE_ARCS_DEC_WIDTH_Msk        0xfff0000
#define JPEG_DEC_PIC_SIZE_CFG_E_WBUF_BURST_THD_Pos    12
#define JPEG_DEC_PIC_SIZE_CFG_E_WBUF_BURST_THD_Msk    0xf000
#define JPEG_DEC_PIC_SIZE_ARCS_DEC_HEIGHT_Pos       0
#define JPEG_DEC_PIC_SIZE_ARCS_DEC_HEIGHT_Msk       0x7ff

#define JPEG_RELOAD_OFFSET                          0x070
#define JPEG_RELOAD_RELOAD_Pos                      0
#define JPEG_RELOAD_RELOAD_Msk                      0x1

#define JPEG_IFCTRL_OFFSET                          0x074
#define JPEG_IFCTRL_P_WPIX_NUM_SEL_Pos              3
#define JPEG_IFCTRL_P_WPIX_NUM_SEL_Msk              0x8
#define JPEG_IFCTRL_MULTI_FRM_EN_Pos                2
#define JPEG_IFCTRL_MULTI_FRM_EN_Msk                0x4
#define JPEG_IFCTRL_XMODE_Pos                       1
#define JPEG_IFCTRL_XMODE_Msk                       0x2
#define JPEG_IFCTRL_JPEG_ENABLE_Pos                 0
#define JPEG_IFCTRL_JPEG_ENABLE_Msk                 0x1

#define JPEG_JCR0_OFFSET                            0x800
#define JPEG_JCR0_JCR_START_STOP_Pos                0
#define JPEG_JCR0_JCR_START_STOP_Msk                0x1

#define JPEG_JCR1_OFFSET                            0x804
#define JPEG_JCR1_JCR_DE_Pos                        3
#define JPEG_JCR1_JCR_DE_Msk                        0x8
#define JPEG_JCR1_JCR_RE_Pos                        2
#define JPEG_JCR1_JCR_RE_Msk                        0x4
#define JPEG_JCR1_JCR_NOL_Pos                       0
#define JPEG_JCR1_JCR_NOL_Msk                       0x3

#define JPEG_JCR2_OFFSET                            0x808
#define JPEG_JCR2_JCR_NMCU_Pos                      0
#define JPEG_JCR2_JCR_NMCU_Msk                      0x3ffffff

#define JPEG_JCR3_OFFSET                            0x80C
#define JPEG_JCR3_JCR_NRST_Pos                      0
#define JPEG_JCR3_JCR_NRST_Msk                      0xffff

#define JPEG_JCR4_OFFSET                            0x810
#define JPEG_JCR4_JCR_NBLOCK0_Pos                   4
#define JPEG_JCR4_JCR_NBLOCK0_Msk                   0xf0
#define JPEG_JCR4_JCR_QT0_Pos                       2
#define JPEG_JCR4_JCR_QT0_Msk                       0xc
#define JPEG_JCR4_JCR_HA0_Pos                       1
#define JPEG_JCR4_JCR_HA0_Msk                       0x2
#define JPEG_JCR4_JCR_HD0_Pos                       0
#define JPEG_JCR4_JCR_HD0_Msk                       0x1

#define JPEG_JCR5_OFFSET                            0x814
#define JPEG_JCR5_JCR_NBLOCK1_Pos                   4
#define JPEG_JCR5_JCR_NBLOCK1_Msk                   0xf0
#define JPEG_JCR5_JCR_QT1_Pos                       2
#define JPEG_JCR5_JCR_QT1_Msk                       0xc
#define JPEG_JCR5_JCR_HA1_Pos                       1
#define JPEG_JCR5_JCR_HA1_Msk                       0x2
#define JPEG_JCR5_JCR_HD1_Pos                       0
#define JPEG_JCR5_JCR_HD1_Msk                       0x1

#define JPEG_JCR6_OFFSET                            0x818
#define JPEG_JCR6_JCR_NBLOCK2_Pos                   4
#define JPEG_JCR6_JCR_NBLOCK2_Msk                   0xf0
#define JPEG_JCR6_JCR_QT2_Pos                       2
#define JPEG_JCR6_JCR_QT2_Msk                       0xc
#define JPEG_JCR6_JCR_HA2_Pos                       1
#define JPEG_JCR6_JCR_HA2_Msk                       0x2
#define JPEG_JCR6_JCR_HD2_Pos                       0
#define JPEG_JCR6_JCR_HD2_Msk                       0x1

#define JPEG_JCR7_OFFSET                            0x81C
#define JPEG_JCR7_JCR_NBLOCK3_Pos                   4
#define JPEG_JCR7_JCR_NBLOCK3_Msk                   0xf0
#define JPEG_JCR7_JCR_QT3_Pos                       2
#define JPEG_JCR7_JCR_QT3_Msk                       0xc
#define JPEG_JCR7_JCR_HA3_Pos                       1
#define JPEG_JCR7_JCR_HA3_Msk                       0x2
#define JPEG_JCR7_JCR_HD3_Pos                       0
#define JPEG_JCR7_JCR_HD3_Msk                       0x1

struct JPEG_REG_RSV_BITS
{
    volatile uint32_t RESV_0_31                     : 32; // bit 0~31
};

union JPEG_REG_RSV {
    volatile uint32_t                               all;
    struct JPEG_REG_RSV_BITS                        bit;
};

struct JPEG_REG_CONTRL_BITS
{
    volatile uint32_t MODE                          : 1; // bit 0~0
    volatile uint32_t DEC_IN_FORMAT                 : 2; // bit 1~2
    volatile uint32_t DEC_OU_FORMAT                 : 1; // bit 3~3
    volatile uint32_t ENC_MIRROR_EN                 : 1; // bit 4~4
    volatile uint32_t RESV_5_31                     : 27; // bit 5~31
};

union JPEG_REG_CONTRL {
    volatile uint32_t                               all;
    struct JPEG_REG_CONTRL_BITS                     bit;
};

struct JPEG_REG_PIXEL_DMA_START_BITS
{
    volatile uint32_t PDMA_START                    : 1; // bit 0~0
    volatile uint32_t RESV_1_31                     : 31; // bit 1~31
};

union JPEG_REG_PIXEL_DMA_START {
    volatile uint32_t                               all;
    struct JPEG_REG_PIXEL_DMA_START_BITS            bit;
};

struct JPEG_REG_ECS_DMA_START_BITS
{
    volatile uint32_t EDMA_START                    : 1; // bit 0~0
    volatile uint32_t RESV_1_31                     : 31; // bit 1~31
};

union JPEG_REG_ECS_DMA_START {
    volatile uint32_t                               all;
    struct JPEG_REG_ECS_DMA_START_BITS              bit;
};

struct JPEG_REG_PIXEL_DMA_TRANSFER_SIZE_BITS
{
    volatile uint32_t PDMA_SIZE                     : 24; // bit 0~23
    volatile uint32_t RESV_24_31                    : 8; // bit 24~31
};

union JPEG_REG_PIXEL_DMA_TRANSFER_SIZE {
    volatile uint32_t                               all;
    struct JPEG_REG_PIXEL_DMA_TRANSFER_SIZE_BITS    bit;
};

struct JPEG_REG_ECS_DMA_TRANSFER_SIZE_BITS
{
    volatile uint32_t EDMA_SIZE                     : 20; // bit 0~19
    volatile uint32_t RESV_20_31                    : 12; // bit 20~31
};

union JPEG_REG_ECS_DMA_TRANSFER_SIZE {
    volatile uint32_t                               all;
    struct JPEG_REG_ECS_DMA_TRANSFER_SIZE_BITS      bit;
};

struct JPEG_REG_SOURCE_DATA_LENGTH_BITS
{
    volatile uint32_t SRC_LEN                       : 24; // bit 0~23
    volatile uint32_t RESV_24_31                    : 8; // bit 24~31
};

union JPEG_REG_SOURCE_DATA_LENGTH {
    volatile uint32_t                               all;
    struct JPEG_REG_SOURCE_DATA_LENGTH_BITS         bit;
};

struct JPEG_REG_RESULT_DATA_LENGTH_BITS
{
    volatile uint32_t RESULT_LEN                    : 24; // bit 0~23
    volatile uint32_t RESV_24_31                    : 8; // bit 24~31
};

union JPEG_REG_RESULT_DATA_LENGTH {
    volatile uint32_t                               all;
    struct JPEG_REG_RESULT_DATA_LENGTH_BITS         bit;
};

struct JPEG_REG_DEC_DUMMY_BITS
{
    volatile uint32_t DUMMY_BYTE                    : 2; // bit 0~1
    volatile uint32_t RESV_2_31                     : 30; // bit 2~31
};

union JPEG_REG_DEC_DUMMY {
    volatile uint32_t                               all;
    struct JPEG_REG_DEC_DUMMY_BITS                  bit;
};

struct JPEG_REG_INT_ST_CLR_BITS
{
    volatile uint32_t CODEC_DONE                    : 1; // bit 0~0
    volatile uint32_t RESV_1_1                      : 1; // bit 1~1
    volatile uint32_t PDMA_DONE                     : 1; // bit 2~2
    volatile uint32_t EDMA_DONE                     : 1; // bit 3~3
    volatile uint32_t RESV_4_31                     : 28; // bit 4~31
};

union JPEG_REG_INT_ST_CLR {
    volatile uint32_t                               all;
    struct JPEG_REG_INT_ST_CLR_BITS                 bit;
};

struct JPEG_REG_INT_MASK_BITS
{
    volatile uint32_t CODEC_DONE_MASK               : 1; // bit 0~0
    volatile uint32_t RESV_1_1                      : 1; // bit 1~1
    volatile uint32_t PDMA_DONE_MASK                : 1; // bit 2~2
    volatile uint32_t EDMA_DONE_MASK                : 1; // bit 3~3
    volatile uint32_t RESV_4_31                     : 28; // bit 4~31
};

union JPEG_REG_INT_MASK {
    volatile uint32_t                               all;
    struct JPEG_REG_INT_MASK_BITS                   bit;
};

struct JPEG_REG_SCALING_CTRL_BITS
{
    volatile uint32_t SCALING_MODE                  : 1; // bit 0~0
    volatile uint32_t SCALING_EN                    : 1; // bit 1~1
    volatile uint32_t FAKE_MODE                     : 1; // bit 2~2
    volatile uint32_t FIX_BUG                       : 1; // bit 3~3
    volatile uint32_t RESV_4_31                     : 28; // bit 4~31
};

union JPEG_REG_SCALING_CTRL {
    volatile uint32_t                               all;
    struct JPEG_REG_SCALING_CTRL_BITS               bit;
};

struct JPEG_REG_ENC_PDMA_START_BITS
{
    volatile uint32_t ARCS_PDMA_START               : 1; // bit 0~0
    volatile uint32_t RESV_1_31                     : 31; // bit 1~31
};

union JPEG_REG_ENC_PDMA_START {
    volatile uint32_t                               all;
    struct JPEG_REG_ENC_PDMA_START_BITS             bit;
};

struct JPEG_REG_ENC_PIC_SIZE_BITS
{
    volatile uint32_t ARCS_ENC_HEIGHT               : 11; // bit 0~10
    volatile uint32_t RESV_11_11                    : 1; // bit 11~11
    volatile uint32_t CFG_P_WBUF_BURST_THD          : 4; // bit 12~15
    volatile uint32_t ARCS_ENC_WIDTH                : 12; // bit 16~27
    volatile uint32_t RESV_28_31                    : 4; // bit 28~31
};

union JPEG_REG_ENC_PIC_SIZE {
    volatile uint32_t                               all;
    struct JPEG_REG_ENC_PIC_SIZE_BITS               bit;
};

struct JPEG_REG_DEC_PIC_SIZE_BITS
{
    volatile uint32_t ARCS_DEC_HEIGHT               : 11; // bit 0~10
    volatile uint32_t RESV_11_11                    : 1; // bit 11~11
    volatile uint32_t CFG_E_WBUF_BURST_THD          : 4; // bit 12~15
    volatile uint32_t ARCS_DEC_WIDTH                : 12; // bit 16~27
    volatile uint32_t RESV_28_31                    : 4; // bit 28~31
};

union JPEG_REG_DEC_PIC_SIZE {
    volatile uint32_t                               all;
    struct JPEG_REG_DEC_PIC_SIZE_BITS               bit;
};

struct JPEG_REG_RELOAD_BITS
{
    volatile uint32_t RELOAD                        : 1; // bit 0~0
    volatile uint32_t RESV_1_31                     : 31; // bit 1~31
};

union JPEG_REG_RELOAD {
    volatile uint32_t                               all;
    struct JPEG_REG_RELOAD_BITS                     bit;
};

struct JPEG_REG_IFCTRL_BITS
{
    volatile uint32_t JPEG_ENABLE                   : 1; // bit 0~0
    volatile uint32_t XMODE                         : 1; // bit 1~1
    volatile uint32_t MULTI_FRM_EN                  : 1; // bit 2~2
    volatile uint32_t P_WPIX_NUM_SEL                : 1; // bit 3~3
    volatile uint32_t RESV_4_31                     : 28; // bit 4~31
};

union JPEG_REG_IFCTRL {
    volatile uint32_t                               all;
    struct JPEG_REG_IFCTRL_BITS                     bit;
};

struct JPEG_REG_JCR0_BITS
{
    volatile uint32_t JCR_START_STOP                : 1; // bit 0~0
    volatile uint32_t RESV_1_31                     : 31; // bit 1~31
};

union JPEG_REG_JCR0 {
    volatile uint32_t                               all;
    struct JPEG_REG_JCR0_BITS                       bit;
};

struct JPEG_REG_JCR1_BITS
{
    volatile uint32_t JCR_NOL                       : 2; // bit 0~1
    volatile uint32_t JCR_RE                        : 1; // bit 2~2
    volatile uint32_t JCR_DE                        : 1; // bit 3~3
    volatile uint32_t RESV_4_31                     : 28; // bit 4~31
};

union JPEG_REG_JCR1 {
    volatile uint32_t                               all;
    struct JPEG_REG_JCR1_BITS                       bit;
};

struct JPEG_REG_JCR2_BITS
{
    volatile uint32_t JCR_NMCU                      : 26; // bit 0~25
    volatile uint32_t RESV_26_31                    : 6; // bit 26~31
};

union JPEG_REG_JCR2 {
    volatile uint32_t                               all;
    struct JPEG_REG_JCR2_BITS                       bit;
};

struct JPEG_REG_JCR3_BITS
{
    volatile uint32_t JCR_NRST                      : 16; // bit 0~15
    volatile uint32_t RESV_16_31                    : 16; // bit 16~31
};

union JPEG_REG_JCR3 {
    volatile uint32_t                               all;
    struct JPEG_REG_JCR3_BITS                       bit;
};

struct JPEG_REG_JCR4_BITS
{
    volatile uint32_t JCR_HD0                       : 1; // bit 0~0
    volatile uint32_t JCR_HA0                       : 1; // bit 1~1
    volatile uint32_t JCR_QT0                       : 2; // bit 2~3
    volatile uint32_t JCR_NBLOCK0                   : 4; // bit 4~7
    volatile uint32_t RESV_8_31                     : 24; // bit 8~31
};

union JPEG_REG_JCR4 {
    volatile uint32_t                               all;
    struct JPEG_REG_JCR4_BITS                       bit;
};

struct JPEG_REG_JCR5_BITS
{
    volatile uint32_t JCR_HD1                       : 1; // bit 0~0
    volatile uint32_t JCR_HA1                       : 1; // bit 1~1
    volatile uint32_t JCR_QT1                       : 2; // bit 2~3
    volatile uint32_t JCR_NBLOCK1                   : 4; // bit 4~7
    volatile uint32_t RESV_8_31                     : 24; // bit 8~31
};

union JPEG_REG_JCR5 {
    volatile uint32_t                               all;
    struct JPEG_REG_JCR5_BITS                       bit;
};

struct JPEG_REG_JCR6_BITS
{
    volatile uint32_t JCR_HD2                       : 1; // bit 0~0
    volatile uint32_t JCR_HA2                       : 1; // bit 1~1
    volatile uint32_t JCR_QT2                       : 2; // bit 2~3
    volatile uint32_t JCR_NBLOCK2                   : 4; // bit 4~7
    volatile uint32_t RESV_8_31                     : 24; // bit 8~31
};

union JPEG_REG_JCR6 {
    volatile uint32_t                               all;
    struct JPEG_REG_JCR6_BITS                       bit;
};

struct JPEG_REG_JCR7_BITS
{
    volatile uint32_t JCR_HD3                       : 1; // bit 0~0
    volatile uint32_t JCR_HA3                       : 1; // bit 1~1
    volatile uint32_t JCR_QT3                       : 2; // bit 2~3
    volatile uint32_t JCR_NBLOCK3                   : 4; // bit 4~7
    volatile uint32_t RESV_8_31                     : 24; // bit 8~31
};

union JPEG_REG_JCR7 {
    volatile uint32_t                               all;
    struct JPEG_REG_JCR7_BITS                       bit;
};

typedef struct
{
    union JPEG_REG_RSV                              REG_RSV;     // 0x000
    union JPEG_REG_CONTRL                           REG_CONTRL;  // 0x004
    union JPEG_REG_PIXEL_DMA_START                  REG_PIXEL_DMA_START; // 0x008
    union JPEG_REG_ECS_DMA_START                    REG_ECS_DMA_START; // 0x00C
    union JPEG_REG_PIXEL_DMA_TRANSFER_SIZE          REG_PIXEL_DMA_TRANSFER_SIZE; // 0x010
    union JPEG_REG_ECS_DMA_TRANSFER_SIZE            REG_ECS_DMA_TRANSFER_SIZE; // 0x014
    union JPEG_REG_SOURCE_DATA_LENGTH               REG_SOURCE_DATA_LENGTH; // 0x018
    union JPEG_REG_RESULT_DATA_LENGTH               REG_RESULT_DATA_LENGTH; // 0x01C
    union JPEG_REG_DEC_DUMMY                        REG_DEC_DUMMY; // 0x020
    volatile uint32_t                               REG_RESV_0X24_0X3C[7];
    union JPEG_REG_INT_ST_CLR                       REG_INT_ST_CLR; // 0x040
    union JPEG_REG_INT_MASK                         REG_INT_MASK; // 0x044
    volatile uint32_t                               REG_RESV_0X48_0X5C[6];
    union JPEG_REG_SCALING_CTRL                     REG_SCALING_CTRL; // 0x060
    union JPEG_REG_ENC_PDMA_START                   REG_ENC_PDMA_START; // 0x064
    union JPEG_REG_ENC_PIC_SIZE                     REG_ENC_PIC_SIZE; // 0x068
    union JPEG_REG_DEC_PIC_SIZE                     REG_DEC_PIC_SIZE; // 0x06C
    union JPEG_REG_RELOAD                           REG_RELOAD;  // 0x070
    union JPEG_REG_IFCTRL                           REG_IFCTRL;  // 0x074
    volatile uint32_t                               REG_RESV_0X78_0X7FC[482];
    union JPEG_REG_JCR0                             REG_JCR0;    // 0x800
    union JPEG_REG_JCR1                             REG_JCR1;    // 0x804
    union JPEG_REG_JCR2                             REG_JCR2;    // 0x808
    union JPEG_REG_JCR3                             REG_JCR3;    // 0x80C
    union JPEG_REG_JCR4                             REG_JCR4;    // 0x810
    union JPEG_REG_JCR5                             REG_JCR5;    // 0x814
    union JPEG_REG_JCR6                             REG_JCR6;    // 0x818
    union JPEG_REG_JCR7                             REG_JCR7;    // 0x81C
} JPEG_RegDef;


#endif // __JPEG_REGFILE_H__

