//  ----------------------------------------------------------------------
//  File Name   : GenCFold/wifi_bd_if_reg_arcs.h
//  Description : C header file generated by Python script.
//  Script Ver  £ºLS.AUTO_REG.2024.03.01
//  Create Time : 2024-06-07 10:54:54
//  Comments    : 
//  ----------------------------------------------------------------------

#ifndef __WIFI_BD_IF_REGFILE_H__
#define __WIFI_BD_IF_REGFILE_H__

#include <stdint.h>

#define WIFI_BD_IF_SIGNATURE_OFFSET                 0x000
#define WIFI_BD_IF_SIGNATURE_FPGA_SIGNATURE_Pos     0
#define WIFI_BD_IF_SIGNATURE_FPGA_SIGNATURE_Msk     0xffffffff

#define WIFI_BD_IF_DATE_OFFSET                      0x004
#define WIFI_BD_IF_DATE_FPGA_DATE_Pos               0
#define WIFI_BD_IF_DATE_FPGA_DATE_Msk               0xffffffff

#define WIFI_BD_IF_DIAGPORT_CONF1_OFFSET            0x010
#define WIFI_BD_IF_DIAGPORT_CONF1_MICTOR2_SEL_Pos    8
#define WIFI_BD_IF_DIAGPORT_CONF1_MICTOR2_SEL_Msk    0xff00
#define WIFI_BD_IF_DIAGPORT_CONF1_MICTOR1_SEL_Pos    0
#define WIFI_BD_IF_DIAGPORT_CONF1_MICTOR1_SEL_Msk    0xff

#define WIFI_BD_IF_DIAGPORT_CONF2_OFFSET            0x014
#define WIFI_BD_IF_DIAGPORT_CONF2_MICTOR0_SEL_Pos    0
#define WIFI_BD_IF_DIAGPORT_CONF2_MICTOR0_SEL_Msk    0xffff

#define WIFI_BD_IF_FB_CNTL_OFFSET                   0x020
#define WIFI_BD_IF_FB_CNTL_FB_CAPTURE_DONE_Pos      31
#define WIFI_BD_IF_FB_CNTL_FB_CAPTURE_DONE_Msk      0x80000000
#define WIFI_BD_IF_FB_CNTL_FB_CAPTURE_EN_Pos        20
#define WIFI_BD_IF_FB_CNTL_FB_CAPTURE_EN_Msk        0x300000
#define WIFI_BD_IF_FB_CNTL_FB_PLAYBACK_EN_Pos       16
#define WIFI_BD_IF_FB_CNTL_FB_PLAYBACK_EN_Msk       0x30000
#define WIFI_BD_IF_FB_CNTL_FB_PLAYBACK_COUNT_Pos    0
#define WIFI_BD_IF_FB_CNTL_FB_PLAYBACK_COUNT_Msk    0xffff

#define WIFI_BD_IF_FB_PATHMUX_OFFSET                0x024
#define WIFI_BD_IF_FB_PATHMUX_FB_PATHMUX_SEL_Pos    0
#define WIFI_BD_IF_FB_PATHMUX_FB_PATHMUX_SEL_Msk    0xf

#define WIFI_BD_IF_ADC_SPI_CNTL_OFFSET              0x100
#define WIFI_BD_IF_ADC_SPI_CNTL_ADC_SPI_DONE_Pos    31
#define WIFI_BD_IF_ADC_SPI_CNTL_ADC_SPI_DONE_Msk    0x80000000
#define WIFI_BD_IF_ADC_SPI_CNTL_ADC_SPI_PRESCALER_Pos    8
#define WIFI_BD_IF_ADC_SPI_CNTL_ADC_SPI_PRESCALER_Msk    0x1f00
#define WIFI_BD_IF_ADC_SPI_CNTL_ADC_SPI_AUTOPOWER_Pos    1
#define WIFI_BD_IF_ADC_SPI_CNTL_ADC_SPI_AUTOPOWER_Msk    0x2
#define WIFI_BD_IF_ADC_SPI_CNTL_ADC_SPI_START_Pos    0
#define WIFI_BD_IF_ADC_SPI_CNTL_ADC_SPI_START_Msk    0x1

#define WIFI_BD_IF_ADC_SPI_ADDR_OFFSET              0x104
#define WIFI_BD_IF_ADC_SPI_ADDR_ADC_SPI_WE_Pos      31
#define WIFI_BD_IF_ADC_SPI_ADDR_ADC_SPI_WE_Msk      0x80000000
#define WIFI_BD_IF_ADC_SPI_ADDR_ADC_SPI_SEL_Pos     16
#define WIFI_BD_IF_ADC_SPI_ADDR_ADC_SPI_SEL_Msk     0xf0000
#define WIFI_BD_IF_ADC_SPI_ADDR_ADC_SPI_ADDR_Pos    0
#define WIFI_BD_IF_ADC_SPI_ADDR_ADC_SPI_ADDR_Msk    0xffff

#define WIFI_BD_IF_ADC_SPI_DATA_OFFSET              0x108
#define WIFI_BD_IF_ADC_SPI_DATA_ADC_SPI_RDATA_Pos    16
#define WIFI_BD_IF_ADC_SPI_DATA_ADC_SPI_RDATA_Msk    0xffff0000
#define WIFI_BD_IF_ADC_SPI_DATA_ADC_SPI_WDATA_Pos    0
#define WIFI_BD_IF_ADC_SPI_DATA_ADC_SPI_WDATA_Msk    0xffff

#define WIFI_BD_IF_DAC_SPI_CNTL_OFFSET              0x200
#define WIFI_BD_IF_DAC_SPI_CNTL_DAC_SPI_DONE_Pos    31
#define WIFI_BD_IF_DAC_SPI_CNTL_DAC_SPI_DONE_Msk    0x80000000
#define WIFI_BD_IF_DAC_SPI_CNTL_DAC_SPI_PRESCALER_Pos    8
#define WIFI_BD_IF_DAC_SPI_CNTL_DAC_SPI_PRESCALER_Msk    0x1f00
#define WIFI_BD_IF_DAC_SPI_CNTL_DAC_RESET_Pos       2
#define WIFI_BD_IF_DAC_SPI_CNTL_DAC_RESET_Msk       0x4
#define WIFI_BD_IF_DAC_SPI_CNTL_DAC_SPI_AUTOPOWER_Pos    1
#define WIFI_BD_IF_DAC_SPI_CNTL_DAC_SPI_AUTOPOWER_Msk    0x2
#define WIFI_BD_IF_DAC_SPI_CNTL_DAC_SPI_START_Pos    0
#define WIFI_BD_IF_DAC_SPI_CNTL_DAC_SPI_START_Msk    0x1

#define WIFI_BD_IF_DAC_SPI_ADDR_OFFSET              0x204
#define WIFI_BD_IF_DAC_SPI_ADDR_DAC_SPI_WE_Pos      31
#define WIFI_BD_IF_DAC_SPI_ADDR_DAC_SPI_WE_Msk      0x80000000
#define WIFI_BD_IF_DAC_SPI_ADDR_DAC_SPI_SEL_Pos     16
#define WIFI_BD_IF_DAC_SPI_ADDR_DAC_SPI_SEL_Msk     0xf0000
#define WIFI_BD_IF_DAC_SPI_ADDR_DAC_SPI_ADDR_Pos    0
#define WIFI_BD_IF_DAC_SPI_ADDR_DAC_SPI_ADDR_Msk    0xffff

#define WIFI_BD_IF_DAC_SPI_DATA_OFFSET              0x208
#define WIFI_BD_IF_DAC_SPI_DATA_DAC_SPI_RDATA_Pos    16
#define WIFI_BD_IF_DAC_SPI_DATA_DAC_SPI_RDATA_Msk    0xffff0000
#define WIFI_BD_IF_DAC_SPI_DATA_DAC_SPI_WDATA_Pos    0
#define WIFI_BD_IF_DAC_SPI_DATA_DAC_SPI_WDATA_Msk    0xffff

#define WIFI_BD_IF_DAC_SPI_AUTOPOWER_OFFSET         0x20C
#define WIFI_BD_IF_DAC_SPI_AUTOPOWER_DAC_POWERUP_Pos    16
#define WIFI_BD_IF_DAC_SPI_AUTOPOWER_DAC_POWERUP_Msk    0xffff0000
#define WIFI_BD_IF_DAC_SPI_AUTOPOWER_DAC_POWERDOWN_Pos    0
#define WIFI_BD_IF_DAC_SPI_AUTOPOWER_DAC_POWERDOWN_Msk    0xffff

#define WIFI_BD_IF_DIAG0_STAT_OFFSET                0x04C
#define WIFI_BD_IF_DIAG0_STAT_DIAG0_STAT_Pos        0
#define WIFI_BD_IF_DIAG0_STAT_DIAG0_STAT_Msk        0xffffffff

#define WIFI_BD_IF_DIAG1_STAT_OFFSET                0x050
#define WIFI_BD_IF_DIAG1_STAT_DIAG1_STAT_Pos        0
#define WIFI_BD_IF_DIAG1_STAT_DIAG1_STAT_Msk        0xffffffff

#define WIFI_BD_IF_DIAG2_STAT_OFFSET                0x054
#define WIFI_BD_IF_DIAG2_STAT_DIAG2_STAT_Pos        0
#define WIFI_BD_IF_DIAG2_STAT_DIAG2_STAT_Msk        0xffffffff

#define WIFI_BD_IF_DIAG3_STAT_OFFSET                0x058
#define WIFI_BD_IF_DIAG3_STAT_DIAG3_STAT_Pos        0
#define WIFI_BD_IF_DIAG3_STAT_DIAG3_STAT_Msk        0xffffffff

#define WIFI_BD_IF_DIAG4_STAT_OFFSET                0x05C
#define WIFI_BD_IF_DIAG4_STAT_DIAG4_STAT_Pos        0
#define WIFI_BD_IF_DIAG4_STAT_DIAG4_STAT_Msk        0xffffffff

#define WIFI_BD_IF_INTERRUPT_SET_OFFSET             0x380
#define WIFI_BD_IF_INTERRUPT_SET_DOORBELL_INT_SET_Pos    0
#define WIFI_BD_IF_INTERRUPT_SET_DOORBELL_INT_SET_Msk    0x1

#define WIFI_BD_IF_INTERRUPT_CLEAR_OFFSET           0x384
#define WIFI_BD_IF_INTERRUPT_CLEAR_DOORBELL_INT_CLEAR_Pos    0
#define WIFI_BD_IF_INTERRUPT_CLEAR_DOORBELL_INT_CLEAR_Msk    0x1

#define WIFI_BD_IF_INTERRUPT_UNMASK_OFFSET          0x388
#define WIFI_BD_IF_INTERRUPT_UNMASK_DOORBELL_INT_MASK_Pos    0
#define WIFI_BD_IF_INTERRUPT_UNMASK_DOORBELL_INT_MASK_Msk    0x1

#define WIFI_BD_IF_INTERRUPT_STATUS_OFFSET          0x38C
#define WIFI_BD_IF_INTERRUPT_STATUS_DOORBELL_INT_STATUS_Pos    0
#define WIFI_BD_IF_INTERRUPT_STATUS_DOORBELL_INT_STATUS_Msk    0x1

#define WIFI_BD_IF_V7_GPIO_OFFSET                   0x390
#define WIFI_BD_IF_V7_GPIO_V7_GPIO_EN_Pos           31
#define WIFI_BD_IF_V7_GPIO_V7_GPIO_EN_Msk           0x80000000
#define WIFI_BD_IF_V7_GPIO_V7_GPIO6_Pos             6
#define WIFI_BD_IF_V7_GPIO_V7_GPIO6_Msk             0x40
#define WIFI_BD_IF_V7_GPIO_V7_GPIO5_Pos             5
#define WIFI_BD_IF_V7_GPIO_V7_GPIO5_Msk             0x20
#define WIFI_BD_IF_V7_GPIO_V7_GPIO3_Pos             3
#define WIFI_BD_IF_V7_GPIO_V7_GPIO3_Msk             0x8
#define WIFI_BD_IF_V7_GPIO_V7_GPIO2_Pos             2
#define WIFI_BD_IF_V7_GPIO_V7_GPIO2_Msk             0x4
#define WIFI_BD_IF_V7_GPIO_V7_GPIO1_Pos             1
#define WIFI_BD_IF_V7_GPIO_V7_GPIO1_Msk             0x2
#define WIFI_BD_IF_V7_GPIO_V7_GPIO0_Pos             0
#define WIFI_BD_IF_V7_GPIO_V7_GPIO0_Msk             0x1

#define WIFI_BD_IF_IODELAY_CNTL_OFFSET              0x400
#define WIFI_BD_IF_IODELAY_CNTL_IODELAY_DONE_Pos    31
#define WIFI_BD_IF_IODELAY_CNTL_IODELAY_DONE_Msk    0x80000000
#define WIFI_BD_IF_IODELAY_CNTL_IODELAY_START_Pos    0
#define WIFI_BD_IF_IODELAY_CNTL_IODELAY_START_Msk    0x1

#define WIFI_BD_IF_IODELAY_ADC0_OFFSET              0x404
#define WIFI_BD_IF_IODELAY_ADC0_IODELAY_ADC0_Pos    0
#define WIFI_BD_IF_IODELAY_ADC0_IODELAY_ADC0_Msk    0xff

#define WIFI_BD_IF_IODELAY_DAC0_OFFSET              0x408
#define WIFI_BD_IF_IODELAY_DAC0_IODELAY_DAC0_Pos    0
#define WIFI_BD_IF_IODELAY_DAC0_IODELAY_DAC0_Msk    0xff

#define WIFI_BD_IF_IODELAY_ADC1_OFFSET              0x40C
#define WIFI_BD_IF_IODELAY_ADC1_IODELAY_ADC1_Pos    0
#define WIFI_BD_IF_IODELAY_ADC1_IODELAY_ADC1_Msk    0xff

#define WIFI_BD_IF_IODELAY_DAC1_OFFSET              0x410
#define WIFI_BD_IF_IODELAY_DAC1_IODELAY_DAC1_Pos    0
#define WIFI_BD_IF_IODELAY_DAC1_IODELAY_DAC1_Msk    0xff

#define WIFI_BD_IF_IQCOMP_ADC0_OFFSET               0x480
#define WIFI_BD_IF_IQCOMP_ADC0_GCOS_ADC0_Pos        16
#define WIFI_BD_IF_IQCOMP_ADC0_GCOS_ADC0_Msk        0x3ff0000
#define WIFI_BD_IF_IQCOMP_ADC0_GSIN_ADC0_Pos        0
#define WIFI_BD_IF_IQCOMP_ADC0_GSIN_ADC0_Msk        0x3ff

#define WIFI_BD_IF_IQCOMP_DAC0_OFFSET               0x484
#define WIFI_BD_IF_IQCOMP_DAC0_GCOS_DAC0_Pos        16
#define WIFI_BD_IF_IQCOMP_DAC0_GCOS_DAC0_Msk        0x3ff0000
#define WIFI_BD_IF_IQCOMP_DAC0_GSIN_DAC0_Pos        0
#define WIFI_BD_IF_IQCOMP_DAC0_GSIN_DAC0_Msk        0x3ff

#define WIFI_BD_IF_IQCOMP_ADC1_OFFSET               0x488
#define WIFI_BD_IF_IQCOMP_ADC1_GCOS_ADC1_Pos        16
#define WIFI_BD_IF_IQCOMP_ADC1_GCOS_ADC1_Msk        0x3ff0000
#define WIFI_BD_IF_IQCOMP_ADC1_GSIN_ADC1_Pos        0
#define WIFI_BD_IF_IQCOMP_ADC1_GSIN_ADC1_Msk        0x3ff

#define WIFI_BD_IF_IQCOMP_DAC1_OFFSET               0x48C
#define WIFI_BD_IF_IQCOMP_DAC1_GCOS_DAC1_Pos        16
#define WIFI_BD_IF_IQCOMP_DAC1_GCOS_DAC1_Msk        0x3ff0000
#define WIFI_BD_IF_IQCOMP_DAC1_GSIN_DAC1_Pos        0
#define WIFI_BD_IF_IQCOMP_DAC1_GSIN_DAC1_Msk        0x3ff

#define WIFI_BD_IF_RF_CNTRL_OFFSET                  0x500
#define WIFI_BD_IF_RF_CNTRL_RF_SPI_DONE_Pos         31
#define WIFI_BD_IF_RF_CNTRL_RF_SPI_DONE_Msk         0x80000000
#define WIFI_BD_IF_RF_CNTRL_RF_SPI_PRESCALER_Pos    8
#define WIFI_BD_IF_RF_CNTRL_RF_SPI_PRESCALER_Msk    0xf00
#define WIFI_BD_IF_RF_CNTRL_RF_SPI_START_Pos        0
#define WIFI_BD_IF_RF_CNTRL_RF_SPI_START_Msk        0x1

#define WIFI_BD_IF_RF_SPI_ADDR_OFFSET               0x504
#define WIFI_BD_IF_RF_SPI_ADDR_RF_SPI_WE_Pos        31
#define WIFI_BD_IF_RF_SPI_ADDR_RF_SPI_WE_Msk        0x80000000
#define WIFI_BD_IF_RF_SPI_ADDR_RF_SPI_SEL_Pos       16
#define WIFI_BD_IF_RF_SPI_ADDR_RF_SPI_SEL_Msk       0xf0000
#define WIFI_BD_IF_RF_SPI_ADDR_RF_SPI_ADDR_Pos      0
#define WIFI_BD_IF_RF_SPI_ADDR_RF_SPI_ADDR_Msk      0xffff

#define WIFI_BD_IF_RF_SPI_DATA_OFFSET               0x508
#define WIFI_BD_IF_RF_SPI_DATA_RF_SPI_RDATA_Pos     16
#define WIFI_BD_IF_RF_SPI_DATA_RF_SPI_RDATA_Msk     0xffff0000
#define WIFI_BD_IF_RF_SPI_DATA_RF_SPI_WDATA_Pos     0
#define WIFI_BD_IF_RF_SPI_DATA_RF_SPI_WDATA_Msk     0xffff

#define WIFI_BD_IF_RF_FORCE_OFFSET                  0x50C
#define WIFI_BD_IF_RF_FORCE_RF_FORCE_EN_Pos         16
#define WIFI_BD_IF_RF_FORCE_RF_FORCE_EN_Msk         0xffff0000
#define WIFI_BD_IF_RF_FORCE_RF_FORCE_Pos            0
#define WIFI_BD_IF_RF_FORCE_RF_FORCE_Msk            0xffff

#define WIFI_BD_IF_RF_GPIO_OFFSET                   0x510
#define WIFI_BD_IF_RF_GPIO_RF_GPIO_Pos              0
#define WIFI_BD_IF_RF_GPIO_RF_GPIO_Msk              0xff

#define WIFI_BD_IF_RF_IRQ_OFFSET                    0x514
#define WIFI_BD_IF_RF_IRQ_RF_IRQ_Pos                0
#define WIFI_BD_IF_RF_IRQ_RF_IRQ_Msk                0xff

#define WIFI_BD_IF_SVNREV_MODEM_OFFSET              0x064
#define WIFI_BD_IF_SVNREV_MODEM_SVNREV_MODEM_Pos    0
#define WIFI_BD_IF_SVNREV_MODEM_SVNREV_MODEM_Msk    0xffffffff

#define WIFI_BD_IF_SVNREV_FPGAB_OFFSET              0x068
#define WIFI_BD_IF_SVNREV_FPGAB_SVNREV_FPGAB_Pos    0
#define WIFI_BD_IF_SVNREV_FPGAB_SVNREV_FPGAB_Msk    0xffffffff

struct WIFI_BD_IF_REG_SIGNATURE_BITS
{
    volatile uint32_t FPGA_SIGNATURE                : 32; // bit 0~31
};

union WIFI_BD_IF_REG_SIGNATURE {
    volatile uint32_t                               all;
    struct WIFI_BD_IF_REG_SIGNATURE_BITS            bit;
};

struct WIFI_BD_IF_REG_DATE_BITS
{
    volatile uint32_t FPGA_DATE                     : 32; // bit 0~31
};

union WIFI_BD_IF_REG_DATE {
    volatile uint32_t                               all;
    struct WIFI_BD_IF_REG_DATE_BITS                 bit;
};

struct WIFI_BD_IF_REG_DIAGPORT_CONF1_BITS
{
    volatile uint32_t MICTOR1_SEL                   : 8; // bit 0~7
    volatile uint32_t MICTOR2_SEL                   : 8; // bit 8~15
    volatile uint32_t RESV_16_31                    : 16; // bit 16~31
};

union WIFI_BD_IF_REG_DIAGPORT_CONF1 {
    volatile uint32_t                               all;
    struct WIFI_BD_IF_REG_DIAGPORT_CONF1_BITS       bit;
};

struct WIFI_BD_IF_REG_DIAGPORT_CONF2_BITS
{
    volatile uint32_t MICTOR0_SEL                   : 16; // bit 0~15
    volatile uint32_t RESV_16_31                    : 16; // bit 16~31
};

union WIFI_BD_IF_REG_DIAGPORT_CONF2 {
    volatile uint32_t                               all;
    struct WIFI_BD_IF_REG_DIAGPORT_CONF2_BITS       bit;
};

struct WIFI_BD_IF_REG_FB_CNTL_BITS
{
    volatile uint32_t FB_PLAYBACK_COUNT             : 16; // bit 0~15
    volatile uint32_t FB_PLAYBACK_EN                : 2; // bit 16~17
    volatile uint32_t RESV_18_19                    : 2; // bit 18~19
    volatile uint32_t FB_CAPTURE_EN                 : 2; // bit 20~21
    volatile uint32_t RESV_22_30                    : 9; // bit 22~30
    volatile uint32_t FB_CAPTURE_DONE               : 1; // bit 31~31
};

union WIFI_BD_IF_REG_FB_CNTL {
    volatile uint32_t                               all;
    struct WIFI_BD_IF_REG_FB_CNTL_BITS              bit;
};

struct WIFI_BD_IF_REG_FB_PATHMUX_BITS
{
    volatile uint32_t FB_PATHMUX_SEL                : 4; // bit 0~3
    volatile uint32_t RESV_4_31                     : 28; // bit 4~31
};

union WIFI_BD_IF_REG_FB_PATHMUX {
    volatile uint32_t                               all;
    struct WIFI_BD_IF_REG_FB_PATHMUX_BITS           bit;
};

struct WIFI_BD_IF_REG_ADC_SPI_CNTL_BITS
{
    volatile uint32_t ADC_SPI_START                 : 1; // bit 0~0
    volatile uint32_t ADC_SPI_AUTOPOWER             : 1; // bit 1~1
    volatile uint32_t RESV_2_7                      : 6; // bit 2~7
    volatile uint32_t ADC_SPI_PRESCALER             : 5; // bit 8~12
    volatile uint32_t RESV_13_30                    : 18; // bit 13~30
    volatile uint32_t ADC_SPI_DONE                  : 1; // bit 31~31
};

union WIFI_BD_IF_REG_ADC_SPI_CNTL {
    volatile uint32_t                               all;
    struct WIFI_BD_IF_REG_ADC_SPI_CNTL_BITS         bit;
};

struct WIFI_BD_IF_REG_ADC_SPI_ADDR_BITS
{
    volatile uint32_t ADC_SPI_ADDR                  : 16; // bit 0~15
    volatile uint32_t ADC_SPI_SEL                   : 4; // bit 16~19
    volatile uint32_t RESV_20_30                    : 11; // bit 20~30
    volatile uint32_t ADC_SPI_WE                    : 1; // bit 31~31
};

union WIFI_BD_IF_REG_ADC_SPI_ADDR {
    volatile uint32_t                               all;
    struct WIFI_BD_IF_REG_ADC_SPI_ADDR_BITS         bit;
};

struct WIFI_BD_IF_REG_ADC_SPI_DATA_BITS
{
    volatile uint32_t ADC_SPI_WDATA                 : 16; // bit 0~15
    volatile uint32_t ADC_SPI_RDATA                 : 16; // bit 16~31
};

union WIFI_BD_IF_REG_ADC_SPI_DATA {
    volatile uint32_t                               all;
    struct WIFI_BD_IF_REG_ADC_SPI_DATA_BITS         bit;
};

struct WIFI_BD_IF_REG_DAC_SPI_CNTL_BITS
{
    volatile uint32_t DAC_SPI_START                 : 1; // bit 0~0
    volatile uint32_t DAC_SPI_AUTOPOWER             : 1; // bit 1~1
    volatile uint32_t DAC_RESET                     : 1; // bit 2~2
    volatile uint32_t RESV_3_7                      : 5; // bit 3~7
    volatile uint32_t DAC_SPI_PRESCALER             : 5; // bit 8~12
    volatile uint32_t RESV_13_30                    : 18; // bit 13~30
    volatile uint32_t DAC_SPI_DONE                  : 1; // bit 31~31
};

union WIFI_BD_IF_REG_DAC_SPI_CNTL {
    volatile uint32_t                               all;
    struct WIFI_BD_IF_REG_DAC_SPI_CNTL_BITS         bit;
};

struct WIFI_BD_IF_REG_DAC_SPI_ADDR_BITS
{
    volatile uint32_t DAC_SPI_ADDR                  : 16; // bit 0~15
    volatile uint32_t DAC_SPI_SEL                   : 4; // bit 16~19
    volatile uint32_t RESV_20_30                    : 11; // bit 20~30
    volatile uint32_t DAC_SPI_WE                    : 1; // bit 31~31
};

union WIFI_BD_IF_REG_DAC_SPI_ADDR {
    volatile uint32_t                               all;
    struct WIFI_BD_IF_REG_DAC_SPI_ADDR_BITS         bit;
};

struct WIFI_BD_IF_REG_DAC_SPI_DATA_BITS
{
    volatile uint32_t DAC_SPI_WDATA                 : 16; // bit 0~15
    volatile uint32_t DAC_SPI_RDATA                 : 16; // bit 16~31
};

union WIFI_BD_IF_REG_DAC_SPI_DATA {
    volatile uint32_t                               all;
    struct WIFI_BD_IF_REG_DAC_SPI_DATA_BITS         bit;
};

struct WIFI_BD_IF_REG_DAC_SPI_AUTOPOWER_BITS
{
    volatile uint32_t DAC_POWERDOWN                 : 16; // bit 0~15
    volatile uint32_t DAC_POWERUP                   : 16; // bit 16~31
};

union WIFI_BD_IF_REG_DAC_SPI_AUTOPOWER {
    volatile uint32_t                               all;
    struct WIFI_BD_IF_REG_DAC_SPI_AUTOPOWER_BITS    bit;
};

struct WIFI_BD_IF_REG_DIAG0_STAT_BITS
{
    volatile uint32_t DIAG0_STAT                    : 32; // bit 0~31
};

union WIFI_BD_IF_REG_DIAG0_STAT {
    volatile uint32_t                               all;
    struct WIFI_BD_IF_REG_DIAG0_STAT_BITS           bit;
};

struct WIFI_BD_IF_REG_DIAG1_STAT_BITS
{
    volatile uint32_t DIAG1_STAT                    : 32; // bit 0~31
};

union WIFI_BD_IF_REG_DIAG1_STAT {
    volatile uint32_t                               all;
    struct WIFI_BD_IF_REG_DIAG1_STAT_BITS           bit;
};

struct WIFI_BD_IF_REG_DIAG2_STAT_BITS
{
    volatile uint32_t DIAG2_STAT                    : 32; // bit 0~31
};

union WIFI_BD_IF_REG_DIAG2_STAT {
    volatile uint32_t                               all;
    struct WIFI_BD_IF_REG_DIAG2_STAT_BITS           bit;
};

struct WIFI_BD_IF_REG_DIAG3_STAT_BITS
{
    volatile uint32_t DIAG3_STAT                    : 32; // bit 0~31
};

union WIFI_BD_IF_REG_DIAG3_STAT {
    volatile uint32_t                               all;
    struct WIFI_BD_IF_REG_DIAG3_STAT_BITS           bit;
};

struct WIFI_BD_IF_REG_DIAG4_STAT_BITS
{
    volatile uint32_t DIAG4_STAT                    : 32; // bit 0~31
};

union WIFI_BD_IF_REG_DIAG4_STAT {
    volatile uint32_t                               all;
    struct WIFI_BD_IF_REG_DIAG4_STAT_BITS           bit;
};

struct WIFI_BD_IF_REG_INTERRUPT_SET_BITS
{
    volatile uint32_t DOORBELL_INT_SET              : 1; // bit 0~0
    volatile uint32_t RESV_1_31                     : 31; // bit 1~31
};

union WIFI_BD_IF_REG_INTERRUPT_SET {
    volatile uint32_t                               all;
    struct WIFI_BD_IF_REG_INTERRUPT_SET_BITS        bit;
};

struct WIFI_BD_IF_REG_INTERRUPT_CLEAR_BITS
{
    volatile uint32_t DOORBELL_INT_CLEAR            : 1; // bit 0~0
    volatile uint32_t RESV_1_31                     : 31; // bit 1~31
};

union WIFI_BD_IF_REG_INTERRUPT_CLEAR {
    volatile uint32_t                               all;
    struct WIFI_BD_IF_REG_INTERRUPT_CLEAR_BITS      bit;
};

struct WIFI_BD_IF_REG_INTERRUPT_UNMASK_BITS
{
    volatile uint32_t DOORBELL_INT_MASK             : 1; // bit 0~0
    volatile uint32_t RESV_1_31                     : 31; // bit 1~31
};

union WIFI_BD_IF_REG_INTERRUPT_UNMASK {
    volatile uint32_t                               all;
    struct WIFI_BD_IF_REG_INTERRUPT_UNMASK_BITS     bit;
};

struct WIFI_BD_IF_REG_INTERRUPT_STATUS_BITS
{
    volatile uint32_t DOORBELL_INT_STATUS           : 1; // bit 0~0
    volatile uint32_t RESV_1_31                     : 31; // bit 1~31
};

union WIFI_BD_IF_REG_INTERRUPT_STATUS {
    volatile uint32_t                               all;
    struct WIFI_BD_IF_REG_INTERRUPT_STATUS_BITS     bit;
};

struct WIFI_BD_IF_REG_V7_GPIO_BITS
{
    volatile uint32_t V7_GPIO0                      : 1; // bit 0~0
    volatile uint32_t V7_GPIO1                      : 1; // bit 1~1
    volatile uint32_t V7_GPIO2                      : 1; // bit 2~2
    volatile uint32_t V7_GPIO3                      : 1; // bit 3~3
    volatile uint32_t RESV_4_4                      : 1; // bit 4~4
    volatile uint32_t V7_GPIO5                      : 1; // bit 5~5
    volatile uint32_t V7_GPIO6                      : 1; // bit 6~6
    volatile uint32_t RESV_7_30                     : 24; // bit 7~30
    volatile uint32_t V7_GPIO_EN                    : 1; // bit 31~31
};

union WIFI_BD_IF_REG_V7_GPIO {
    volatile uint32_t                               all;
    struct WIFI_BD_IF_REG_V7_GPIO_BITS              bit;
};

struct WIFI_BD_IF_REG_IODELAY_CNTL_BITS
{
    volatile uint32_t IODELAY_START                 : 1; // bit 0~0
    volatile uint32_t RESV_1_30                     : 30; // bit 1~30
    volatile uint32_t IODELAY_DONE                  : 1; // bit 31~31
};

union WIFI_BD_IF_REG_IODELAY_CNTL {
    volatile uint32_t                               all;
    struct WIFI_BD_IF_REG_IODELAY_CNTL_BITS         bit;
};

struct WIFI_BD_IF_REG_IODELAY_ADC0_BITS
{
    volatile uint32_t IODELAY_ADC0                  : 8; // bit 0~7
    volatile uint32_t RESV_8_31                     : 24; // bit 8~31
};

union WIFI_BD_IF_REG_IODELAY_ADC0 {
    volatile uint32_t                               all;
    struct WIFI_BD_IF_REG_IODELAY_ADC0_BITS         bit;
};

struct WIFI_BD_IF_REG_IODELAY_DAC0_BITS
{
    volatile uint32_t IODELAY_DAC0                  : 8; // bit 0~7
    volatile uint32_t RESV_8_31                     : 24; // bit 8~31
};

union WIFI_BD_IF_REG_IODELAY_DAC0 {
    volatile uint32_t                               all;
    struct WIFI_BD_IF_REG_IODELAY_DAC0_BITS         bit;
};

struct WIFI_BD_IF_REG_IODELAY_ADC1_BITS
{
    volatile uint32_t IODELAY_ADC1                  : 8; // bit 0~7
    volatile uint32_t RESV_8_31                     : 24; // bit 8~31
};

union WIFI_BD_IF_REG_IODELAY_ADC1 {
    volatile uint32_t                               all;
    struct WIFI_BD_IF_REG_IODELAY_ADC1_BITS         bit;
};

struct WIFI_BD_IF_REG_IODELAY_DAC1_BITS
{
    volatile uint32_t IODELAY_DAC1                  : 8; // bit 0~7
    volatile uint32_t RESV_8_31                     : 24; // bit 8~31
};

union WIFI_BD_IF_REG_IODELAY_DAC1 {
    volatile uint32_t                               all;
    struct WIFI_BD_IF_REG_IODELAY_DAC1_BITS         bit;
};

struct WIFI_BD_IF_REG_IQCOMP_ADC0_BITS
{
    volatile uint32_t GSIN_ADC0                     : 10; // bit 0~9
    volatile uint32_t RESV_10_15                    : 6; // bit 10~15
    volatile uint32_t GCOS_ADC0                     : 10; // bit 16~25
    volatile uint32_t RESV_26_31                    : 6; // bit 26~31
};

union WIFI_BD_IF_REG_IQCOMP_ADC0 {
    volatile uint32_t                               all;
    struct WIFI_BD_IF_REG_IQCOMP_ADC0_BITS          bit;
};

struct WIFI_BD_IF_REG_IQCOMP_DAC0_BITS
{
    volatile uint32_t GSIN_DAC0                     : 10; // bit 0~9
    volatile uint32_t RESV_10_15                    : 6; // bit 10~15
    volatile uint32_t GCOS_DAC0                     : 10; // bit 16~25
    volatile uint32_t RESV_26_31                    : 6; // bit 26~31
};

union WIFI_BD_IF_REG_IQCOMP_DAC0 {
    volatile uint32_t                               all;
    struct WIFI_BD_IF_REG_IQCOMP_DAC0_BITS          bit;
};

struct WIFI_BD_IF_REG_IQCOMP_ADC1_BITS
{
    volatile uint32_t GSIN_ADC1                     : 10; // bit 0~9
    volatile uint32_t RESV_10_15                    : 6; // bit 10~15
    volatile uint32_t GCOS_ADC1                     : 10; // bit 16~25
    volatile uint32_t RESV_26_31                    : 6; // bit 26~31
};

union WIFI_BD_IF_REG_IQCOMP_ADC1 {
    volatile uint32_t                               all;
    struct WIFI_BD_IF_REG_IQCOMP_ADC1_BITS          bit;
};

struct WIFI_BD_IF_REG_IQCOMP_DAC1_BITS
{
    volatile uint32_t GSIN_DAC1                     : 10; // bit 0~9
    volatile uint32_t RESV_10_15                    : 6; // bit 10~15
    volatile uint32_t GCOS_DAC1                     : 10; // bit 16~25
    volatile uint32_t RESV_26_31                    : 6; // bit 26~31
};

union WIFI_BD_IF_REG_IQCOMP_DAC1 {
    volatile uint32_t                               all;
    struct WIFI_BD_IF_REG_IQCOMP_DAC1_BITS          bit;
};

struct WIFI_BD_IF_REG_RF_CNTRL_BITS
{
    volatile uint32_t RF_SPI_START                  : 1; // bit 0~0
    volatile uint32_t RESV_1_7                      : 7; // bit 1~7
    volatile uint32_t RF_SPI_PRESCALER              : 4; // bit 8~11
    volatile uint32_t RESV_12_30                    : 19; // bit 12~30
    volatile uint32_t RF_SPI_DONE                   : 1; // bit 31~31
};

union WIFI_BD_IF_REG_RF_CNTRL {
    volatile uint32_t                               all;
    struct WIFI_BD_IF_REG_RF_CNTRL_BITS             bit;
};

struct WIFI_BD_IF_REG_RF_SPI_ADDR_BITS
{
    volatile uint32_t RF_SPI_ADDR                   : 16; // bit 0~15
    volatile uint32_t RF_SPI_SEL                    : 4; // bit 16~19
    volatile uint32_t RESV_20_30                    : 11; // bit 20~30
    volatile uint32_t RF_SPI_WE                     : 1; // bit 31~31
};

union WIFI_BD_IF_REG_RF_SPI_ADDR {
    volatile uint32_t                               all;
    struct WIFI_BD_IF_REG_RF_SPI_ADDR_BITS          bit;
};

struct WIFI_BD_IF_REG_RF_SPI_DATA_BITS
{
    volatile uint32_t RF_SPI_WDATA                  : 16; // bit 0~15
    volatile uint32_t RF_SPI_RDATA                  : 16; // bit 16~31
};

union WIFI_BD_IF_REG_RF_SPI_DATA {
    volatile uint32_t                               all;
    struct WIFI_BD_IF_REG_RF_SPI_DATA_BITS          bit;
};

struct WIFI_BD_IF_REG_RF_FORCE_BITS
{
    volatile uint32_t RF_FORCE                      : 16; // bit 0~15
    volatile uint32_t RF_FORCE_EN                   : 16; // bit 16~31
};

union WIFI_BD_IF_REG_RF_FORCE {
    volatile uint32_t                               all;
    struct WIFI_BD_IF_REG_RF_FORCE_BITS             bit;
};

struct WIFI_BD_IF_REG_RF_GPIO_BITS
{
    volatile uint32_t RF_GPIO                       : 8; // bit 0~7
    volatile uint32_t RESV_8_31                     : 24; // bit 8~31
};

union WIFI_BD_IF_REG_RF_GPIO {
    volatile uint32_t                               all;
    struct WIFI_BD_IF_REG_RF_GPIO_BITS              bit;
};

struct WIFI_BD_IF_REG_RF_IRQ_BITS
{
    volatile uint32_t RF_IRQ                        : 8; // bit 0~7
    volatile uint32_t RESV_8_31                     : 24; // bit 8~31
};

union WIFI_BD_IF_REG_RF_IRQ {
    volatile uint32_t                               all;
    struct WIFI_BD_IF_REG_RF_IRQ_BITS               bit;
};

struct WIFI_BD_IF_REG_SVNREV_MODEM_BITS
{
    volatile uint32_t SVNREV_MODEM                  : 32; // bit 0~31
};

union WIFI_BD_IF_REG_SVNREV_MODEM {
    volatile uint32_t                               all;
    struct WIFI_BD_IF_REG_SVNREV_MODEM_BITS         bit;
};

struct WIFI_BD_IF_REG_SVNREV_FPGAB_BITS
{
    volatile uint32_t SVNREV_FPGAB                  : 32; // bit 0~31
};

union WIFI_BD_IF_REG_SVNREV_FPGAB {
    volatile uint32_t                               all;
    struct WIFI_BD_IF_REG_SVNREV_FPGAB_BITS         bit;
};

typedef struct
{
    union WIFI_BD_IF_REG_SIGNATURE                  REG_SIGNATURE; // 0x000
    union WIFI_BD_IF_REG_DATE                       REG_DATE;    // 0x004
    volatile uint32_t                               REG_RESV_0X8_0XC[2];
    union WIFI_BD_IF_REG_DIAGPORT_CONF1             REG_DIAGPORT_CONF1; // 0x010
    union WIFI_BD_IF_REG_DIAGPORT_CONF2             REG_DIAGPORT_CONF2; // 0x014
    volatile uint32_t                               REG_RESV_0X18_0X1C[2];
    union WIFI_BD_IF_REG_FB_CNTL                    REG_FB_CNTL; // 0x020
    union WIFI_BD_IF_REG_FB_PATHMUX                 REG_FB_PATHMUX; // 0x024
    volatile uint32_t                               REG_RESV_0X28_0XFC[54];
    union WIFI_BD_IF_REG_ADC_SPI_CNTL               REG_ADC_SPI_CNTL; // 0x100
    union WIFI_BD_IF_REG_ADC_SPI_ADDR               REG_ADC_SPI_ADDR; // 0x104
    union WIFI_BD_IF_REG_ADC_SPI_DATA               REG_ADC_SPI_DATA; // 0x108
    volatile uint32_t                               REG_RESV_0X10C_0X1FC[61];
    union WIFI_BD_IF_REG_DAC_SPI_CNTL               REG_DAC_SPI_CNTL; // 0x200
    union WIFI_BD_IF_REG_DAC_SPI_ADDR               REG_DAC_SPI_ADDR; // 0x204
    union WIFI_BD_IF_REG_DAC_SPI_DATA               REG_DAC_SPI_DATA; // 0x208
    union WIFI_BD_IF_REG_DAC_SPI_AUTOPOWER          REG_DAC_SPI_AUTOPOWER; // 0x20C
    union WIFI_BD_IF_REG_DIAG0_STAT                 REG_DIAG0_STAT; // 0x04C
    union WIFI_BD_IF_REG_DIAG1_STAT                 REG_DIAG1_STAT; // 0x050
    union WIFI_BD_IF_REG_DIAG2_STAT                 REG_DIAG2_STAT; // 0x054
    union WIFI_BD_IF_REG_DIAG3_STAT                 REG_DIAG3_STAT; // 0x058
    union WIFI_BD_IF_REG_DIAG4_STAT                 REG_DIAG4_STAT; // 0x05C
    volatile uint32_t                               REG_RESV_0X210_0X37C[92];
    union WIFI_BD_IF_REG_INTERRUPT_SET              REG_INTERRUPT_SET; // 0x380
    union WIFI_BD_IF_REG_INTERRUPT_CLEAR            REG_INTERRUPT_CLEAR; // 0x384
    union WIFI_BD_IF_REG_INTERRUPT_UNMASK           REG_INTERRUPT_UNMASK; // 0x388
    union WIFI_BD_IF_REG_INTERRUPT_STATUS           REG_INTERRUPT_STATUS; // 0x38C
    union WIFI_BD_IF_REG_V7_GPIO                    REG_V7_GPIO; // 0x390
    volatile uint32_t                               REG_RESV_0X394_0X3FC[27];
    union WIFI_BD_IF_REG_IODELAY_CNTL               REG_IODELAY_CNTL; // 0x400
    union WIFI_BD_IF_REG_IODELAY_ADC0               REG_IODELAY_ADC0; // 0x404
    union WIFI_BD_IF_REG_IODELAY_DAC0               REG_IODELAY_DAC0; // 0x408
    union WIFI_BD_IF_REG_IODELAY_ADC1               REG_IODELAY_ADC1; // 0x40C
    union WIFI_BD_IF_REG_IODELAY_DAC1               REG_IODELAY_DAC1; // 0x410
    volatile uint32_t                               REG_RESV_0X414_0X47C[27];
    union WIFI_BD_IF_REG_IQCOMP_ADC0                REG_IQCOMP_ADC0; // 0x480
    union WIFI_BD_IF_REG_IQCOMP_DAC0                REG_IQCOMP_DAC0; // 0x484
    union WIFI_BD_IF_REG_IQCOMP_ADC1                REG_IQCOMP_ADC1; // 0x488
    union WIFI_BD_IF_REG_IQCOMP_DAC1                REG_IQCOMP_DAC1; // 0x48C
    volatile uint32_t                               REG_RESV_0X490_0X4FC[28];
    union WIFI_BD_IF_REG_RF_CNTRL                   REG_RF_CNTRL; // 0x500
    union WIFI_BD_IF_REG_RF_SPI_ADDR                REG_RF_SPI_ADDR; // 0x504
    union WIFI_BD_IF_REG_RF_SPI_DATA                REG_RF_SPI_DATA; // 0x508
    union WIFI_BD_IF_REG_RF_FORCE                   REG_RF_FORCE; // 0x50C
    union WIFI_BD_IF_REG_RF_GPIO                    REG_RF_GPIO; // 0x510
    union WIFI_BD_IF_REG_RF_IRQ                     REG_RF_IRQ;  // 0x514
    union WIFI_BD_IF_REG_SVNREV_MODEM               REG_SVNREV_MODEM; // 0x064
    union WIFI_BD_IF_REG_SVNREV_FPGAB               REG_SVNREV_FPGAB; // 0x068
} WIFI_BD_IF_RegDef;


#endif // __WIFI_BD_IF_REGFILE_H__

