//  ----------------------------------------------------------------------
//  File Name   : GenCFold/wifi_crm_reg_arcs.h
//  Description : C header file generated by Python script.
//  Author      : klqi
//  Script Ver  : LS.AUTO_REG.2024.09.20
//  SVN Revision: Can't find <<ARCS-D_SoC_Memory_Mapping.xlsx>> SVN detail info,pls chk£¡£¡
//  Create Time : 2024-12-10 19:23:31
//  Comments    : 
//  ----------------------------------------------------------------------

#ifndef __WIFI_CRM_REGFILE_H__
#define __WIFI_CRM_REGFILE_H__

#include <stdint.h>

#define WIFI_CRM_RESERVED_OFFSET                    0x000

#define WIFI_CRM_CLKRST_CNTL_OFFSET                 0x008
#define WIFI_CRM_CLKRST_CNTL_LACLK_FREQ_SEL_Pos     24
#define WIFI_CRM_CLKRST_CNTL_LACLK_FREQ_SEL_Msk     0x3000000
#define WIFI_CRM_CLKRST_CNTL_LDPCTXCLK_FREQ_SEL_Pos    22
#define WIFI_CRM_CLKRST_CNTL_LDPCTXCLK_FREQ_SEL_Msk    0xc00000
#define WIFI_CRM_CLKRST_CNTL_LDPCRXCLK_FREQ_SEL_Pos    20
#define WIFI_CRM_CLKRST_CNTL_LDPCRXCLK_FREQ_SEL_Msk    0x300000
#define WIFI_CRM_CLKRST_CNTL_VTBCLK_FREQ_SEL_Pos    18
#define WIFI_CRM_CLKRST_CNTL_VTBCLK_FREQ_SEL_Msk    0xc0000
#define WIFI_CRM_CLKRST_CNTL_MPIFCLK_FREQ_SEL_Pos    16
#define WIFI_CRM_CLKRST_CNTL_MPIFCLK_FREQ_SEL_Msk    0x30000
#define WIFI_CRM_CLKRST_CNTL_MACWTCLK_RATIO_SEL_Pos    12
#define WIFI_CRM_CLKRST_CNTL_MACWTCLK_RATIO_SEL_Msk    0x3000
#define WIFI_CRM_CLKRST_CNTL_MACCORECLK_FREQ_SEL_Pos    8
#define WIFI_CRM_CLKRST_CNTL_MACCORECLK_FREQ_SEL_Msk    0xf00
#define WIFI_CRM_CLKRST_CNTL_FECLK_FREQ_SEL_Pos     4
#define WIFI_CRM_CLKRST_CNTL_FECLK_FREQ_SEL_Msk     0x30
#define WIFI_CRM_CLKRST_CNTL_LACLK_INV_EN_Pos       1
#define WIFI_CRM_CLKRST_CNTL_LACLK_INV_EN_Msk       0x2
#define WIFI_CRM_CLKRST_CNTL_PLFCLK_SEL_Pos         0
#define WIFI_CRM_CLKRST_CNTL_PLFCLK_SEL_Msk         0x1

#define WIFI_CRM_CLKRST_STAT_OFFSET                 0x00C
#define WIFI_CRM_CLKRST_STAT_MMC_LOCK_Pos           4
#define WIFI_CRM_CLKRST_STAT_MMC_LOCK_Msk           0x7f0

#define WIFI_CRM_CLKGATEPHYFCTRL0_OFFSET            0x010
#define WIFI_CRM_CLKGATEPHYFCTRL0_PHYTXCLKFORCE_Pos    31
#define WIFI_CRM_CLKGATEPHYFCTRL0_PHYTXCLKFORCE_Msk    0x80000000
#define WIFI_CRM_CLKGATEPHYFCTRL0_AGCMEMCLKFORCE_Pos    29
#define WIFI_CRM_CLKGATEPHYFCTRL0_AGCMEMCLKFORCE_Msk    0x20000000
#define WIFI_CRM_CLKGATEPHYFCTRL0_AGCCLKFORCE_Pos    28
#define WIFI_CRM_CLKGATEPHYFCTRL0_AGCCLKFORCE_Msk    0x10000000
#define WIFI_CRM_CLKGATEPHYFCTRL0_RCCLKFORCE_Pos    27
#define WIFI_CRM_CLKGATEPHYFCTRL0_RCCLKFORCE_Msk    0x8000000
#define WIFI_CRM_CLKGATEPHYFCTRL0_FECLKFORCE_Pos    24
#define WIFI_CRM_CLKGATEPHYFCTRL0_FECLKFORCE_Msk    0x1000000
#define WIFI_CRM_CLKGATEPHYFCTRL0_FDOCLKFORCE_Pos    23
#define WIFI_CRM_CLKGATEPHYFCTRL0_FDOCLKFORCE_Msk    0x800000
#define WIFI_CRM_CLKGATEPHYFCTRL0_EQUCLKFORCE_Pos    22
#define WIFI_CRM_CLKGATEPHYFCTRL0_EQUCLKFORCE_Msk    0x400000
#define WIFI_CRM_CLKGATEPHYFCTRL0_PHYSVDCLKFORCE_Pos    20
#define WIFI_CRM_CLKGATEPHYFCTRL0_PHYSVDCLKFORCE_Msk    0x100000
#define WIFI_CRM_CLKGATEPHYFCTRL0_TDCOMPCLKFORCE_Pos    18
#define WIFI_CRM_CLKGATEPHYFCTRL0_TDCOMPCLKFORCE_Msk    0x40000
#define WIFI_CRM_CLKGATEPHYFCTRL0_TDFOESTCLKFORCE_Pos    17
#define WIFI_CRM_CLKGATEPHYFCTRL0_TDFOESTCLKFORCE_Msk    0x20000
#define WIFI_CRM_CLKGATEPHYFCTRL0_TBECLKFORCE_Pos    16
#define WIFI_CRM_CLKGATEPHYFCTRL0_TBECLKFORCE_Msk    0x10000
#define WIFI_CRM_CLKGATEPHYFCTRL0_FFTCLKFORCE_Pos    9
#define WIFI_CRM_CLKGATEPHYFCTRL0_FFTCLKFORCE_Msk    0x200
#define WIFI_CRM_CLKGATEPHYFCTRL0_CHESTCLKFORCE_Pos    6
#define WIFI_CRM_CLKGATEPHYFCTRL0_CHESTCLKFORCE_Msk    0x40
#define WIFI_CRM_CLKGATEPHYFCTRL0_VTBCLKFORCE_Pos    1
#define WIFI_CRM_CLKGATEPHYFCTRL0_VTBCLKFORCE_Msk    0x2

#define WIFI_CRM_CLKGATEPHYFCTRL1_OFFSET            0x014
#define WIFI_CRM_CLKGATEPHYFCTRL1_LACLKFORCE_Pos    8
#define WIFI_CRM_CLKGATEPHYFCTRL1_LACLKFORCE_Msk    0x100
#define WIFI_CRM_CLKGATEPHYFCTRL1_RADARTIMCLKFORCE_Pos    5
#define WIFI_CRM_CLKGATEPHYFCTRL1_RADARTIMCLKFORCE_Msk    0x20
#define WIFI_CRM_CLKGATEPHYFCTRL1_MDMBTXCLKFORCE_Pos    4
#define WIFI_CRM_CLKGATEPHYFCTRL1_MDMBTXCLKFORCE_Msk    0x10
#define WIFI_CRM_CLKGATEPHYFCTRL1_MDMBRXCLKFORCE_Pos    3
#define WIFI_CRM_CLKGATEPHYFCTRL1_MDMBRXCLKFORCE_Msk    0x8
#define WIFI_CRM_CLKGATEPHYFCTRL1_MDMBCLKFORCE_Pos    2
#define WIFI_CRM_CLKGATEPHYFCTRL1_MDMBCLKFORCE_Msk    0x4
#define WIFI_CRM_CLKGATEPHYFCTRL1_LDPCENCCLKFORCE_Pos    1
#define WIFI_CRM_CLKGATEPHYFCTRL1_LDPCENCCLKFORCE_Msk    0x2
#define WIFI_CRM_CLKGATEPHYFCTRL1_LDPCDECCLKFORCE_Pos    0
#define WIFI_CRM_CLKGATEPHYFCTRL1_LDPCDECCLKFORCE_Msk    0x1

#define WIFI_CRM_RSTCTRL_OFFSET                     0x018
#define WIFI_CRM_RSTCTRL_WIFISTSRESET_Pos           12
#define WIFI_CRM_RSTCTRL_WIFISTSRESET_Msk           0x1000
#define WIFI_CRM_RSTCTRL_RCSWRESET_Pos              8
#define WIFI_CRM_RSTCTRL_RCSWRESET_Msk              0x100
#define WIFI_CRM_RSTCTRL_AGCSWRESET_Pos             4
#define WIFI_CRM_RSTCTRL_AGCSWRESET_Msk             0x10
#define WIFI_CRM_RSTCTRL_PHYSWRESET_Pos             0
#define WIFI_CRM_RSTCTRL_PHYSWRESET_Msk             0x1

#define WIFI_CRM_LA_SAMPLING_FREQ_OFFSET            0x06C
#define WIFI_CRM_LA_SAMPLING_FREQ_LA_SAMPLING_FREQ_Pos    0
#define WIFI_CRM_LA_SAMPLING_FREQ_LA_SAMPLING_FREQ_Msk    0xff

#define WIFI_CRM_DYNCFGMMC_CNTL_OFFSET              0x300
#define WIFI_CRM_DYNCFGMMC_CNTL_DYNCFGMMC_DONE_Pos    31
#define WIFI_CRM_DYNCFGMMC_CNTL_DYNCFGMMC_DONE_Msk    0x80000000
#define WIFI_CRM_DYNCFGMMC_CNTL_FMETRE_DONE_Pos     30
#define WIFI_CRM_DYNCFGMMC_CNTL_FMETRE_DONE_Msk     0x40000000
#define WIFI_CRM_DYNCFGMMC_CNTL_FMETRE_START_Pos    1
#define WIFI_CRM_DYNCFGMMC_CNTL_FMETRE_START_Msk    0x2
#define WIFI_CRM_DYNCFGMMC_CNTL_DYNCFGMMC_START_Pos    0
#define WIFI_CRM_DYNCFGMMC_CNTL_DYNCFGMMC_START_Msk    0x1

#define WIFI_CRM_DYNCFGMMC_ADDR_OFFSET              0x304
#define WIFI_CRM_DYNCFGMMC_ADDR_DYNCFGMMC_WE_Pos    31
#define WIFI_CRM_DYNCFGMMC_ADDR_DYNCFGMMC_WE_Msk    0x80000000
#define WIFI_CRM_DYNCFGMMC_ADDR_DYNCFGMMC_SEL_Pos    16
#define WIFI_CRM_DYNCFGMMC_ADDR_DYNCFGMMC_SEL_Msk    0xf0000
#define WIFI_CRM_DYNCFGMMC_ADDR_DYNCFGMMC_ADDR_Pos    0
#define WIFI_CRM_DYNCFGMMC_ADDR_DYNCFGMMC_ADDR_Msk    0xffff

#define WIFI_CRM_DYNCFGMMC_DATA_OFFSET              0x308
#define WIFI_CRM_DYNCFGMMC_DATA_DYNCFGMMC_RDATA_Pos    16
#define WIFI_CRM_DYNCFGMMC_DATA_DYNCFGMMC_RDATA_Msk    0xffff0000
#define WIFI_CRM_DYNCFGMMC_DATA_DYNCFGMMC_WDATA_Pos    0
#define WIFI_CRM_DYNCFGMMC_DATA_DYNCFGMMC_WDATA_Msk    0xffff

#define WIFI_CRM_FMETRE_REF44_OFFSET                0x310
#define WIFI_CRM_FMETRE_REF44_FMETRE_REF44_Pos      0
#define WIFI_CRM_FMETRE_REF44_FMETRE_REF44_Msk      0xfffff

#define WIFI_CRM_FMETRE_LDPCRX_OFFSET               0x314
#define WIFI_CRM_FMETRE_LDPCRX_FMETRE_LDPCRX_Pos    0
#define WIFI_CRM_FMETRE_LDPCRX_FMETRE_LDPCRX_Msk    0xfffff

#define WIFI_CRM_FMETRE_REF40_OFFSET                0x31C
#define WIFI_CRM_FMETRE_REF40_FMETRE_REF40_Pos      0
#define WIFI_CRM_FMETRE_REF40_FMETRE_REF40_Msk      0xfffff

#define WIFI_CRM_FMETRE_REF80_OFFSET                0x320
#define WIFI_CRM_FMETRE_REF80_FMETRE_REF80_Pos      0
#define WIFI_CRM_FMETRE_REF80_FMETRE_REF80_Msk      0xfffff

#define WIFI_CRM_FMETRE_FE_OFFSET                   0x324
#define WIFI_CRM_FMETRE_FE_FMETRE_FE_Pos            0
#define WIFI_CRM_FMETRE_FE_FMETRE_FE_Msk            0xfffff

#define WIFI_CRM_FMETRE_VTB_OFFSET                  0x328
#define WIFI_CRM_FMETRE_VTB_FMETRE_VTB_Pos          0
#define WIFI_CRM_FMETRE_VTB_FMETRE_VTB_Msk          0xfffff

#define WIFI_CRM_FMETRE_PHY_OFFSET                  0x32C
#define WIFI_CRM_FMETRE_PHY_FMETRE_PHY_Pos          0
#define WIFI_CRM_FMETRE_PHY_FMETRE_PHY_Msk          0xfffff

#define WIFI_CRM_FMETRE_MPIF_OFFSET                 0x330
#define WIFI_CRM_FMETRE_MPIF_FMETRE_MPIF_Pos        0
#define WIFI_CRM_FMETRE_MPIF_FMETRE_MPIF_Msk        0xfffff

#define WIFI_CRM_FMETRE_LA_OFFSET                   0x334
#define WIFI_CRM_FMETRE_LA_FMETRE_LA_Pos            0
#define WIFI_CRM_FMETRE_LA_FMETRE_LA_Msk            0xfffff

#define WIFI_CRM_FMETRE_MACCORE_OFFSET              0x338
#define WIFI_CRM_FMETRE_MACCORE_FMETRE_MACCORE_Pos    0
#define WIFI_CRM_FMETRE_MACCORE_FMETRE_MACCORE_Msk    0xfffff

#define WIFI_CRM_FMETRE_MACWT_OFFSET                0x33C
#define WIFI_CRM_FMETRE_MACWT_FMETRE_MACWT_Pos      0
#define WIFI_CRM_FMETRE_MACWT_FMETRE_MACWT_Msk      0xfffff

#define WIFI_CRM_FMETRE_PLF_OFFSET                  0x340
#define WIFI_CRM_FMETRE_PLF_FMETRE_PLF_Pos          0
#define WIFI_CRM_FMETRE_PLF_FMETRE_PLF_Msk          0xfffff

#define WIFI_CRM_FMETRE_DAC_OFFSET                  0x344
#define WIFI_CRM_FMETRE_DAC_FMETRE_DAC_Pos          0
#define WIFI_CRM_FMETRE_DAC_FMETRE_DAC_Msk          0xfffff

struct WIFI_CRM_REG_RESERVED_BITS
{
    volatile uint32_t RESV_0_31                     : 32; // bit 0~31
};

union WIFI_CRM_REG_RESERVED {
    volatile uint32_t                               all;
    struct WIFI_CRM_REG_RESERVED_BITS               bit;
};

struct WIFI_CRM_REG_CLKRST_CNTL_BITS
{
    volatile uint32_t PLFCLK_SEL                    : 1; // bit 0~0
    volatile uint32_t LACLK_INV_EN                  : 1; // bit 1~1
    volatile uint32_t RESV_2_3                      : 2; // bit 2~3
    volatile uint32_t FECLK_FREQ_SEL                : 2; // bit 4~5
    volatile uint32_t RESV_6_7                      : 2; // bit 6~7
    volatile uint32_t MACCORECLK_FREQ_SEL           : 4; // bit 8~11
    volatile uint32_t MACWTCLK_RATIO_SEL            : 2; // bit 12~13
    volatile uint32_t RESV_14_15                    : 2; // bit 14~15
    volatile uint32_t MPIFCLK_FREQ_SEL              : 2; // bit 16~17
    volatile uint32_t VTBCLK_FREQ_SEL               : 2; // bit 18~19
    volatile uint32_t LDPCRXCLK_FREQ_SEL            : 2; // bit 20~21
    volatile uint32_t LDPCTXCLK_FREQ_SEL            : 2; // bit 22~23
    volatile uint32_t LACLK_FREQ_SEL                : 2; // bit 24~25
    volatile uint32_t RESV_26_31                    : 6; // bit 26~31
};

union WIFI_CRM_REG_CLKRST_CNTL {
    volatile uint32_t                               all;
    struct WIFI_CRM_REG_CLKRST_CNTL_BITS            bit;
};

struct WIFI_CRM_REG_CLKRST_STAT_BITS
{
    volatile uint32_t RESV_0_3                      : 4; // bit 0~3
    volatile uint32_t MMC_LOCK                      : 7; // bit 4~10
    volatile uint32_t RESV_11_31                    : 21; // bit 11~31
};

union WIFI_CRM_REG_CLKRST_STAT {
    volatile uint32_t                               all;
    struct WIFI_CRM_REG_CLKRST_STAT_BITS            bit;
};

struct WIFI_CRM_REG_CLKGATEPHYFCTRL0_BITS
{
    volatile uint32_t RESV_0_0                      : 1; // bit 0~0
    volatile uint32_t VTBCLKFORCE                   : 1; // bit 1~1
    volatile uint32_t RESV_2_5                      : 4; // bit 2~5
    volatile uint32_t CHESTCLKFORCE                 : 1; // bit 6~6
    volatile uint32_t RESV_7_8                      : 2; // bit 7~8
    volatile uint32_t FFTCLKFORCE                   : 1; // bit 9~9
    volatile uint32_t RESV_10_15                    : 6; // bit 10~15
    volatile uint32_t TBECLKFORCE                   : 1; // bit 16~16
    volatile uint32_t TDFOESTCLKFORCE               : 1; // bit 17~17
    volatile uint32_t TDCOMPCLKFORCE                : 1; // bit 18~18
    volatile uint32_t RESV_19_19                    : 1; // bit 19~19
    volatile uint32_t PHYSVDCLKFORCE                : 1; // bit 20~20
    volatile uint32_t RESV_21_21                    : 1; // bit 21~21
    volatile uint32_t EQUCLKFORCE                   : 1; // bit 22~22
    volatile uint32_t FDOCLKFORCE                   : 1; // bit 23~23
    volatile uint32_t FECLKFORCE                    : 1; // bit 24~24
    volatile uint32_t RESV_25_26                    : 2; // bit 25~26
    volatile uint32_t RCCLKFORCE                    : 1; // bit 27~27
    volatile uint32_t AGCCLKFORCE                   : 1; // bit 28~28
    volatile uint32_t AGCMEMCLKFORCE                : 1; // bit 29~29
    volatile uint32_t RESV_30_30                    : 1; // bit 30~30
    volatile uint32_t PHYTXCLKFORCE                 : 1; // bit 31~31
};

union WIFI_CRM_REG_CLKGATEPHYFCTRL0 {
    volatile uint32_t                               all;
    struct WIFI_CRM_REG_CLKGATEPHYFCTRL0_BITS       bit;
};

struct WIFI_CRM_REG_CLKGATEPHYFCTRL1_BITS
{
    volatile uint32_t LDPCDECCLKFORCE               : 1; // bit 0~0
    volatile uint32_t LDPCENCCLKFORCE               : 1; // bit 1~1
    volatile uint32_t MDMBCLKFORCE                  : 1; // bit 2~2
    volatile uint32_t MDMBRXCLKFORCE                : 1; // bit 3~3
    volatile uint32_t MDMBTXCLKFORCE                : 1; // bit 4~4
    volatile uint32_t RADARTIMCLKFORCE              : 1; // bit 5~5
    volatile uint32_t RESV_6_7                      : 2; // bit 6~7
    volatile uint32_t LACLKFORCE                    : 1; // bit 8~8
    volatile uint32_t RESV_9_31                     : 23; // bit 9~31
};

union WIFI_CRM_REG_CLKGATEPHYFCTRL1 {
    volatile uint32_t                               all;
    struct WIFI_CRM_REG_CLKGATEPHYFCTRL1_BITS       bit;
};

struct WIFI_CRM_REG_RSTCTRL_BITS
{
    volatile uint32_t PHYSWRESET                    : 1; // bit 0~0
    volatile uint32_t RESV_1_3                      : 3; // bit 1~3
    volatile uint32_t AGCSWRESET                    : 1; // bit 4~4
    volatile uint32_t RESV_5_7                      : 3; // bit 5~7
    volatile uint32_t RCSWRESET                     : 1; // bit 8~8
    volatile uint32_t RESV_9_11                     : 3; // bit 9~11
    volatile uint32_t WIFISTSRESET                  : 1; // bit 12~12
    volatile uint32_t RESV_13_31                    : 19; // bit 13~31
};

union WIFI_CRM_REG_RSTCTRL {
    volatile uint32_t                               all;
    struct WIFI_CRM_REG_RSTCTRL_BITS                bit;
};

struct WIFI_CRM_REG_LA_SAMPLING_FREQ_BITS
{
    volatile uint32_t LA_SAMPLING_FREQ              : 8; // bit 0~7
    volatile uint32_t RESV_8_31                     : 24; // bit 8~31
};

union WIFI_CRM_REG_LA_SAMPLING_FREQ {
    volatile uint32_t                               all;
    struct WIFI_CRM_REG_LA_SAMPLING_FREQ_BITS       bit;
};

struct WIFI_CRM_REG_DYNCFGMMC_CNTL_BITS
{
    volatile uint32_t DYNCFGMMC_START               : 1; // bit 0~0
    volatile uint32_t FMETRE_START                  : 1; // bit 1~1
    volatile uint32_t RESV_2_29                     : 28; // bit 2~29
    volatile uint32_t FMETRE_DONE                   : 1; // bit 30~30
    volatile uint32_t DYNCFGMMC_DONE                : 1; // bit 31~31
};

union WIFI_CRM_REG_DYNCFGMMC_CNTL {
    volatile uint32_t                               all;
    struct WIFI_CRM_REG_DYNCFGMMC_CNTL_BITS         bit;
};

struct WIFI_CRM_REG_DYNCFGMMC_ADDR_BITS
{
    volatile uint32_t DYNCFGMMC_ADDR                : 16; // bit 0~15
    volatile uint32_t DYNCFGMMC_SEL                 : 4; // bit 16~19
    volatile uint32_t RESV_20_30                    : 11; // bit 20~30
    volatile uint32_t DYNCFGMMC_WE                  : 1; // bit 31~31
};

union WIFI_CRM_REG_DYNCFGMMC_ADDR {
    volatile uint32_t                               all;
    struct WIFI_CRM_REG_DYNCFGMMC_ADDR_BITS         bit;
};

struct WIFI_CRM_REG_DYNCFGMMC_DATA_BITS
{
    volatile uint32_t DYNCFGMMC_WDATA               : 16; // bit 0~15
    volatile uint32_t DYNCFGMMC_RDATA               : 16; // bit 16~31
};

union WIFI_CRM_REG_DYNCFGMMC_DATA {
    volatile uint32_t                               all;
    struct WIFI_CRM_REG_DYNCFGMMC_DATA_BITS         bit;
};

struct WIFI_CRM_REG_FMETRE_REF44_BITS
{
    volatile uint32_t FMETRE_REF44                  : 20; // bit 0~19
    volatile uint32_t RESV_20_31                    : 12; // bit 20~31
};

union WIFI_CRM_REG_FMETRE_REF44 {
    volatile uint32_t                               all;
    struct WIFI_CRM_REG_FMETRE_REF44_BITS           bit;
};

struct WIFI_CRM_REG_FMETRE_LDPCRX_BITS
{
    volatile uint32_t FMETRE_LDPCRX                 : 20; // bit 0~19
    volatile uint32_t RESV_20_31                    : 12; // bit 20~31
};

union WIFI_CRM_REG_FMETRE_LDPCRX {
    volatile uint32_t                               all;
    struct WIFI_CRM_REG_FMETRE_LDPCRX_BITS          bit;
};

struct WIFI_CRM_REG_FMETRE_REF40_BITS
{
    volatile uint32_t FMETRE_REF40                  : 20; // bit 0~19
    volatile uint32_t RESV_20_31                    : 12; // bit 20~31
};

union WIFI_CRM_REG_FMETRE_REF40 {
    volatile uint32_t                               all;
    struct WIFI_CRM_REG_FMETRE_REF40_BITS           bit;
};

struct WIFI_CRM_REG_FMETRE_REF80_BITS
{
    volatile uint32_t FMETRE_REF80                  : 20; // bit 0~19
    volatile uint32_t RESV_20_31                    : 12; // bit 20~31
};

union WIFI_CRM_REG_FMETRE_REF80 {
    volatile uint32_t                               all;
    struct WIFI_CRM_REG_FMETRE_REF80_BITS           bit;
};

struct WIFI_CRM_REG_FMETRE_FE_BITS
{
    volatile uint32_t FMETRE_FE                     : 20; // bit 0~19
    volatile uint32_t RESV_20_31                    : 12; // bit 20~31
};

union WIFI_CRM_REG_FMETRE_FE {
    volatile uint32_t                               all;
    struct WIFI_CRM_REG_FMETRE_FE_BITS              bit;
};

struct WIFI_CRM_REG_FMETRE_VTB_BITS
{
    volatile uint32_t FMETRE_VTB                    : 20; // bit 0~19
    volatile uint32_t RESV_20_31                    : 12; // bit 20~31
};

union WIFI_CRM_REG_FMETRE_VTB {
    volatile uint32_t                               all;
    struct WIFI_CRM_REG_FMETRE_VTB_BITS             bit;
};

struct WIFI_CRM_REG_FMETRE_PHY_BITS
{
    volatile uint32_t FMETRE_PHY                    : 20; // bit 0~19
    volatile uint32_t RESV_20_31                    : 12; // bit 20~31
};

union WIFI_CRM_REG_FMETRE_PHY {
    volatile uint32_t                               all;
    struct WIFI_CRM_REG_FMETRE_PHY_BITS             bit;
};

struct WIFI_CRM_REG_FMETRE_MPIF_BITS
{
    volatile uint32_t FMETRE_MPIF                   : 20; // bit 0~19
    volatile uint32_t RESV_20_31                    : 12; // bit 20~31
};

union WIFI_CRM_REG_FMETRE_MPIF {
    volatile uint32_t                               all;
    struct WIFI_CRM_REG_FMETRE_MPIF_BITS            bit;
};

struct WIFI_CRM_REG_FMETRE_LA_BITS
{
    volatile uint32_t FMETRE_LA                     : 20; // bit 0~19
    volatile uint32_t RESV_20_31                    : 12; // bit 20~31
};

union WIFI_CRM_REG_FMETRE_LA {
    volatile uint32_t                               all;
    struct WIFI_CRM_REG_FMETRE_LA_BITS              bit;
};

struct WIFI_CRM_REG_FMETRE_MACCORE_BITS
{
    volatile uint32_t FMETRE_MACCORE                : 20; // bit 0~19
    volatile uint32_t RESV_20_31                    : 12; // bit 20~31
};

union WIFI_CRM_REG_FMETRE_MACCORE {
    volatile uint32_t                               all;
    struct WIFI_CRM_REG_FMETRE_MACCORE_BITS         bit;
};

struct WIFI_CRM_REG_FMETRE_MACWT_BITS
{
    volatile uint32_t FMETRE_MACWT                  : 20; // bit 0~19
    volatile uint32_t RESV_20_31                    : 12; // bit 20~31
};

union WIFI_CRM_REG_FMETRE_MACWT {
    volatile uint32_t                               all;
    struct WIFI_CRM_REG_FMETRE_MACWT_BITS           bit;
};

struct WIFI_CRM_REG_FMETRE_PLF_BITS
{
    volatile uint32_t FMETRE_PLF                    : 20; // bit 0~19
    volatile uint32_t RESV_20_31                    : 12; // bit 20~31
};

union WIFI_CRM_REG_FMETRE_PLF {
    volatile uint32_t                               all;
    struct WIFI_CRM_REG_FMETRE_PLF_BITS             bit;
};

struct WIFI_CRM_REG_FMETRE_DAC_BITS
{
    volatile uint32_t FMETRE_DAC                    : 20; // bit 0~19
    volatile uint32_t RESV_20_31                    : 12; // bit 20~31
};

union WIFI_CRM_REG_FMETRE_DAC {
    volatile uint32_t                               all;
    struct WIFI_CRM_REG_FMETRE_DAC_BITS             bit;
};

typedef struct
{
    union WIFI_CRM_REG_RESERVED                     REG_RESERVED; // 0x000
    volatile uint32_t                               REG_RESV_0X4_0X4[1];
    union WIFI_CRM_REG_CLKRST_CNTL                  REG_CLKRST_CNTL; // 0x008
    union WIFI_CRM_REG_CLKRST_STAT                  REG_CLKRST_STAT; // 0x00C
    union WIFI_CRM_REG_CLKGATEPHYFCTRL0             REG_CLKGATEPHYFCTRL0; // 0x010
    union WIFI_CRM_REG_CLKGATEPHYFCTRL1             REG_CLKGATEPHYFCTRL1; // 0x014
    union WIFI_CRM_REG_RSTCTRL                      REG_RSTCTRL; // 0x018
    volatile uint32_t                               REG_RESV_0X1C_0X68[20];
    union WIFI_CRM_REG_LA_SAMPLING_FREQ             REG_LA_SAMPLING_FREQ; // 0x06C
    volatile uint32_t                               REG_RESV_0X70_0X2FC[164];
    union WIFI_CRM_REG_DYNCFGMMC_CNTL               REG_DYNCFGMMC_CNTL; // 0x300
    union WIFI_CRM_REG_DYNCFGMMC_ADDR               REG_DYNCFGMMC_ADDR; // 0x304
    union WIFI_CRM_REG_DYNCFGMMC_DATA               REG_DYNCFGMMC_DATA; // 0x308
    volatile uint32_t                               REG_RESV_0X30C_0X30C[1];
    union WIFI_CRM_REG_FMETRE_REF44                 REG_FMETRE_REF44; // 0x310
    union WIFI_CRM_REG_FMETRE_LDPCRX                REG_FMETRE_LDPCRX; // 0x314
    volatile uint32_t                               REG_RESV_0X318_0X318[1];
    union WIFI_CRM_REG_FMETRE_REF40                 REG_FMETRE_REF40; // 0x31C
    union WIFI_CRM_REG_FMETRE_REF80                 REG_FMETRE_REF80; // 0x320
    union WIFI_CRM_REG_FMETRE_FE                    REG_FMETRE_FE; // 0x324
    union WIFI_CRM_REG_FMETRE_VTB                   REG_FMETRE_VTB; // 0x328
    union WIFI_CRM_REG_FMETRE_PHY                   REG_FMETRE_PHY; // 0x32C
    union WIFI_CRM_REG_FMETRE_MPIF                  REG_FMETRE_MPIF; // 0x330
    union WIFI_CRM_REG_FMETRE_LA                    REG_FMETRE_LA; // 0x334
    union WIFI_CRM_REG_FMETRE_MACCORE               REG_FMETRE_MACCORE; // 0x338
    union WIFI_CRM_REG_FMETRE_MACWT                 REG_FMETRE_MACWT; // 0x33C
    union WIFI_CRM_REG_FMETRE_PLF                   REG_FMETRE_PLF; // 0x340
    union WIFI_CRM_REG_FMETRE_DAC                   REG_FMETRE_DAC; // 0x344
} WIFI_CRM_RegDef;


#endif // __WIFI_CRM_REGFILE_H__

