//  ----------------------------------------------------------------------
//  File Name   : GenCFold/wifi_mdmdsss_reg_arcs.h
//  Description : C header file generated by Python script.
//  Script Ver  £ºLS.AUTO_REG.2024.03.01
//  Create Time : 2024-06-07 10:54:54
//  Comments    : 
//  ----------------------------------------------------------------------

#ifndef __WIFI_MDMDSSS_REGFILE_H__
#define __WIFI_MDMDSSS_REGFILE_H__

#include <stdint.h>

#define WIFI_MDMDSSS_FEBCNTL_OFFSET                 0x000
#define WIFI_MDMDSSS_FEBCNTL_TXNORM_Pos             24
#define WIFI_MDMDSSS_FEBCNTL_TXNORM_Msk             0x3f000000
#define WIFI_MDMDSSS_FEBCNTL_MAXSTAGE_Pos           16
#define WIFI_MDMDSSS_FEBCNTL_MAXSTAGE_Msk           0x3f0000
#define WIFI_MDMDSSS_FEBCNTL_FIRDISB_Pos            3
#define WIFI_MDMDSSS_FEBCNTL_FIRDISB_Msk            0x8
#define WIFI_MDMDSSS_FEBCNTL_GAINDISB_Pos           2
#define WIFI_MDMDSSS_FEBCNTL_GAINDISB_Msk           0x4
#define WIFI_MDMDSSS_FEBCNTL_INTERPDISB_Pos         1
#define WIFI_MDMDSSS_FEBCNTL_INTERPDISB_Msk         0x2
#define WIFI_MDMDSSS_FEBCNTL_FIRCOEFSEL_Pos         0
#define WIFI_MDMDSSS_FEBCNTL_FIRCOEFSEL_Msk         0x1

#define WIFI_MDMDSSS_MDMBCNTL_OFFSET                0x004
#define WIFI_MDMDSSS_MDMBCNTL_IQMMDISB_Pos          28
#define WIFI_MDMDSSS_MDMBCNTL_IQMMDISB_Msk          0x10000000
#define WIFI_MDMDSSS_MDMBCNTL_PRECOMPDISB_Pos       26
#define WIFI_MDMDSSS_MDMBCNTL_PRECOMPDISB_Msk       0x4000000
#define WIFI_MDMDSSS_MDMBCNTL_DCOFFDISB_Pos         25
#define WIFI_MDMDSSS_MDMBCNTL_DCOFFDISB_Msk         0x2000000
#define WIFI_MDMDSSS_MDMBCNTL_COMPDISB_Pos          24
#define WIFI_MDMDSSS_MDMBCNTL_COMPDISB_Msk          0x1000000
#define WIFI_MDMDSSS_MDMBCNTL_EQDISB_Pos            23
#define WIFI_MDMDSSS_MDMBCNTL_EQDISB_Msk            0x800000
#define WIFI_MDMDSSS_MDMBCNTL_SPREADDISB_Pos        21
#define WIFI_MDMDSSS_MDMBCNTL_SPREADDISB_Msk        0x200000
#define WIFI_MDMDSSS_MDMBCNTL_SCRAMBDISB_Pos        20
#define WIFI_MDMDSSS_MDMBCNTL_SCRAMBDISB_Msk        0x100000
#define WIFI_MDMDSSS_MDMBCNTL_SFDERR_Pos            12
#define WIFI_MDMDSSS_MDMBCNTL_SFDERR_Msk            0x7000
#define WIFI_MDMDSSS_MDMBCNTL_SFDLEN_Pos            8
#define WIFI_MDMDSSS_MDMBCNTL_SFDLEN_Msk            0x700
#define WIFI_MDMDSSS_MDMBCNTL_PREPRE_Pos            0
#define WIFI_MDMDSSS_MDMBCNTL_PREPRE_Msk            0x3f

#define WIFI_MDMDSSS_MDMBPRMINIT_OFFSET             0x008
#define WIFI_MDMDSSS_MDMBPRMINIT_RHO_Pos            20
#define WIFI_MDMDSSS_MDMBPRMINIT_RHO_Msk            0x300000
#define WIFI_MDMDSSS_MDMBPRMINIT_MU_Pos             16
#define WIFI_MDMDSSS_MDMBPRMINIT_MU_Msk             0x30000
#define WIFI_MDMDSSS_MDMBPRMINIT_BETA_Pos           4
#define WIFI_MDMDSSS_MDMBPRMINIT_BETA_Msk           0x30
#define WIFI_MDMDSSS_MDMBPRMINIT_ALPHA_Pos          0
#define WIFI_MDMDSSS_MDMBPRMINIT_ALPHA_Msk          0x3

#define WIFI_MDMDSSS_MDMBTALPHA_OFFSET              0x00C
#define WIFI_MDMDSSS_MDMBTALPHA_TALPHA3_Pos         12
#define WIFI_MDMDSSS_MDMBTALPHA_TALPHA3_Msk         0xf000
#define WIFI_MDMDSSS_MDMBTALPHA_TALPHA2_Pos         8
#define WIFI_MDMDSSS_MDMBTALPHA_TALPHA2_Msk         0xf00
#define WIFI_MDMDSSS_MDMBTALPHA_TALPHA1_Pos         4
#define WIFI_MDMDSSS_MDMBTALPHA_TALPHA1_Msk         0xf0
#define WIFI_MDMDSSS_MDMBTALPHA_TALPHA0_Pos         0
#define WIFI_MDMDSSS_MDMBTALPHA_TALPHA0_Msk         0xf

#define WIFI_MDMDSSS_MDMBTBETA_OFFSET               0x010
#define WIFI_MDMDSSS_MDMBTBETA_TBETA3_Pos           12
#define WIFI_MDMDSSS_MDMBTBETA_TBETA3_Msk           0xf000
#define WIFI_MDMDSSS_MDMBTBETA_TBETA2_Pos           8
#define WIFI_MDMDSSS_MDMBTBETA_TBETA2_Msk           0xf00
#define WIFI_MDMDSSS_MDMBTBETA_TBETA1_Pos           4
#define WIFI_MDMDSSS_MDMBTBETA_TBETA1_Msk           0xf0
#define WIFI_MDMDSSS_MDMBTBETA_TBETA0_Pos           0
#define WIFI_MDMDSSS_MDMBTBETA_TBETA0_Msk           0xf

#define WIFI_MDMDSSS_MDMBTMU_OFFSET                 0x014
#define WIFI_MDMDSSS_MDMBTMU_TMU3_Pos               12
#define WIFI_MDMDSSS_MDMBTMU_TMU3_Msk               0xf000
#define WIFI_MDMDSSS_MDMBTMU_TMU2_Pos               8
#define WIFI_MDMDSSS_MDMBTMU_TMU2_Msk               0xf00
#define WIFI_MDMDSSS_MDMBTMU_TMU1_Pos               4
#define WIFI_MDMDSSS_MDMBTMU_TMU1_Msk               0xf0
#define WIFI_MDMDSSS_MDMBTMU_TMU0_Pos               0
#define WIFI_MDMDSSS_MDMBTMU_TMU0_Msk               0xf

#define WIFI_MDMDSSS_MDMBCNTL1_OFFSET               0x018
#define WIFI_MDMDSSS_MDMBCNTL1_RXLENCHKEN_Pos       12
#define WIFI_MDMDSSS_MDMBCNTL1_RXLENCHKEN_Msk       0x1000
#define WIFI_MDMDSSS_MDMBCNTL1_RXMAXLENGTH_Pos      0
#define WIFI_MDMDSSS_MDMBCNTL1_RXMAXLENGTH_Msk      0xfff

#define WIFI_MDMDSSS_MDMBRFCNTL_OFFSET              0x01C
#define WIFI_MDMDSSS_MDMBRFCNTL_TXENDDEL_Pos        0
#define WIFI_MDMDSSS_MDMBRFCNTL_TXENDDEL_Msk        0xff

#define WIFI_MDMDSSS_MDMBEQCNTL_OFFSET              0x020
#define WIFI_MDMDSSS_MDMBEQCNTL_EQHOLD_Pos          16
#define WIFI_MDMDSSS_MDMBEQCNTL_EQHOLD_Msk          0xfff0000
#define WIFI_MDMDSSS_MDMBEQCNTL_COMPTIME_Pos        10
#define WIFI_MDMDSSS_MDMBEQCNTL_COMPTIME_Msk        0x7c00
#define WIFI_MDMDSSS_MDMBEQCNTL_ESTTIME_Pos         5
#define WIFI_MDMDSSS_MDMBEQCNTL_ESTTIME_Msk         0x3e0
#define WIFI_MDMDSSS_MDMBEQCNTL_EQTIME_Pos          0
#define WIFI_MDMDSSS_MDMBEQCNTL_EQTIME_Msk          0xf

#define WIFI_MDMDSSS_MDMBCNTL2_OFFSET               0x024
#define WIFI_MDMDSSS_MDMBCNTL2_PRECOMP_Pos          16
#define WIFI_MDMDSSS_MDMBCNTL2_PRECOMP_Msk          0x3f0000
#define WIFI_MDMDSSS_MDMBCNTL2_SYNCTIME_Pos         8
#define WIFI_MDMDSSS_MDMBCNTL2_SYNCTIME_Msk         0x3f00
#define WIFI_MDMDSSS_MDMBCNTL2_LOOPTIME_Pos         0
#define WIFI_MDMDSSS_MDMBCNTL2_LOOPTIME_Msk         0xf

#define WIFI_MDMDSSS_MDMBSTAT0_OFFSET               0x028
#define WIFI_MDMDSSS_MDMBSTAT0_EQSUMQ_Pos           24
#define WIFI_MDMDSSS_MDMBSTAT0_EQSUMQ_Msk           0xff000000
#define WIFI_MDMDSSS_MDMBSTAT0_EQSUMI_Pos           16
#define WIFI_MDMDSSS_MDMBSTAT0_EQSUMI_Msk           0xff0000
#define WIFI_MDMDSSS_MDMBSTAT0_DCOFFSETQ_Pos        8
#define WIFI_MDMDSSS_MDMBSTAT0_DCOFFSETQ_Msk        0x3f00
#define WIFI_MDMDSSS_MDMBSTAT0_DCOFFSETI_Pos        0
#define WIFI_MDMDSSS_MDMBSTAT0_DCOFFSETI_Msk        0x3f

#define WIFI_MDMDSSS_MDMBSTAT1_OFFSET               0x02C
#define WIFI_MDMDSSS_MDMBSTAT1_RXERRORSTAT_Pos      30
#define WIFI_MDMDSSS_MDMBSTAT1_RXERRORSTAT_Msk      0xc0000000
#define WIFI_MDMDSSS_MDMBSTAT1_EVM_Pos              16
#define WIFI_MDMDSSS_MDMBSTAT1_EVM_Msk              0x1fff0000
#define WIFI_MDMDSSS_MDMBSTAT1_IQGAINESTIM_Pos      8
#define WIFI_MDMDSSS_MDMBSTAT1_IQGAINESTIM_Msk      0x7f00
#define WIFI_MDMDSSS_MDMBSTAT1_FREQOFFESTIM_Pos     0
#define WIFI_MDMDSSS_MDMBSTAT1_FREQOFFESTIM_Msk     0xff

struct WIFI_MDMDSSS_REG_FEBCNTL_BITS
{
    volatile uint32_t FIRCOEFSEL                    : 1; // bit 0~0
    volatile uint32_t INTERPDISB                    : 1; // bit 1~1
    volatile uint32_t GAINDISB                      : 1; // bit 2~2
    volatile uint32_t FIRDISB                       : 1; // bit 3~3
    volatile uint32_t RESV_4_15                     : 12; // bit 4~15
    volatile uint32_t MAXSTAGE                      : 6; // bit 16~21
    volatile uint32_t RESV_22_23                    : 2; // bit 22~23
    volatile uint32_t TXNORM                        : 6; // bit 24~29
    volatile uint32_t RESV_30_31                    : 2; // bit 30~31
};

union WIFI_MDMDSSS_REG_FEBCNTL {
    volatile uint32_t                               all;
    struct WIFI_MDMDSSS_REG_FEBCNTL_BITS            bit;
};

struct WIFI_MDMDSSS_REG_MDMBCNTL_BITS
{
    volatile uint32_t PREPRE                        : 6; // bit 0~5
    volatile uint32_t RESV_6_7                      : 2; // bit 6~7
    volatile uint32_t SFDLEN                        : 3; // bit 8~10
    volatile uint32_t RESV_11_11                    : 1; // bit 11~11
    volatile uint32_t SFDERR                        : 3; // bit 12~14
    volatile uint32_t RESV_15_19                    : 5; // bit 15~19
    volatile uint32_t SCRAMBDISB                    : 1; // bit 20~20
    volatile uint32_t SPREADDISB                    : 1; // bit 21~21
    volatile uint32_t RESV_22_22                    : 1; // bit 22~22
    volatile uint32_t EQDISB                        : 1; // bit 23~23
    volatile uint32_t COMPDISB                      : 1; // bit 24~24
    volatile uint32_t DCOFFDISB                     : 1; // bit 25~25
    volatile uint32_t PRECOMPDISB                   : 1; // bit 26~26
    volatile uint32_t RESV_27_27                    : 1; // bit 27~27
    volatile uint32_t IQMMDISB                      : 1; // bit 28~28
    volatile uint32_t RESV_29_31                    : 3; // bit 29~31
};

union WIFI_MDMDSSS_REG_MDMBCNTL {
    volatile uint32_t                               all;
    struct WIFI_MDMDSSS_REG_MDMBCNTL_BITS           bit;
};

struct WIFI_MDMDSSS_REG_MDMBPRMINIT_BITS
{
    volatile uint32_t ALPHA                         : 2; // bit 0~1
    volatile uint32_t RESV_2_3                      : 2; // bit 2~3
    volatile uint32_t BETA                          : 2; // bit 4~5
    volatile uint32_t RESV_6_15                     : 10; // bit 6~15
    volatile uint32_t MU                            : 2; // bit 16~17
    volatile uint32_t RESV_18_19                    : 2; // bit 18~19
    volatile uint32_t RHO                           : 2; // bit 20~21
    volatile uint32_t RESV_22_31                    : 10; // bit 22~31
};

union WIFI_MDMDSSS_REG_MDMBPRMINIT {
    volatile uint32_t                               all;
    struct WIFI_MDMDSSS_REG_MDMBPRMINIT_BITS        bit;
};

struct WIFI_MDMDSSS_REG_MDMBTALPHA_BITS
{
    volatile uint32_t TALPHA0                       : 4; // bit 0~3
    volatile uint32_t TALPHA1                       : 4; // bit 4~7
    volatile uint32_t TALPHA2                       : 4; // bit 8~11
    volatile uint32_t TALPHA3                       : 4; // bit 12~15
    volatile uint32_t RESV_16_31                    : 16; // bit 16~31
};

union WIFI_MDMDSSS_REG_MDMBTALPHA {
    volatile uint32_t                               all;
    struct WIFI_MDMDSSS_REG_MDMBTALPHA_BITS         bit;
};

struct WIFI_MDMDSSS_REG_MDMBTBETA_BITS
{
    volatile uint32_t TBETA0                        : 4; // bit 0~3
    volatile uint32_t TBETA1                        : 4; // bit 4~7
    volatile uint32_t TBETA2                        : 4; // bit 8~11
    volatile uint32_t TBETA3                        : 4; // bit 12~15
    volatile uint32_t RESV_16_31                    : 16; // bit 16~31
};

union WIFI_MDMDSSS_REG_MDMBTBETA {
    volatile uint32_t                               all;
    struct WIFI_MDMDSSS_REG_MDMBTBETA_BITS          bit;
};

struct WIFI_MDMDSSS_REG_MDMBTMU_BITS
{
    volatile uint32_t TMU0                          : 4; // bit 0~3
    volatile uint32_t TMU1                          : 4; // bit 4~7
    volatile uint32_t TMU2                          : 4; // bit 8~11
    volatile uint32_t TMU3                          : 4; // bit 12~15
    volatile uint32_t RESV_16_31                    : 16; // bit 16~31
};

union WIFI_MDMDSSS_REG_MDMBTMU {
    volatile uint32_t                               all;
    struct WIFI_MDMDSSS_REG_MDMBTMU_BITS            bit;
};

struct WIFI_MDMDSSS_REG_MDMBCNTL1_BITS
{
    volatile uint32_t RXMAXLENGTH                   : 12; // bit 0~11
    volatile uint32_t RXLENCHKEN                    : 1; // bit 12~12
    volatile uint32_t RESV_13_31                    : 19; // bit 13~31
};

union WIFI_MDMDSSS_REG_MDMBCNTL1 {
    volatile uint32_t                               all;
    struct WIFI_MDMDSSS_REG_MDMBCNTL1_BITS          bit;
};

struct WIFI_MDMDSSS_REG_MDMBRFCNTL_BITS
{
    volatile uint32_t TXENDDEL                      : 8; // bit 0~7
    volatile uint32_t RESV_8_31                     : 24; // bit 8~31
};

union WIFI_MDMDSSS_REG_MDMBRFCNTL {
    volatile uint32_t                               all;
    struct WIFI_MDMDSSS_REG_MDMBRFCNTL_BITS         bit;
};

struct WIFI_MDMDSSS_REG_MDMBEQCNTL_BITS
{
    volatile uint32_t EQTIME                        : 4; // bit 0~3
    volatile uint32_t RESV_4_4                      : 1; // bit 4~4
    volatile uint32_t ESTTIME                       : 5; // bit 5~9
    volatile uint32_t COMPTIME                      : 5; // bit 10~14
    volatile uint32_t RESV_15_15                    : 1; // bit 15~15
    volatile uint32_t EQHOLD                        : 12; // bit 16~27
    volatile uint32_t RESV_28_31                    : 4; // bit 28~31
};

union WIFI_MDMDSSS_REG_MDMBEQCNTL {
    volatile uint32_t                               all;
    struct WIFI_MDMDSSS_REG_MDMBEQCNTL_BITS         bit;
};

struct WIFI_MDMDSSS_REG_MDMBCNTL2_BITS
{
    volatile uint32_t LOOPTIME                      : 4; // bit 0~3
    volatile uint32_t RESV_4_7                      : 4; // bit 4~7
    volatile uint32_t SYNCTIME                      : 6; // bit 8~13
    volatile uint32_t RESV_14_15                    : 2; // bit 14~15
    volatile uint32_t PRECOMP                       : 6; // bit 16~21
    volatile uint32_t RESV_22_31                    : 10; // bit 22~31
};

union WIFI_MDMDSSS_REG_MDMBCNTL2 {
    volatile uint32_t                               all;
    struct WIFI_MDMDSSS_REG_MDMBCNTL2_BITS          bit;
};

struct WIFI_MDMDSSS_REG_MDMBSTAT0_BITS
{
    volatile uint32_t DCOFFSETI                     : 6; // bit 0~5
    volatile uint32_t RESV_6_7                      : 2; // bit 6~7
    volatile uint32_t DCOFFSETQ                     : 6; // bit 8~13
    volatile uint32_t RESV_14_15                    : 2; // bit 14~15
    volatile uint32_t EQSUMI                        : 8; // bit 16~23
    volatile uint32_t EQSUMQ                        : 8; // bit 24~31
};

union WIFI_MDMDSSS_REG_MDMBSTAT0 {
    volatile uint32_t                               all;
    struct WIFI_MDMDSSS_REG_MDMBSTAT0_BITS          bit;
};

struct WIFI_MDMDSSS_REG_MDMBSTAT1_BITS
{
    volatile uint32_t FREQOFFESTIM                  : 8; // bit 0~7
    volatile uint32_t IQGAINESTIM                   : 7; // bit 8~14
    volatile uint32_t RESV_15_15                    : 1; // bit 15~15
    volatile uint32_t EVM                           : 13; // bit 16~28
    volatile uint32_t RESV_29_29                    : 1; // bit 29~29
    volatile uint32_t RXERRORSTAT                   : 2; // bit 30~31
};

union WIFI_MDMDSSS_REG_MDMBSTAT1 {
    volatile uint32_t                               all;
    struct WIFI_MDMDSSS_REG_MDMBSTAT1_BITS          bit;
};

typedef struct
{
    union WIFI_MDMDSSS_REG_FEBCNTL                  REG_FEBCNTL; // 0x000
    union WIFI_MDMDSSS_REG_MDMBCNTL                 REG_MDMBCNTL; // 0x004
    union WIFI_MDMDSSS_REG_MDMBPRMINIT              REG_MDMBPRMINIT; // 0x008
    union WIFI_MDMDSSS_REG_MDMBTALPHA               REG_MDMBTALPHA; // 0x00C
    union WIFI_MDMDSSS_REG_MDMBTBETA                REG_MDMBTBETA; // 0x010
    union WIFI_MDMDSSS_REG_MDMBTMU                  REG_MDMBTMU; // 0x014
    union WIFI_MDMDSSS_REG_MDMBCNTL1                REG_MDMBCNTL1; // 0x018
    union WIFI_MDMDSSS_REG_MDMBRFCNTL               REG_MDMBRFCNTL; // 0x01C
    union WIFI_MDMDSSS_REG_MDMBEQCNTL               REG_MDMBEQCNTL; // 0x020
    union WIFI_MDMDSSS_REG_MDMBCNTL2                REG_MDMBCNTL2; // 0x024
    union WIFI_MDMDSSS_REG_MDMBSTAT0                REG_MDMBSTAT0; // 0x028
    union WIFI_MDMDSSS_REG_MDMBSTAT1                REG_MDMBSTAT1; // 0x02C
} WIFI_MDMDSSS_RegDef;


#endif // __WIFI_MDMDSSS_REGFILE_H__

