# 项目可根据需要在此文件中设置对应的配置
CONFIG_MEM_CONFIG=y

CONFIG_MEM_SRAM_BASE=0x20010000
CONFIG_MEM_SRAM_SIZE=0x00020000

CONFIG_MEM_PSRAM_BASE=0x28000000
CONFIG_MEM_PSRAM_SIZE=0x00800000

CONFIG_MEM_FLASH_BASE=0x30000000
CONFIG_MEM_FLASH_SIZE=0x00200000

# AP core
CONFIG_ARCS_AP_CORE=y
CONFIG_CLOCK_INIT=y
CONFIG_PSRAM_INIT=y

# LSF
CONFIG_ARCS_HAL_LSF=y
CONFIG_IPC_LSF=y
CONFIG_DISK_MEM=n

# CONFIG_ARCS_HAL_IC_MUTEX=n

# LOG UART
CONFIG_SYSLOG_UART_PORT=1
CONFIG_SYSLOG_UART_BAUDRATE=921600
CONFIG_SYSLOG_UART_TX_PIN=21
CONFIG_SYSLOG_UART_TX_PIN_FUNC_SEL=3

# C LIB
CONFIG_LINK_OPTION_NONE_SPECS=y

# HEAP
CONFIG_HEAP_SIZE=0x10000
CONFIG_PSRAM_HEAP_SIZE=0x100000

# CPP
CONFIG_LINK_CPP_RUNTIME_SECTIONS=n
CONFIG_CPP_EXCEPTIONS=n

# Debug
CONFIG_BACK_TRACE=y

# freertos
CONFIG_FREERTOS_STATIC_ALLOCATION_ENABLE=y
CONFIG_FREERTOS_FAST_FUNC_SECTION=".text"

# main task
CONFIG_MAIN_TASK_STACK_SIZE=8192
CONFIG_MAIN_TASK_PRIORITY=1

CONFIG_LOG=y
CONFIG_SYSLOG_PRINTK_REDIRECT=y
CONFIG_SYSLOG_UART_TX_PORT=1
CONFIG_SYSLOG_UART_TX_PIN=2
CONFIG_SYSLOG_UART_TX_PIN_FUNC_SEL=3
CONFIG_SYSLOG_UART_PORT=1
CONFIG_SYSLOG_UART_BAUDRATE=921600
