#ifndef INCLUDE_LINKER_SCRIPT_CONFIG_H_
#define INCLUDE_LINKER_SCRIPT_CONFIG_H_

/**
 * 
 * MEMORY DEFINE
 */
#define __HAL_LS_CFG_CORE_ROM_NICK     CORE_ROM
#define __HAL_LS_CFG_CORE_ROM_BASE     (0x0)
#define __HAL_LS_CFG_CORE_ROM_SIZE     (0x8000)

#define __HAL_LS_CFG_CORE0_ILM_NICK    CORE0_ILM
#define __HAL_LS_CFG_CORE0_ILM_BASE    (0x80000)
#define __HAL_LS_CFG_CORE0_ILM_SIZE    (0x2000)

#define __HAL_LS_CFG_CORE0_DLM_NICK    CORE0_DLM
#define __HAL_LS_CFG_CORE0_DLM_BASE    (0x100000)
#define __HAL_LS_CFG_CORE0_DLM_SIZE    (0x2000)

#define __HAL_LS_CFG_CORE1_ILM_NICK    CORE1_ILM
#define __HAL_LS_CFG_CORE1_ILM_BASE    (0x200000)
#define __HAL_LS_CFG_CORE1_ILM_SIZE    (0x2000)

#define __HAL_LS_CFG_CORE1_DLM_NICK    CORE1_DLM
#define __HAL_LS_CFG_CORE1_DLM_BASE    (0x300000)
#define __HAL_LS_CFG_CORE1_DLM_SIZE    (0x2000)

#define __HAL_LS_CFG_CMN_RAM0_NICK     CMN_RAM0
#define __HAL_LS_CFG_CMN_RAM0_BASE     (0x20000000)
#define __HAL_LS_CFG_CMN_RAM0_SIZE     (0x10000)

#define __HAL_LS_CFG_CMN_RAM1_NICK     CMN_RAM1
#define __HAL_LS_CFG_CMN_RAM1_BASE     (0x20010000)
#define __HAL_LS_CFG_CMN_RAM1_SIZE     (0x10000)

#define __HAL_LS_CFG_CMN_LUNA_RAM_NICK CMN_LUNA
#define __HAL_LS_CFG_CMN_LUNA_RAM_BASE (0x20020000)
#define __HAL_LS_CFG_CMN_LUNA_RAM_SIZE (0x60000)

#define __HAL_LS_CFG_CMN_FLASH_NICK    CMN_FLASH
#define __HAL_LS_CFG_CMN_FLASH_BASE    (0x30000000)
#define __HAL_LS_CFG_CMN_FLASH_SIZE    (0x400000)

#define __HAL_LS_CFG_CMN_PSRAM_NICK    CMN_PSRAM
#define __HAL_LS_CFG_CMN_PSRAM_BASE    (0x38000000)
#define __HAL_LS_CFG_CMN_PSRAM_SIZE    (0x400000)


#define __HAL_LS_CFG_CMN_TEXT_VMA  __HAL_LS_CFG_CMN_FLASH_NICK
#define __HAL_LS_CFG_CMN_TEXT_LMA  __HAL_LS_CFG_CMN_FLASH_NICK

#define __HAL_LS_CFG_CMN_DATA_VMA  __HAL_LS_CFG_CMN_RAM0_NICK
#define __HAL_LS_CFG_CMN_DATA_LMA  __HAL_LS_CFG_CMN_FLASH_NICK

/**
 * @brief  Core count
 */
#define __HAL_LS_CFG_CORE_CNT          2

/** 
 * @brief  System stack size
 */
#define __HAL_LS_CFG_SYSTEM_STACK_SIZE      0x400

/**
 * @brief  System heap size
 */
#define __HAL_LS_CFG_SYSTEM_HEAP_SIZE_LIMIT 0x400

#endif
