//  ----------------------------------------------------------------------
//  File Name   : GenCFold/cmn_buscfg_reg_venusa.h
//  Description : C header file generated by Python script.
//  Author      : dlchang
//  Script Ver  : LS.AUTO_REG.2025.2.6
//  SVN Revision: Can't find <<VenusA_SoC_Memory_Mapping.xlsx>> SVN detail info,pls chk£¡£¡
//  Create Time : 2025-07-16 10:08:29
//  Comments    : 
//  ----------------------------------------------------------------------

#ifndef __CMN_BUSCFG_REGFILE_H__
#define __CMN_BUSCFG_REGFILE_H__

#include <stdint.h>

#define CMN_BUSCFG_BUS_CLK_CFG0_OFFSET              0x000
#define CMN_BUSCFG_BUS_CLK_CFG0_DIV_HCLK_LD_Pos     25
#define CMN_BUSCFG_BUS_CLK_CFG0_DIV_HCLK_LD_Msk     0x2000000
#define CMN_BUSCFG_BUS_CLK_CFG0_DIV_HCLK_N_Pos      21
#define CMN_BUSCFG_BUS_CLK_CFG0_DIV_HCLK_N_Msk      0x1e00000
#define CMN_BUSCFG_BUS_CLK_CFG0_DIV_HCLK_M_Pos      16
#define CMN_BUSCFG_BUS_CLK_CFG0_DIV_HCLK_M_Msk      0x1f0000
#define CMN_BUSCFG_BUS_CLK_CFG0_DIS_SYS_PLL_UNLOCK_Pos    2
#define CMN_BUSCFG_BUS_CLK_CFG0_DIS_SYS_PLL_UNLOCK_Msk    0x4
#define CMN_BUSCFG_BUS_CLK_CFG0_SEL_HCLK_Pos        0
#define CMN_BUSCFG_BUS_CLK_CFG0_SEL_HCLK_Msk        0x3

#define CMN_BUSCFG_BUS_CLK_CFG1_OFFSET              0x004
#define CMN_BUSCFG_BUS_CLK_CFG1_DIV_AON_CFG_PCLK_LD_Pos    27
#define CMN_BUSCFG_BUS_CLK_CFG1_DIV_AON_CFG_PCLK_LD_Msk    0x8000000
#define CMN_BUSCFG_BUS_CLK_CFG1_DIV_AON_CFG_PCLK_N_Pos    22
#define CMN_BUSCFG_BUS_CLK_CFG1_DIV_AON_CFG_PCLK_N_Msk    0x7c00000
#define CMN_BUSCFG_BUS_CLK_CFG1_DIV_AON_CFG_PCLK_M_Pos    16
#define CMN_BUSCFG_BUS_CLK_CFG1_DIV_AON_CFG_PCLK_M_Msk    0x3f0000
#define CMN_BUSCFG_BUS_CLK_CFG1_DIV_CMN_PERI_PCLK_LD_Pos    9
#define CMN_BUSCFG_BUS_CLK_CFG1_DIV_CMN_PERI_PCLK_LD_Msk    0x200
#define CMN_BUSCFG_BUS_CLK_CFG1_DIV_CMN_PERI_PCLK_N_Pos    5
#define CMN_BUSCFG_BUS_CLK_CFG1_DIV_CMN_PERI_PCLK_N_Msk    0x1e0
#define CMN_BUSCFG_BUS_CLK_CFG1_DIV_CMN_PERI_PCLK_M_Pos    0
#define CMN_BUSCFG_BUS_CLK_CFG1_DIV_CMN_PERI_PCLK_M_Msk    0x1f

#define CMN_BUSCFG_SYSPLL_CFG0_OFFSET               0x008
#define CMN_BUSCFG_SYSPLL_CFG0_SYSPLL_REF_SEL_Pos    29
#define CMN_BUSCFG_SYSPLL_CFG0_SYSPLL_REF_SEL_Msk    0x20000000
#define CMN_BUSCFG_SYSPLL_CFG0_SYSPLL_POSTDIV_AUD_EN_Pos    28
#define CMN_BUSCFG_SYSPLL_CFG0_SYSPLL_POSTDIV_AUD_EN_Msk    0x10000000
#define CMN_BUSCFG_SYSPLL_CFG0_SYSPLL_POSTDIV_FLASH_EN_Pos    27
#define CMN_BUSCFG_SYSPLL_CFG0_SYSPLL_POSTDIV_FLASH_EN_Msk    0x8000000
#define CMN_BUSCFG_SYSPLL_CFG0_SYSPLL_POSTDIV_PERI_EN_Pos    26
#define CMN_BUSCFG_SYSPLL_CFG0_SYSPLL_POSTDIV_PERI_EN_Msk    0x4000000
#define CMN_BUSCFG_SYSPLL_CFG0_SYSPLL_POSTDIV_PSRAM_EN_Pos    25
#define CMN_BUSCFG_SYSPLL_CFG0_SYSPLL_POSTDIV_PSRAM_EN_Msk    0x2000000
#define CMN_BUSCFG_SYSPLL_CFG0_SYSPLL_POSTDIV_SDIO_EN_Pos    24
#define CMN_BUSCFG_SYSPLL_CFG0_SYSPLL_POSTDIV_SDIO_EN_Msk    0x1000000
#define CMN_BUSCFG_SYSPLL_CFG0_SYSPLL_POSTDIV_SYSTEM_EN_Pos    23
#define CMN_BUSCFG_SYSPLL_CFG0_SYSPLL_POSTDIV_SYSTEM_EN_Msk    0x800000
#define CMN_BUSCFG_SYSPLL_CFG0_SYSPLL_LOCK_Pos      22
#define CMN_BUSCFG_SYSPLL_CFG0_SYSPLL_LOCK_Msk      0x400000
#define CMN_BUSCFG_SYSPLL_CFG0_SYSPLL_LOCK_CNT_Pos    11
#define CMN_BUSCFG_SYSPLL_CFG0_SYSPLL_LOCK_CNT_Msk    0x3ff800
#define CMN_BUSCFG_SYSPLL_CFG0_SYSPLL_CALIB_EN_Pos    10
#define CMN_BUSCFG_SYSPLL_CFG0_SYSPLL_CALIB_EN_Msk    0x400
#define CMN_BUSCFG_SYSPLL_CFG0_SYSPLL_FC_EN_CNT_Pos    1
#define CMN_BUSCFG_SYSPLL_CFG0_SYSPLL_FC_EN_CNT_Msk    0x3fe
#define CMN_BUSCFG_SYSPLL_CFG0_SYSPLL_ENABLE_Pos    0
#define CMN_BUSCFG_SYSPLL_CFG0_SYSPLL_ENABLE_Msk    0x1

#define CMN_BUSCFG_SYSPLL_CFG1_OFFSET               0x00C
#define CMN_BUSCFG_SYSPLL_CFG1_SYSPLL_POSTDIV_SDIO_DIV_SEL_Pos    28
#define CMN_BUSCFG_SYSPLL_CFG1_SYSPLL_POSTDIV_SDIO_DIV_SEL_Msk    0x70000000
#define CMN_BUSCFG_SYSPLL_CFG1_SYSPLL_LPF_C3_Pos    25
#define CMN_BUSCFG_SYSPLL_CFG1_SYSPLL_LPF_C3_Msk    0xe000000
#define CMN_BUSCFG_SYSPLL_CFG1_SYSPLL_LPF_R2_Pos    22
#define CMN_BUSCFG_SYSPLL_CFG1_SYSPLL_LPF_R2_Msk    0x1c00000
#define CMN_BUSCFG_SYSPLL_CFG1_SYSPLL_VCO_IBIT_Pos    19
#define CMN_BUSCFG_SYSPLL_CFG1_SYSPLL_VCO_IBIT_Msk    0x380000
#define CMN_BUSCFG_SYSPLL_CFG1_SYSPLL_VCO_KVCO_Pos    16
#define CMN_BUSCFG_SYSPLL_CFG1_SYSPLL_VCO_KVCO_Msk    0x70000
#define CMN_BUSCFG_SYSPLL_CFG1_SYSPLL_POSTDIV_PERI_DIV_SEL_Pos    12
#define CMN_BUSCFG_SYSPLL_CFG1_SYSPLL_POSTDIV_PERI_DIV_SEL_Msk    0xf000
#define CMN_BUSCFG_SYSPLL_CFG1_SYSPLL_POSTDIV_FLASH_DIV_SEL_Pos    9
#define CMN_BUSCFG_SYSPLL_CFG1_SYSPLL_POSTDIV_FLASH_DIV_SEL_Msk    0xe00
#define CMN_BUSCFG_SYSPLL_CFG1_SYSPLL_POSTDIV_SYSTEM_DIV_SEL_Pos    1
#define CMN_BUSCFG_SYSPLL_CFG1_SYSPLL_POSTDIV_SYSTEM_DIV_SEL_Msk    0x1e

#define CMN_BUSCFG_SYSPLL_CFG2_OFFSET               0x010
#define CMN_BUSCFG_SYSPLL_CFG2_SYSPLL_POSTDIV_SYSTEM_LOAD_Pos    23
#define CMN_BUSCFG_SYSPLL_CFG2_SYSPLL_POSTDIV_SYSTEM_LOAD_Msk    0x800000
#define CMN_BUSCFG_SYSPLL_CFG2_SYSPLL_POSTDIV_FLASH_LOAD_Pos    22
#define CMN_BUSCFG_SYSPLL_CFG2_SYSPLL_POSTDIV_FLASH_LOAD_Msk    0x400000
#define CMN_BUSCFG_SYSPLL_CFG2_SYSPLL_POSTDIV_PSRAM_LOAD_Pos    21
#define CMN_BUSCFG_SYSPLL_CFG2_SYSPLL_POSTDIV_PSRAM_LOAD_Msk    0x200000
#define CMN_BUSCFG_SYSPLL_CFG2_SYSPLL_POSTDIV_PSRAM_DIV_SEL_Pos    17
#define CMN_BUSCFG_SYSPLL_CFG2_SYSPLL_POSTDIV_PSRAM_DIV_SEL_Msk    0x1e0000
#define CMN_BUSCFG_SYSPLL_CFG2_SYSPLL_VCO_LDO_OUT_Pos    14
#define CMN_BUSCFG_SYSPLL_CFG2_SYSPLL_VCO_LDO_OUT_Msk    0x1c000
#define CMN_BUSCFG_SYSPLL_CFG2_SYSPLL_CP_CPI_OFF_Pos    10
#define CMN_BUSCFG_SYSPLL_CFG2_SYSPLL_CP_CPI_OFF_Msk    0x3c00
#define CMN_BUSCFG_SYSPLL_CFG2_SYSPLL_CP_CPI_Pos    6
#define CMN_BUSCFG_SYSPLL_CFG2_SYSPLL_CP_CPI_Msk    0x3c0
#define CMN_BUSCFG_SYSPLL_CFG2_SYSPLL_LPF_C1_Pos    3
#define CMN_BUSCFG_SYSPLL_CFG2_SYSPLL_LPF_C1_Msk    0x38
#define CMN_BUSCFG_SYSPLL_CFG2_SYSPLL_LPF_C2_Pos    0
#define CMN_BUSCFG_SYSPLL_CFG2_SYSPLL_LPF_C2_Msk    0x7

#define CMN_BUSCFG_SYSPLL_CFG3_OFFSET               0x014
#define CMN_BUSCFG_SYSPLL_CFG3_SYSPLL_SDM_DIVN_FRAC_Pos    0
#define CMN_BUSCFG_SYSPLL_CFG3_SYSPLL_SDM_DIVN_FRAC_Msk    0x7ffffff

#define CMN_BUSCFG_SYSPLL_CFG4_OFFSET               0x018
#define CMN_BUSCFG_SYSPLL_CFG4_SYSPLL_SDM_TESTMODE_Pos    13
#define CMN_BUSCFG_SYSPLL_CFG4_SYSPLL_SDM_TESTMODE_Msk    0x2000
#define CMN_BUSCFG_SYSPLL_CFG4_SYSPLL_SDM_DITHER_EN_Pos    12
#define CMN_BUSCFG_SYSPLL_CFG4_SYSPLL_SDM_DITHER_EN_Msk    0x1000
#define CMN_BUSCFG_SYSPLL_CFG4_SYSPLL_SDM_ORDER_Pos    10
#define CMN_BUSCFG_SYSPLL_CFG4_SYSPLL_SDM_ORDER_Msk    0xc00
#define CMN_BUSCFG_SYSPLL_CFG4_SYSPLL_SDM_EN_Pos    9
#define CMN_BUSCFG_SYSPLL_CFG4_SYSPLL_SDM_EN_Msk    0x200
#define CMN_BUSCFG_SYSPLL_CFG4_SYSPLL_SDM_DIVN_INTEG_Pos    0
#define CMN_BUSCFG_SYSPLL_CFG4_SYSPLL_SDM_DIVN_INTEG_Msk    0x1ff

#define CMN_BUSCFG_SYSPLL_FORCE_OFFSET              0x03C
#define CMN_BUSCFG_SYSPLL_FORCE_SYSPLL_SDM_RST_FORCEDATA_Pos    13
#define CMN_BUSCFG_SYSPLL_FORCE_SYSPLL_SDM_RST_FORCEDATA_Msk    0x2000
#define CMN_BUSCFG_SYSPLL_FORCE_SYSPLL_SDM_RST_FORCE_Pos    12
#define CMN_BUSCFG_SYSPLL_FORCE_SYSPLL_SDM_RST_FORCE_Msk    0x1000
#define CMN_BUSCFG_SYSPLL_FORCE_SYSPLL_POSTDIV_RST_FORCEDATA_Pos    11
#define CMN_BUSCFG_SYSPLL_FORCE_SYSPLL_POSTDIV_RST_FORCEDATA_Msk    0x800
#define CMN_BUSCFG_SYSPLL_FORCE_SYSPLL_POSTDIV_RST_FORCE_Pos    10
#define CMN_BUSCFG_SYSPLL_FORCE_SYSPLL_POSTDIV_RST_FORCE_Msk    0x400
#define CMN_BUSCFG_SYSPLL_FORCE_SYSPLL_VCO_EN_FORCEDATA_Pos    9
#define CMN_BUSCFG_SYSPLL_FORCE_SYSPLL_VCO_EN_FORCEDATA_Msk    0x200
#define CMN_BUSCFG_SYSPLL_FORCE_SYSPLL_VCO_EN_FORCE_Pos    8
#define CMN_BUSCFG_SYSPLL_FORCE_SYSPLL_VCO_EN_FORCE_Msk    0x100
#define CMN_BUSCFG_SYSPLL_FORCE_SYSPLL_FBDIV_EN_FORCEDATA_Pos    7
#define CMN_BUSCFG_SYSPLL_FORCE_SYSPLL_FBDIV_EN_FORCEDATA_Msk    0x80
#define CMN_BUSCFG_SYSPLL_FORCE_SYSPLL_FBDIV_EN_FORCE_Pos    6
#define CMN_BUSCFG_SYSPLL_FORCE_SYSPLL_FBDIV_EN_FORCE_Msk    0x40
#define CMN_BUSCFG_SYSPLL_FORCE_SYSPLL_CP_EN_FORCEDATA_Pos    5
#define CMN_BUSCFG_SYSPLL_FORCE_SYSPLL_CP_EN_FORCEDATA_Msk    0x20
#define CMN_BUSCFG_SYSPLL_FORCE_SYSPLL_CP_EN_FORCE_Pos    4
#define CMN_BUSCFG_SYSPLL_FORCE_SYSPLL_CP_EN_FORCE_Msk    0x10
#define CMN_BUSCFG_SYSPLL_FORCE_SYSPLL_PFD_EN_FORCEDATA_Pos    3
#define CMN_BUSCFG_SYSPLL_FORCE_SYSPLL_PFD_EN_FORCEDATA_Msk    0x8
#define CMN_BUSCFG_SYSPLL_FORCE_SYSPLL_PFD_EN_FORCE_Pos    2
#define CMN_BUSCFG_SYSPLL_FORCE_SYSPLL_PFD_EN_FORCE_Msk    0x4
#define CMN_BUSCFG_SYSPLL_FORCE_SYSPLL_VCO_LDO_EN_FORCEDATA_Pos    1
#define CMN_BUSCFG_SYSPLL_FORCE_SYSPLL_VCO_LDO_EN_FORCEDATA_Msk    0x2
#define CMN_BUSCFG_SYSPLL_FORCE_SYSPLL_VCO_LDO_EN_FORCE_Pos    0
#define CMN_BUSCFG_SYSPLL_FORCE_SYSPLL_VCO_LDO_EN_FORCE_Msk    0x1

struct CMN_BUSCFG_REG_BUS_CLK_CFG0_BITS
{
    volatile uint32_t SEL_HCLK                      : 2; // bit 0~1
    volatile uint32_t DIS_SYS_PLL_UNLOCK            : 1; // bit 2~2
    volatile uint32_t RESV_3_15                     : 13; // bit 3~15
    volatile uint32_t DIV_HCLK_M                    : 5; // bit 16~20
    volatile uint32_t DIV_HCLK_N                    : 4; // bit 21~24
    volatile uint32_t DIV_HCLK_LD                   : 1; // bit 25~25
    volatile uint32_t RESV_26_31                    : 6; // bit 26~31
};

union CMN_BUSCFG_REG_BUS_CLK_CFG0 {
    volatile uint32_t                               all;
    struct CMN_BUSCFG_REG_BUS_CLK_CFG0_BITS         bit;
};

struct CMN_BUSCFG_REG_BUS_CLK_CFG1_BITS
{
    volatile uint32_t DIV_CMN_PERI_PCLK_M           : 5; // bit 0~4
    volatile uint32_t DIV_CMN_PERI_PCLK_N           : 4; // bit 5~8
    volatile uint32_t DIV_CMN_PERI_PCLK_LD          : 1; // bit 9~9
    volatile uint32_t RESV_10_15                    : 6; // bit 10~15
    volatile uint32_t DIV_AON_CFG_PCLK_M            : 6; // bit 16~21
    volatile uint32_t DIV_AON_CFG_PCLK_N            : 5; // bit 22~26
    volatile uint32_t DIV_AON_CFG_PCLK_LD           : 1; // bit 27~27
    volatile uint32_t RESV_28_31                    : 4; // bit 28~31
};

union CMN_BUSCFG_REG_BUS_CLK_CFG1 {
    volatile uint32_t                               all;
    struct CMN_BUSCFG_REG_BUS_CLK_CFG1_BITS         bit;
};

struct CMN_BUSCFG_REG_SYSPLL_CFG0_BITS
{
    volatile uint32_t SYSPLL_ENABLE                 : 1; // bit 0~0
    volatile uint32_t SYSPLL_FC_EN_CNT              : 9; // bit 1~9
    volatile uint32_t SYSPLL_CALIB_EN               : 1; // bit 10~10
    volatile uint32_t SYSPLL_LOCK_CNT               : 11; // bit 11~21
    volatile uint32_t SYSPLL_LOCK                   : 1; // bit 22~22
    volatile uint32_t SYSPLL_POSTDIV_SYSTEM_EN      : 1; // bit 23~23
    volatile uint32_t SYSPLL_POSTDIV_SDIO_EN        : 1; // bit 24~24
    volatile uint32_t SYSPLL_POSTDIV_PSRAM_EN       : 1; // bit 25~25
    volatile uint32_t SYSPLL_POSTDIV_PERI_EN        : 1; // bit 26~26
    volatile uint32_t SYSPLL_POSTDIV_FLASH_EN       : 1; // bit 27~27
    volatile uint32_t SYSPLL_POSTDIV_AUD_EN         : 1; // bit 28~28
    volatile uint32_t SYSPLL_REF_SEL                : 1; // bit 29~29
    volatile uint32_t RESV_30_31                    : 2; // bit 30~31
};

union CMN_BUSCFG_REG_SYSPLL_CFG0 {
    volatile uint32_t                               all;
    struct CMN_BUSCFG_REG_SYSPLL_CFG0_BITS          bit;
};

struct CMN_BUSCFG_REG_SYSPLL_CFG1_BITS
{
    volatile uint32_t RESV_0_0                      : 1; // bit 0~0
    volatile uint32_t SYSPLL_POSTDIV_SYSTEM_DIV_SEL    : 4; // bit 1~4
    volatile uint32_t RESV_5_8                      : 4; // bit 5~8
    volatile uint32_t SYSPLL_POSTDIV_FLASH_DIV_SEL    : 3; // bit 9~11
    volatile uint32_t SYSPLL_POSTDIV_PERI_DIV_SEL    : 4; // bit 12~15
    volatile uint32_t SYSPLL_VCO_KVCO               : 3; // bit 16~18
    volatile uint32_t SYSPLL_VCO_IBIT               : 3; // bit 19~21
    volatile uint32_t SYSPLL_LPF_R2                 : 3; // bit 22~24
    volatile uint32_t SYSPLL_LPF_C3                 : 3; // bit 25~27
    volatile uint32_t SYSPLL_POSTDIV_SDIO_DIV_SEL    : 3; // bit 28~30
    volatile uint32_t RESV_31_31                    : 1; // bit 31~31
};

union CMN_BUSCFG_REG_SYSPLL_CFG1 {
    volatile uint32_t                               all;
    struct CMN_BUSCFG_REG_SYSPLL_CFG1_BITS          bit;
};

struct CMN_BUSCFG_REG_SYSPLL_CFG2_BITS
{
    volatile uint32_t SYSPLL_LPF_C2                 : 3; // bit 0~2
    volatile uint32_t SYSPLL_LPF_C1                 : 3; // bit 3~5
    volatile uint32_t SYSPLL_CP_CPI                 : 4; // bit 6~9
    volatile uint32_t SYSPLL_CP_CPI_OFF             : 4; // bit 10~13
    volatile uint32_t SYSPLL_VCO_LDO_OUT            : 3; // bit 14~16
    volatile uint32_t SYSPLL_POSTDIV_PSRAM_DIV_SEL    : 4; // bit 17~20
    volatile uint32_t SYSPLL_POSTDIV_PSRAM_LOAD     : 1; // bit 21~21
    volatile uint32_t SYSPLL_POSTDIV_FLASH_LOAD     : 1; // bit 22~22
    volatile uint32_t SYSPLL_POSTDIV_SYSTEM_LOAD    : 1; // bit 23~23
    volatile uint32_t RESV_24_31                    : 8; // bit 24~31
};

union CMN_BUSCFG_REG_SYSPLL_CFG2 {
    volatile uint32_t                               all;
    struct CMN_BUSCFG_REG_SYSPLL_CFG2_BITS          bit;
};

struct CMN_BUSCFG_REG_SYSPLL_CFG3_BITS
{
    volatile uint32_t SYSPLL_SDM_DIVN_FRAC          : 27; // bit 0~26
    volatile uint32_t RESV_27_31                    : 5; // bit 27~31
};

union CMN_BUSCFG_REG_SYSPLL_CFG3 {
    volatile uint32_t                               all;
    struct CMN_BUSCFG_REG_SYSPLL_CFG3_BITS          bit;
};

struct CMN_BUSCFG_REG_SYSPLL_CFG4_BITS
{
    volatile uint32_t SYSPLL_SDM_DIVN_INTEG         : 9; // bit 0~8
    volatile uint32_t SYSPLL_SDM_EN                 : 1; // bit 9~9
    volatile uint32_t SYSPLL_SDM_ORDER              : 2; // bit 10~11
    volatile uint32_t SYSPLL_SDM_DITHER_EN          : 1; // bit 12~12
    volatile uint32_t SYSPLL_SDM_TESTMODE           : 1; // bit 13~13
    volatile uint32_t RESV_14_31                    : 18; // bit 14~31
};

union CMN_BUSCFG_REG_SYSPLL_CFG4 {
    volatile uint32_t                               all;
    struct CMN_BUSCFG_REG_SYSPLL_CFG4_BITS          bit;
};

struct CMN_BUSCFG_REG_SYSPLL_FORCE_BITS
{
    volatile uint32_t SYSPLL_VCO_LDO_EN_FORCE       : 1; // bit 0~0
    volatile uint32_t SYSPLL_VCO_LDO_EN_FORCEDATA    : 1; // bit 1~1
    volatile uint32_t SYSPLL_PFD_EN_FORCE           : 1; // bit 2~2
    volatile uint32_t SYSPLL_PFD_EN_FORCEDATA       : 1; // bit 3~3
    volatile uint32_t SYSPLL_CP_EN_FORCE            : 1; // bit 4~4
    volatile uint32_t SYSPLL_CP_EN_FORCEDATA        : 1; // bit 5~5
    volatile uint32_t SYSPLL_FBDIV_EN_FORCE         : 1; // bit 6~6
    volatile uint32_t SYSPLL_FBDIV_EN_FORCEDATA     : 1; // bit 7~7
    volatile uint32_t SYSPLL_VCO_EN_FORCE           : 1; // bit 8~8
    volatile uint32_t SYSPLL_VCO_EN_FORCEDATA       : 1; // bit 9~9
    volatile uint32_t SYSPLL_POSTDIV_RST_FORCE      : 1; // bit 10~10
    volatile uint32_t SYSPLL_POSTDIV_RST_FORCEDATA    : 1; // bit 11~11
    volatile uint32_t SYSPLL_SDM_RST_FORCE          : 1; // bit 12~12
    volatile uint32_t SYSPLL_SDM_RST_FORCEDATA      : 1; // bit 13~13
    volatile uint32_t RESV_14_31                    : 18; // bit 14~31
};

union CMN_BUSCFG_REG_SYSPLL_FORCE {
    volatile uint32_t                               all;
    struct CMN_BUSCFG_REG_SYSPLL_FORCE_BITS         bit;
};

typedef struct
{
    union CMN_BUSCFG_REG_BUS_CLK_CFG0               REG_BUS_CLK_CFG0; // 0x000
    union CMN_BUSCFG_REG_BUS_CLK_CFG1               REG_BUS_CLK_CFG1; // 0x004
    union CMN_BUSCFG_REG_SYSPLL_CFG0                REG_SYSPLL_CFG0; // 0x008
    union CMN_BUSCFG_REG_SYSPLL_CFG1                REG_SYSPLL_CFG1; // 0x00C
    union CMN_BUSCFG_REG_SYSPLL_CFG2                REG_SYSPLL_CFG2; // 0x010
    union CMN_BUSCFG_REG_SYSPLL_CFG3                REG_SYSPLL_CFG3; // 0x014
    union CMN_BUSCFG_REG_SYSPLL_CFG4                REG_SYSPLL_CFG4; // 0x018
    volatile uint32_t                               REG_RESV_0X1C_0X38[8];
    union CMN_BUSCFG_REG_SYSPLL_FORCE               REG_SYSPLL_FORCE; // 0x03C
} CMN_BUSCFG_RegDef;


#endif // __CMN_BUSCFG_REGFILE_H__

