# 项目可根据需要在此文件中设置对应的配置
CONFIG_ARCS_HAL_WARNING_DISABLE=y
# CONFIG_ARCS_HAL_DEBUG=y
CONFIG_MODULE_FREERTOS=y
CONFIG_MODULE_HEAP=y
CONFIG_LINK_OPTION_NOSYS_SPECS=y
# CONFIG_SDK_MODULE_EASYLOGGER=n

# 文件系统配置
CONFIG_FILE_SYSTEM=y
CONFIG_FATFS_FILESYSTEM=y

# DISK驱动使能
CONFIG_DISK_DRIVER=y

# DISK FLASH驱动使能及配置
# CONFIG_DISK_DRIVER_FLASH=y
# CONFIG_DISK_FLASH_START_ADDR=0x100000
# CONFIG_DISK_FLASH_MAX_RW_SIZE=4096
# CONFIG_DISK_FLASH_ERASE_ALIGNMENT=4096
# CONFIG_DISK_FLASH_ERASE_BLOCK_SIZE=4096
# CONFIG_DISK_FLASH_SECTOR_SIZE=512
# CONFIG_DISK_FLASH_VOLUME_SIZE=65536

# DISK RAM驱动使能及配置
CONFIG_DISK_DRIVER_RAM=y

# DISK SDMMC驱动使能及配置
CONFIG_DISK_DRIVER_SDMMC=y

# 抽象文件系统
CONFIG_LSFS=y
CONFIG_LSFS_FAT=y