# Default recovery_basic config uses CherryUSB.
CONFIG_BOOT_ADB_SYNC=y
CONFIG_BOOT_ADB_SDMMC_RAW=y
CONFIG_BOOT_ADB_SDMMC_FS=y
CONFIG_BOOT_ADB_BACKEND_CHERRYUSB=y
# CONFIG_FS_ENV_MEMORY_MANAGEMENT_USE_PSRAM is not set
CONFIG_BOOT_OTA_PACKAGE=y
CONFIG_BOOT_OTA_SOURCE_TF=y
