/**
 ****************************************************************************************
 *
 * Don't modify this file. It is automatically generated by a script.
 *
 * Author: KeHuatao
 *
 * Copyright (C) ListenAI 2025
 *
 ****************************************************************************************
 */
#include <stdint.h>
#include <string.h>
#include "ls_err.h"
//#include "ls_wifi_type.h"
#include "bt_ipc_api.h"
#include "ipc.h"
#include "mrpc.h"
#include "mrpc_bt_api_msg.h"
#include "mrpc_bt_api_server.h"

ls_err_t btos_send_event_api(btos_task_id task_id, void ** event, btos_msg_t * msg_body, uint32_t msg_body_len, TickType_t time_out)
{
    mrpc_btos_send_event_api_req_t *req;
    mrpc_btos_send_event_api_resp_t resp;

    req = rtos_malloc(sizeof(mrpc_btos_send_event_api_req_t) + msg_body_len);
    if (req == NULL)
        return  LS_FAIL;
    req->hdr.len = sizeof(mrpc_btos_send_event_api_req_t) + msg_body_len;
    if (req->hdr.len > IPC_MSG_BUFFER_SIZE)
        return LS_FAIL;

    req->hdr.id = MRPC_MSG_ID_BTOS_SEND_EVENT_API;
    req->task_id = task_id;
    req->event = *event;
    memcpy(req->data_buffer, msg_body, msg_body_len);
    req->msg_body_len = msg_body_len;
    req->time_out = time_out;
    if (mrpc_msg_send(req, req->hdr.len, &resp))
        return LS_FAIL;
    rtos_free(req);

    return (ls_err_t)resp.hdr.status;
}

ls_err_t btos_send_at_evt_api(btos_task_id task_id, uint16_t msg_id, void * msg_body, uint32_t msg_body_len, TickType_t time_out)
{
    mrpc_btos_send_at_evt_api_req_t *req;
    mrpc_btos_send_at_evt_api_resp_t resp;

    req = rtos_malloc(sizeof(mrpc_btos_send_at_evt_api_req_t) + msg_body_len);
    if (req == NULL)
        return  LS_FAIL;
    req->hdr.len = sizeof(mrpc_btos_send_at_evt_api_req_t) + msg_body_len;
    if (req->hdr.len > IPC_MSG_BUFFER_SIZE)
        return LS_FAIL;

    req->hdr.id = MRPC_MSG_ID_BTOS_SEND_AT_EVT_API;
    req->task_id = task_id;
    req->msg_id = msg_id;
    memcpy(req->data_buffer, msg_body, msg_body_len);
    req->msg_body_len = msg_body_len;
    req->time_out = time_out;
    if (mrpc_msg_send(req, req->hdr.len, &resp))
        return LS_FAIL;
    rtos_free(req);

    return (ls_err_t)resp.hdr.status;
}

ls_err_t btos_send_app_evt_api(btos_task_id task_id, uint16_t msg_id, void * msg_body, uint32_t msg_body_len, TickType_t time_out)
{
    mrpc_btos_send_app_evt_api_req_t *req;
    mrpc_btos_send_app_evt_api_resp_t resp;

    req = rtos_malloc(sizeof(mrpc_btos_send_app_evt_api_req_t) + msg_body_len);
    if (req == NULL)
        return  LS_FAIL;
    req->hdr.len = sizeof(mrpc_btos_send_app_evt_api_req_t) + msg_body_len;
    if (req->hdr.len > IPC_MSG_BUFFER_SIZE)
        return LS_FAIL;

    req->hdr.id = MRPC_MSG_ID_BTOS_SEND_APP_EVT_API;
    req->task_id = task_id;
    req->msg_id = msg_id;
    memcpy(req->data_buffer, msg_body, msg_body_len);
    req->msg_body_len = msg_body_len;
    req->time_out = time_out;
    if (mrpc_msg_send(req, req->hdr.len, &resp))
        return LS_FAIL;
    rtos_free(req);

    return (ls_err_t)resp.hdr.status;
}

ls_err_t ble_gap_set_loc_pub_addr_api(struct out_bd_addr * bd_addr)
{
    mrpc_ble_gap_set_loc_pub_addr_api_req_t req;
    mrpc_ble_gap_set_loc_pub_addr_api_resp_t resp;

    if (sizeof(mrpc_ble_gap_set_loc_pub_addr_api_req_t) > IPC_MSG_BUFFER_SIZE)
        return LS_FAIL;

    req.hdr.id = MRPC_MSG_ID_BLE_GAP_SET_LOC_PUB_ADDR_API;
    req.bd_addr = *bd_addr;
    if (mrpc_msg_send(&req, sizeof(mrpc_ble_gap_set_loc_pub_addr_api_req_t), &resp))
        return LS_FAIL;

    return (ls_err_t)resp.hdr.status;
}

ls_err_t llm_get_local_pub_addr_api(struct out_bd_addr * bd_addr)
{
    mrpc_llm_get_local_pub_addr_api_req_t req;
    mrpc_llm_get_local_pub_addr_api_resp_t resp;

    if (sizeof(mrpc_llm_get_local_pub_addr_api_req_t) > IPC_MSG_BUFFER_SIZE)
        return LS_FAIL;

    req.hdr.id = MRPC_MSG_ID_LLM_GET_LOCAL_PUB_ADDR_API;
    if (mrpc_msg_send(&req, sizeof(mrpc_llm_get_local_pub_addr_api_req_t), &resp))
        return LS_FAIL;
    *bd_addr = resp.bd_addr;

    return (ls_err_t)resp.hdr.status;
}

ls_err_t btos_malloc_api(void ** buffer_ptr, uint32_t size)
{
    mrpc_btos_malloc_api_req_t req;
    mrpc_btos_malloc_api_resp_t resp;

    if (sizeof(mrpc_btos_malloc_api_req_t) > IPC_MSG_BUFFER_SIZE)
        return LS_FAIL;

    req.hdr.id = MRPC_MSG_ID_BTOS_MALLOC_API;
    req.size = size;
    if (mrpc_msg_send(&req, sizeof(mrpc_btos_malloc_api_req_t), &resp))
        return LS_FAIL;
    *buffer_ptr = resp.buffer_ptr;

    return (ls_err_t)resp.hdr.status;
}

ls_err_t btos_free_api(void ** ptr)
{
    mrpc_btos_free_api_req_t req;
    mrpc_btos_free_api_resp_t resp;

    if (sizeof(mrpc_btos_free_api_req_t) > IPC_MSG_BUFFER_SIZE)
        return LS_FAIL;

    req.hdr.id = MRPC_MSG_ID_BTOS_FREE_API;
    req.ptr = *ptr;
    if (mrpc_msg_send(&req, sizeof(mrpc_btos_free_api_req_t), &resp))
        return LS_FAIL;

    return (ls_err_t)resp.hdr.status;
}

ls_err_t lsip_reset_api(void)
{
    mrpc_lsip_reset_api_req_t req;
    mrpc_lsip_reset_api_resp_t resp;

    req.hdr.id = MRPC_MSG_ID_LSIP_RESET_API;
    if (mrpc_msg_send(&req, sizeof(mrpc_lsip_reset_api_req_t), &resp))
        return LS_FAIL;

    return (ls_err_t)resp.hdr.status;
}

