/**
 ****************************************************************************************
 *
 * Don't modify this file. It is automatically generated by a script.
 *
 * Author: KeHuatao
 *
 * Copyright (C) ListenAI 2025
 *
 ****************************************************************************************
 */
#include <stdio.h>
#include <stdint.h>
#include <string.h>
#include "ls_err.h"
//#include "ls_wifi_type.h"
#include "ipc.h"
#include "mrpc.h"
#include "mrpc_bt_api_msg.h"
#include "mrpc_bt_api_server.h"

static void mrpc_btos_send_event_api(void *msg, struct mrpc_resp_msg *resp_msg)
{
    mrpc_btos_send_event_api_req_t *req;
    mrpc_btos_send_event_api_resp_t *resp;

    req = (mrpc_btos_send_event_api_req_t*)msg;
    resp = (mrpc_btos_send_event_api_resp_t*)resp_msg;
    memset(resp, 0, sizeof(mrpc_btos_send_event_api_resp_t));
    req->msg_body = (btos_msg_t *)req->data_buffer;
    resp_msg->len = sizeof(mrpc_btos_send_event_api_resp_t);
    resp_msg->status = btos_send_event_api(req->task_id, &req->event, req->msg_body, req->msg_body_len, req->time_out);
}

static void mrpc_btos_send_at_evt_api(void *msg, struct mrpc_resp_msg *resp_msg)
{
    mrpc_btos_send_at_evt_api_req_t *req;
    mrpc_btos_send_at_evt_api_resp_t *resp;

    req = (mrpc_btos_send_at_evt_api_req_t*)msg;
    resp = (mrpc_btos_send_at_evt_api_resp_t*)resp_msg;
    memset(resp, 0, sizeof(mrpc_btos_send_at_evt_api_resp_t));
    req->msg_body = (void *)req->data_buffer;
    resp_msg->len = sizeof(mrpc_btos_send_at_evt_api_resp_t);
    resp_msg->status = btos_send_at_evt_api(req->task_id, req->msg_id, req->msg_body, req->msg_body_len, req->time_out);
}

static void mrpc_btos_send_app_evt_api(void *msg, struct mrpc_resp_msg *resp_msg)
{
    mrpc_btos_send_app_evt_api_req_t *req;
    mrpc_btos_send_app_evt_api_resp_t *resp;

    req = (mrpc_btos_send_app_evt_api_req_t*)msg;
    resp = (mrpc_btos_send_app_evt_api_resp_t*)resp_msg;
    memset(resp, 0, sizeof(mrpc_btos_send_app_evt_api_resp_t));
    req->msg_body = (void *)req->data_buffer;
    resp_msg->len = sizeof(mrpc_btos_send_app_evt_api_resp_t);
    resp_msg->status = btos_send_app_evt_api(req->task_id, req->msg_id, req->msg_body, req->msg_body_len, req->time_out);
}

static void mrpc_ble_gap_set_loc_pub_addr_api(void *msg, struct mrpc_resp_msg *resp_msg)
{
    mrpc_ble_gap_set_loc_pub_addr_api_req_t *req;
    mrpc_ble_gap_set_loc_pub_addr_api_resp_t *resp;

    req = (mrpc_ble_gap_set_loc_pub_addr_api_req_t*)msg;
    resp = (mrpc_ble_gap_set_loc_pub_addr_api_resp_t*)resp_msg;
    memset(resp, 0, sizeof(mrpc_ble_gap_set_loc_pub_addr_api_resp_t));
    resp_msg->len = sizeof(mrpc_ble_gap_set_loc_pub_addr_api_resp_t);
    resp_msg->status = ble_gap_set_loc_pub_addr_api(&req->bd_addr);
}

static void mrpc_llm_get_local_pub_addr_api(void *msg, struct mrpc_resp_msg *resp_msg)
{
    mrpc_llm_get_local_pub_addr_api_req_t *req;
    mrpc_llm_get_local_pub_addr_api_resp_t *resp;

    req = (mrpc_llm_get_local_pub_addr_api_req_t*)msg;
    resp = (mrpc_llm_get_local_pub_addr_api_resp_t*)resp_msg;
    memset(resp, 0, sizeof(mrpc_llm_get_local_pub_addr_api_resp_t));
    resp_msg->len = sizeof(mrpc_llm_get_local_pub_addr_api_resp_t);
    resp_msg->status = llm_get_local_pub_addr_api(&resp->bd_addr);
}

static void mrpc_btos_malloc_api(void *msg, struct mrpc_resp_msg *resp_msg)
{
    mrpc_btos_malloc_api_req_t *req;
    mrpc_btos_malloc_api_resp_t *resp;

    req = (mrpc_btos_malloc_api_req_t*)msg;
    resp = (mrpc_btos_malloc_api_resp_t*)resp_msg;
    memset(resp, 0, sizeof(mrpc_btos_malloc_api_resp_t));
    resp_msg->len = sizeof(mrpc_btos_malloc_api_resp_t);
    resp_msg->status = btos_malloc_api(&resp->buffer_ptr, req->size);
}

static void mrpc_btos_free_api(void *msg, struct mrpc_resp_msg *resp_msg)
{
    mrpc_btos_free_api_req_t *req;
    mrpc_btos_free_api_resp_t *resp;

    req = (mrpc_btos_free_api_req_t*)msg;
    resp = (mrpc_btos_free_api_resp_t*)resp_msg;
    memset(resp, 0, sizeof(mrpc_btos_free_api_resp_t));
    resp_msg->len = sizeof(mrpc_btos_free_api_resp_t);
    resp_msg->status = btos_free_api(&req->ptr);
}

static void mrpc_lsip_reset_api(void *msg, struct mrpc_resp_msg *resp_msg)
{
    mrpc_lsip_reset_api_req_t *req;
    mrpc_lsip_reset_api_resp_t *resp;

    req = (mrpc_lsip_reset_api_req_t*)msg;
    resp = (mrpc_lsip_reset_api_resp_t*)resp_msg;
    memset(resp, 0, sizeof(mrpc_lsip_reset_api_resp_t));
    resp_msg->len = sizeof(mrpc_lsip_reset_api_resp_t);
    resp_msg->status = lsip_reset_api();
}


mrpc_msg_handler_t mrpc_msg_bt_handlers[MRPC_MSG_ID_BT_MAX - MRPC_MSG_ID_BT_START] =
{
    mrpc_btos_send_event_api,  /*MRPC_MSG_ID_BTOS_SEND_EVENT_API*/
    mrpc_btos_send_at_evt_api,  /*MRPC_MSG_ID_BTOS_SEND_AT_EVT_API*/
    mrpc_btos_send_app_evt_api,  /*MRPC_MSG_ID_BTOS_SEND_APP_EVT_API*/
    mrpc_ble_gap_set_loc_pub_addr_api,  /*MRPC_MSG_ID_BLE_GAP_SET_LOC_PUB_ADDR_API*/
    mrpc_llm_get_local_pub_addr_api,  /*MRPC_MSG_ID_LLM_GET_LOCAL_PUB_ADDR_API*/
    mrpc_btos_malloc_api,  /*MRPC_MSG_ID_BTOS_MALLOC_API*/
    mrpc_btos_free_api,  /*MRPC_MSG_ID_BTOS_FREE_API*/
    mrpc_lsip_reset_api,  /*MRPC_MSG_ID_LSIP_RESET_API*/
    NULL
};