/**
 * @file    Driver_QSPI_IN.h
 * @author  CSK Development Team
 * @brief   Header file for QSPI_IN (Serial Peripheral Interface) Driver definitions
 * @details This file contains all necessary definitions, configuration structures,
 *          and function declarations for the QSPI_IN driver module.
 */

#ifndef _DRIVER_QSPI_IN_H
#define _DRIVER_QSPI_IN_H

#include "Driver_Common.h"

/** @defgroup QSPI_IN
  * @brief QSPI_IN HAL module driver
  * @{
  */
/** @defgroup QSPI_IN_Exported_Constants QSPI_IN Exported Constants
  * @{
  */
/** @defgroup QSPI_IN_DRV_Version QSPI_IN API Version
  * @{
  */
/**
 * @def CSK_QSPI_IN_API_VERSION
 * @brief API version number following major.minor format
 * @details Indicates the application programming interface version required by this driver.
 */
#define CSK_QSPI_IN_API_VERSION CSK_DRIVER_VERSION_MAJOR_MINOR(1,0)  /* API version */
/** @} */ /* End of group QSPI_IN_DRV_Version */
/** @} */ /* End of group QSPI_IN_Exported_Constants */

/** @defgroup QSPI_IN_Exported_Types QSPI_IN Exported Types
  * @{
  */
/**
 * @enum em_QSPI_IN_IrqEvent
 * @brief Interrupt event types generated by QSPI_IN peripheral
 * @var QSPI_IN_IRQ_EVENT_RXFIFOOR    Receive FIFO Overflow/Underflow event
 * @var QSPI_IN_IRQ_EVENT_RXFIFO      Receive FIFO Threshold reached event
 * @var QSPI_IN_IRQ_EVENT_MTK_TRANS_ERR MediaTek transport error event
 * @var QSPI_IN_IRQ_EVENT_END         End of transaction event
 * @var QSPI_IN_IRQ_EVENT_SLVCMD      Slave command completion event
 * @var QSPI_IN_IRQ_EVENT_CRC_ERR     CRC verification error event
 * @var QSPI_IN_IRQ_EVENT_FRAME_START Start of frame detection event
 * @var QSPI_IN_IRQ_EVENT_FRAME_END   End of frame detection event
 * @var QSPI_IN_IRQ_EVENT_LINE_END    End of line detection event
 * @var QSPI_IN_IRQ_EVENT_LINE_START  Start of line detection event
 * @var QSPI_IN_IRQ_EVENT_BUTT        End of enumeration sentinel
 */
typedef enum
{
    QSPI_IN_IRQ_EVENT_RXFIFOOR       = 0,   /*!< Receive FIFO Overflow/Underflow */
    QSPI_IN_IRQ_EVENT_RXFIFO         = 2,   /*!< Receive FIFO Threshold reached */
    QSPI_IN_IRQ_EVENT_MTK_TRANS_ERR  = 3,   /*!< MediaTek transport error */
    QSPI_IN_IRQ_EVENT_END            = 4,   /*!< End of transaction */
    QSPI_IN_IRQ_EVENT_SLVCMD         = 5,   /*!< Slave command completion */
    QSPI_IN_IRQ_EVENT_CRC_ERR        = 6,   /*!< CRC verification error */
    QSPI_IN_IRQ_EVENT_FRAME_START    = 7,   /*!< Start of frame (SOF) */
    QSPI_IN_IRQ_EVENT_FRAME_END      = 8,   /*!< End of frame (EOF) */
    QSPI_IN_IRQ_EVENT_LINE_END       = 9,   /*!< End of line (EOL) */
    QSPI_IN_IRQ_EVENT_LINE_START     = 10,  /*!< Start of line (SOL) */
    QSPI_IN_IRQ_EVENT_BUTT                  /*!< End of enumeration */
} QSPI_IN_emIrqEvent;

/**
 * @enum em_QSPI_IN_SyncMode
 * @brief Synchronization mode selection for QSPI input
 * @var QSPI_IN_SYNC_MODE_SPRD    Standard protocol mode
 * @var QSPI_IN_SYNC_MODE_MTK     MediaTek specific protocol mode
 * @var QSPI_IN_SYNC_MODE_ALL     Combined synchronization modes
 * @var QSPI_IN_SYNC_MODE_BUTT    End of enumeration sentinel
 */
typedef enum {
    QSPI_IN_SYNC_MODE_SPRD = 0,  /*!< Standard protocol mode */
    QSPI_IN_SYNC_MODE_MTK,       /*!< MediaTek specific protocol mode */
    QSPI_IN_SYNC_MODE_ALL,       /*!< Combined synchronization modes */
    QSPI_IN_SYNC_MODE_BUTT       /*!< End of enumeration sentinel */
} QSPI_IN_emSyncMode;

/**
 * @enum em_QSPI_IN_CPOL_CPHA
 * @brief Clock polarity and phase configuration options
 * @var QSPI_IN_CPOL0_CPHA0      Rising edge clock with no phase shift
 * @var QSPI_IN_CPOL0_CPHA1      Rising edge clock with 90° phase shift
 * @var QSPI_IN_CPOL1_CPHA0      Falling edge clock with no phase shift
 * @var QSPI_IN_CPOL1_CPHA1      Falling edge clock with 90° phase shift
 * @var QSPI_IN_CPOL_CPHA_BUTT   End of enumeration sentinel
 */
typedef enum {
    QSPI_IN_CPOL0_CPHA0 = 0,    /*!< Rising edge, no phase shift */
    QSPI_IN_CPOL0_CPHA1,        /*!< Rising edge, 90° phase shift */
    QSPI_IN_CPOL1_CPHA0,        /*!< Falling edge, no phase shift */
    QSPI_IN_CPOL1_CPHA1,        /*!< Falling edge, 90° phase shift */
    QSPI_IN_CPOL_CPHA_BUTT      /*!< End of enumeration sentinel */
} QSPI_IN_emCPOL_CPHA;

typedef enum {
    QSPI_IN_DATA_1LANE = 0,     /*!< Single data line (standard SPI) 1line */
    QSPI_IN_DATA_2LANE,         /*!< Dual data lines (double throughput) 2line */
    QSPI_IN_DATA_4LANE,         /*!< Quad data lines (quadrupled throughput) 4line */
    QSPI_IN_DATA_BUTT           /*!< End of enumeration sentinel */
} QSPI_IN_emDataLane;

/**
 * @struct QSPI_IN_SyncCode_t
 * @brief Synchronization codes used for frame/line detection
 * @var sof Start of Frame code (default: 0xFF0000AB)
 * @var sol Start of Line code (default: 0xFF000080)
 * @var eol End of Line code (default: 0xFF00009D) or data packet marker
 * @var eof End of Frame code (default: 0xFF0000B6)
 */
typedef struct {
    uint32_t sof;               /*!< Start of Frame sync code */
    uint32_t sol;               /*!< Start of Line sync code */
    uint32_t eol;               /*!< End of Line sync code or data packet marker */
    uint32_t eof;               /*!< End of Frame sync code */
} QSPI_IN_SyncCodeDef;

/**
 * @struct QSPI_IN_InitTypeDef
 * @brief Configuration structure for QSPI_IN initialization
 * @var mode Synchronization mode (@ref em_QSPI_IN_SyncMode)
 * @var sync_code Synchronization codes (@ref QSPI_IN_SyncCode_t)
 * @var cp Clock polarity/phase configuration (@ref em_QSPI_IN_CPOL_CPHA)
 * @var lane_num Number of data lanes (1/2/4)
 * @var FrameWidth Image frame width in pixels
 * @var FrameHeight Image frame height in lines
 * @var PixelOffset Clock cycles between HSYNC deactivation and activation
 * @var LineOffset First valid image line offset from VSYNC deactivation
 * @var WindowWidth Active window width in pixels
 * @var WindowHeight Active window height in lines
 * @var is_lsb Least Significant Bit first ordering flag
 * @var data_merge Data merging enable flag
 * @var wire_order Data wire order swapping flag
 * @var BurstThreshold DMA burst threshold size (1/4/8/16)
 */
typedef struct {
    QSPI_IN_emSyncMode mode;            /*!< Synchronization mode selection */
    QSPI_IN_SyncCodeDef  sync_code;     /*!< Synchronization codes configuration */
    QSPI_IN_emCPOL_CPHA cp;             /*!< Clock polarity and phase settings */
    QSPI_IN_emDataLane lane_num;        /*!< Number of data lanes (1/2/4) */

    uint16_t  FrameWidth;               /*!< Image frame width in pixels */
    uint16_t  FrameHeight;              /*!< Image frame height in lines */
    uint16_t  PixelOffset;              /*!< HSYNC timing offset in clock cycles */
    uint16_t  LineOffset;               /*!< VSYNC timing offset in lines */
    uint16_t  WindowWidth;              /*!< Active window width in pixels */
    uint16_t  WindowHeight;             /*!< Active window height in lines */

    bool is_lsb;                        /*!< LSB-first data ordering */
    bool data_merge;                    /*!< Data merging enable */
    bool wire_order;                    /*!< Data wire order swapping */
    uint8_t  BurstThreshold;            /*!< DMA burst threshold size 1/4/8/16 */
    uint32_t clk_in_hz;                 /*!< The clock frequency inputted by the sensor to qspi_in */
} QSPI_IN_InitTypeDef;

/**
 * @typedef QSPI_IN_SignalEvent_t
 * @brief Event callback function pointer type
 * @param[in] event QSPI interrupt event (@ref em_QSPI_IN_IrqEvent)
 * @param[in] param User-defined parameter passed with event notification
 * @note Must be implemented by application layer for event handling
 */
typedef void (*QSPI_IN_SignalEvent_t)(QSPI_IN_emIrqEvent event, uint32_t param);
/** @} */ /* End of group QSPI_IN_Exported_Types */

/* Exported functions --------------------------------------------------------*/
/** @defgroup QSPI_IN_Exported_Functions QSPI_IN Exported Functions
  * @{
  */
/**
 * @fn CSK_DRIVER_VERSION QSPI_IN_GetVersion(void)
 * @brief Retrieves QSPI_IN driver version information
 * @return Driver version number (@ref CSK_DRIVER_VERSION)
 * @details Returns compiled-in version information for compatibility checking
 */
CSK_DRIVER_VERSION QSPI_IN_GetVersion(void);

/**
 * @fn void* QSPI_IN0(void)
 * @brief Obtains instance handle for primary QSPI_IN controller
 * @return Opaque handle to QSPI_IN instance 0 resources
 * @details Used for multi-instance systems where separate controllers exist
 */
void* QSPI_IN0(void);

/**
 * @fn uint32_t QSPI_IN0_Buf(void)
 * @brief Gets physical address of QSPI_IN buffer memory region
 * @return Physical address of QSPI_IN buffer
 * @details Returns base address of main data buffer used by the peripheral
 */
uint32_t QSPI_IN0_Buf(void);

/**
 * @fn int32_t QSPI_IN_Initialize(void *pDev, void *pCallback, QSPI_IN_InitTypeDef *pCfg)
 * @brief Initializes QSPI_IN device with specified parameters
 * @param[out] pDev Opaque device handle returned after initialization
 * @param[in] callback Event callback function (@ref QSPI_IN_SignalEvent_t)
 * @param[in] pCfg Configuration structure (@ref QSPI_IN_InitTypeDef)
 * @return Negative error code on failure, non-negative status code on success
 * @details Allocates resources, sets operational parameters, and registers event handler
 */
int32_t QSPI_IN_Initialize(void *pDev, QSPI_IN_SignalEvent_t callback, QSPI_IN_InitTypeDef *pCfg);

/**
 * @fn int32_t QSPI_IN_Uninitialize(void *pDev)
 * @brief Uninitializes and releases QSPI_IN device resources
 * @param[in] pDev Device handle obtained from successful initialization
 * @return CSK_DRIVER_OK if successful, negative error code otherwise
 * @details Frees allocated resources and disables peripheral clocks
 */
int32_t QSPI_IN_Uninitialize(void *pDev);

/**
 * @fn int32_t QSPI_IN_Start(void *pDev)
 * @brief Starts QSPI_IN processing operation
 * @param[in] pDev Device handle from successful initialization
 * @return CSK_DRIVER_OK if successful, negative error code otherwise
 * @details Begins data capture and processing based on current configuration
 */
int32_t QSPI_IN_Start(void *pDev);

/**
 * @fn int32_t QSPI_IN_Stop(void *pDev)
 * @brief Stops QSPI_IN processing and releases resources
 * @param[in] pDev Device handle from successful initialization
 * @return CSK_DRIVER_OK if successful, negative error code otherwise
 * @details Aborts current operation and returns hardware to idle state
 */
int32_t QSPI_IN_Stop(void *pDev);

/** @} */ /* End of group QSPI_IN_Exported_Functions */
/**
  * @}
  */ /* End of group QSPI_IN */
#endif /* __DRIVER_QSPI_IN_H */
