/*!
 * @file Driver_DVP.h
 * @brief Digital Video Processor (DVP) Driver Interface
 *        This file contains the interface definitions for the CSK DVP peripheral driver.
 *        It provides functionality for video capture, format conversion, and timing control.
 */
#ifndef DRIVER_DVP_H
#define DRIVER_DVP_H

#include "Driver_Common.h"

/** @defgroup DVP
  * @brief DVP HAL module driver
  * @{
  */

/* Exported constants --------------------------------------------------------*/
/** @defgroup DVP_Exported_Constants DVP Exported Constants
  * @{
  */

/** @defgroup DVP_API_Version DVP API Version
  * @{
  */

/**
 * @def CSK_DVP_API_VERSION
 * @brief API version number following major.minor format
 */
#define CSK_DVP_API_VERSION CSK_DRIVER_VERSION_MAJOR_MINOR(1,0) /*!< API version */
/** @} */ /* End of group DVP_API_Version */

/**
  * @}
  */ /* End of group DVP_Exported_Constants */

/* Exported types ------------------------------------------------------------*/
/** @defgroup DVP_Exported_Types DVP Exported Types
  * @{
  */

/**
 * @enum DVP_emPol
 * @brief Signal polarity configuration options for DVP synchronization signals
 * @var DVP_POL_RISING Signal effective on rising edge
 * @var DVP_POL_FALLING Signal effective on falling edge
 */
typedef enum
{
    DVP_POL_RISING         = 0x00U,  /*!< Signal polarity is effective on the rising edge  */
    DVP_POL_FALLING        = 0x01U,  /*!< Signal polarity is effective on the falling edge */
    DVP_POL_BUTT
} DVP_emPol;

/**
 * @enum DVP_emDataAlign
 * @brief Data bus alignment configuration options
 * @var DVP_DATA_ALIGN_RIGHT Right-aligned data placement (bit7~0)
 * @var DVP_DATA_ALIGN_LEFT Left-aligned data placement (bit11~4)
 */
typedef enum
{
    DVP_DATA_ALIGN_RIGHT   = 0x00U,  /*!< Keep data right aligned (bit7~0) */
    DVP_DATA_ALIGN_LEFT    = 0x01U,  /*!< Keep data left aligned (bit11~4) */
    DVP_DATA_ALIGN_BUTT
} DVP_emDataAlign;

/**
 * @enum DVP_emInputFormat
 * @brief Supported input frame formats for video capture
 * @var DVP_INPUT_FORM_YUV422_Y0CBY1CR YUV422 YUYV format
 * @var DVP_INPUT_FORM_YUV422_CBY0CRY1 YUV422 UYVY format
 * @var DVP_INPUT_FORM_YUV422_Y0CRY1CB YUV422 YVYU format
 * @var DVP_INPUT_FORM_YUV422_CRY0CBY1 YUV422 VYUY format
 * @var DVP_INPUT_FORM_YUV444_Y0CBCR YUV444 full chroma format
 * @var DVP_INPUT_FORM_RGB565_RGGB RGB565 RRRRRGGG_GGGBBBBB format
 * @var DVP_INPUT_FORM_RGB565_GBRG RGB565 GGGBBBBB_RRRRRGGG format
 * @var DVP_INPUT_FORM_RGB888 RGB888 full color format
 */
typedef enum
{
    DVP_INPUT_FORM_YUV422_Y0CBY1CR       = 0x00U,  /*!< YUV422 YUYV   */
    DVP_INPUT_FORM_YUV422_CBY0CRY1       = 0x01U,  /*!< YUV422 UYVY   */
    DVP_INPUT_FORM_YUV422_Y0CRY1CB       = 0x02U,  /*!< YUV422 YVYU   */
    DVP_INPUT_FORM_YUV422_CRY0CBY1       = 0x03U,  /*!< YUV422 VYUY   */
    DVP_INPUT_FORM_YUV420_Y0CBY1Y2CRY3   = 0x04U,  /*!< invalid       */
    DVP_INPUT_FORM_YUV420_CBY0Y1CRY2Y3   = 0x05U,  /*!< invalid       */
    DVP_INPUT_FORM_YUV420_Y0Y1CBY2Y3CR   = 0x06U,  /*!< invalid       */
    DVP_INPUT_FORM_YUV444_Y0CBCR         = 0x07U,  /*!< YUV444 YUV    */
    DVP_INPUT_FORM_LUMINA_12BIT          = 0x08U,  /*!< invalid       */
    DVP_INPUT_FORM_LUMINA_10BIT          = 0x09U,  /*!< invalid       */
    DVP_INPUT_FORM_LUMINA_8BIT           = 0x0AU,  /*!< RAW8          */
    DVP_INPUT_FORM_RGB555_RGGB           = 0x10U,  /*!< RGB555 0RRRRRGG_GGGBBBBB */
    DVP_INPUT_FORM_RGB555_GBRG           = 0x11U,  /*!< RGB555 GGGBBBBB_0RRRRRGG */
    DVP_INPUT_FORM_RGB565_RGGB           = 0x12U,  /*!< RGB565 RRRRRGGG_GGGBBBBB */
    DVP_INPUT_FORM_RGB565_GBRG           = 0x13U,  /*!< RGB565 GGGBBBBB_RRRRRGGG */
    DVP_INPUT_FORM_RGB888                = 0x14U,  /*!< RGB888        */
    DVP_INPUT_FORM_BUTT
} DVP_emInputFormat;

/**
 * @enum DVP_emIrqEvent
 * @brief Interrupt events generated by the DVP module
 * @var DVP_IRQ_EVENT_DMA_VIC_SINGLE Single DMA VIC event
 * @var DVP_IRQ_EVENT_DMA_VIC_REQ DMA VIC request event
 * @var DVP_IRQ_EVENT_FIFO_UNFLOW FIFO underflow interrupt
 * @var DVP_IRQ_EVENT_FIFO_OVFLOW FIFO overflow interrupt
 * @var DVP_IRQ_EVENT_FIFO_RD_EMPTY Read empty FIFO interrupt
 * @var DVP_IRQ_EVENT_FIFO_WR_FULL Write full FIFO interrupt
 * @var DVP_IRQ_EVENT_EOF End-of-frame detection
 * @var DVP_IRQ_EVENT_SOF Start-of-frame detection
 * @var DVP_IRQ_EVENT_EOF_CNT_ABNOR End-of-frame count abnormality
 * @var DVP_IRQ_EVENT_FRAME_FINISH Frame completion notification
 * @var DVP_IRQ_EVENT_H_SYNC_ABNOR Horizontal sync abnormality
 * @var DVP_IRQ_EVENT_PIXEL_ABNOR Pixel data abnormality
 */
typedef enum
{
    DVP_IRQ_EVENT_DMA_VIC_SINGLE      = 0x00U,  /*!< DVP dma_vic_single  */
    DVP_IRQ_EVENT_DMA_VIC_REQ         = 0x01U,  /*!< DVP dma_vic_req     */
    DVP_IRQ_EVENT_FIFO_UNFLOW         = 0x02U,  /*!< DVP fifo_unflow     */
    DVP_IRQ_EVENT_FIFO_OVFLOW         = 0x03U,  /*!< DVP fifo_ovflow     */
    DVP_IRQ_EVENT_FIFO_RD_EMPTY       = 0x04U,  /*!< DVP fifo_rd_empty   */
    DVP_IRQ_EVENT_FIFO_WR_FULL        = 0x05U,  /*!< DVP fifo_wr_full    */
    DVP_IRQ_EVENT_EOF                 = 0x06U,  /*!< DVP eof             */
    DVP_IRQ_EVENT_SOF                 = 0x07U,  /*!< DVP sof             */
    DVP_IRQ_EVENT_EOF_CNT_ABNOR       = 0x08U,  /*!< DVP EOF_CNT_ABNOR   */
    DVP_IRQ_EVENT_FRAME_FINISH        = 0x09U,  /*!< DVP FRAME_FINISH   */
    DVP_IRQ_EVENT_H_SYNC_ABNOR        = 0x0AU,  /*!< DVP H_SYNC_ABNOR   */
    DVP_IRQ_EVENT_PIXEL_ABNOR         = 0x0BU,  /*!< DVP PIXEL_ABNOR   */
    DVP_IRQ_EVENT_BUTT                          /*!< End of enumeration */
} DVP_emIrqEvent;

/**
 * @struct DVP_InitTypeDef
 * @brief Initialization structure for DVP configuration
 * @var FrameWidth Image frame width in pixels
 * @var FrameHeight Image frame height in lines
 * @var PixelOffset Clock cycles between h_sync deactivation/activation
 * @var LineOffset First valid line offset from v_sync deactivation
 * @var InputFormat Image sensor input format
 * @var DataAlign Data bus alignment (right/left)
 * @var VSPolarity Vertical synchronization polarity
 * @var HSPolarity Horizontal synchronization polarity
 * @var PCKPolarity Pixel clock polarity
 * @var BurstThreshold DMA burst threshold (1/4/8/16)
 */
typedef struct
{
    uint16_t            FrameWidth;     /*!< Specifies the width of frame in pixels.  1~8191 */
    uint16_t            FrameHeight;    /*!< Specifies the height of frame in lines.  1~8191 */
    uint16_t            PixelOffset;    /*!< Specifies the clock cycles between deactivation and activation of the h_sync.  0~8191 */
    uint16_t            LineOffset;     /*!< Specifies the first valid image line offset from the deactivation of the v_sync. 0~8191 */
    DVP_emInputFormat   InputFormat;    /*!< Specifies the input format of image sensor. */
    DVP_emDataAlign     DataAlign;      /*!< Specifies the data on the bus aligned to right or left. */
    DVP_emPol           VSPolarity;     /*!< Specifies the Vertical synchronization polarity: High or Low. This parameter can be a value of @ref DVP_emPol */
    DVP_emPol           HSPolarity;     /*!< Specifies the Horizontal synchronization polarity: High or Low. This parameter can be a value of @ref DVP_emPol */
    DVP_emPol           PCKPolarity;    /*!< Specifies the Pixel clock polarity: Falling or Rising. This parameter can be a value of @ref DVP_emPol */
    uint8_t             BurstThreshold; /*!< DMA burst threshold 1/4/8/16 */
} DVP_InitTypeDef;

/**
 * @typedef CSK_DVP_SignalEvent_t
 * @brief Event callback function type for DVP interrupts
 * @param[in] event DVP event notification mask (@ref DVP_emIrqEvent)
 * @param[in] param User-defined parameter passed with the event
 * @note The callback function should follow this exact signature
 */
typedef void (*DVP_SignalEvent_t)(DVP_emIrqEvent event, uint32_t param);
/**
  * @}
  */ /* End of group DVP_Exported_Types */

/* Exported functions --------------------------------------------------------*/
/** @defgroup DVP_Exported_Functions DVP Exported Functions
  * @{
  */

/**
 * @fn CSK_DRIVER_VERSION DVP_GetVersion(void)
 * @brief Get the DVP driver API version
 * @return Returns the API version number (@ref CSK_DRIVER_VERSION)
 */
CSK_DRIVER_VERSION DVP_GetVersion(void);

/**
 * @fn void* DVP0(void)
 * @brief Get default DVP device instance
 * @return Pointer to default DVP device instance
 */
void* DVP0(void);

/**
 * @fn uint32_t DVP0_Buf(void)
 * @brief Get buffer address for default DVP device
 * @return 32-bit address of DVP buffer memory
 */
uint32_t DVP0_Buf(void);

/**
 * @fn int32_t DVP_Initialize(void *pDvpDev, void *pCallback, DVP_InitTypeDef *pCfg)
 * @brief Initialize the DVP device with specified configuration
 * @param[in] pDev Pointer to DVP device instance
 * @param[in] pCallback Event callback function (@ref CSK_DVP_SignalEvent_t)
 * @param[in] pCfg Pointer to initialization configuration (@ref DVP_InitTypeDef)
 * @return CSK_DRIVER_OK on success, negative error code otherwise
 */
int32_t DVP_Initialize(void *pDev, DVP_SignalEvent_t callback, DVP_InitTypeDef *pCfg);

/**
 * @fn int32_t DVP_Uninitialize(void *pDvpDev)
 * @brief Uninitialize and reset the DVP device
 * @param[in] pDvpDev Pointer to DVP device instance
 * @return CSK_DRIVER_OK on success, negative error code otherwise
 */
int32_t DVP_Uninitialize(void *pDev);

/**
 * @fn int32_t DVP_Start(void *pDvpDev)
 * @brief Start video capture operation
 * @param[in] pDvpDev Pointer to DVP device instance
 * @return CSK_DRIVER_OK on success, negative error code otherwise
 */
int32_t DVP_Start(void *pDev);

/**
 * @fn int32_t DVP_Stop(void *pDvpDev)
 * @brief Stop video capture and release resources
 * @param[in] pDvpDev Pointer to DVP device instance
 * @return CSK_DRIVER_OK on success, negative error code otherwise
 */
int32_t DVP_Stop(void *pDev);

/**
 * @fn int32_t DVP_EnableClockout(uint32_t freq_hz)
 * @brief Enable DVP clock output with specified frequency
 * @param[in] freq_hz Desired output frequency in Hertz
 * @details Frequency range clamped between min/max limits (47KHz-200MHz).
 * @return CSK_DRIVER_OK on success, negative error code otherwise
 */
int32_t DVP_EnableClockout(uint32_t freq_hz);

/**
 * @fn int32_t DVP_DisableClockout(void)
 * @brief Disable DVP clock output
 * @return CSK_DRIVER_OK on success, negative error code otherwise
 */
int32_t DVP_DisableClockout(void);

/** @} */ /* End of group DVP_Exported_Functions */
/**
  * @}
  */ /* End of group DVP */

#endif /* DRIVER_DVP_H */
