/**
 * @file    Driver_JPEG.h
 * @author  USER
 * @brief   Header file for JPEG codec driver definitions
 * @details This file contains all necessary definitions, configuration structures,
 *          and function declarations for the JPEG compression/decompression hardware module.
 */

#ifndef __DRIVER_JPEG_H__
#define __DRIVER_JPEG_H__

#include "Driver_Common.h"

#ifdef __cplusplus
extern "C" {
#endif

/** @defgroup JPEG
  * @brief JPEG HAL module driver
  * @{
  */
/** @defgroup JPEG_Exported_Constants JPEG Exported Constants
  * @{
  */
/** @defgroup JPEG_API_Version JPEG API Version
  * @{
  */
/**
 * @def CSK_JPEG_API_VERSION
 * @brief API version number definition
 * @details Formatted as major.minor using CSK_DRIVER_VERSION_MAJOR_MINOR macro
 * @note Indicates minimum required driver version for compatibility
 */
#define CSK_JPEG_API_VERSION CSK_DRIVER_VERSION_MAJOR_MINOR(1,0)         /*!< API version */
/** @} */ /* End of group JPEG_API_Version */
/** @} */ /* End of group JPEG_Exported_Constants */

/* Exported types ------------------------------------------------------------*/
/** @defgroup JPEG_Exported_Types JPEG Exported Types
  * @{
  */
/**
 * @enum Jpeg_emMode
 * @brief Operation mode selection for JPEG engine
 * @var JPEG_MODE_ENCODE Encode input image to JPEG stream
 * @var JPEG_MODE_DECODE Decode JPEG stream to output image
 * @var JPEG_MODE_BUTT End of enumeration list marker
 */
typedef enum
{
    JPEG_MODE_ENCODE  = 0x00U,        ///< Encoding mode (image->JPEG)
    JPEG_MODE_DECODE  = 0x01U,       ///< Decoding mode (JPEG->image)
    JPEG_MODE_BUTT                  ///< End of enumeration sentinel
}Jpeg_emMode;

/**
 * @enum Jpeg_emFormatIn
 * @brief Input data format selection for decoding mode
 * @var JPEG_DECODE_IN_FORMAT_YUV422 YUV422 planar format
 * @var JPEG_DECODE_IN_FORMAT_YUV420 YUV420 planar format
 * @var JPEG_DECODE_IN_FORMAT_YUV444 YUV444 planar format
 * @var JPEG_DECODE_IN_FORMAT_YUV411 YUV411 planar format
 * @var JPEG_DECODE_IN_FORMAT_GRAY Grayscale format
 * @var JPEG_DECODE_IN_FORMAT_BUTT End of enumeration list marker
 */
typedef enum
{
    JPEG_DECODE_IN_FORMAT_YUV422  = 0x00U,    ///< YUV422 Planar
    JPEG_DECODE_IN_FORMAT_YUV420  = 0x01U,    ///< YUV420 Planar (default)
    JPEG_DECODE_IN_FORMAT_YUV444  = 0x02U,    ///< YUV444 Planar
    JPEG_DECODE_IN_FORMAT_YUV411  = 0x03U,    ///< YUV411 Planar
    JPEG_DECODE_IN_FORMAT_GRAY    = 0x04U,    ///< Grayscale Image
    JPEG_DECODE_IN_FORMAT_BUTT                    ///< End of enumeration sentinel
}Jpeg_emFormatIn;

/**
 * @enum Jpeg_emtFormatOut
 * @brief Output data format selection for decoding mode
 * @var JPEG_DECODE_OUT_FORMAT_YUV422 YUV422 planar format
 * @var JPEG_DECODE_OUT_FORMAT_RGB RGB888 format
 * @var JPEG_DECODE_OUT_FORMAT_BUTT End of enumeration list marker
 */
typedef enum
{
    JPEG_DECODE_OUT_FORMAT_YUV422  = 0x00U,    ///< YUV422 Planar
    JPEG_DECODE_OUT_FORMAT_RGB     = 0x01U,    ///< RGB888 Format
    JPEG_DECODE_OUT_FORMAT_BUTT               ///< End of enumeration sentinel
}Jpeg_emtFormatOut;

/**
 * @enum Jpeg_emIrqEvent
 * @brief Interrupt event types generated by JPEG engine
 * @var JPEG_IRQ_EVENT_CODEC_DONE Codec operation completed
 * @var JPEG_IRQ_EVENT_PDMA_DONE PDMA transfer completed
 * @var JPEG_IRQ_EVENT_EDMA_DONE EDMA transfer completed
 * @var JPEG_IRQ_EVENT_BUTT End of enumeration list marker
 */
typedef enum
{
    JPEG_IRQ_EVENT_CODEC_DONE      = 0x00U,      ///< Codec operation complete interrupt
    JPEG_IRQ_EVENT_PDMA_DONE       = 0x01U,      ///< PDMA transfer completion interrupt
    JPEG_IRQ_EVENT_EDMA_DONE       = 0x02U,      ///< EDMA transfer completion interrupt
    JPEG_IRQ_EVENT_BUTT                      ///< End of enumeration sentinel
}Jpeg_emIrqEvent;

/**
 * @struct Jpeg_InitTypeDef
 * @brief Configuration structure for JPEG device initialization
 * @var mode Operation mode (@ref Jpeg_emMode)
 * @var format_in Input data format (@ref Jpeg_emFormatIn) - DECODE only
 * @var format_out Output data format (@ref Jpeg_emtFormatOut) - DECODE only
 * @var pixel_size Image data size in bytes per pixel
 * @var ecs_size Excessive Coefficient Set buffer size in bytes
 * @var src_size Source image buffer size in bytes
 * @var img_width Image width in pixels
 * @var img_height Image height in pixels
 * @var img_width_align Aligned image width (multiple of MCU width)
 * @var img_height_align Aligned image height (multiple of MCU height)
 * @var rst_enable Restart marker enable flag
 * @var rst_num Number of MCUs between restart markers
 * @var sampling_h Horizontal chroma subsampling factor (block size)
 * @var sampling_v Vertical chroma subsampling factor (block size)
 * @var qt_index Quantization table selection indexes [luma][cb][cr]
 * @var ht_index Huffman table selection indexes [DC][AC] per component
 */
typedef struct
{
    Jpeg_emMode  mode;                          ///< Operation mode (encode/decode)
    Jpeg_emFormatIn  format_in;              ///< Input format (decode only)
    Jpeg_emtFormatOut  format_out;           ///< Output format (decode only)
    uint32_t pixel_size;                     // byte
    uint32_t ecs_size;                       // byte
    uint32_t src_size;                       // byte
    uint16_t img_width;                      ///< Image width in pixels
    uint16_t img_height;                    ///< Image height in pixels
    uint16_t img_width_align;                ///< Aligned width (MCU multiple)
    uint16_t img_height_align;               ///< Aligned height (MCU multiple)
    uint8_t rst_enable;                      ///< Restart marker enable flag
    uint8_t rst_num;                         ///< MCUs between restart markers
    uint8_t sampling_h;                      ///< Horizontal chroma subsampling (block size)
    uint8_t sampling_v;                     ///< Vertical chroma subsampling (block size)
    uint8_t qt_index[4];                    ///< Quantization table indexes [L][Cb][Cr]
    uint8_t ht_index[4];                    ///< Huffman table indexes [DC][AC] per component
}Jpeg_InitTypeDef;

/**
 * @typedef Jpeg_SignalEvent_t
 * @brief Event callback function pointer type
 * @param[in] event JPEG interrupt event (@ref Jpeg_emIrqEvent)
 * @param[in] param User-defined parameter passed with event notification
 * @note Must be implemented by application layer for event handling
 */
typedef void (*Jpeg_SignalEvent_t)(Jpeg_emIrqEvent event, uint32_t param);
/** @} */ /* End of group JPEG_Exported_Types */

/* Exported functions --------------------------------------------------------*/
/** @defgroup JPEG_Exported_Functions JPEG Exported Functions
  * @{
  */
/**
 * @fn CSK_DRIVER_VERSION Jpeg_GetVersion(void)
 * @brief Retrieves JPEG driver version information
 * @return Driver version number (@ref CSK_DRIVER_VERSION)
 * @details Returns compiled-in version information for compatibility checking
 */
CSK_DRIVER_VERSION Jpeg_GetVersion(void);

/**
 * @fn int32_t Jpeg_Initialize(void *pJpegDev, void *pCallback, Jpeg_InitTypeDef *pCfg)
 * @brief Initializes JPEG device with specified parameters
 * @param[out] pJpegDev Opaque device handle returned after initialization
 * @param[in] pCallback Event callback function (@ref Jpeg_SignalEvent_t)
 * @param[in] pCfg Configuration structure (@ref Jpeg_InitTypeDef)
 * @return Negative error code on failure, non-negative status code on success
 * @details Allocates resources, sets operational parameters, and registers event handler
 */
int32_t Jpeg_Initialize(void *pJpegDev, void *pCallback, Jpeg_InitTypeDef *pCfg);

/**
 * @fn int32_t Jpeg_Uninitialize(void *pJpegDev)
 * @brief Uninitializes and releases JPEG device resources
 * @param[in] pJpegDev Device handle obtained from successful initialization
 * @return CSK_DRIVER_OK if successful, negative error code otherwise
 * @details Frees allocated resources and disables peripheral clocks
 */
int32_t Jpeg_Uninitialize(void *pJpegDev);

/**
 * @fn int32_t Jpeg_Start(void *pJpegDev)
 * @brief Starts JPEG processing operation
 * @param[in] pJpegDev Device handle from successful initialization
 * @return CSK_DRIVER_OK if successful, negative error code otherwise
 * @details Begins encoding or decoding operation based on current configuration
 */
int32_t Jpeg_Start(void *pJpegDev);

/**
 * @fn int32_t Jpeg_Stop(void *pJpegDev)
 * @brief Stops JPEG processing and releases resources
 * @param[in] pJpegDev Device handle from successful initialization
 * @return CSK_DRIVER_OK if successful, negative error code otherwise
 * @details Aborts current operation and returns hardware to idle state
 */
int32_t Jpeg_Stop(void *pJpegDev);

/**
 * @fn void Jpeg_Reset(void)
 * @brief Hard resets JPEG module to default state
 * @details Forces immediate reset of JPEG hardware logic
 */
void Jpeg_Reset(void);

/**
 * @fn void* Jpeg0(void)
 * @brief Obtains instance handle for primary JPEG controller
 * @return Opaque handle to JPEG instance 0 resources
 * @details Used for multi-instance systems where separate controllers exist
 */
void* Jpeg0(void);

/**
 * @fn uint32_t Jpeg0_PixelBuf(void)
 * @brief Gets physical address of pixel buffer memory region
 * @return Physical address of pixel buffer
 * @details Returns base address of main image storage buffer
 */
uint32_t Jpeg0_PixelBuf(void);

/**
 * @fn uint32_t Jpeg0_ECSBuf(void)
 * @brief Gets physical address of Excessive Coefficient Set buffer
 * @return Physical address of ECS buffer
 * @details Returns base address of coefficient buffer used during encoding
 */
uint32_t Jpeg0_ECSBuf(void);

/**
 * @fn uint32_t Jpeg0_EncodeQuanBuf(void)
 * @brief Gets physical address of encoding quantization tables
 * @return Physical address of quantization tables
 * @details Returns base address of quantization tables used for encoding
 */
uint32_t Jpeg0_EncodeQuanBuf(void);

/**
 * @fn uint32_t Jpeg0_EncodeHuffBuf(void)
 * @brief Gets physical address of encoding Huffman tables
 * @return Physical address of Huffman tables
 * @details Returns base address of Huffman tables used for encoding
 */
uint32_t Jpeg0_EncodeHuffBuf(void);

/**
 * @fn uint32_t Jpeg0_DecodeMinBuf(void)
 * @brief Gets physical address of decoding minCode tables
 * @return Physical address of minCode tables
 * @details Returns base address of minimum code tables used for decoding
 */
uint32_t Jpeg0_DecodeMinBuf(void);

/**
 * @fn uint32_t Jpeg0_DecodeBaseBuf(void)
 * @brief Gets physical address of decoding base tables
 * @return Physical address of base tables
 * @details Returns base address of base tables used for decoding
 */
uint32_t Jpeg0_DecodeBaseBuf(void);

/**
 * @fn uint32_t Jpeg0_DecodeSymBuf(void)
 * @brief Gets physical address of decoding symbol tables
 * @return Physical address of symbol tables
 * @details Returns base address of symbol tables used for decoding
 */
uint32_t Jpeg0_DecodeSymBuf(void);
/** @} */ /* End of group JPEG_Exported_Functions */
/**
  * @}
  */ /* End of group JPEG */

#ifdef __cplusplus
}
#endif

#endif /* __DRIVER_JPEG_H__ */
