#pragma once

#define ACOMP_PALM_MAX_RESULT_CNT   (10)
#define ACOMP_PALM_MAX_ALIGN_CNT    (5)
#define ACOMP_PALM_MAX_FEATURE_CNT  (256)

typedef enum {
    PARAM_PALM_NONE = 0,

    PARAM_PALM_DETECT_BEGIN = 100000,
    PARAM_PALM_DETECT_OUT_THRES = 100001,
    PARAM_PALM_DETECT_PROTHRES = 100002,
    PARAM_PALM_DETECT_NMSTHRES = 100003,
    PARAM_PALM_DETECT_PIXESIZE = 100004,
    PARAM_PALM_DETECT_END,

    PARAM_PALM_VERIFY_BEGIN = 200000,
    PARAM_PALM_VERIFY_THRES = 200001,
    PARAM_PALM_VERIFY_REGU_A = 200002,
    PARAM_PALM_VERIFY_REGU_B = 200003,
    PARAM_PALM_VERIFY_END,

    PARAM_PALM_MAX = 0XFFFFFFFF,
} acomp_palm_params_e;

typedef enum {
    ACOMP_PALM_PIX_FMT_BGR888 = 0,
    ACOMP_PALM_PIX_FMT_YUV422_YUYV_PACKED = 1,
    ACOMP_PALM_PIX_FMT_RGB565 = 2,
    ACOMP_PALM_PIX_FMT_GRAY = 3,
    ACOMP_PALM_PIX_FMT_MAX = 0XFFFFFFFF,
} acomp_palm_pixel_format_t;
