#pragma once

#include "IOMuxManager.h"

#define LISA_CP_LOG_UART_RX_PORT        CSK_IOMUX_PAD_A
#define LISA_CP_LOG_UART_RX_PIN         2
#define LISA_CP_LOG_UART_RX_FUNC        CSK_IOMUX_FUNC_ALTER2

#define LISA_CP_LOG_UART_TX_PORT        CSK_IOMUX_PAD_A
#define LISA_CP_LOG_UART_TX_PIN         3
#define LISA_CP_LOG_UART_TX_FUNC        CSK_IOMUX_FUNC_ALTER2


#define LISA_AP_LOG_UART_TX_PORT        CSK_IOMUX_PAD_B
#define LISA_AP_LOG_UART_TX_PIN         2
#define LISA_AP_LOG_UART_TX_FUNC        CSK_IOMUX_FUNC_ALTER3


#define LISA_DISPLAY_SPI_CS_PORT        CSK_IOMUX_PAD_A
#define LISA_DISPLAY_SPI_CS_PIN         22
#define LISA_DISPLAY_SPI_CS_FUNC        CSK_IOMUX_FUNC_DEFAULT

#define LISA_DISPLAY_SPI_SDA_PORT       CSK_IOMUX_PAD_A
#define LISA_DISPLAY_SPI_SDA_PIN        24
#define LISA_DISPLAY_SPI_SDA_FUNC       CSK_IOMUX_FUNC_ALTER6
#define LISA_DISPLAY_SPI_DEV            SPI1()

#define LISA_DISPLAY_SPI_DC_PORT        CSK_IOMUX_PAD_A
#define LISA_DISPLAY_SPI_DC_PIN         23
#define LISA_DISPLAY_SPI_DC_FUNC        CSK_IOMUX_FUNC_DEFAULT

#define LISA_DISPLAY_SPI_CLK_PORT       CSK_IOMUX_PAD_A
#define LISA_DISPLAY_SPI_CLK_PIN        25
#define LISA_DISPLAY_SPI_CLK_FUNC       CSK_IOMUX_FUNC_ALTER6

#define LISA_DISPLAY_BL_PWM_PORT        CSK_IOMUX_PAD_A
#define LISA_DISPLAY_BL_PWM_PIN         21
#define LISA_DISPLAY_BL_PWM_FUNC        CSK_IOMUX_FUNC_ALTER12
#define LISA_DISPLAY_BL_CHANNEL         1

#define LISA_DISPLAY_RESET_PORT         CSK_IOMUX_PAD_B
#define LISA_DISPLAY_RESET_PIN          9
#define LISA_DISPLAY_RESET_FUNC         CSK_IOMUX_FUNC_DEFAULT

#define LISA_DISPLAY_TE_PORT            CSK_IOMUX_PAD_A
#define LISA_DISPLAY_TE_PIN             27
#define LISA_DISPLAY_TE_FUNC            CSK_IOMUX_FUNC_DEFAULT


#define LISA_CAMERA_I2C_SDA_PORT        CSK_IOMUX_PAD_B
#define LISA_CAMERA_I2C_SDA_PIN         6
#define LISA_CAMERA_I2C_SDA_FUNC        CSK_IOMUX_FUNC_ALTER8

#define LISA_CAMERA_I2C_SCL_PORT        CSK_IOMUX_PAD_B
#define LISA_CAMERA_I2C_SCL_PIN         7
#define LISA_CAMERA_I2C_SCL_FUNC        CSK_IOMUX_FUNC_ALTER8

#define LISA_CAMERA_MCLK_PORT           CSK_IOMUX_PAD_A
#define LISA_CAMERA_MCLK_PIN            26
#define LISA_CAMERA_MCLK_FUNC           CSK_IOMUX_FUNC_ALTER16

#define LISA_CAMERA_DVP_HSYNC_PORT      CSK_IOMUX_PAD_A
#define LISA_CAMERA_DVP_HSYNC_PIN       10
#define LISA_CAMERA_DVP_HSYNC_FUNC      CSK_IOMUX_FUNC_ALTER16

#define LISA_CAMERA_DVP_VSYNC_PORT      CSK_IOMUX_PAD_A
#define LISA_CAMERA_DVP_VSYNC_PIN       11
#define LISA_CAMERA_DVP_VSYNC_FUNC      CSK_IOMUX_FUNC_ALTER16

#define LISA_CAMERA_DVP_PCLK_PORT       CSK_IOMUX_PAD_A
#define LISA_CAMERA_DVP_PCLK_PIN        12
#define LISA_CAMERA_DVP_PCLK_FUNC       CSK_IOMUX_FUNC_ALTER16

#define LISA_CAMERA_DVP_DATA0_PORT      CSK_IOMUX_PAD_A
#define LISA_CAMERA_DVP_DATA0_PIN       13
#define LISA_CAMERA_DVP_DATA0_FUNC      CSK_IOMUX_FUNC_ALTER16

#define LISA_CAMERA_DVP_DATA1_PORT      CSK_IOMUX_PAD_A
#define LISA_CAMERA_DVP_DATA1_PIN       14
#define LISA_CAMERA_DVP_DATA1_FUNC      CSK_IOMUX_FUNC_ALTER16

#define LISA_CAMERA_DVP_DATA2_PORT      CSK_IOMUX_PAD_A
#define LISA_CAMERA_DVP_DATA2_PIN       15
#define LISA_CAMERA_DVP_DATA2_FUNC      CSK_IOMUX_FUNC_ALTER16

#define LISA_CAMERA_DVP_DATA3_PORT      CSK_IOMUX_PAD_A
#define LISA_CAMERA_DVP_DATA3_PIN       16
#define LISA_CAMERA_DVP_DATA3_FUNC      CSK_IOMUX_FUNC_ALTER16

#define LISA_CAMERA_DVP_DATA4_PORT      CSK_IOMUX_PAD_A
#define LISA_CAMERA_DVP_DATA4_PIN       17
#define LISA_CAMERA_DVP_DATA4_FUNC      CSK_IOMUX_FUNC_ALTER16

#define LISA_CAMERA_DVP_DATA5_PORT      CSK_IOMUX_PAD_A
#define LISA_CAMERA_DVP_DATA5_PIN       18
#define LISA_CAMERA_DVP_DATA5_FUNC      CSK_IOMUX_FUNC_ALTER16

#define LISA_CAMERA_DVP_DATA6_PORT      CSK_IOMUX_PAD_A
#define LISA_CAMERA_DVP_DATA6_PIN       19
#define LISA_CAMERA_DVP_DATA6_FUNC      CSK_IOMUX_FUNC_ALTER16

#define LISA_CAMERA_DVP_DATA7_PORT      CSK_IOMUX_PAD_A
#define LISA_CAMERA_DVP_DATA7_PIN       20
#define LISA_CAMERA_DVP_DATA7_FUNC      CSK_IOMUX_FUNC_ALTER16


#define LISA_PA_MUTE_PORT               CSK_IOMUX_PAD_A
#define LISA_PA_MUTE_PIN                1
#define LISA_PA_MUTE_FUNC               CSK_IOMUX_FUNC_ALTER1

#define LISA_USB_DET_PORT               CSK_IOMUX_PAD_B
#define LISA_USB_DET_PIN                0
#define LISA_USB_DET_FUNC               CSK_IOMUX_FUNC_DEFAULT

#define LISA_LED_GREEN_PORT             CSK_IOMUX_PAD_B
#define LISA_LED_GREEN_PIN              1
#define LISA_LED_GREEN_FUNC             CSK_IOMUX_FUNC_DEFAULT

#define LISA_PWR_LOCK_PORT              CSK_IOMUX_PAD_B
#define LISA_PWR_LOCK_PIN               3
#define LISA_PWR_LOCK_FUNC              CSK_IOMUX_FUNC_DEFAULT

#define LISA_PWR_KEY_PORT               CSK_IOMUX_PAD_B
#define LISA_PWR_KEY_PIN                4
#define LISA_PWR_KEY_FUNC               CSK_IOMUX_FUNC_DEFAULT

#define LISA_BAT_ADC_AON_PORT           CSK_IOMUX_PAD_B
#define LISA_BAT_ADC_AON_PIN            5
#define LISA_BAT_ADC_AON_FUNC           CSK_AON_IOMUX_FUNC_ALTER3

#define LISA_CHGR_STATUS_PORT           CSK_IOMUX_PAD_B
#define LISA_CHGR_STATUS_PIN            8
#define LISA_CHGR_STATUS_FUNC           CSK_IOMUX_FUNC_DEFAULT



