#ifndef __ASSISTANT_CONTROLLER_H__
#define __ASSISTANT_CONTROLLER_H__

#ifdef __cplusplus
extern "C" {
#endif

typedef enum {

    CONTROLLER_EVENT_STATE_AUDIO_IDLE = 0,
    CONTROLLER_EVENT_STATE_AUDIO_PRE_IDLE,
    CONTROLLER_EVENT_STATE_AUDIO_WAKEUP,
    CONTROLLER_EVENT_STATE_AUDIO_CONNECT_CLOUD_FAILED,
    CONTROLLER_EVENT_STATE_AUDIO_RECORD_START,
    CONTROLLER_EVENT_STATE_AUDIO_RECORD_STOP,
    CONTROLLER_EVENT_STATE_VAD_END,
    CONTROLLER_EVENT_STATE_SESSION_END, 
    CONTROLLER_EVENT_STATE_AUDIO_PLAY_START,
    CONTROLLER_EVENT_STATE_AUDIO_PLAY_STOP,
    CONTROLLER_EVENT_STATE_AUDIO_UPDATE_MUSIC,
    CONTROLLER_EVENT_STATE_CLOUD_UPDATE_IAT_TEXT,
    CONTROLLER_EVENT_STATE_ALARM_ADD_ITEM,
    CONTROLLER_EVENT_STATE_ALARM_DELETE_ITEM,
    CONTROLLER_EVENT_STATE_WEATHER_UPDATE,
    CONTROLLER_EVENT_STATE_TTS_PLAY_START,
    CONTROLLER_EVENT_STATE_TTS_PLAY_FINISH,
    CONTROLLER_EVENT_STATE_SOUND_PLAY_START,
    CONTROLLER_EVENT_STATE_SOUND_PLAY_FINISH,
    CONTROLLER_EVENT_STATE_CLOUD_GET_ROLES_SUCCESS,
    CONTROLLER_EVENT_STATE_CLOUD_GET_ROLES_FAILED,
    CONTROLLER_EVENT_STATE_WIFI_CONNECTED,
    CONTROLLER_EVENT_STATE_WIFI_DISCONNECTED,
    CONTROLLER_EVENT_STATE_WIFI_CONNECTING,
    CONTROLLER_EVENT_STATE_WIFI_SCANNING,
    CONTROLLER_EVENT_STATE_WIFI_SCANNED,
    CONTROLLER_EVENT_STATE_ROLE_EMOJI_UPDATE,
    CONTROLLER_EVENT_STATE_MCP_EMOJI_UPDATE,
    CONTROLLER_EVENT_STATE_REPLY_TEXT_UPDATE,
    CONTROLLER_EVENT_STATE_STANDBY_TEXTS_UPDATE,
    CONTROLLER_EVENT_STATE_DEVICE_CONFIG_UPDATE,
    CONTROLLER_EVENT_STATE_OUTOF_LIMIT_ERROR,
    CONTROLLER_EVENT_BATTERY_INFO_UPDATE,
    CONTROLLER_EVENT_OPT_WIFI_CONNECT,
    CONTROLLER_EVENT_OPT_WIFI_DISCONNECT,
    CONTROLLER_EVENT_OPT_WIFI_SCAN,
    CONTROLLER_EVENT_OPT_TOGGLE_INFO_PAGE,
    CONTROLLER_EVENT_OPT_ENTER_BLE_CONFIG,
    CONTROLLER_EVENT_OPT_EXIT_BLE_CONFIG,

    CONTROLLER_EVENT_MAX_NUMBER,

} assistant_controller_event_id_e;

typedef struct{
    const char* name;
    const char* artist;
}assistant_controller_event_update_music_payload_t;

int assist_controller_init(void);
int assist_controller_trigger_event(assistant_controller_event_id_e event_id, void *arg, uint32_t len);
int assist_controller_set_mcp_emoji(const char *emoji_name);

#ifdef __cplusplus
}
#endif

#endif /* assist_controller.h */
