# 项目可根据需要在此文件中设置对应的配置

# TinyUSB 配置
CONFIG_TINY_USB=y
CONFIG_TINY_USB_USE_CUSTOM_CONFIG_FILE=y
CONFIG_TINY_USB_CONFIG_FILE="tusb_config.h"

# 文件系统配置
CONFIG_FILE_SYSTEM=y
CONFIG_FATFS_FILESYSTEM=y
CONFIG_DISK_DRIVER=y
CONFIG_DISK_DRIVER_SDMMC=y

# 抽象文件系统
CONFIG_LSFS=y
CONFIG_LSFS_FAT=y

# ADB 配置
CONFIG_TUSB_APP_CLASS=y
CONFIG_ADB_SYNC=y
CONFIG_ADB_PUSH_PULL_DEFAULT_ROOT="/SD:/adb/"
CONFIG_ADB_SHELL=y

# Shell 配置
CONFIG_SDK_MODULE_LETTER_SHELL=y
CONFIG_SDK_MODULE_LETTER_SHELL_CONFIG_FILE="shell_cfg_user.h"

# 系统配置
CONFIG_SYSLOG_UART_BAUDRATE=921600
CONFIG_LINK_OPTION_NOSYS_SPECS=y
CONFIG_DCACHE_ENABLE=y

# 内存配置
CONFIG_PSRAM_HEAP_SIZE=0x300000
CONFIG_HEAP_SIZE=0x10000

# 日志配置
CONFIG_EASYLOGGER_ASYNC_BUF_SIZE=102400
