# 项目可根据需要在此文件中设置对应的配置
CONFIG_ARCS_HAL_WARNING_DISABLE=y

CONFIG_SYSLOG_UART_BAUDRATE=921600
CONFIG_LINK_OPTION_NOSYS_SPECS=y
CONFIG_PSRAM_HEAP_SIZE=0x300000
CONFIG_HEAP_SIZE=0x10000
CONFIG_DCACHE_ENABLE=y

CONFIG_SDK_MODULE_LETTER_SHELL=y
CONFIG_SDK_MODULE_LETTER_SHELL_CONFIG_FILE="shell_cfg_user.h"

CONFIG_BACK_TRACE=y
CONFIG_EASYLOGGER_ASYNC_BUF_SIZE=102400
