# 项目可根据需要在此文件中设置对应的配置

# 模块配置
CONFIG_MODULE_FREERTOS=y
CONFIG_MODULE_HEAP=y
CONFIG_LINK_OPTION_NOSYS_SPECS=y
CONFIG_LISA_OS=y
CONFIG_FREERTOS_STATIC_ALLOCATION_ENABLE=y

# 内存配置
CONFIG_PSRAM_HEAP_SIZE=0x1e8480
CONFIG_HEAP_SIZE=0x186a0

# 文件系统配置
CONFIG_FILE_SYSTEM=y
CONFIG_FATFS_FILESYSTEM=y

# DISK驱动使能
CONFIG_DISK_DRIVER=y

# DISK FLASH驱动使能及配置
# CONFIG_DISK_DRIVER_FLASH=y
# CONFIG_DISK_FLASH_START_ADDR=0x100000
# CONFIG_DISK_FLASH_MAX_RW_SIZE=4096
# CONFIG_DISK_FLASH_ERASE_ALIGNMENT=4096
# CONFIG_DISK_FLASH_ERASE_BLOCK_SIZE=4096
# CONFIG_DISK_FLASH_SECTOR_SIZE=512
# CONFIG_DISK_FLASH_VOLUME_SIZE=3145728

# DISK RAM驱动使能及配置
# CONFIG_DISK_DRIVER_RAM=y

# DISK SDMMC驱动使能及配置
CONFIG_DISK_DRIVER_SDMMC=y

# 抽象文件系统
CONFIG_LSFS=y
CONFIG_LSFS_FAT=y

# SQLite 配置
CONFIG_CSK_SQLITE=y
CONFIG_CSK_SQLITE_SDK_ARCS=y

# mbedtls 配置（用于硬件解码）
CONFIG_SDK_MODULE_MBEDTLS=y
CONFIG_CUSTOM_MBEDTLS_CFG_FILE=y
CONFIG_MBEDTLS_CFG_FILE="mbedtls_config.h"
CONFIG_MBEDTLS_HARDWARE_ENTROPY=y
CONFIG_MBEDTLS_HARDWARE_AES=y
