# ============================================
# LISA Flash Dual-Core Example - AP Core
# (Remote Core - Gets Halted by CP Core)
# ============================================

# Core Configuration
CONFIG_ARCS_AP_CORE=y

# IPC Configuration for Dual-Core
CONFIG_RTOS_AL=y
CONFIG_ARCS_HAL_IPC=y
CONFIG_ARCS_HAL_IPC_SLAVE=y
CONFIG_ARCS_HAL_IPC_HALT_BY_PEER_CORE=y

CONFIG_SYSLOG_UART_DEVICE_UART1=y

# redefine memory config for AP core
CONFIG_MEM_SRAM_BASE=0x20010000
CONFIG_MEM_SRAM_SIZE=0x00020000
CONFIG_MEM_PSRAM_BASE=0x28000000
CONFIG_MEM_PSRAM_SIZE=0x00100000