# 项目可根据需要在此文件中设置对应的配置

# 内存配置
CONFIG_MEM_CONFIG=y
CONFIG_MAIN_TASK_STACK_SIZE=20480
CONFIG_HEAP_SIZE=0x30000
CONFIG_PSRAM_HEAP_SIZE=0x100000

# 日志和调试
CONFIG_LOG_LEVEL_DEBUG=y
CONFIG_ARCS_HAL_LOG_LEVEL_DEBUG=y
CONFIG_BACK_TRACE=y

# 启用 quirc 模块
CONFIG_SDK_MODULE_QUIRC=y

# 启用耗时统计依赖
CONFIG_LISA_OS=y