/*
 * InfoNES mapper compile-time selection.
 *
 * Default keeps every split mapper enabled. To trim binary size, define
 * INFONES_ENABLE_ALL_MAPPERS=0 and enable only the mapper IDs you need,
 * for example: -DINFONES_ENABLE_MAPPER_004=1 -DINFONES_ENABLE_MAPPER_023=1.
 * Mapper 000 provides default callbacks used by many mapper bodies and is
 * kept enabled unless explicitly overridden.
 * Mapper 206 reuses Mapper 004's MMC3 state and needs Mapper 004 enabled.
 */
#pragma once

#ifndef CONFIG_NES_MAPPER_INFONES_ENABLE
#define CONFIG_NES_MAPPER_INFONES_ENABLE 1
#endif

#ifndef INFONES_ENABLE_ALL_MAPPERS
#ifdef CONFIG_NES_MAPPER_INFONES_ALL
#define INFONES_ENABLE_ALL_MAPPERS (CONFIG_NES_MAPPER_INFONES_ENABLE && CONFIG_NES_MAPPER_INFONES_ALL)
#else
#define INFONES_ENABLE_ALL_MAPPERS 0
#endif
#endif

#ifndef INFONES_ENABLE_DEFAULT_MAPPERS
#ifdef CONFIG_NES_MAPPER_INFONES_DEFAULT_SET
#define INFONES_ENABLE_DEFAULT_MAPPERS (CONFIG_NES_MAPPER_INFONES_ENABLE && CONFIG_NES_MAPPER_INFONES_DEFAULT_SET)
#else
#define INFONES_ENABLE_DEFAULT_MAPPERS CONFIG_NES_MAPPER_INFONES_ENABLE
#endif
#endif

/*
 * Keep a broad but not exhaustive fallback set enabled by default. Native mapper
 * files in this port are still selected first; this list only covers mapper IDs
 * that are otherwise unsupported. Define INFONES_ENABLE_ALL_MAPPERS=1 to build
 * the whole imported InfoNES table, or set INFONES_ENABLE_DEFAULT_MAPPERS=0 and
 * enable individual INFONES_ENABLE_MAPPER_xxx macros to trim further.
 */
#if INFONES_ENABLE_DEFAULT_MAPPERS && !INFONES_ENABLE_ALL_MAPPERS
#ifndef INFONES_ENABLE_MAPPER_002
#define INFONES_ENABLE_MAPPER_002 1
#endif
#ifndef INFONES_ENABLE_MAPPER_004
#define INFONES_ENABLE_MAPPER_004 1
#endif
#ifndef INFONES_ENABLE_MAPPER_008
#define INFONES_ENABLE_MAPPER_008 1
#endif
#ifndef INFONES_ENABLE_MAPPER_009
#define INFONES_ENABLE_MAPPER_009 1
#endif
#ifndef INFONES_ENABLE_MAPPER_010
#define INFONES_ENABLE_MAPPER_010 1
#endif
#ifndef INFONES_ENABLE_MAPPER_013
#define INFONES_ENABLE_MAPPER_013 1
#endif
#ifndef INFONES_ENABLE_MAPPER_015
#define INFONES_ENABLE_MAPPER_015 1
#endif
#ifndef INFONES_ENABLE_MAPPER_016
#define INFONES_ENABLE_MAPPER_016 1
#endif
#ifndef INFONES_ENABLE_MAPPER_018
#define INFONES_ENABLE_MAPPER_018 1
#endif
#ifndef INFONES_ENABLE_MAPPER_019
#define INFONES_ENABLE_MAPPER_019 1
#endif
#ifndef INFONES_ENABLE_MAPPER_021
#define INFONES_ENABLE_MAPPER_021 1
#endif
#ifndef INFONES_ENABLE_MAPPER_022
#define INFONES_ENABLE_MAPPER_022 1
#endif
#ifndef INFONES_ENABLE_MAPPER_023
#define INFONES_ENABLE_MAPPER_023 1
#endif
#ifndef INFONES_ENABLE_MAPPER_024
#define INFONES_ENABLE_MAPPER_024 1
#endif
#ifndef INFONES_ENABLE_MAPPER_025
#define INFONES_ENABLE_MAPPER_025 1
#endif
#ifndef INFONES_ENABLE_MAPPER_026
#define INFONES_ENABLE_MAPPER_026 1
#endif
#ifndef INFONES_ENABLE_MAPPER_030
#define INFONES_ENABLE_MAPPER_030 1
#endif
#ifndef INFONES_ENABLE_MAPPER_032
#define INFONES_ENABLE_MAPPER_032 1
#endif
#ifndef INFONES_ENABLE_MAPPER_033
#define INFONES_ENABLE_MAPPER_033 1
#endif
#ifndef INFONES_ENABLE_MAPPER_034
#define INFONES_ENABLE_MAPPER_034 1
#endif
#ifndef INFONES_ENABLE_MAPPER_040
#define INFONES_ENABLE_MAPPER_040 1
#endif
#ifndef INFONES_ENABLE_MAPPER_041
#define INFONES_ENABLE_MAPPER_041 1
#endif
#ifndef INFONES_ENABLE_MAPPER_042
#define INFONES_ENABLE_MAPPER_042 1
#endif
#ifndef INFONES_ENABLE_MAPPER_064
#define INFONES_ENABLE_MAPPER_064 1
#endif
#ifndef INFONES_ENABLE_MAPPER_065
#define INFONES_ENABLE_MAPPER_065 1
#endif
#ifndef INFONES_ENABLE_MAPPER_067
#define INFONES_ENABLE_MAPPER_067 1
#endif
#ifndef INFONES_ENABLE_MAPPER_068
#define INFONES_ENABLE_MAPPER_068 1
#endif
#ifndef INFONES_ENABLE_MAPPER_069
#define INFONES_ENABLE_MAPPER_069 1
#endif
#ifndef INFONES_ENABLE_MAPPER_073
#define INFONES_ENABLE_MAPPER_073 1
#endif
#ifndef INFONES_ENABLE_MAPPER_075
#define INFONES_ENABLE_MAPPER_075 1
#endif
#ifndef INFONES_ENABLE_MAPPER_076
#define INFONES_ENABLE_MAPPER_076 1
#endif
#ifndef INFONES_ENABLE_MAPPER_079
#define INFONES_ENABLE_MAPPER_079 1
#endif
#ifndef INFONES_ENABLE_MAPPER_080
#define INFONES_ENABLE_MAPPER_080 1
#endif
#ifndef INFONES_ENABLE_MAPPER_088
#define INFONES_ENABLE_MAPPER_088 1
#endif
#ifndef INFONES_ENABLE_MAPPER_089
#define INFONES_ENABLE_MAPPER_089 1
#endif
#ifndef INFONES_ENABLE_MAPPER_090
#define INFONES_ENABLE_MAPPER_090 1
#endif
#ifndef INFONES_ENABLE_MAPPER_095
#define INFONES_ENABLE_MAPPER_095 1
#endif
#ifndef INFONES_ENABLE_MAPPER_105
#define INFONES_ENABLE_MAPPER_105 1
#endif
#ifndef INFONES_ENABLE_MAPPER_108
#define INFONES_ENABLE_MAPPER_108 1
#endif
#ifndef INFONES_ENABLE_MAPPER_109
#define INFONES_ENABLE_MAPPER_109 1
#endif
#ifndef INFONES_ENABLE_MAPPER_112
#define INFONES_ENABLE_MAPPER_112 1
#endif
#ifndef INFONES_ENABLE_MAPPER_113
#define INFONES_ENABLE_MAPPER_113 1
#endif
#ifndef INFONES_ENABLE_MAPPER_114
#define INFONES_ENABLE_MAPPER_114 1
#endif
#ifndef INFONES_ENABLE_MAPPER_115
#define INFONES_ENABLE_MAPPER_115 1
#endif
#ifndef INFONES_ENABLE_MAPPER_116
#define INFONES_ENABLE_MAPPER_116 1
#endif
#ifndef INFONES_ENABLE_MAPPER_118
#define INFONES_ENABLE_MAPPER_118 1
#endif
#ifndef INFONES_ENABLE_MAPPER_119
#define INFONES_ENABLE_MAPPER_119 1
#endif
#ifndef INFONES_ENABLE_MAPPER_122
#define INFONES_ENABLE_MAPPER_122 1
#endif
#ifndef INFONES_ENABLE_MAPPER_133
#define INFONES_ENABLE_MAPPER_133 1
#endif
#ifndef INFONES_ENABLE_MAPPER_140
#define INFONES_ENABLE_MAPPER_140 1
#endif
#ifndef INFONES_ENABLE_MAPPER_151
#define INFONES_ENABLE_MAPPER_151 1
#endif
#ifndef INFONES_ENABLE_MAPPER_182
#define INFONES_ENABLE_MAPPER_182 1
#endif
#ifndef INFONES_ENABLE_MAPPER_185
#define INFONES_ENABLE_MAPPER_185 1
#endif
#ifndef INFONES_ENABLE_MAPPER_187
#define INFONES_ENABLE_MAPPER_187 1
#endif
#ifndef INFONES_ENABLE_MAPPER_189
#define INFONES_ENABLE_MAPPER_189 1
#endif
#ifndef INFONES_ENABLE_MAPPER_191
#define INFONES_ENABLE_MAPPER_191 1
#endif
#ifndef INFONES_ENABLE_MAPPER_193
#define INFONES_ENABLE_MAPPER_193 1
#endif
#ifndef INFONES_ENABLE_MAPPER_194
#define INFONES_ENABLE_MAPPER_194 1
#endif
#ifndef INFONES_ENABLE_MAPPER_206
#define INFONES_ENABLE_MAPPER_206 1
#endif
#ifndef INFONES_ENABLE_MAPPER_225
#define INFONES_ENABLE_MAPPER_225 1
#endif
#ifndef INFONES_ENABLE_MAPPER_226
#define INFONES_ENABLE_MAPPER_226 1
#endif
#ifndef INFONES_ENABLE_MAPPER_227
#define INFONES_ENABLE_MAPPER_227 1
#endif
#ifndef INFONES_ENABLE_MAPPER_228
#define INFONES_ENABLE_MAPPER_228 1
#endif
#ifndef INFONES_ENABLE_MAPPER_229
#define INFONES_ENABLE_MAPPER_229 1
#endif
#ifndef INFONES_ENABLE_MAPPER_230
#define INFONES_ENABLE_MAPPER_230 1
#endif
#ifndef INFONES_ENABLE_MAPPER_231
#define INFONES_ENABLE_MAPPER_231 1
#endif
#ifndef INFONES_ENABLE_MAPPER_232
#define INFONES_ENABLE_MAPPER_232 1
#endif
#ifndef INFONES_ENABLE_MAPPER_233
#define INFONES_ENABLE_MAPPER_233 1
#endif
#ifndef INFONES_ENABLE_MAPPER_234
#define INFONES_ENABLE_MAPPER_234 1
#endif
#ifndef INFONES_ENABLE_MAPPER_235
#define INFONES_ENABLE_MAPPER_235 1
#endif
#ifndef INFONES_ENABLE_MAPPER_236
#define INFONES_ENABLE_MAPPER_236 1
#endif
#ifndef INFONES_ENABLE_MAPPER_241
#define INFONES_ENABLE_MAPPER_241 1
#endif
#ifndef INFONES_ENABLE_MAPPER_243
#define INFONES_ENABLE_MAPPER_243 1
#endif
#ifndef INFONES_ENABLE_MAPPER_244
#define INFONES_ENABLE_MAPPER_244 1
#endif
#ifndef INFONES_ENABLE_MAPPER_245
#define INFONES_ENABLE_MAPPER_245 1
#endif
#ifndef INFONES_ENABLE_MAPPER_246
#define INFONES_ENABLE_MAPPER_246 1
#endif
#ifndef INFONES_ENABLE_MAPPER_248
#define INFONES_ENABLE_MAPPER_248 1
#endif
#ifndef INFONES_ENABLE_MAPPER_249
#define INFONES_ENABLE_MAPPER_249 1
#endif
#ifndef INFONES_ENABLE_MAPPER_251
#define INFONES_ENABLE_MAPPER_251 1
#endif
#ifndef INFONES_ENABLE_MAPPER_252
#define INFONES_ENABLE_MAPPER_252 1
#endif
#ifndef INFONES_ENABLE_MAPPER_255
#define INFONES_ENABLE_MAPPER_255 1
#endif
#endif

#ifndef INFONES_ENABLE_MAPPER_000
#define INFONES_ENABLE_MAPPER_000 1
#endif
#ifndef INFONES_ENABLE_MAPPER_001
#define INFONES_ENABLE_MAPPER_001 INFONES_ENABLE_ALL_MAPPERS
#endif
#ifndef INFONES_ENABLE_MAPPER_002
#define INFONES_ENABLE_MAPPER_002 INFONES_ENABLE_ALL_MAPPERS
#endif
#ifndef INFONES_ENABLE_MAPPER_003
#define INFONES_ENABLE_MAPPER_003 INFONES_ENABLE_ALL_MAPPERS
#endif
#ifndef INFONES_ENABLE_MAPPER_004
#define INFONES_ENABLE_MAPPER_004 INFONES_ENABLE_ALL_MAPPERS
#endif
#ifndef INFONES_ENABLE_MAPPER_007
#define INFONES_ENABLE_MAPPER_007 INFONES_ENABLE_ALL_MAPPERS
#endif
#ifndef INFONES_ENABLE_MAPPER_008
#define INFONES_ENABLE_MAPPER_008 INFONES_ENABLE_ALL_MAPPERS
#endif
#ifndef INFONES_ENABLE_MAPPER_009
#define INFONES_ENABLE_MAPPER_009 INFONES_ENABLE_ALL_MAPPERS
#endif
#ifndef INFONES_ENABLE_MAPPER_010
#define INFONES_ENABLE_MAPPER_010 INFONES_ENABLE_ALL_MAPPERS
#endif
#ifndef INFONES_ENABLE_MAPPER_011
#define INFONES_ENABLE_MAPPER_011 INFONES_ENABLE_ALL_MAPPERS
#endif
#ifndef INFONES_ENABLE_MAPPER_013
#define INFONES_ENABLE_MAPPER_013 INFONES_ENABLE_ALL_MAPPERS
#endif
#ifndef INFONES_ENABLE_MAPPER_015
#define INFONES_ENABLE_MAPPER_015 INFONES_ENABLE_ALL_MAPPERS
#endif
#ifndef INFONES_ENABLE_MAPPER_016
#define INFONES_ENABLE_MAPPER_016 INFONES_ENABLE_ALL_MAPPERS
#endif
#ifndef INFONES_ENABLE_MAPPER_017
#define INFONES_ENABLE_MAPPER_017 INFONES_ENABLE_ALL_MAPPERS
#endif
#ifndef INFONES_ENABLE_MAPPER_018
#define INFONES_ENABLE_MAPPER_018 INFONES_ENABLE_ALL_MAPPERS
#endif
#ifndef INFONES_ENABLE_MAPPER_019
#define INFONES_ENABLE_MAPPER_019 INFONES_ENABLE_ALL_MAPPERS
#endif
#ifndef INFONES_ENABLE_MAPPER_021
#define INFONES_ENABLE_MAPPER_021 INFONES_ENABLE_ALL_MAPPERS
#endif
#ifndef INFONES_ENABLE_MAPPER_022
#define INFONES_ENABLE_MAPPER_022 INFONES_ENABLE_ALL_MAPPERS
#endif
#ifndef INFONES_ENABLE_MAPPER_023
#define INFONES_ENABLE_MAPPER_023 INFONES_ENABLE_ALL_MAPPERS
#endif
#ifndef INFONES_ENABLE_MAPPER_024
#define INFONES_ENABLE_MAPPER_024 INFONES_ENABLE_ALL_MAPPERS
#endif
#ifndef INFONES_ENABLE_MAPPER_025
#define INFONES_ENABLE_MAPPER_025 INFONES_ENABLE_ALL_MAPPERS
#endif
#ifndef INFONES_ENABLE_MAPPER_026
#define INFONES_ENABLE_MAPPER_026 INFONES_ENABLE_ALL_MAPPERS
#endif
#ifndef INFONES_ENABLE_MAPPER_030
#define INFONES_ENABLE_MAPPER_030 INFONES_ENABLE_ALL_MAPPERS
#endif
#ifndef INFONES_ENABLE_MAPPER_032
#define INFONES_ENABLE_MAPPER_032 INFONES_ENABLE_ALL_MAPPERS
#endif
#ifndef INFONES_ENABLE_MAPPER_033
#define INFONES_ENABLE_MAPPER_033 INFONES_ENABLE_ALL_MAPPERS
#endif
#ifndef INFONES_ENABLE_MAPPER_034
#define INFONES_ENABLE_MAPPER_034 INFONES_ENABLE_ALL_MAPPERS
#endif
#ifndef INFONES_ENABLE_MAPPER_040
#define INFONES_ENABLE_MAPPER_040 INFONES_ENABLE_ALL_MAPPERS
#endif
#ifndef INFONES_ENABLE_MAPPER_041
#define INFONES_ENABLE_MAPPER_041 INFONES_ENABLE_ALL_MAPPERS
#endif
#ifndef INFONES_ENABLE_MAPPER_042
#define INFONES_ENABLE_MAPPER_042 INFONES_ENABLE_ALL_MAPPERS
#endif
#ifndef INFONES_ENABLE_MAPPER_043
#define INFONES_ENABLE_MAPPER_043 INFONES_ENABLE_ALL_MAPPERS
#endif
#ifndef INFONES_ENABLE_MAPPER_044
#define INFONES_ENABLE_MAPPER_044 INFONES_ENABLE_ALL_MAPPERS
#endif
#ifndef INFONES_ENABLE_MAPPER_045
#define INFONES_ENABLE_MAPPER_045 INFONES_ENABLE_ALL_MAPPERS
#endif
#ifndef INFONES_ENABLE_MAPPER_046
#define INFONES_ENABLE_MAPPER_046 INFONES_ENABLE_ALL_MAPPERS
#endif
#ifndef INFONES_ENABLE_MAPPER_047
#define INFONES_ENABLE_MAPPER_047 INFONES_ENABLE_ALL_MAPPERS
#endif
#ifndef INFONES_ENABLE_MAPPER_048
#define INFONES_ENABLE_MAPPER_048 INFONES_ENABLE_ALL_MAPPERS
#endif
#ifndef INFONES_ENABLE_MAPPER_049
#define INFONES_ENABLE_MAPPER_049 INFONES_ENABLE_ALL_MAPPERS
#endif
#ifndef INFONES_ENABLE_MAPPER_050
#define INFONES_ENABLE_MAPPER_050 INFONES_ENABLE_ALL_MAPPERS
#endif
#ifndef INFONES_ENABLE_MAPPER_051
#define INFONES_ENABLE_MAPPER_051 INFONES_ENABLE_ALL_MAPPERS
#endif
#ifndef INFONES_ENABLE_MAPPER_057
#define INFONES_ENABLE_MAPPER_057 INFONES_ENABLE_ALL_MAPPERS
#endif
#ifndef INFONES_ENABLE_MAPPER_058
#define INFONES_ENABLE_MAPPER_058 INFONES_ENABLE_ALL_MAPPERS
#endif
#ifndef INFONES_ENABLE_MAPPER_060
#define INFONES_ENABLE_MAPPER_060 INFONES_ENABLE_ALL_MAPPERS
#endif
#ifndef INFONES_ENABLE_MAPPER_061
#define INFONES_ENABLE_MAPPER_061 INFONES_ENABLE_ALL_MAPPERS
#endif
#ifndef INFONES_ENABLE_MAPPER_062
#define INFONES_ENABLE_MAPPER_062 INFONES_ENABLE_ALL_MAPPERS
#endif
#ifndef INFONES_ENABLE_MAPPER_064
#define INFONES_ENABLE_MAPPER_064 INFONES_ENABLE_ALL_MAPPERS
#endif
#ifndef INFONES_ENABLE_MAPPER_065
#define INFONES_ENABLE_MAPPER_065 INFONES_ENABLE_ALL_MAPPERS
#endif
#ifndef INFONES_ENABLE_MAPPER_066
#define INFONES_ENABLE_MAPPER_066 INFONES_ENABLE_ALL_MAPPERS
#endif
#ifndef INFONES_ENABLE_MAPPER_067
#define INFONES_ENABLE_MAPPER_067 INFONES_ENABLE_ALL_MAPPERS
#endif
#ifndef INFONES_ENABLE_MAPPER_068
#define INFONES_ENABLE_MAPPER_068 INFONES_ENABLE_ALL_MAPPERS
#endif
#ifndef INFONES_ENABLE_MAPPER_069
#define INFONES_ENABLE_MAPPER_069 INFONES_ENABLE_ALL_MAPPERS
#endif
#ifndef INFONES_ENABLE_MAPPER_070
#define INFONES_ENABLE_MAPPER_070 INFONES_ENABLE_ALL_MAPPERS
#endif
#ifndef INFONES_ENABLE_MAPPER_071
#define INFONES_ENABLE_MAPPER_071 INFONES_ENABLE_ALL_MAPPERS
#endif
#ifndef INFONES_ENABLE_MAPPER_072
#define INFONES_ENABLE_MAPPER_072 INFONES_ENABLE_ALL_MAPPERS
#endif
#ifndef INFONES_ENABLE_MAPPER_073
#define INFONES_ENABLE_MAPPER_073 INFONES_ENABLE_ALL_MAPPERS
#endif
#ifndef INFONES_ENABLE_MAPPER_074
#define INFONES_ENABLE_MAPPER_074 INFONES_ENABLE_ALL_MAPPERS
#endif
#ifndef INFONES_ENABLE_MAPPER_075
#define INFONES_ENABLE_MAPPER_075 INFONES_ENABLE_ALL_MAPPERS
#endif
#ifndef INFONES_ENABLE_MAPPER_076
#define INFONES_ENABLE_MAPPER_076 INFONES_ENABLE_ALL_MAPPERS
#endif
#ifndef INFONES_ENABLE_MAPPER_077
#define INFONES_ENABLE_MAPPER_077 INFONES_ENABLE_ALL_MAPPERS
#endif
#ifndef INFONES_ENABLE_MAPPER_078
#define INFONES_ENABLE_MAPPER_078 INFONES_ENABLE_ALL_MAPPERS
#endif
#ifndef INFONES_ENABLE_MAPPER_079
#define INFONES_ENABLE_MAPPER_079 INFONES_ENABLE_ALL_MAPPERS
#endif
#ifndef INFONES_ENABLE_MAPPER_080
#define INFONES_ENABLE_MAPPER_080 INFONES_ENABLE_ALL_MAPPERS
#endif
#ifndef INFONES_ENABLE_MAPPER_082
#define INFONES_ENABLE_MAPPER_082 INFONES_ENABLE_ALL_MAPPERS
#endif
#ifndef INFONES_ENABLE_MAPPER_083
#define INFONES_ENABLE_MAPPER_083 INFONES_ENABLE_ALL_MAPPERS
#endif
#ifndef INFONES_ENABLE_MAPPER_086
#define INFONES_ENABLE_MAPPER_086 INFONES_ENABLE_ALL_MAPPERS
#endif
#ifndef INFONES_ENABLE_MAPPER_087
#define INFONES_ENABLE_MAPPER_087 INFONES_ENABLE_ALL_MAPPERS
#endif
#ifndef INFONES_ENABLE_MAPPER_088
#define INFONES_ENABLE_MAPPER_088 INFONES_ENABLE_ALL_MAPPERS
#endif
#ifndef INFONES_ENABLE_MAPPER_089
#define INFONES_ENABLE_MAPPER_089 INFONES_ENABLE_ALL_MAPPERS
#endif
#ifndef INFONES_ENABLE_MAPPER_090
#define INFONES_ENABLE_MAPPER_090 INFONES_ENABLE_ALL_MAPPERS
#endif
#ifndef INFONES_ENABLE_MAPPER_091
#define INFONES_ENABLE_MAPPER_091 INFONES_ENABLE_ALL_MAPPERS
#endif
#ifndef INFONES_ENABLE_MAPPER_092
#define INFONES_ENABLE_MAPPER_092 INFONES_ENABLE_ALL_MAPPERS
#endif
#ifndef INFONES_ENABLE_MAPPER_093
#define INFONES_ENABLE_MAPPER_093 INFONES_ENABLE_ALL_MAPPERS
#endif
#ifndef INFONES_ENABLE_MAPPER_094
#define INFONES_ENABLE_MAPPER_094 INFONES_ENABLE_ALL_MAPPERS
#endif
#ifndef INFONES_ENABLE_MAPPER_095
#define INFONES_ENABLE_MAPPER_095 INFONES_ENABLE_ALL_MAPPERS
#endif
#ifndef INFONES_ENABLE_MAPPER_096
#define INFONES_ENABLE_MAPPER_096 INFONES_ENABLE_ALL_MAPPERS
#endif
#ifndef INFONES_ENABLE_MAPPER_097
#define INFONES_ENABLE_MAPPER_097 INFONES_ENABLE_ALL_MAPPERS
#endif
#ifndef INFONES_ENABLE_MAPPER_100
#define INFONES_ENABLE_MAPPER_100 INFONES_ENABLE_ALL_MAPPERS
#endif
#ifndef INFONES_ENABLE_MAPPER_101
#define INFONES_ENABLE_MAPPER_101 INFONES_ENABLE_ALL_MAPPERS
#endif
#ifndef INFONES_ENABLE_MAPPER_105
#define INFONES_ENABLE_MAPPER_105 INFONES_ENABLE_ALL_MAPPERS
#endif
#ifndef INFONES_ENABLE_MAPPER_107
#define INFONES_ENABLE_MAPPER_107 INFONES_ENABLE_ALL_MAPPERS
#endif
#ifndef INFONES_ENABLE_MAPPER_108
#define INFONES_ENABLE_MAPPER_108 INFONES_ENABLE_ALL_MAPPERS
#endif
#ifndef INFONES_ENABLE_MAPPER_109
#define INFONES_ENABLE_MAPPER_109 INFONES_ENABLE_ALL_MAPPERS
#endif
#ifndef INFONES_ENABLE_MAPPER_110
#define INFONES_ENABLE_MAPPER_110 INFONES_ENABLE_ALL_MAPPERS
#endif
#ifndef INFONES_ENABLE_MAPPER_112
#define INFONES_ENABLE_MAPPER_112 INFONES_ENABLE_ALL_MAPPERS
#endif
#ifndef INFONES_ENABLE_MAPPER_113
#define INFONES_ENABLE_MAPPER_113 INFONES_ENABLE_ALL_MAPPERS
#endif
#ifndef INFONES_ENABLE_MAPPER_114
#define INFONES_ENABLE_MAPPER_114 INFONES_ENABLE_ALL_MAPPERS
#endif
#ifndef INFONES_ENABLE_MAPPER_115
#define INFONES_ENABLE_MAPPER_115 INFONES_ENABLE_ALL_MAPPERS
#endif
#ifndef INFONES_ENABLE_MAPPER_116
#define INFONES_ENABLE_MAPPER_116 INFONES_ENABLE_ALL_MAPPERS
#endif
#ifndef INFONES_ENABLE_MAPPER_117
#define INFONES_ENABLE_MAPPER_117 INFONES_ENABLE_ALL_MAPPERS
#endif
#ifndef INFONES_ENABLE_MAPPER_118
#define INFONES_ENABLE_MAPPER_118 INFONES_ENABLE_ALL_MAPPERS
#endif
#ifndef INFONES_ENABLE_MAPPER_119
#define INFONES_ENABLE_MAPPER_119 INFONES_ENABLE_ALL_MAPPERS
#endif
#ifndef INFONES_ENABLE_MAPPER_122
#define INFONES_ENABLE_MAPPER_122 INFONES_ENABLE_ALL_MAPPERS
#endif
#ifndef INFONES_ENABLE_MAPPER_133
#define INFONES_ENABLE_MAPPER_133 INFONES_ENABLE_ALL_MAPPERS
#endif
#ifndef INFONES_ENABLE_MAPPER_134
#define INFONES_ENABLE_MAPPER_134 INFONES_ENABLE_ALL_MAPPERS
#endif
#ifndef INFONES_ENABLE_MAPPER_135
#define INFONES_ENABLE_MAPPER_135 INFONES_ENABLE_ALL_MAPPERS
#endif
#ifndef INFONES_ENABLE_MAPPER_140
#define INFONES_ENABLE_MAPPER_140 INFONES_ENABLE_ALL_MAPPERS
#endif
#ifndef INFONES_ENABLE_MAPPER_151
#define INFONES_ENABLE_MAPPER_151 INFONES_ENABLE_ALL_MAPPERS
#endif
#ifndef INFONES_ENABLE_MAPPER_160
#define INFONES_ENABLE_MAPPER_160 INFONES_ENABLE_ALL_MAPPERS
#endif
#ifndef INFONES_ENABLE_MAPPER_180
#define INFONES_ENABLE_MAPPER_180 INFONES_ENABLE_ALL_MAPPERS
#endif
#ifndef INFONES_ENABLE_MAPPER_181
#define INFONES_ENABLE_MAPPER_181 INFONES_ENABLE_ALL_MAPPERS
#endif
#ifndef INFONES_ENABLE_MAPPER_182
#define INFONES_ENABLE_MAPPER_182 INFONES_ENABLE_ALL_MAPPERS
#endif
#ifndef INFONES_ENABLE_MAPPER_183
#define INFONES_ENABLE_MAPPER_183 INFONES_ENABLE_ALL_MAPPERS
#endif
#ifndef INFONES_ENABLE_MAPPER_184
#define INFONES_ENABLE_MAPPER_184 INFONES_ENABLE_ALL_MAPPERS
#endif
#ifndef INFONES_ENABLE_MAPPER_185
#define INFONES_ENABLE_MAPPER_185 INFONES_ENABLE_ALL_MAPPERS
#endif
#ifndef INFONES_ENABLE_MAPPER_187
#define INFONES_ENABLE_MAPPER_187 INFONES_ENABLE_ALL_MAPPERS
#endif
#ifndef INFONES_ENABLE_MAPPER_188
#define INFONES_ENABLE_MAPPER_188 INFONES_ENABLE_ALL_MAPPERS
#endif
#ifndef INFONES_ENABLE_MAPPER_189
#define INFONES_ENABLE_MAPPER_189 INFONES_ENABLE_ALL_MAPPERS
#endif
#ifndef INFONES_ENABLE_MAPPER_191
#define INFONES_ENABLE_MAPPER_191 INFONES_ENABLE_ALL_MAPPERS
#endif
#ifndef INFONES_ENABLE_MAPPER_193
#define INFONES_ENABLE_MAPPER_193 INFONES_ENABLE_ALL_MAPPERS
#endif
#ifndef INFONES_ENABLE_MAPPER_194
#define INFONES_ENABLE_MAPPER_194 INFONES_ENABLE_ALL_MAPPERS
#endif
#ifndef INFONES_ENABLE_MAPPER_200
#define INFONES_ENABLE_MAPPER_200 INFONES_ENABLE_ALL_MAPPERS
#endif
#ifndef INFONES_ENABLE_MAPPER_201
#define INFONES_ENABLE_MAPPER_201 INFONES_ENABLE_ALL_MAPPERS
#endif
#ifndef INFONES_ENABLE_MAPPER_202
#define INFONES_ENABLE_MAPPER_202 INFONES_ENABLE_ALL_MAPPERS
#endif
#ifndef INFONES_ENABLE_MAPPER_206
#define INFONES_ENABLE_MAPPER_206 INFONES_ENABLE_ALL_MAPPERS
#endif
#ifndef INFONES_ENABLE_MAPPER_222
#define INFONES_ENABLE_MAPPER_222 INFONES_ENABLE_ALL_MAPPERS
#endif
#ifndef INFONES_ENABLE_MAPPER_225
#define INFONES_ENABLE_MAPPER_225 INFONES_ENABLE_ALL_MAPPERS
#endif
#ifndef INFONES_ENABLE_MAPPER_226
#define INFONES_ENABLE_MAPPER_226 INFONES_ENABLE_ALL_MAPPERS
#endif
#ifndef INFONES_ENABLE_MAPPER_227
#define INFONES_ENABLE_MAPPER_227 INFONES_ENABLE_ALL_MAPPERS
#endif
#ifndef INFONES_ENABLE_MAPPER_228
#define INFONES_ENABLE_MAPPER_228 INFONES_ENABLE_ALL_MAPPERS
#endif
#ifndef INFONES_ENABLE_MAPPER_229
#define INFONES_ENABLE_MAPPER_229 INFONES_ENABLE_ALL_MAPPERS
#endif
#ifndef INFONES_ENABLE_MAPPER_230
#define INFONES_ENABLE_MAPPER_230 INFONES_ENABLE_ALL_MAPPERS
#endif
#ifndef INFONES_ENABLE_MAPPER_231
#define INFONES_ENABLE_MAPPER_231 INFONES_ENABLE_ALL_MAPPERS
#endif
#ifndef INFONES_ENABLE_MAPPER_232
#define INFONES_ENABLE_MAPPER_232 INFONES_ENABLE_ALL_MAPPERS
#endif
#ifndef INFONES_ENABLE_MAPPER_233
#define INFONES_ENABLE_MAPPER_233 INFONES_ENABLE_ALL_MAPPERS
#endif
#ifndef INFONES_ENABLE_MAPPER_234
#define INFONES_ENABLE_MAPPER_234 INFONES_ENABLE_ALL_MAPPERS
#endif
#ifndef INFONES_ENABLE_MAPPER_235
#define INFONES_ENABLE_MAPPER_235 INFONES_ENABLE_ALL_MAPPERS
#endif
#ifndef INFONES_ENABLE_MAPPER_236
#define INFONES_ENABLE_MAPPER_236 INFONES_ENABLE_ALL_MAPPERS
#endif
#ifndef INFONES_ENABLE_MAPPER_240
#define INFONES_ENABLE_MAPPER_240 INFONES_ENABLE_ALL_MAPPERS
#endif
#ifndef INFONES_ENABLE_MAPPER_241
#define INFONES_ENABLE_MAPPER_241 INFONES_ENABLE_ALL_MAPPERS
#endif
#ifndef INFONES_ENABLE_MAPPER_242
#define INFONES_ENABLE_MAPPER_242 INFONES_ENABLE_ALL_MAPPERS
#endif
#ifndef INFONES_ENABLE_MAPPER_243
#define INFONES_ENABLE_MAPPER_243 INFONES_ENABLE_ALL_MAPPERS
#endif
#ifndef INFONES_ENABLE_MAPPER_244
#define INFONES_ENABLE_MAPPER_244 INFONES_ENABLE_ALL_MAPPERS
#endif
#ifndef INFONES_ENABLE_MAPPER_245
#define INFONES_ENABLE_MAPPER_245 INFONES_ENABLE_ALL_MAPPERS
#endif
#ifndef INFONES_ENABLE_MAPPER_246
#define INFONES_ENABLE_MAPPER_246 INFONES_ENABLE_ALL_MAPPERS
#endif
#ifndef INFONES_ENABLE_MAPPER_248
#define INFONES_ENABLE_MAPPER_248 INFONES_ENABLE_ALL_MAPPERS
#endif
#ifndef INFONES_ENABLE_MAPPER_249
#define INFONES_ENABLE_MAPPER_249 INFONES_ENABLE_ALL_MAPPERS
#endif
#ifndef INFONES_ENABLE_MAPPER_251
#define INFONES_ENABLE_MAPPER_251 INFONES_ENABLE_ALL_MAPPERS
#endif
#ifndef INFONES_ENABLE_MAPPER_252
#define INFONES_ENABLE_MAPPER_252 INFONES_ENABLE_ALL_MAPPERS
#endif
#ifndef INFONES_ENABLE_MAPPER_255
#define INFONES_ENABLE_MAPPER_255 INFONES_ENABLE_ALL_MAPPERS
#endif
