//  ----------------------------------------------------------------------
//  File Name   : GenCFold/ap_cfg_reg_arcs.h
//  Description : C header file generated by Python script.
//  Script Ver  £ºLS.AUTO_REG.2024.03.01
//  Create Time : 2024-06-20 11:17:02
//  Comments    : 
//  ----------------------------------------------------------------------

#ifndef __AP_CFG_REGFILE_H__
#define __AP_CFG_REGFILE_H__

#include <stdint.h>

#define AP_CFG_SW_RESET_OFFSET                      0x000
#define AP_CFG_SW_RESET_APWDT2APSOC_RST_EN_Pos      20
#define AP_CFG_SW_RESET_APWDT2APSOC_RST_EN_Msk      0x100000
#define AP_CFG_SW_RESET_APSW2APSOC_RST_EN_Pos       19
#define AP_CFG_SW_RESET_APSW2APSOC_RST_EN_Msk       0x80000
#define AP_CFG_SW_RESET_SYSRSTREQ2APSOC_RST_EN_Pos    18
#define AP_CFG_SW_RESET_SYSRSTREQ2APSOC_RST_EN_Msk    0x40000
#define AP_CFG_SW_RESET_APWDT2AP_RST_EN_Pos         17
#define AP_CFG_SW_RESET_APWDT2AP_RST_EN_Msk         0x20000
#define AP_CFG_SW_RESET_SYSRSTREQ2AP_RST_EN_Pos     16
#define AP_CFG_SW_RESET_SYSRSTREQ2AP_RST_EN_Msk     0x10000
#define AP_CFG_SW_RESET_JPEG_RESET_Pos              14
#define AP_CFG_SW_RESET_JPEG_RESET_Msk              0x4000
#define AP_CFG_SW_RESET_BLENDER_RESET_Pos           13
#define AP_CFG_SW_RESET_BLENDER_RESET_Msk           0x2000
#define AP_CFG_SW_RESET_RGB_RESET_Pos               12
#define AP_CFG_SW_RESET_RGB_RESET_Msk               0x1000
#define AP_CFG_SW_RESET_QSPI1_RESET_Pos             11
#define AP_CFG_SW_RESET_QSPI1_RESET_Msk             0x800
#define AP_CFG_SW_RESET_QSPI0_RESET_Pos             10
#define AP_CFG_SW_RESET_QSPI0_RESET_Msk             0x400
#define AP_CFG_SW_RESET_VIC_RESET_Pos               9
#define AP_CFG_SW_RESET_VIC_RESET_Msk               0x200
#define AP_CFG_SW_RESET_LUNA_RESET_Pos              8
#define AP_CFG_SW_RESET_LUNA_RESET_Msk              0x100
#define AP_CFG_SW_RESET_APC_RESET_Pos               7
#define AP_CFG_SW_RESET_APC_RESET_Msk               0x80
#define AP_CFG_SW_RESET_CODEC_RESET_Pos             6
#define AP_CFG_SW_RESET_CODEC_RESET_Msk             0x40
#define AP_CFG_SW_RESET_I2S_RESET_Pos               5
#define AP_CFG_SW_RESET_I2S_RESET_Msk               0x20
#define AP_CFG_SW_RESET_SDIOH_RESET_Pos             4
#define AP_CFG_SW_RESET_SDIOH_RESET_Msk             0x10
#define AP_CFG_SW_RESET_VIDEO_RESET_Pos             3
#define AP_CFG_SW_RESET_VIDEO_RESET_Msk             0x8
#define AP_CFG_SW_RESET_CRYPTO_RESET_Pos            2
#define AP_CFG_SW_RESET_CRYPTO_RESET_Msk            0x4
#define AP_CFG_SW_RESET_DMAC_GP_RESET_Pos           1
#define AP_CFG_SW_RESET_DMAC_GP_RESET_Msk           0x2
#define AP_CFG_SW_RESET_MCU_CORE_RESET_Pos          0
#define AP_CFG_SW_RESET_MCU_CORE_RESET_Msk          0x1

#define AP_CFG_AP_RESET_OFFSET                      0x004
#define AP_CFG_AP_RESET_AP_RESET_Pos                0
#define AP_CFG_AP_RESET_AP_RESET_Msk                0x1

#define AP_CFG_CLK_CFG0_OFFSET                      0x008
#define AP_CFG_CLK_CFG0_SEL_RGB_INV_CLK_Pos         30
#define AP_CFG_CLK_CFG0_SEL_RGB_INV_CLK_Msk         0x40000000
#define AP_CFG_CLK_CFG0_DIV_RGB_CLK_LD_Pos          29
#define AP_CFG_CLK_CFG0_DIV_RGB_CLK_LD_Msk          0x20000000
#define AP_CFG_CLK_CFG0_DIV_RGB_CLK_M_Pos           25
#define AP_CFG_CLK_CFG0_DIV_RGB_CLK_M_Msk           0x1e000000
#define AP_CFG_CLK_CFG0_SEL_RGB_CLK_Pos             24
#define AP_CFG_CLK_CFG0_SEL_RGB_CLK_Msk             0x1000000
#define AP_CFG_CLK_CFG0_ENA_RGB_CLK_Pos             23
#define AP_CFG_CLK_CFG0_ENA_RGB_CLK_Msk             0x800000
#define AP_CFG_CLK_CFG0_SEL_VIC_CLK_Pos             22
#define AP_CFG_CLK_CFG0_SEL_VIC_CLK_Msk             0x400000
#define AP_CFG_CLK_CFG0_ENA_VIC_CLK_Pos             21
#define AP_CFG_CLK_CFG0_ENA_VIC_CLK_Msk             0x200000
#define AP_CFG_CLK_CFG0_AUD_DAC_MCLK_SRC_Pos        20
#define AP_CFG_CLK_CFG0_AUD_DAC_MCLK_SRC_Msk        0x100000
#define AP_CFG_CLK_CFG0_AUD_ADC_CLK_SRC_Pos         19
#define AP_CFG_CLK_CFG0_AUD_ADC_CLK_SRC_Msk         0x80000
#define AP_CFG_CLK_CFG0_ENA_CODEC_ADC_CLK_Pos       18
#define AP_CFG_CLK_CFG0_ENA_CODEC_ADC_CLK_Msk       0x40000
#define AP_CFG_CLK_CFG0_ENA_CODEC_DAC_CLK_Pos       17
#define AP_CFG_CLK_CFG0_ENA_CODEC_DAC_CLK_Msk       0x20000
#define AP_CFG_CLK_CFG0_ENA_APC_CLK_Pos             16
#define AP_CFG_CLK_CFG0_ENA_APC_CLK_Msk             0x10000
#define AP_CFG_CLK_CFG0_ENA_VIDEO_CLK_Pos           15
#define AP_CFG_CLK_CFG0_ENA_VIDEO_CLK_Msk           0x8000
#define AP_CFG_CLK_CFG0_ENA_DMAC_GP_CLK_Pos         14
#define AP_CFG_CLK_CFG0_ENA_DMAC_GP_CLK_Msk         0x4000
#define AP_CFG_CLK_CFG0_ENA_CRYPTO_CLK_Pos          13
#define AP_CFG_CLK_CFG0_ENA_CRYPTO_CLK_Msk          0x2000
#define AP_CFG_CLK_CFG0_ENA_LUNA_CLK_Pos            12
#define AP_CFG_CLK_CFG0_ENA_LUNA_CLK_Msk            0x1000
#define AP_CFG_CLK_CFG0_SEL_I2S_MCLK_Pos            11
#define AP_CFG_CLK_CFG0_SEL_I2S_MCLK_Msk            0x800
#define AP_CFG_CLK_CFG0_ENA_I2S_CLK_Pos             10
#define AP_CFG_CLK_CFG0_ENA_I2S_CLK_Msk             0x400
#define AP_CFG_CLK_CFG0_DIV_AP_PERI_PCLK_LD_Pos     9
#define AP_CFG_CLK_CFG0_DIV_AP_PERI_PCLK_LD_Msk     0x200
#define AP_CFG_CLK_CFG0_DIV_AP_PERI_PCLK_N_Pos      5
#define AP_CFG_CLK_CFG0_DIV_AP_PERI_PCLK_N_Msk      0x1e0
#define AP_CFG_CLK_CFG0_DIV_AP_PERI_PCLK_M_Pos      0
#define AP_CFG_CLK_CFG0_DIV_AP_PERI_PCLK_M_Msk      0x1f

#define AP_CFG_CLK_CFG1_OFFSET                      0x00C
#define AP_CFG_CLK_CFG1_ENA_JPEG_CLK_Pos            31
#define AP_CFG_CLK_CFG1_ENA_JPEG_CLK_Msk            0x80000000
#define AP_CFG_CLK_CFG1_ENA_BLENDER_CLK_Pos         30
#define AP_CFG_CLK_CFG1_ENA_BLENDER_CLK_Msk         0x40000000
#define AP_CFG_CLK_CFG1_DIV_QSPI1_CLK_LD_Pos        29
#define AP_CFG_CLK_CFG1_DIV_QSPI1_CLK_LD_Msk        0x20000000
#define AP_CFG_CLK_CFG1_DIV_QSPI1_CLK_N_Pos         26
#define AP_CFG_CLK_CFG1_DIV_QSPI1_CLK_N_Msk         0x1c000000
#define AP_CFG_CLK_CFG1_DIV_QSPI1_CLK_M_Pos         22
#define AP_CFG_CLK_CFG1_DIV_QSPI1_CLK_M_Msk         0x3c00000
#define AP_CFG_CLK_CFG1_ENA_QSPI1_CLK_Pos           21
#define AP_CFG_CLK_CFG1_ENA_QSPI1_CLK_Msk           0x200000
#define AP_CFG_CLK_CFG1_SEL_QSPI1_CLK_Pos           20
#define AP_CFG_CLK_CFG1_SEL_QSPI1_CLK_Msk           0x100000
#define AP_CFG_CLK_CFG1_DIV_QSPI0_CLK_LD_Pos        19
#define AP_CFG_CLK_CFG1_DIV_QSPI0_CLK_LD_Msk        0x80000
#define AP_CFG_CLK_CFG1_DIV_QSPI0_CLK_N_Pos         16
#define AP_CFG_CLK_CFG1_DIV_QSPI0_CLK_N_Msk         0x70000
#define AP_CFG_CLK_CFG1_DIV_QSPI0_CLK_M_Pos         12
#define AP_CFG_CLK_CFG1_DIV_QSPI0_CLK_M_Msk         0xf000
#define AP_CFG_CLK_CFG1_ENA_QSPI0_CLK_Pos           11
#define AP_CFG_CLK_CFG1_ENA_QSPI0_CLK_Msk           0x800
#define AP_CFG_CLK_CFG1_SEL_QSPI0_CLK_Pos           10
#define AP_CFG_CLK_CFG1_SEL_QSPI0_CLK_Msk           0x400
#define AP_CFG_CLK_CFG1_DIV_SDIOH_CLK2X_LD_Pos      9
#define AP_CFG_CLK_CFG1_DIV_SDIOH_CLK2X_LD_Msk      0x200
#define AP_CFG_CLK_CFG1_DIV_SDIOH_CLK2X_N_Pos       6
#define AP_CFG_CLK_CFG1_DIV_SDIOH_CLK2X_N_Msk       0x1c0
#define AP_CFG_CLK_CFG1_DIV_SDIOH_CLK2X_M_Pos       2
#define AP_CFG_CLK_CFG1_DIV_SDIOH_CLK2X_M_Msk       0x3c
#define AP_CFG_CLK_CFG1_ENA_SDIOH_CLK_Pos           1
#define AP_CFG_CLK_CFG1_ENA_SDIOH_CLK_Msk           0x2
#define AP_CFG_CLK_CFG1_SEL_SDIOH_CLK2X_Pos         0
#define AP_CFG_CLK_CFG1_SEL_SDIOH_CLK2X_Msk         0x1

#define AP_CFG_ECC_CTRL_OFFSET                      0x010
#define AP_CFG_ECC_CTRL_AES_FIFO_SW_RST_Pos         4
#define AP_CFG_ECC_CTRL_AES_FIFO_SW_RST_Msk         0x10
#define AP_CFG_ECC_CTRL_ECC_ENGINE_EN_Pos           3
#define AP_CFG_ECC_CTRL_ECC_ENGINE_EN_Msk           0x8
#define AP_CFG_ECC_CTRL_ECC_KEY4_DISABLE_Pos        2
#define AP_CFG_ECC_CTRL_ECC_KEY4_DISABLE_Msk        0x4
#define AP_CFG_ECC_CTRL_ECC_D7_KEY_LOAD_Pos         1
#define AP_CFG_ECC_CTRL_ECC_D7_KEY_LOAD_Msk         0x2
#define AP_CFG_ECC_CTRL_ECC_B0_KEY_LOAD_Pos         0
#define AP_CFG_ECC_CTRL_ECC_B0_KEY_LOAD_Msk         0x1

#define AP_CFG_MCU_AP_RST_ADDR_OFFSET               0x014
#define AP_CFG_MCU_AP_RST_ADDR_RESET_VECTOR_Pos     0
#define AP_CFG_MCU_AP_RST_ADDR_RESET_VECTOR_Msk     0xffffffff

#define AP_CFG_MCU_AP_CFG_OFFSET                    0x018
#define AP_CFG_MCU_AP_CFG_DBG_STOPTIME_Pos          16
#define AP_CFG_MCU_AP_CFG_DBG_STOPTIME_Msk          0x10000
#define AP_CFG_MCU_AP_CFG_DBG_STOP_Pos              2
#define AP_CFG_MCU_AP_CFG_DBG_STOP_Msk              0x4
#define AP_CFG_MCU_AP_CFG_DBG_STOP_AT_BOOT_Pos      1
#define AP_CFG_MCU_AP_CFG_DBG_STOP_AT_BOOT_Msk      0x2
#define AP_CFG_MCU_AP_CFG_OVERRIDE_DM_SLEEP_Pos     0
#define AP_CFG_MCU_AP_CFG_OVERRIDE_DM_SLEEP_Msk     0x1

#define AP_CFG_DMA_SEL_OFFSET                       0x01C
#define AP_CFG_DMA_SEL_SEL_DVP_QSPI_Pos             1
#define AP_CFG_DMA_SEL_SEL_DVP_QSPI_Msk             0x2
#define AP_CFG_DMA_SEL_DMA_SEL_Pos                  0
#define AP_CFG_DMA_SEL_DMA_SEL_Msk                  0x1

struct AP_CFG_REG_SW_RESET_BITS
{
    volatile uint32_t MCU_CORE_RESET                : 1; // bit 0~0
    volatile uint32_t DMAC_GP_RESET                 : 1; // bit 1~1
    volatile uint32_t CRYPTO_RESET                  : 1; // bit 2~2
    volatile uint32_t VIDEO_RESET                   : 1; // bit 3~3
    volatile uint32_t SDIOH_RESET                   : 1; // bit 4~4
    volatile uint32_t I2S_RESET                     : 1; // bit 5~5
    volatile uint32_t CODEC_RESET                   : 1; // bit 6~6
    volatile uint32_t APC_RESET                     : 1; // bit 7~7
    volatile uint32_t LUNA_RESET                    : 1; // bit 8~8
    volatile uint32_t VIC_RESET                     : 1; // bit 9~9
    volatile uint32_t QSPI0_RESET                   : 1; // bit 10~10
    volatile uint32_t QSPI1_RESET                   : 1; // bit 11~11
    volatile uint32_t RGB_RESET                     : 1; // bit 12~12
    volatile uint32_t BLENDER_RESET                 : 1; // bit 13~13
    volatile uint32_t JPEG_RESET                    : 1; // bit 14~14
    volatile uint32_t RESV_15_15                    : 1; // bit 15~15
    volatile uint32_t SYSRSTREQ2AP_RST_EN           : 1; // bit 16~16
    volatile uint32_t APWDT2AP_RST_EN               : 1; // bit 17~17
    volatile uint32_t SYSRSTREQ2APSOC_RST_EN        : 1; // bit 18~18
    volatile uint32_t APSW2APSOC_RST_EN             : 1; // bit 19~19
    volatile uint32_t APWDT2APSOC_RST_EN            : 1; // bit 20~20
    volatile uint32_t RESV_21_31                    : 11; // bit 21~31
};

union AP_CFG_REG_SW_RESET {
    volatile uint32_t                               all;
    struct AP_CFG_REG_SW_RESET_BITS                 bit;
};

struct AP_CFG_REG_AP_RESET_BITS
{
    volatile uint32_t AP_RESET                      : 1; // bit 0~0
    volatile uint32_t RESV_1_31                     : 31; // bit 1~31
};

union AP_CFG_REG_AP_RESET {
    volatile uint32_t                               all;
    struct AP_CFG_REG_AP_RESET_BITS                 bit;
};

struct AP_CFG_REG_CLK_CFG0_BITS
{
    volatile uint32_t DIV_AP_PERI_PCLK_M            : 5; // bit 0~4
    volatile uint32_t DIV_AP_PERI_PCLK_N            : 4; // bit 5~8
    volatile uint32_t DIV_AP_PERI_PCLK_LD           : 1; // bit 9~9
    volatile uint32_t ENA_I2S_CLK                   : 1; // bit 10~10
    volatile uint32_t SEL_I2S_MCLK                  : 1; // bit 11~11
    volatile uint32_t ENA_LUNA_CLK                  : 1; // bit 12~12
    volatile uint32_t ENA_CRYPTO_CLK                : 1; // bit 13~13
    volatile uint32_t ENA_DMAC_GP_CLK               : 1; // bit 14~14
    volatile uint32_t ENA_VIDEO_CLK                 : 1; // bit 15~15
    volatile uint32_t ENA_APC_CLK                   : 1; // bit 16~16
    volatile uint32_t ENA_CODEC_DAC_CLK             : 1; // bit 17~17
    volatile uint32_t ENA_CODEC_ADC_CLK             : 1; // bit 18~18
    volatile uint32_t AUD_ADC_CLK_SRC               : 1; // bit 19~19
    volatile uint32_t AUD_DAC_MCLK_SRC              : 1; // bit 20~20
    volatile uint32_t ENA_VIC_CLK                   : 1; // bit 21~21
    volatile uint32_t SEL_VIC_CLK                   : 1; // bit 22~22
    volatile uint32_t ENA_RGB_CLK                   : 1; // bit 23~23
    volatile uint32_t SEL_RGB_CLK                   : 1; // bit 24~24
    volatile uint32_t DIV_RGB_CLK_M                 : 4; // bit 25~28
    volatile uint32_t DIV_RGB_CLK_LD                : 1; // bit 29~29
    volatile uint32_t SEL_RGB_INV_CLK               : 1; // bit 30~30
    volatile uint32_t RESV_31_31                    : 1; // bit 31~31
};

union AP_CFG_REG_CLK_CFG0 {
    volatile uint32_t                               all;
    struct AP_CFG_REG_CLK_CFG0_BITS                 bit;
};

struct AP_CFG_REG_CLK_CFG1_BITS
{
    volatile uint32_t SEL_SDIOH_CLK2X               : 1; // bit 0~0
    volatile uint32_t ENA_SDIOH_CLK                 : 1; // bit 1~1
    volatile uint32_t DIV_SDIOH_CLK2X_M             : 4; // bit 2~5
    volatile uint32_t DIV_SDIOH_CLK2X_N             : 3; // bit 6~8
    volatile uint32_t DIV_SDIOH_CLK2X_LD            : 1; // bit 9~9
    volatile uint32_t SEL_QSPI0_CLK                 : 1; // bit 10~10
    volatile uint32_t ENA_QSPI0_CLK                 : 1; // bit 11~11
    volatile uint32_t DIV_QSPI0_CLK_M               : 4; // bit 12~15
    volatile uint32_t DIV_QSPI0_CLK_N               : 3; // bit 16~18
    volatile uint32_t DIV_QSPI0_CLK_LD              : 1; // bit 19~19
    volatile uint32_t SEL_QSPI1_CLK                 : 1; // bit 20~20
    volatile uint32_t ENA_QSPI1_CLK                 : 1; // bit 21~21
    volatile uint32_t DIV_QSPI1_CLK_M               : 4; // bit 22~25
    volatile uint32_t DIV_QSPI1_CLK_N               : 3; // bit 26~28
    volatile uint32_t DIV_QSPI1_CLK_LD              : 1; // bit 29~29
    volatile uint32_t ENA_BLENDER_CLK               : 1; // bit 30~30
    volatile uint32_t ENA_JPEG_CLK                  : 1; // bit 31~31
};

union AP_CFG_REG_CLK_CFG1 {
    volatile uint32_t                               all;
    struct AP_CFG_REG_CLK_CFG1_BITS                 bit;
};

struct AP_CFG_REG_ECC_CTRL_BITS
{
    volatile uint32_t ECC_B0_KEY_LOAD               : 1; // bit 0~0
    volatile uint32_t ECC_D7_KEY_LOAD               : 1; // bit 1~1
    volatile uint32_t ECC_KEY4_DISABLE              : 1; // bit 2~2
    volatile uint32_t ECC_ENGINE_EN                 : 1; // bit 3~3
    volatile uint32_t AES_FIFO_SW_RST               : 1; // bit 4~4
    volatile uint32_t RESV_5_31                     : 27; // bit 5~31
};

union AP_CFG_REG_ECC_CTRL {
    volatile uint32_t                               all;
    struct AP_CFG_REG_ECC_CTRL_BITS                 bit;
};

struct AP_CFG_REG_MCU_AP_RST_ADDR_BITS
{
    volatile uint32_t RESET_VECTOR                  : 32; // bit 0~31
};

union AP_CFG_REG_MCU_AP_RST_ADDR {
    volatile uint32_t                               all;
    struct AP_CFG_REG_MCU_AP_RST_ADDR_BITS          bit;
};

struct AP_CFG_REG_MCU_AP_CFG_BITS
{
    volatile uint32_t OVERRIDE_DM_SLEEP             : 1; // bit 0~0
    volatile uint32_t DBG_STOP_AT_BOOT              : 1; // bit 1~1
    volatile uint32_t DBG_STOP                      : 1; // bit 2~2
    volatile uint32_t RESV_3_15                     : 13; // bit 3~15
    volatile uint32_t DBG_STOPTIME                  : 1; // bit 16~16
    volatile uint32_t RESV_17_31                    : 15; // bit 17~31
};

union AP_CFG_REG_MCU_AP_CFG {
    volatile uint32_t                               all;
    struct AP_CFG_REG_MCU_AP_CFG_BITS               bit;
};

struct AP_CFG_REG_DMA_SEL_BITS
{
    volatile uint32_t DMA_SEL                       : 1; // bit 0~0
    volatile uint32_t SEL_DVP_QSPI                  : 1; // bit 1~1
    volatile uint32_t RESV_2_31                     : 30; // bit 2~31
};

union AP_CFG_REG_DMA_SEL {
    volatile uint32_t                               all;
    struct AP_CFG_REG_DMA_SEL_BITS                  bit;
};

typedef struct
{
    union AP_CFG_REG_SW_RESET                       REG_SW_RESET; // 0x000
    union AP_CFG_REG_AP_RESET                       REG_AP_RESET; // 0x004
    union AP_CFG_REG_CLK_CFG0                       REG_CLK_CFG0; // 0x008
    union AP_CFG_REG_CLK_CFG1                       REG_CLK_CFG1; // 0x00C
    union AP_CFG_REG_ECC_CTRL                       REG_ECC_CTRL; // 0x010
    union AP_CFG_REG_MCU_AP_RST_ADDR                REG_MCU_AP_RST_ADDR; // 0x014
    union AP_CFG_REG_MCU_AP_CFG                     REG_MCU_AP_CFG; // 0x018
    union AP_CFG_REG_DMA_SEL                        REG_DMA_SEL; // 0x01C
} AP_CFG_RegDef;


#endif // __AP_CFG_REGFILE_H__

