//  ----------------------------------------------------------------------
//  File Name   : GenCFold/crypto_ecc_reg_arcs.h
//  Description : C header file generated by Python script.
//  Script Ver  £ºLS.AUTO_REG.2024.03.01
//  Create Time : 2024-06-20 11:17:02
//  Comments    : 
//  ----------------------------------------------------------------------

#ifndef __CRYPTO_ECC_REGFILE_H__
#define __CRYPTO_ECC_REGFILE_H__

#include <stdint.h>

#define CRYPTO_ECC_ELP_CLUE_CNTL_OFFSET             0x000
#define CRYPTO_ECC_ELP_CLUE_CNTL_CTRL_GO_Pos        31
#define CRYPTO_ECC_ELP_CLUE_CNTL_CTRL_GO_Msk        0x80000000
#define CRYPTO_ECC_ELP_CLUE_CNTL_CTRL_STOP_RQST_Pos    27
#define CRYPTO_ECC_ELP_CLUE_CNTL_CTRL_STOP_RQST_Msk    0x8000000
#define CRYPTO_ECC_ELP_CLUE_CNTL_CTRL_M521_MODE_Pos    16
#define CRYPTO_ECC_ELP_CLUE_CNTL_CTRL_M521_MODE_Msk    0x1f0000
#define CRYPTO_ECC_ELP_CLUE_CNTL_CTRL_BASE_RADIX_Pos    8
#define CRYPTO_ECC_ELP_CLUE_CNTL_CTRL_BASE_RADIX_Msk    0x700
#define CRYPTO_ECC_ELP_CLUE_CNTL_CTRL_PARTIAL_RADIX_Pos    0
#define CRYPTO_ECC_ELP_CLUE_CNTL_CTRL_PARTIAL_RADIX_Msk    0xff

#define CRYPTO_ECC_ELP_CLUE_NEXT_FETCH_OFFSET       0x004
#define CRYPTO_ECC_ELP_CLUE_NEXT_FETCH_PROG_ADDR_Pos    0
#define CRYPTO_ECC_ELP_CLUE_NEXT_FETCH_PROG_ADDR_Msk    0x3ff

#define CRYPTO_ECC_ELP_CLUE_RET_CODE_OFFSET         0x008
#define CRYPTO_ECC_ELP_CLUE_RET_CODE_RC_BUSY_Pos    31
#define CRYPTO_ECC_ELP_CLUE_RET_CODE_RC_BUSY_Msk    0x80000000
#define CRYPTO_ECC_ELP_CLUE_RET_CODE_RC_IRQ_Pos     30
#define CRYPTO_ECC_ELP_CLUE_RET_CODE_RC_IRQ_Msk     0x40000000
#define CRYPTO_ECC_ELP_CLUE_RET_CODE_RC_WR_PENDING_Pos    29
#define CRYPTO_ECC_ELP_CLUE_RET_CODE_RC_WR_PENDING_Msk    0x20000000
#define CRYPTO_ECC_ELP_CLUE_RET_CODE_RC_ZERO_Pos    28
#define CRYPTO_ECC_ELP_CLUE_RET_CODE_RC_ZERO_Msk    0x10000000
#define CRYPTO_ECC_ELP_CLUE_RET_CODE_RC_DPA_EN_Pos    27
#define CRYPTO_ECC_ELP_CLUE_RET_CODE_RC_DPA_EN_Msk    0x8000000
#define CRYPTO_ECC_ELP_CLUE_RET_CODE_RC_STOP_REASON_Pos    16
#define CRYPTO_ECC_ELP_CLUE_RET_CODE_RC_STOP_REASON_Msk    0xff0000

#define CRYPTO_ECC_ELP_CLUE_BUILD_CFG_OFFSET        0x00C
#define CRYPTO_ECC_ELP_CLUE_BUILD_CFG_BC_FORMAT_TYPE_Pos    30
#define CRYPTO_ECC_ELP_CLUE_BUILD_CFG_BC_FORMAT_TYPE_Msk    0xc0000000
#define CRYPTO_ECC_ELP_CLUE_BUILD_CFG_BC_ALU_SIZE_Pos    19
#define CRYPTO_ECC_ELP_CLUE_BUILD_CFG_BC_ALU_SIZE_Msk    0x180000
#define CRYPTO_ECC_ELP_CLUE_BUILD_CFG_BC_RSA_SIZE_Pos    16
#define CRYPTO_ECC_ELP_CLUE_BUILD_CFG_BC_RSA_SIZE_Msk    0x70000
#define CRYPTO_ECC_ELP_CLUE_BUILD_CFG_BC_ECC_SIZE_Pos    14
#define CRYPTO_ECC_ELP_CLUE_BUILD_CFG_BC_ECC_SIZE_Msk    0xc000
#define CRYPTO_ECC_ELP_CLUE_BUILD_CFG_BC_FW_MIX_Pos    12
#define CRYPTO_ECC_ELP_CLUE_BUILD_CFG_BC_FW_MIX_Msk    0x3000
#define CRYPTO_ECC_ELP_CLUE_BUILD_CFG_BC_FW_ROM_Pos    10
#define CRYPTO_ECC_ELP_CLUE_BUILD_CFG_BC_FW_ROM_Msk    0xc00
#define CRYPTO_ECC_ELP_CLUE_BUILD_CFG_BC_FW_RAM_Pos    8
#define CRYPTO_ECC_ELP_CLUE_BUILD_CFG_BC_FW_RAM_Msk    0x300
#define CRYPTO_ECC_ELP_CLUE_BUILD_CFG_BC_BANK_SW_D_Pos    6
#define CRYPTO_ECC_ELP_CLUE_BUILD_CFG_BC_BANK_SW_D_Msk    0xc0
#define CRYPTO_ECC_ELP_CLUE_BUILD_CFG_BC_BANK_SW_C_Pos    4
#define CRYPTO_ECC_ELP_CLUE_BUILD_CFG_BC_BANK_SW_C_Msk    0x30
#define CRYPTO_ECC_ELP_CLUE_BUILD_CFG_BC_BANK_SW_B_Pos    2
#define CRYPTO_ECC_ELP_CLUE_BUILD_CFG_BC_BANK_SW_B_Msk    0xc
#define CRYPTO_ECC_ELP_CLUE_BUILD_CFG_BC_BANK_SW_A_Pos    0
#define CRYPTO_ECC_ELP_CLUE_BUILD_CFG_BC_BANK_SW_A_Msk    0x3

#define CRYPTO_ECC_ELP_CLUE_STACK_OFFSET            0x010
#define CRYPTO_ECC_ELP_CLUE_STACK_SEQ_TOS_Pos       16
#define CRYPTO_ECC_ELP_CLUE_STACK_SEQ_TOS_Msk       0xfff0000
#define CRYPTO_ECC_ELP_CLUE_STACK_MAX_STACK_DEPTH_Pos    8
#define CRYPTO_ECC_ELP_CLUE_STACK_MAX_STACK_DEPTH_Msk    0xf00
#define CRYPTO_ECC_ELP_CLUE_STACK_FSTACK_POINTER_Pos    0
#define CRYPTO_ECC_ELP_CLUE_STACK_FSTACK_POINTER_Msk    0xf

#define CRYPTO_ECC_ELP_CLUE_INSTRUCTIONS_SINCE_GO_OFFSET    0x014
#define CRYPTO_ECC_ELP_CLUE_INSTRUCTIONS_SINCE_GO_INSTRUCTIONS_SINCE_GO_Pos    0
#define CRYPTO_ECC_ELP_CLUE_INSTRUCTIONS_SINCE_GO_INSTRUCTIONS_SINCE_GO_Msk    0xffffffff

#define CRYPTO_ECC_ELP_CLUE_PSTACK_OFFSET           0x018
#define CRYPTO_ECC_ELP_CLUE_PSTACK_PSTACK_POINTER_Pos    0
#define CRYPTO_ECC_ELP_CLUE_PSTACK_PSTACK_POINTER_Msk    0x3f

#define CRYPTO_ECC_ELP_CLUE_CONFIG_OFFSET           0x01C
#define CRYPTO_ECC_ELP_CLUE_CONFIG_CFG_ENDIAN_BYTE_SWAP_Pos    26
#define CRYPTO_ECC_ELP_CLUE_CONFIG_CFG_ENDIAN_BYTE_SWAP_Msk    0x4000000
#define CRYPTO_ECC_ELP_CLUE_CONFIG_CFG_DPA_ALT_ACCESS_Pos    0
#define CRYPTO_ECC_ELP_CLUE_CONFIG_CFG_DPA_ALT_ACCESS_Msk    0x1

#define CRYPTO_ECC_ELP_CLUE_STAT_OFFSET             0x020
#define CRYPTO_ECC_ELP_CLUE_STAT_STAT_IRQ_Pos       30
#define CRYPTO_ECC_ELP_CLUE_STAT_STAT_IRQ_Msk       0x40000000

#define CRYPTO_ECC_ELP_CLUE_FLAGS_OFFSET            0x024
#define CRYPTO_ECC_ELP_CLUE_FLAGS_FLAG_F3_Pos       7
#define CRYPTO_ECC_ELP_CLUE_FLAGS_FLAG_F3_Msk       0x80
#define CRYPTO_ECC_ELP_CLUE_FLAGS_FLAG_F2_Pos       6
#define CRYPTO_ECC_ELP_CLUE_FLAGS_FLAG_F2_Msk       0x40
#define CRYPTO_ECC_ELP_CLUE_FLAGS_FLAG_F1_Pos       5
#define CRYPTO_ECC_ELP_CLUE_FLAGS_FLAG_F1_Msk       0x20
#define CRYPTO_ECC_ELP_CLUE_FLAGS_FLAG_F0_Pos       4
#define CRYPTO_ECC_ELP_CLUE_FLAGS_FLAG_F0_Msk       0x10
#define CRYPTO_ECC_ELP_CLUE_FLAGS_FLAG_CARRY_Pos    3
#define CRYPTO_ECC_ELP_CLUE_FLAGS_FLAG_CARRY_Msk    0x8
#define CRYPTO_ECC_ELP_CLUE_FLAGS_FLAG_BORROW_Pos    2
#define CRYPTO_ECC_ELP_CLUE_FLAGS_FLAG_BORROW_Msk    0x4
#define CRYPTO_ECC_ELP_CLUE_FLAGS_FLAG_MEMBIT_Pos    1
#define CRYPTO_ECC_ELP_CLUE_FLAGS_FLAG_MEMBIT_Msk    0x2
#define CRYPTO_ECC_ELP_CLUE_FLAGS_FLAG_ZERO_Pos     0
#define CRYPTO_ECC_ELP_CLUE_FLAGS_FLAG_ZERO_Msk     0x1

#define CRYPTO_ECC_ELP_CLUE_CYCLES_UNTIL_HALT_OFFSET    0x028
#define CRYPTO_ECC_ELP_CLUE_CYCLES_UNTIL_HALT_INSTRUCTIONS_UNTIL_HALT_Pos    0
#define CRYPTO_ECC_ELP_CLUE_CYCLES_UNTIL_HALT_INSTRUCTIONS_UNTIL_HALT_Msk    0xffffffff

#define CRYPTO_ECC_ELP_CLUE_CYCLES_SINCE_GO_OFFSET    0x02C
#define CRYPTO_ECC_ELP_CLUE_CYCLES_SINCE_GO_CYCLES_SINCE_GO_Pos    0
#define CRYPTO_ECC_ELP_CLUE_CYCLES_SINCE_GO_CYCLES_SINCE_GO_Msk    0xffffffff

#define CRYPTO_ECC_ELP_CLUE_IDX_I_OFFSET            0x030
#define CRYPTO_ECC_ELP_CLUE_IDX_I_INDEX_I_Pos       0
#define CRYPTO_ECC_ELP_CLUE_IDX_I_INDEX_I_Msk       0xffff

#define CRYPTO_ECC_ELP_CLUE_IDX_J_OFFSET            0x034
#define CRYPTO_ECC_ELP_CLUE_IDX_J_INDEX_J_Pos       0
#define CRYPTO_ECC_ELP_CLUE_IDX_J_INDEX_J_Msk       0xffff

#define CRYPTO_ECC_ELP_CLUE_IDX_K_OFFSET            0x038
#define CRYPTO_ECC_ELP_CLUE_IDX_K_INDEX_K_Pos       0
#define CRYPTO_ECC_ELP_CLUE_IDX_K_INDEX_K_Msk       0xffff

#define CRYPTO_ECC_ELP_CLUE_IDX_L_OFFSET            0x03C
#define CRYPTO_ECC_ELP_CLUE_IDX_L_INDEX_L_Pos       0
#define CRYPTO_ECC_ELP_CLUE_IDX_L_INDEX_L_Msk       0xffff

#define CRYPTO_ECC_ELP_CLUE_IE_OFFSET               0x040
#define CRYPTO_ECC_ELP_CLUE_IE_IE_IRQ_EN_Pos        30
#define CRYPTO_ECC_ELP_CLUE_IE_IE_IRQ_EN_Msk        0x40000000

#define CRYPTO_ECC_ELP_CLUE_PROBABILITY_VALUE_OFFSET    0x044
#define CRYPTO_ECC_ELP_CLUE_PROBABILITY_VALUE_JUMP_PROBABILITY_Pos    0
#define CRYPTO_ECC_ELP_CLUE_PROBABILITY_VALUE_JUMP_PROBABILITY_Msk    0x1fff

#define CRYPTO_ECC_ELP_CLUE_PROBABILITY_SEED_OFFSET    0x048
#define CRYPTO_ECC_ELP_CLUE_PROBABILITY_SEED_PROBABILITY_LFSE_SEED_Pos    0
#define CRYPTO_ECC_ELP_CLUE_PROBABILITY_SEED_PROBABILITY_LFSE_SEED_Msk    0x1fff

#define CRYPTO_ECC_ELP_CLUE_BANK_SWITCH_A_OFFSET    0x050
#define CRYPTO_ECC_ELP_CLUE_BANK_SWITCH_A_BANK_SW_A_Pos    0
#define CRYPTO_ECC_ELP_CLUE_BANK_SWITCH_A_BANK_SW_A_Msk    0x3

#define CRYPTO_ECC_ELP_CLUE_BANK_SWITCH_B_OFFSET    0x054
#define CRYPTO_ECC_ELP_CLUE_BANK_SWITCH_B_BANK_SW_B_Pos    0
#define CRYPTO_ECC_ELP_CLUE_BANK_SWITCH_B_BANK_SW_B_Msk    0x3

#define CRYPTO_ECC_ELP_CLUE_BANK_SWITCH_C_OFFSET    0x058
#define CRYPTO_ECC_ELP_CLUE_BANK_SWITCH_C_BANK_SW_C_Pos    0
#define CRYPTO_ECC_ELP_CLUE_BANK_SWITCH_C_BANK_SW_C_Msk    0x3

#define CRYPTO_ECC_ELP_CLUE_BANK_SWITCH_D_OFFSET    0x05C
#define CRYPTO_ECC_ELP_CLUE_BANK_SWITCH_D_BANK_SW_D_Pos    0
#define CRYPTO_ECC_ELP_CLUE_BANK_SWITCH_D_BANK_SW_D_Msk    0x3

struct CRYPTO_ECC_REG_ELP_CLUE_CNTL_BITS
{
    volatile uint32_t CTRL_PARTIAL_RADIX            : 8; // bit 0~7
    volatile uint32_t CTRL_BASE_RADIX               : 3; // bit 8~10
    volatile uint32_t RESV_11_15                    : 5; // bit 11~15
    volatile uint32_t CTRL_M521_MODE                : 5; // bit 16~20
    volatile uint32_t RESV_21_26                    : 6; // bit 21~26
    volatile uint32_t CTRL_STOP_RQST                : 1; // bit 27~27
    volatile uint32_t RESV_28_30                    : 3; // bit 28~30
    volatile uint32_t CTRL_GO                       : 1; // bit 31~31
};

union CRYPTO_ECC_REG_ELP_CLUE_CNTL {
    volatile uint32_t                               all;
    struct CRYPTO_ECC_REG_ELP_CLUE_CNTL_BITS        bit;
};

struct CRYPTO_ECC_REG_ELP_CLUE_NEXT_FETCH_BITS
{
    volatile uint32_t PROG_ADDR                     : 10; // bit 0~9
    volatile uint32_t RESV_10_31                    : 22; // bit 10~31
};

union CRYPTO_ECC_REG_ELP_CLUE_NEXT_FETCH {
    volatile uint32_t                               all;
    struct CRYPTO_ECC_REG_ELP_CLUE_NEXT_FETCH_BITS    bit;
};

struct CRYPTO_ECC_REG_ELP_CLUE_RET_CODE_BITS
{
    volatile uint32_t RESV_0_15                     : 16; // bit 0~15
    volatile uint32_t RC_STOP_REASON                : 8; // bit 16~23
    volatile uint32_t RESV_24_26                    : 3; // bit 24~26
    volatile uint32_t RC_DPA_EN                     : 1; // bit 27~27
    volatile uint32_t RC_ZERO                       : 1; // bit 28~28
    volatile uint32_t RC_WR_PENDING                 : 1; // bit 29~29
    volatile uint32_t RC_IRQ                        : 1; // bit 30~30
    volatile uint32_t RC_BUSY                       : 1; // bit 31~31
};

union CRYPTO_ECC_REG_ELP_CLUE_RET_CODE {
    volatile uint32_t                               all;
    struct CRYPTO_ECC_REG_ELP_CLUE_RET_CODE_BITS    bit;
};

struct CRYPTO_ECC_REG_ELP_CLUE_BUILD_CFG_BITS
{
    volatile uint32_t BC_BANK_SW_A                  : 2; // bit 0~1
    volatile uint32_t BC_BANK_SW_B                  : 2; // bit 2~3
    volatile uint32_t BC_BANK_SW_C                  : 2; // bit 4~5
    volatile uint32_t BC_BANK_SW_D                  : 2; // bit 6~7
    volatile uint32_t BC_FW_RAM                     : 2; // bit 8~9
    volatile uint32_t BC_FW_ROM                     : 2; // bit 10~11
    volatile uint32_t BC_FW_MIX                     : 2; // bit 12~13
    volatile uint32_t BC_ECC_SIZE                   : 2; // bit 14~15
    volatile uint32_t BC_RSA_SIZE                   : 3; // bit 16~18
    volatile uint32_t BC_ALU_SIZE                   : 2; // bit 19~20
    volatile uint32_t RESV_21_29                    : 9; // bit 21~29
    volatile uint32_t BC_FORMAT_TYPE                : 2; // bit 30~31
};

union CRYPTO_ECC_REG_ELP_CLUE_BUILD_CFG {
    volatile uint32_t                               all;
    struct CRYPTO_ECC_REG_ELP_CLUE_BUILD_CFG_BITS    bit;
};

struct CRYPTO_ECC_REG_ELP_CLUE_STACK_BITS
{
    volatile uint32_t FSTACK_POINTER                : 4; // bit 0~3
    volatile uint32_t RESV_4_7                      : 4; // bit 4~7
    volatile uint32_t MAX_STACK_DEPTH               : 4; // bit 8~11
    volatile uint32_t RESV_12_15                    : 4; // bit 12~15
    volatile uint32_t SEQ_TOS                       : 12; // bit 16~27
    volatile uint32_t RESV_28_31                    : 4; // bit 28~31
};

union CRYPTO_ECC_REG_ELP_CLUE_STACK {
    volatile uint32_t                               all;
    struct CRYPTO_ECC_REG_ELP_CLUE_STACK_BITS       bit;
};

struct CRYPTO_ECC_REG_ELP_CLUE_INSTRUCTIONS_SINCE_GO_BITS
{
    volatile uint32_t INSTRUCTIONS_SINCE_GO         : 32; // bit 0~31
};

union CRYPTO_ECC_REG_ELP_CLUE_INSTRUCTIONS_SINCE_GO {
    volatile uint32_t                               all;
    struct CRYPTO_ECC_REG_ELP_CLUE_INSTRUCTIONS_SINCE_GO_BITS    bit;
};

struct CRYPTO_ECC_REG_ELP_CLUE_PSTACK_BITS
{
    volatile uint32_t PSTACK_POINTER                : 6; // bit 0~5
    volatile uint32_t RESV_6_31                     : 26; // bit 6~31
};

union CRYPTO_ECC_REG_ELP_CLUE_PSTACK {
    volatile uint32_t                               all;
    struct CRYPTO_ECC_REG_ELP_CLUE_PSTACK_BITS      bit;
};

struct CRYPTO_ECC_REG_ELP_CLUE_CONFIG_BITS
{
    volatile uint32_t CFG_DPA_ALT_ACCESS            : 1; // bit 0~0
    volatile uint32_t RESV_1_25                     : 25; // bit 1~25
    volatile uint32_t CFG_ENDIAN_BYTE_SWAP          : 1; // bit 26~26
    volatile uint32_t RESV_27_31                    : 5; // bit 27~31
};

union CRYPTO_ECC_REG_ELP_CLUE_CONFIG {
    volatile uint32_t                               all;
    struct CRYPTO_ECC_REG_ELP_CLUE_CONFIG_BITS      bit;
};

struct CRYPTO_ECC_REG_ELP_CLUE_STAT_BITS
{
    volatile uint32_t RESV_0_29                     : 30; // bit 0~29
    volatile uint32_t STAT_IRQ                      : 1; // bit 30~30
    volatile uint32_t RESV_31_31                    : 1; // bit 31~31
};

union CRYPTO_ECC_REG_ELP_CLUE_STAT {
    volatile uint32_t                               all;
    struct CRYPTO_ECC_REG_ELP_CLUE_STAT_BITS        bit;
};

struct CRYPTO_ECC_REG_ELP_CLUE_FLAGS_BITS
{
    volatile uint32_t FLAG_ZERO                     : 1; // bit 0~0
    volatile uint32_t FLAG_MEMBIT                   : 1; // bit 1~1
    volatile uint32_t FLAG_BORROW                   : 1; // bit 2~2
    volatile uint32_t FLAG_CARRY                    : 1; // bit 3~3
    volatile uint32_t FLAG_F0                       : 1; // bit 4~4
    volatile uint32_t FLAG_F1                       : 1; // bit 5~5
    volatile uint32_t FLAG_F2                       : 1; // bit 6~6
    volatile uint32_t FLAG_F3                       : 1; // bit 7~7
    volatile uint32_t RESV_8_31                     : 24; // bit 8~31
};

union CRYPTO_ECC_REG_ELP_CLUE_FLAGS {
    volatile uint32_t                               all;
    struct CRYPTO_ECC_REG_ELP_CLUE_FLAGS_BITS       bit;
};

struct CRYPTO_ECC_REG_ELP_CLUE_CYCLES_UNTIL_HALT_BITS
{
    volatile uint32_t INSTRUCTIONS_UNTIL_HALT       : 32; // bit 0~31
};

union CRYPTO_ECC_REG_ELP_CLUE_CYCLES_UNTIL_HALT {
    volatile uint32_t                               all;
    struct CRYPTO_ECC_REG_ELP_CLUE_CYCLES_UNTIL_HALT_BITS    bit;
};

struct CRYPTO_ECC_REG_ELP_CLUE_CYCLES_SINCE_GO_BITS
{
    volatile uint32_t CYCLES_SINCE_GO               : 32; // bit 0~31
};

union CRYPTO_ECC_REG_ELP_CLUE_CYCLES_SINCE_GO {
    volatile uint32_t                               all;
    struct CRYPTO_ECC_REG_ELP_CLUE_CYCLES_SINCE_GO_BITS    bit;
};

struct CRYPTO_ECC_REG_ELP_CLUE_IDX_I_BITS
{
    volatile uint32_t INDEX_I                       : 16; // bit 0~15
    volatile uint32_t RESV_16_31                    : 16; // bit 16~31
};

union CRYPTO_ECC_REG_ELP_CLUE_IDX_I {
    volatile uint32_t                               all;
    struct CRYPTO_ECC_REG_ELP_CLUE_IDX_I_BITS       bit;
};

struct CRYPTO_ECC_REG_ELP_CLUE_IDX_J_BITS
{
    volatile uint32_t INDEX_J                       : 16; // bit 0~15
    volatile uint32_t RESV_16_31                    : 16; // bit 16~31
};

union CRYPTO_ECC_REG_ELP_CLUE_IDX_J {
    volatile uint32_t                               all;
    struct CRYPTO_ECC_REG_ELP_CLUE_IDX_J_BITS       bit;
};

struct CRYPTO_ECC_REG_ELP_CLUE_IDX_K_BITS
{
    volatile uint32_t INDEX_K                       : 16; // bit 0~15
    volatile uint32_t RESV_16_31                    : 16; // bit 16~31
};

union CRYPTO_ECC_REG_ELP_CLUE_IDX_K {
    volatile uint32_t                               all;
    struct CRYPTO_ECC_REG_ELP_CLUE_IDX_K_BITS       bit;
};

struct CRYPTO_ECC_REG_ELP_CLUE_IDX_L_BITS
{
    volatile uint32_t INDEX_L                       : 16; // bit 0~15
    volatile uint32_t RESV_16_31                    : 16; // bit 16~31
};

union CRYPTO_ECC_REG_ELP_CLUE_IDX_L {
    volatile uint32_t                               all;
    struct CRYPTO_ECC_REG_ELP_CLUE_IDX_L_BITS       bit;
};

struct CRYPTO_ECC_REG_ELP_CLUE_IE_BITS
{
    volatile uint32_t RESV_0_29                     : 30; // bit 0~29
    volatile uint32_t IE_IRQ_EN                     : 1; // bit 30~30
    volatile uint32_t RESV_31_31                    : 1; // bit 31~31
};

union CRYPTO_ECC_REG_ELP_CLUE_IE {
    volatile uint32_t                               all;
    struct CRYPTO_ECC_REG_ELP_CLUE_IE_BITS          bit;
};

struct CRYPTO_ECC_REG_ELP_CLUE_PROBABILITY_VALUE_BITS
{
    volatile uint32_t JUMP_PROBABILITY              : 13; // bit 0~12
    volatile uint32_t RESV_13_31                    : 19; // bit 13~31
};

union CRYPTO_ECC_REG_ELP_CLUE_PROBABILITY_VALUE {
    volatile uint32_t                               all;
    struct CRYPTO_ECC_REG_ELP_CLUE_PROBABILITY_VALUE_BITS    bit;
};

struct CRYPTO_ECC_REG_ELP_CLUE_PROBABILITY_SEED_BITS
{
    volatile uint32_t PROBABILITY_LFSE_SEED         : 13; // bit 0~12
    volatile uint32_t RESV_13_31                    : 19; // bit 13~31
};

union CRYPTO_ECC_REG_ELP_CLUE_PROBABILITY_SEED {
    volatile uint32_t                               all;
    struct CRYPTO_ECC_REG_ELP_CLUE_PROBABILITY_SEED_BITS    bit;
};

struct CRYPTO_ECC_REG_ELP_CLUE_BANK_SWITCH_A_BITS
{
    volatile uint32_t BANK_SW_A                     : 2; // bit 0~1
    volatile uint32_t RESV_2_31                     : 30; // bit 2~31
};

union CRYPTO_ECC_REG_ELP_CLUE_BANK_SWITCH_A {
    volatile uint32_t                               all;
    struct CRYPTO_ECC_REG_ELP_CLUE_BANK_SWITCH_A_BITS    bit;
};

struct CRYPTO_ECC_REG_ELP_CLUE_BANK_SWITCH_B_BITS
{
    volatile uint32_t BANK_SW_B                     : 2; // bit 0~1
    volatile uint32_t RESV_2_31                     : 30; // bit 2~31
};

union CRYPTO_ECC_REG_ELP_CLUE_BANK_SWITCH_B {
    volatile uint32_t                               all;
    struct CRYPTO_ECC_REG_ELP_CLUE_BANK_SWITCH_B_BITS    bit;
};

struct CRYPTO_ECC_REG_ELP_CLUE_BANK_SWITCH_C_BITS
{
    volatile uint32_t BANK_SW_C                     : 2; // bit 0~1
    volatile uint32_t RESV_2_31                     : 30; // bit 2~31
};

union CRYPTO_ECC_REG_ELP_CLUE_BANK_SWITCH_C {
    volatile uint32_t                               all;
    struct CRYPTO_ECC_REG_ELP_CLUE_BANK_SWITCH_C_BITS    bit;
};

struct CRYPTO_ECC_REG_ELP_CLUE_BANK_SWITCH_D_BITS
{
    volatile uint32_t BANK_SW_D                     : 2; // bit 0~1
    volatile uint32_t RESV_2_31                     : 30; // bit 2~31
};

union CRYPTO_ECC_REG_ELP_CLUE_BANK_SWITCH_D {
    volatile uint32_t                               all;
    struct CRYPTO_ECC_REG_ELP_CLUE_BANK_SWITCH_D_BITS    bit;
};

typedef struct
{
    union CRYPTO_ECC_REG_ELP_CLUE_CNTL              REG_ELP_CLUE_CNTL; // 0x000
    union CRYPTO_ECC_REG_ELP_CLUE_NEXT_FETCH        REG_ELP_CLUE_NEXT_FETCH; // 0x004
    union CRYPTO_ECC_REG_ELP_CLUE_RET_CODE          REG_ELP_CLUE_RET_CODE; // 0x008
    union CRYPTO_ECC_REG_ELP_CLUE_BUILD_CFG         REG_ELP_CLUE_BUILD_CFG; // 0x00C
    union CRYPTO_ECC_REG_ELP_CLUE_STACK             REG_ELP_CLUE_STACK; // 0x010
    union CRYPTO_ECC_REG_ELP_CLUE_INSTRUCTIONS_SINCE_GO    REG_ELP_CLUE_INSTRUCTIONS_SINCE_GO; // 0x014
    union CRYPTO_ECC_REG_ELP_CLUE_PSTACK            REG_ELP_CLUE_PSTACK; // 0x018
    union CRYPTO_ECC_REG_ELP_CLUE_CONFIG            REG_ELP_CLUE_CONFIG; // 0x01C
    union CRYPTO_ECC_REG_ELP_CLUE_STAT              REG_ELP_CLUE_STAT; // 0x020
    union CRYPTO_ECC_REG_ELP_CLUE_FLAGS             REG_ELP_CLUE_FLAGS; // 0x024
    union CRYPTO_ECC_REG_ELP_CLUE_CYCLES_UNTIL_HALT    REG_ELP_CLUE_CYCLES_UNTIL_HALT; // 0x028
    union CRYPTO_ECC_REG_ELP_CLUE_CYCLES_SINCE_GO    REG_ELP_CLUE_CYCLES_SINCE_GO; // 0x02C
    union CRYPTO_ECC_REG_ELP_CLUE_IDX_I             REG_ELP_CLUE_IDX_I; // 0x030
    union CRYPTO_ECC_REG_ELP_CLUE_IDX_J             REG_ELP_CLUE_IDX_J; // 0x034
    union CRYPTO_ECC_REG_ELP_CLUE_IDX_K             REG_ELP_CLUE_IDX_K; // 0x038
    union CRYPTO_ECC_REG_ELP_CLUE_IDX_L             REG_ELP_CLUE_IDX_L; // 0x03C
    union CRYPTO_ECC_REG_ELP_CLUE_IE                REG_ELP_CLUE_IE; // 0x040
    union CRYPTO_ECC_REG_ELP_CLUE_PROBABILITY_VALUE    REG_ELP_CLUE_PROBABILITY_VALUE; // 0x044
    union CRYPTO_ECC_REG_ELP_CLUE_PROBABILITY_SEED    REG_ELP_CLUE_PROBABILITY_SEED; // 0x048
    volatile uint32_t                               REG_RESV_0X4C_0X4C[1];
    union CRYPTO_ECC_REG_ELP_CLUE_BANK_SWITCH_A     REG_ELP_CLUE_BANK_SWITCH_A; // 0x050
    union CRYPTO_ECC_REG_ELP_CLUE_BANK_SWITCH_B     REG_ELP_CLUE_BANK_SWITCH_B; // 0x054
    union CRYPTO_ECC_REG_ELP_CLUE_BANK_SWITCH_C     REG_ELP_CLUE_BANK_SWITCH_C; // 0x058
    union CRYPTO_ECC_REG_ELP_CLUE_BANK_SWITCH_D     REG_ELP_CLUE_BANK_SWITCH_D; // 0x05C
} CRYPTO_ECC_RegDef;


#endif // __CRYPTO_ECC_REGFILE_H__

