//  ----------------------------------------------------------------------
//  File Name   : GenCFold/qspi_sensor_in_reg_arcs.h
//  Description : C header file generated by Python script.
//  Script Ver  £ºLS.AUTO_REG.2024.03.01
//  Create Time : 2024-06-20 11:17:02
//  Comments    : 
//  ----------------------------------------------------------------------

#ifndef __QSPI_SENSOR_IN_REGFILE_H__
#define __QSPI_SENSOR_IN_REGFILE_H__

#include <stdint.h>

#define QSPI_SENSOR_IN_IDREV_OFFSET                 0x000
#define QSPI_SENSOR_IN_IDREV_ID_Pos                 12
#define QSPI_SENSOR_IN_IDREV_ID_Msk                 0xfffff000
#define QSPI_SENSOR_IN_IDREV_REVMAJOR_Pos           4
#define QSPI_SENSOR_IN_IDREV_REVMAJOR_Msk           0xff0
#define QSPI_SENSOR_IN_IDREV_REVMINOR_Pos           0
#define QSPI_SENSOR_IN_IDREV_REVMINOR_Msk           0xf

#define QSPI_SENSOR_IN_TRANSFMT_OFFSET              0x010
#define QSPI_SENSOR_IN_TRANSFMT_ADDRLEN_Pos         16
#define QSPI_SENSOR_IN_TRANSFMT_ADDRLEN_Msk         0x30000
#define QSPI_SENSOR_IN_TRANSFMT_DATALEN_Pos         8
#define QSPI_SENSOR_IN_TRANSFMT_DATALEN_Msk         0x1f00
#define QSPI_SENSOR_IN_TRANSFMT_DATAMERGE_Pos       7
#define QSPI_SENSOR_IN_TRANSFMT_DATAMERGE_Msk       0x80
#define QSPI_SENSOR_IN_TRANSFMT_MOSIBIDIR_Pos       4
#define QSPI_SENSOR_IN_TRANSFMT_MOSIBIDIR_Msk       0x10
#define QSPI_SENSOR_IN_TRANSFMT_LSB_Pos             3
#define QSPI_SENSOR_IN_TRANSFMT_LSB_Msk             0x8
#define QSPI_SENSOR_IN_TRANSFMT_SLVMODE_Pos         2
#define QSPI_SENSOR_IN_TRANSFMT_SLVMODE_Msk         0x4
#define QSPI_SENSOR_IN_TRANSFMT_CPOL_Pos            1
#define QSPI_SENSOR_IN_TRANSFMT_CPOL_Msk            0x2
#define QSPI_SENSOR_IN_TRANSFMT_CPHA_Pos            0
#define QSPI_SENSOR_IN_TRANSFMT_CPHA_Msk            0x1

#define QSPI_SENSOR_IN_DIRECTIO_OFFSET              0x014
#define QSPI_SENSOR_IN_DIRECTIO_DIRECTIOEN_Pos      24
#define QSPI_SENSOR_IN_DIRECTIO_DIRECTIOEN_Msk      0x1000000
#define QSPI_SENSOR_IN_DIRECTIO_HOLD_OE_Pos         21
#define QSPI_SENSOR_IN_DIRECTIO_HOLD_OE_Msk         0x200000
#define QSPI_SENSOR_IN_DIRECTIO_WP_OE_Pos           20
#define QSPI_SENSOR_IN_DIRECTIO_WP_OE_Msk           0x100000
#define QSPI_SENSOR_IN_DIRECTIO_MISO_OE_Pos         19
#define QSPI_SENSOR_IN_DIRECTIO_MISO_OE_Msk         0x80000
#define QSPI_SENSOR_IN_DIRECTIO_MOSI_OE_Pos         18
#define QSPI_SENSOR_IN_DIRECTIO_MOSI_OE_Msk         0x40000
#define QSPI_SENSOR_IN_DIRECTIO_SCLK_OE_Pos         17
#define QSPI_SENSOR_IN_DIRECTIO_SCLK_OE_Msk         0x20000
#define QSPI_SENSOR_IN_DIRECTIO_CS_OE_Pos           16
#define QSPI_SENSOR_IN_DIRECTIO_CS_OE_Msk           0x10000
#define QSPI_SENSOR_IN_DIRECTIO_HOLD_O_Pos          13
#define QSPI_SENSOR_IN_DIRECTIO_HOLD_O_Msk          0x2000
#define QSPI_SENSOR_IN_DIRECTIO_WP_O_Pos            12
#define QSPI_SENSOR_IN_DIRECTIO_WP_O_Msk            0x1000
#define QSPI_SENSOR_IN_DIRECTIO_MISO_O_Pos          11
#define QSPI_SENSOR_IN_DIRECTIO_MISO_O_Msk          0x800
#define QSPI_SENSOR_IN_DIRECTIO_MOSI_O_Pos          10
#define QSPI_SENSOR_IN_DIRECTIO_MOSI_O_Msk          0x400
#define QSPI_SENSOR_IN_DIRECTIO_SCLK_O_Pos          9
#define QSPI_SENSOR_IN_DIRECTIO_SCLK_O_Msk          0x200
#define QSPI_SENSOR_IN_DIRECTIO_CS_O_Pos            8
#define QSPI_SENSOR_IN_DIRECTIO_CS_O_Msk            0x100
#define QSPI_SENSOR_IN_DIRECTIO_HOLD_I_Pos          5
#define QSPI_SENSOR_IN_DIRECTIO_HOLD_I_Msk          0x20
#define QSPI_SENSOR_IN_DIRECTIO_WP_I_Pos            4
#define QSPI_SENSOR_IN_DIRECTIO_WP_I_Msk            0x10
#define QSPI_SENSOR_IN_DIRECTIO_MISO_I_Pos          3
#define QSPI_SENSOR_IN_DIRECTIO_MISO_I_Msk          0x8
#define QSPI_SENSOR_IN_DIRECTIO_MOSI_I_Pos          2
#define QSPI_SENSOR_IN_DIRECTIO_MOSI_I_Msk          0x4
#define QSPI_SENSOR_IN_DIRECTIO_SCLK_I_Pos          1
#define QSPI_SENSOR_IN_DIRECTIO_SCLK_I_Msk          0x2
#define QSPI_SENSOR_IN_DIRECTIO_CS_I_Pos            0
#define QSPI_SENSOR_IN_DIRECTIO_CS_I_Msk            0x1

#define QSPI_SENSOR_IN_TRANSCTRL_OFFSET             0x020
#define QSPI_SENSOR_IN_TRANSCTRL_CMDEN_Pos          30
#define QSPI_SENSOR_IN_TRANSCTRL_CMDEN_Msk          0x40000000
#define QSPI_SENSOR_IN_TRANSCTRL_ADDREN_Pos         29
#define QSPI_SENSOR_IN_TRANSCTRL_ADDREN_Msk         0x20000000
#define QSPI_SENSOR_IN_TRANSCTRL_ADDRFMT_Pos        28
#define QSPI_SENSOR_IN_TRANSCTRL_ADDRFMT_Msk        0x10000000
#define QSPI_SENSOR_IN_TRANSCTRL_TRANSMODE_Pos      24
#define QSPI_SENSOR_IN_TRANSCTRL_TRANSMODE_Msk      0xf000000
#define QSPI_SENSOR_IN_TRANSCTRL_DUALQUAD_Pos       22
#define QSPI_SENSOR_IN_TRANSCTRL_DUALQUAD_Msk       0xc00000
#define QSPI_SENSOR_IN_TRANSCTRL_TOKENEN_Pos        21
#define QSPI_SENSOR_IN_TRANSCTRL_TOKENEN_Msk        0x200000
#define QSPI_SENSOR_IN_TRANSCTRL_WRTRANCNT_Pos      12
#define QSPI_SENSOR_IN_TRANSCTRL_WRTRANCNT_Msk      0x1ff000
#define QSPI_SENSOR_IN_TRANSCTRL_TOKENVALUE_Pos     11
#define QSPI_SENSOR_IN_TRANSCTRL_TOKENVALUE_Msk     0x800
#define QSPI_SENSOR_IN_TRANSCTRL_DUMMYCNT_Pos       9
#define QSPI_SENSOR_IN_TRANSCTRL_DUMMYCNT_Msk       0x600
#define QSPI_SENSOR_IN_TRANSCTRL_RDTRANCNT_Pos      0
#define QSPI_SENSOR_IN_TRANSCTRL_RDTRANCNT_Msk      0x1ff

#define QSPI_SENSOR_IN_CMD_OFFSET                   0x024
#define QSPI_SENSOR_IN_CMD_WIRE_TYPE_Pos            17
#define QSPI_SENSOR_IN_CMD_WIRE_TYPE_Msk            0x3e0000
#define QSPI_SENSOR_IN_CMD_S_OF_Pos                 16
#define QSPI_SENSOR_IN_CMD_S_OF_Msk                 0x10000
#define QSPI_SENSOR_IN_CMD_E_OF_Pos                 15
#define QSPI_SENSOR_IN_CMD_E_OF_Msk                 0x8000
#define QSPI_SENSOR_IN_CMD_S_OL_Pos                 14
#define QSPI_SENSOR_IN_CMD_S_OL_Msk                 0x4000
#define QSPI_SENSOR_IN_CMD_E_OL_Pos                 13
#define QSPI_SENSOR_IN_CMD_E_OL_Msk                 0x2000
#define QSPI_SENSOR_IN_CMD_CTRL_CS_DEBUG_Pos        8
#define QSPI_SENSOR_IN_CMD_CTRL_CS_DEBUG_Msk        0x1f00
#define QSPI_SENSOR_IN_CMD_CMD_Pos                  0
#define QSPI_SENSOR_IN_CMD_CMD_Msk                  0xff

#define QSPI_SENSOR_IN_ADDR_OFFSET                  0x028
#define QSPI_SENSOR_IN_ADDR_ADDR_Pos                0
#define QSPI_SENSOR_IN_ADDR_ADDR_Msk                0xffffffff

#define QSPI_SENSOR_IN_DATA_OFFSET                  0x02C
#define QSPI_SENSOR_IN_DATA_DATA_Pos                0
#define QSPI_SENSOR_IN_DATA_DATA_Msk                0xffffffff

#define QSPI_SENSOR_IN_CTRL_OFFSET                  0x030
#define QSPI_SENSOR_IN_CTRL_SPI_CS_FROM_REG_Pos     22
#define QSPI_SENSOR_IN_CTRL_SPI_CS_FROM_REG_Msk     0x400000
#define QSPI_SENSOR_IN_CTRL_SPI_CS_REG_CFG_EN_Pos    21
#define QSPI_SENSOR_IN_CTRL_SPI_CS_REG_CFG_EN_Msk    0x200000
#define QSPI_SENSOR_IN_CTRL_TXTHRES_Pos             16
#define QSPI_SENSOR_IN_CTRL_TXTHRES_Msk             0x1f0000
#define QSPI_SENSOR_IN_CTRL_RXTHRES_Pos             8
#define QSPI_SENSOR_IN_CTRL_RXTHRES_Msk             0x1f00
#define QSPI_SENSOR_IN_CTRL_TXDMAEN_Pos             4
#define QSPI_SENSOR_IN_CTRL_TXDMAEN_Msk             0x10
#define QSPI_SENSOR_IN_CTRL_RXDMAEN_Pos             3
#define QSPI_SENSOR_IN_CTRL_RXDMAEN_Msk             0x8
#define QSPI_SENSOR_IN_CTRL_TXFIFORST_Pos           2
#define QSPI_SENSOR_IN_CTRL_TXFIFORST_Msk           0x4
#define QSPI_SENSOR_IN_CTRL_RXFIFORST_Pos           1
#define QSPI_SENSOR_IN_CTRL_RXFIFORST_Msk           0x2
#define QSPI_SENSOR_IN_CTRL_SPIRST_Pos              0
#define QSPI_SENSOR_IN_CTRL_SPIRST_Msk              0x1

#define QSPI_SENSOR_IN_STATUS_OFFSET                0x034
#define QSPI_SENSOR_IN_STATUS_TXFULL_Pos            23
#define QSPI_SENSOR_IN_STATUS_TXFULL_Msk            0x800000
#define QSPI_SENSOR_IN_STATUS_TXEMPTY_Pos           22
#define QSPI_SENSOR_IN_STATUS_TXEMPTY_Msk           0x400000
#define QSPI_SENSOR_IN_STATUS_TXNUM_Pos             16
#define QSPI_SENSOR_IN_STATUS_TXNUM_Msk             0x1f0000
#define QSPI_SENSOR_IN_STATUS_RXFULL_Pos            15
#define QSPI_SENSOR_IN_STATUS_RXFULL_Msk            0x8000
#define QSPI_SENSOR_IN_STATUS_RXEMPTY_Pos           14
#define QSPI_SENSOR_IN_STATUS_RXEMPTY_Msk           0x4000
#define QSPI_SENSOR_IN_STATUS_RXNUM_Pos             8
#define QSPI_SENSOR_IN_STATUS_RXNUM_Msk             0x1f00
#define QSPI_SENSOR_IN_STATUS_SPIACTIVE_Pos         0
#define QSPI_SENSOR_IN_STATUS_SPIACTIVE_Msk         0x1

#define QSPI_SENSOR_IN_INTREN_OFFSET                0x038
#define QSPI_SENSOR_IN_INTREN_LINE_START_INT_EN_Pos    10
#define QSPI_SENSOR_IN_INTREN_LINE_START_INT_EN_Msk    0x400
#define QSPI_SENSOR_IN_INTREN_LINE_END_INT_EN_Pos    9
#define QSPI_SENSOR_IN_INTREN_LINE_END_INT_EN_Msk    0x200
#define QSPI_SENSOR_IN_INTREN_FRAME_END_INT_EN_Pos    8
#define QSPI_SENSOR_IN_INTREN_FRAME_END_INT_EN_Msk    0x100
#define QSPI_SENSOR_IN_INTREN_FRAME_START_INT_EN_Pos    7
#define QSPI_SENSOR_IN_INTREN_FRAME_START_INT_EN_Msk    0x80
#define QSPI_SENSOR_IN_INTREN_ERRINTEN_Pos          6
#define QSPI_SENSOR_IN_INTREN_ERRINTEN_Msk          0x40
#define QSPI_SENSOR_IN_INTREN_SLVCMDEN_Pos          5
#define QSPI_SENSOR_IN_INTREN_SLVCMDEN_Msk          0x20
#define QSPI_SENSOR_IN_INTREN_ENDINTEN_Pos          4
#define QSPI_SENSOR_IN_INTREN_ENDINTEN_Msk          0x10
#define QSPI_SENSOR_IN_INTREN_TXFIFOINTEN_Pos       3
#define QSPI_SENSOR_IN_INTREN_TXFIFOINTEN_Msk       0x8
#define QSPI_SENSOR_IN_INTREN_RXFIFOINTEN_Pos       2
#define QSPI_SENSOR_IN_INTREN_RXFIFOINTEN_Msk       0x4
#define QSPI_SENSOR_IN_INTREN_TXFIFOURINTEN_Pos     1
#define QSPI_SENSOR_IN_INTREN_TXFIFOURINTEN_Msk     0x2
#define QSPI_SENSOR_IN_INTREN_RXFIFOORINTEN_Pos     0
#define QSPI_SENSOR_IN_INTREN_RXFIFOORINTEN_Msk     0x1

#define QSPI_SENSOR_IN_INTRST_OFFSET                0x03C
#define QSPI_SENSOR_IN_INTRST_LINE_START_INT_Pos    10
#define QSPI_SENSOR_IN_INTRST_LINE_START_INT_Msk    0x400
#define QSPI_SENSOR_IN_INTRST_LINE_END_INT_Pos      9
#define QSPI_SENSOR_IN_INTRST_LINE_END_INT_Msk      0x200
#define QSPI_SENSOR_IN_INTRST_FRAME_END_INT_Pos     8
#define QSPI_SENSOR_IN_INTRST_FRAME_END_INT_Msk     0x100
#define QSPI_SENSOR_IN_INTRST_FRAME_START_INT_Pos    7
#define QSPI_SENSOR_IN_INTRST_FRAME_START_INT_Msk    0x80
#define QSPI_SENSOR_IN_INTRST_ERRINT_Pos            6
#define QSPI_SENSOR_IN_INTRST_ERRINT_Msk            0x40
#define QSPI_SENSOR_IN_INTRST_SLVCMDINT_Pos         5
#define QSPI_SENSOR_IN_INTRST_SLVCMDINT_Msk         0x20
#define QSPI_SENSOR_IN_INTRST_ENDINT_Pos            4
#define QSPI_SENSOR_IN_INTRST_ENDINT_Msk            0x10
#define QSPI_SENSOR_IN_INTRST_TXFIFOINT_Pos         3
#define QSPI_SENSOR_IN_INTRST_TXFIFOINT_Msk         0x8
#define QSPI_SENSOR_IN_INTRST_RXFIFOINT_Pos         2
#define QSPI_SENSOR_IN_INTRST_RXFIFOINT_Msk         0x4
#define QSPI_SENSOR_IN_INTRST_TXFIFOURINT_Pos       1
#define QSPI_SENSOR_IN_INTRST_TXFIFOURINT_Msk       0x2
#define QSPI_SENSOR_IN_INTRST_RXFIFOORINT_Pos       0
#define QSPI_SENSOR_IN_INTRST_RXFIFOORINT_Msk       0x1

#define QSPI_SENSOR_IN_TIMING_OFFSET                0x040
#define QSPI_SENSOR_IN_TIMING_CS2SCLK_Pos           12
#define QSPI_SENSOR_IN_TIMING_CS2SCLK_Msk           0x3000
#define QSPI_SENSOR_IN_TIMING_CSHT_Pos              8
#define QSPI_SENSOR_IN_TIMING_CSHT_Msk              0xf00
#define QSPI_SENSOR_IN_TIMING_SCLK_DIV_Pos          0
#define QSPI_SENSOR_IN_TIMING_SCLK_DIV_Msk          0xff

#define QSPI_SENSOR_IN_MEMCTRL_OFFSET               0x050
#define QSPI_SENSOR_IN_MEMCTRL_MEMCTRLCHG_Pos       8
#define QSPI_SENSOR_IN_MEMCTRL_MEMCTRLCHG_Msk       0x100
#define QSPI_SENSOR_IN_MEMCTRL_MEMRDCMD_Pos         0
#define QSPI_SENSOR_IN_MEMCTRL_MEMRDCMD_Msk         0xf

#define QSPI_SENSOR_IN_SLVST_OFFSET                 0x060
#define QSPI_SENSOR_IN_SLVST_UNDERRUN_Pos           18
#define QSPI_SENSOR_IN_SLVST_UNDERRUN_Msk           0x40000
#define QSPI_SENSOR_IN_SLVST_OVERRUN_Pos            17
#define QSPI_SENSOR_IN_SLVST_OVERRUN_Msk            0x20000
#define QSPI_SENSOR_IN_SLVST_READY_Pos              16
#define QSPI_SENSOR_IN_SLVST_READY_Msk              0x10000
#define QSPI_SENSOR_IN_SLVST_USR_STATUS_Pos         0
#define QSPI_SENSOR_IN_SLVST_USR_STATUS_Msk         0xffff

#define QSPI_SENSOR_IN_SLVDATACNT_OFFSET            0x064
#define QSPI_SENSOR_IN_SLVDATACNT_RCNT_CLR_Pos      31
#define QSPI_SENSOR_IN_SLVDATACNT_RCNT_CLR_Msk      0x80000000
#define QSPI_SENSOR_IN_SLVDATACNT_RCNT_Pos          0
#define QSPI_SENSOR_IN_SLVDATACNT_RCNT_Msk          0x7fffffff

#define QSPI_SENSOR_IN_PACKET_ID_OFFSET             0x068
#define QSPI_SENSOR_IN_PACKET_ID_FRAME_END_Pos      24
#define QSPI_SENSOR_IN_PACKET_ID_FRAME_END_Msk      0xff000000
#define QSPI_SENSOR_IN_PACKET_ID_LINE_END_Pos       16
#define QSPI_SENSOR_IN_PACKET_ID_LINE_END_Msk       0xff0000
#define QSPI_SENSOR_IN_PACKET_ID_LINE_START_Pos     8
#define QSPI_SENSOR_IN_PACKET_ID_LINE_START_Msk     0xff00
#define QSPI_SENSOR_IN_PACKET_ID_FRAME_START_Pos    0
#define QSPI_SENSOR_IN_PACKET_ID_FRAME_START_Msk    0xff

#define QSPI_SENSOR_IN_SYNC_CODE_OFFSET             0x06C
#define QSPI_SENSOR_IN_SYNC_CODE_SYNC_CODE_Pos      0
#define QSPI_SENSOR_IN_SYNC_CODE_SYNC_CODE_Msk      0xffffff

#define QSPI_SENSOR_IN_SPI_CAMERA_CTRL_OFFSET       0x070
#define QSPI_SENSOR_IN_SPI_CAMERA_CTRL_PK_SIZE_R_Pos    16
#define QSPI_SENSOR_IN_SPI_CAMERA_CTRL_PK_SIZE_R_Msk    0xffff0000
#define QSPI_SENSOR_IN_SPI_CAMERA_CTRL_DATA_ID_R_Pos    8
#define QSPI_SENSOR_IN_SPI_CAMERA_CTRL_DATA_ID_R_Msk    0xff00
#define QSPI_SENSOR_IN_SPI_CAMERA_CTRL_SYNC_CODE_LSB_Pos    7
#define QSPI_SENSOR_IN_SPI_CAMERA_CTRL_SYNC_CODE_LSB_Msk    0x80
#define QSPI_SENSOR_IN_SPI_CAMERA_CTRL_LINE_END_EN_Pos    6
#define QSPI_SENSOR_IN_SPI_CAMERA_CTRL_LINE_END_EN_Msk    0x40
#define QSPI_SENSOR_IN_SPI_CAMERA_CTRL_LINE_START_EN_Pos    5
#define QSPI_SENSOR_IN_SPI_CAMERA_CTRL_LINE_START_EN_Msk    0x20
#define QSPI_SENSOR_IN_SPI_CAMERA_CTRL_FRAME_END_EN_Pos    4
#define QSPI_SENSOR_IN_SPI_CAMERA_CTRL_FRAME_END_EN_Msk    0x10
#define QSPI_SENSOR_IN_SPI_CAMERA_CTRL_FRAME_START_EN_Pos    3
#define QSPI_SENSOR_IN_SPI_CAMERA_CTRL_FRAME_START_EN_Msk    0x8
#define QSPI_SENSOR_IN_SPI_CAMERA_CTRL_ALL_DATA_REC_EN_Pos    2
#define QSPI_SENSOR_IN_SPI_CAMERA_CTRL_ALL_DATA_REC_EN_Msk    0x4
#define QSPI_SENSOR_IN_SPI_CAMERA_CTRL_ERR_INT_EN_Pos    1
#define QSPI_SENSOR_IN_SPI_CAMERA_CTRL_ERR_INT_EN_Msk    0x2
#define QSPI_SENSOR_IN_SPI_CAMERA_CTRL_MTK_Pos      0
#define QSPI_SENSOR_IN_SPI_CAMERA_CTRL_MTK_Msk      0x1

#define QSPI_SENSOR_IN_IMAGE_SIZE_OFFSET            0x074
#define QSPI_SENSOR_IN_IMAGE_SIZE_IMAGE_WIDTH_R_Pos    16
#define QSPI_SENSOR_IN_IMAGE_SIZE_IMAGE_WIDTH_R_Msk    0xffff0000
#define QSPI_SENSOR_IN_IMAGE_SIZE_IMAGE_HEIGHT_R_Pos    0
#define QSPI_SENSOR_IN_IMAGE_SIZE_IMAGE_HEIGHT_R_Msk    0xffff

#define QSPI_SENSOR_IN_LINE_NUM_OFFSET              0x078
#define QSPI_SENSOR_IN_LINE_NUM_LINE_NUM_R_Pos      0
#define QSPI_SENSOR_IN_LINE_NUM_LINE_NUM_R_Msk      0xffff

#define QSPI_SENSOR_IN_CONFIG_OFFSET                0x07C
#define QSPI_SENSOR_IN_CONFIG_SLAVE_Pos             14
#define QSPI_SENSOR_IN_CONFIG_SLAVE_Msk             0x4000
#define QSPI_SENSOR_IN_CONFIG_EILMMEM_Pos           13
#define QSPI_SENSOR_IN_CONFIG_EILMMEM_Msk           0x2000
#define QSPI_SENSOR_IN_CONFIG_AHBMEM_Pos            12
#define QSPI_SENSOR_IN_CONFIG_AHBMEM_Msk            0x1000
#define QSPI_SENSOR_IN_CONFIG_DIRECTIO_Pos          11
#define QSPI_SENSOR_IN_CONFIG_DIRECTIO_Msk          0x800
#define QSPI_SENSOR_IN_CONFIG_QUADSPI_Pos           9
#define QSPI_SENSOR_IN_CONFIG_QUADSPI_Msk           0x200
#define QSPI_SENSOR_IN_CONFIG_DUALSPI_Pos           8
#define QSPI_SENSOR_IN_CONFIG_DUALSPI_Msk           0x100
#define QSPI_SENSOR_IN_CONFIG_TXFIFOSIZE_Pos        4
#define QSPI_SENSOR_IN_CONFIG_TXFIFOSIZE_Msk        0x30
#define QSPI_SENSOR_IN_CONFIG_RXFIFOSIZE_Pos        0
#define QSPI_SENSOR_IN_CONFIG_RXFIFOSIZE_Msk        0x3

struct QSPI_SENSOR_IN_REG_IDREV_BITS
{
    volatile uint32_t REVMINOR                      : 4; // bit 0~3
    volatile uint32_t REVMAJOR                      : 8; // bit 4~11
    volatile uint32_t ID                            : 20; // bit 12~31
};

union QSPI_SENSOR_IN_REG_IDREV {
    volatile uint32_t                               all;
    struct QSPI_SENSOR_IN_REG_IDREV_BITS            bit;
};

struct QSPI_SENSOR_IN_REG_TRANSFMT_BITS
{
    volatile uint32_t CPHA                          : 1; // bit 0~0
    volatile uint32_t CPOL                          : 1; // bit 1~1
    volatile uint32_t SLVMODE                       : 1; // bit 2~2
    volatile uint32_t LSB                           : 1; // bit 3~3
    volatile uint32_t MOSIBIDIR                     : 1; // bit 4~4
    volatile uint32_t RESV_5_6                      : 2; // bit 5~6
    volatile uint32_t DATAMERGE                     : 1; // bit 7~7
    volatile uint32_t DATALEN                       : 5; // bit 8~12
    volatile uint32_t RESV_13_15                    : 3; // bit 13~15
    volatile uint32_t ADDRLEN                       : 2; // bit 16~17
    volatile uint32_t RESV_18_31                    : 14; // bit 18~31
};

union QSPI_SENSOR_IN_REG_TRANSFMT {
    volatile uint32_t                               all;
    struct QSPI_SENSOR_IN_REG_TRANSFMT_BITS         bit;
};

struct QSPI_SENSOR_IN_REG_DIRECTIO_BITS
{
    volatile uint32_t CS_I                          : 1; // bit 0~0
    volatile uint32_t SCLK_I                        : 1; // bit 1~1
    volatile uint32_t MOSI_I                        : 1; // bit 2~2
    volatile uint32_t MISO_I                        : 1; // bit 3~3
    volatile uint32_t WP_I                          : 1; // bit 4~4
    volatile uint32_t HOLD_I                        : 1; // bit 5~5
    volatile uint32_t RESV_6_7                      : 2; // bit 6~7
    volatile uint32_t CS_O                          : 1; // bit 8~8
    volatile uint32_t SCLK_O                        : 1; // bit 9~9
    volatile uint32_t MOSI_O                        : 1; // bit 10~10
    volatile uint32_t MISO_O                        : 1; // bit 11~11
    volatile uint32_t WP_O                          : 1; // bit 12~12
    volatile uint32_t HOLD_O                        : 1; // bit 13~13
    volatile uint32_t RESV_14_15                    : 2; // bit 14~15
    volatile uint32_t CS_OE                         : 1; // bit 16~16
    volatile uint32_t SCLK_OE                       : 1; // bit 17~17
    volatile uint32_t MOSI_OE                       : 1; // bit 18~18
    volatile uint32_t MISO_OE                       : 1; // bit 19~19
    volatile uint32_t WP_OE                         : 1; // bit 20~20
    volatile uint32_t HOLD_OE                       : 1; // bit 21~21
    volatile uint32_t RESV_22_23                    : 2; // bit 22~23
    volatile uint32_t DIRECTIOEN                    : 1; // bit 24~24
    volatile uint32_t RESV_25_31                    : 7; // bit 25~31
};

union QSPI_SENSOR_IN_REG_DIRECTIO {
    volatile uint32_t                               all;
    struct QSPI_SENSOR_IN_REG_DIRECTIO_BITS         bit;
};

struct QSPI_SENSOR_IN_REG_TRANSCTRL_BITS
{
    volatile uint32_t RDTRANCNT                     : 9; // bit 0~8
    volatile uint32_t DUMMYCNT                      : 2; // bit 9~10
    volatile uint32_t TOKENVALUE                    : 1; // bit 11~11
    volatile uint32_t WRTRANCNT                     : 9; // bit 12~20
    volatile uint32_t TOKENEN                       : 1; // bit 21~21
    volatile uint32_t DUALQUAD                      : 2; // bit 22~23
    volatile uint32_t TRANSMODE                     : 4; // bit 24~27
    volatile uint32_t ADDRFMT                       : 1; // bit 28~28
    volatile uint32_t ADDREN                        : 1; // bit 29~29
    volatile uint32_t CMDEN                         : 1; // bit 30~30
    volatile uint32_t RESV_31_31                    : 1; // bit 31~31
};

union QSPI_SENSOR_IN_REG_TRANSCTRL {
    volatile uint32_t                               all;
    struct QSPI_SENSOR_IN_REG_TRANSCTRL_BITS        bit;
};

struct QSPI_SENSOR_IN_REG_CMD_BITS
{
    volatile uint32_t CMD                           : 8; // bit 0~7
    volatile uint32_t CTRL_CS_DEBUG                 : 5; // bit 8~12
    volatile uint32_t E_OL                          : 1; // bit 13~13
    volatile uint32_t S_OL                          : 1; // bit 14~14
    volatile uint32_t E_OF                          : 1; // bit 15~15
    volatile uint32_t S_OF                          : 1; // bit 16~16
    volatile uint32_t WIRE_TYPE                     : 5; // bit 17~21
    volatile uint32_t RESV_22_31                    : 10; // bit 22~31
};

union QSPI_SENSOR_IN_REG_CMD {
    volatile uint32_t                               all;
    struct QSPI_SENSOR_IN_REG_CMD_BITS              bit;
};

struct QSPI_SENSOR_IN_REG_ADDR_BITS
{
    volatile uint32_t ADDR                          : 32; // bit 0~31
};

union QSPI_SENSOR_IN_REG_ADDR {
    volatile uint32_t                               all;
    struct QSPI_SENSOR_IN_REG_ADDR_BITS             bit;
};

struct QSPI_SENSOR_IN_REG_DATA_BITS
{
    volatile uint32_t DATA                          : 32; // bit 0~31
};

union QSPI_SENSOR_IN_REG_DATA {
    volatile uint32_t                               all;
    struct QSPI_SENSOR_IN_REG_DATA_BITS             bit;
};

struct QSPI_SENSOR_IN_REG_CTRL_BITS
{
    volatile uint32_t SPIRST                        : 1; // bit 0~0
    volatile uint32_t RXFIFORST                     : 1; // bit 1~1
    volatile uint32_t TXFIFORST                     : 1; // bit 2~2
    volatile uint32_t RXDMAEN                       : 1; // bit 3~3
    volatile uint32_t TXDMAEN                       : 1; // bit 4~4
    volatile uint32_t RESV_5_7                      : 3; // bit 5~7
    volatile uint32_t RXTHRES                       : 5; // bit 8~12
    volatile uint32_t RESV_13_15                    : 3; // bit 13~15
    volatile uint32_t TXTHRES                       : 5; // bit 16~20
    volatile uint32_t SPI_CS_REG_CFG_EN             : 1; // bit 21~21
    volatile uint32_t SPI_CS_FROM_REG               : 1; // bit 22~22
    volatile uint32_t RESV_23_31                    : 9; // bit 23~31
};

union QSPI_SENSOR_IN_REG_CTRL {
    volatile uint32_t                               all;
    struct QSPI_SENSOR_IN_REG_CTRL_BITS             bit;
};

struct QSPI_SENSOR_IN_REG_STATUS_BITS
{
    volatile uint32_t SPIACTIVE                     : 1; // bit 0~0
    volatile uint32_t RESV_1_7                      : 7; // bit 1~7
    volatile uint32_t RXNUM                         : 5; // bit 8~12
    volatile uint32_t RESV_13_13                    : 1; // bit 13~13
    volatile uint32_t RXEMPTY                       : 1; // bit 14~14
    volatile uint32_t RXFULL                        : 1; // bit 15~15
    volatile uint32_t TXNUM                         : 5; // bit 16~20
    volatile uint32_t RESV_21_21                    : 1; // bit 21~21
    volatile uint32_t TXEMPTY                       : 1; // bit 22~22
    volatile uint32_t TXFULL                        : 1; // bit 23~23
    volatile uint32_t RESV_24_31                    : 8; // bit 24~31
};

union QSPI_SENSOR_IN_REG_STATUS {
    volatile uint32_t                               all;
    struct QSPI_SENSOR_IN_REG_STATUS_BITS           bit;
};

struct QSPI_SENSOR_IN_REG_INTREN_BITS
{
    volatile uint32_t RXFIFOORINTEN                 : 1; // bit 0~0
    volatile uint32_t TXFIFOURINTEN                 : 1; // bit 1~1
    volatile uint32_t RXFIFOINTEN                   : 1; // bit 2~2
    volatile uint32_t TXFIFOINTEN                   : 1; // bit 3~3
    volatile uint32_t ENDINTEN                      : 1; // bit 4~4
    volatile uint32_t SLVCMDEN                      : 1; // bit 5~5
    volatile uint32_t ERRINTEN                      : 1; // bit 6~6
    volatile uint32_t FRAME_START_INT_EN            : 1; // bit 7~7
    volatile uint32_t FRAME_END_INT_EN              : 1; // bit 8~8
    volatile uint32_t LINE_END_INT_EN               : 1; // bit 9~9
    volatile uint32_t LINE_START_INT_EN             : 1; // bit 10~10
    volatile uint32_t RESV_11_31                    : 21; // bit 11~31
};

union QSPI_SENSOR_IN_REG_INTREN {
    volatile uint32_t                               all;
    struct QSPI_SENSOR_IN_REG_INTREN_BITS           bit;
};

struct QSPI_SENSOR_IN_REG_INTRST_BITS
{
    volatile uint32_t RXFIFOORINT                   : 1; // bit 0~0
    volatile uint32_t TXFIFOURINT                   : 1; // bit 1~1
    volatile uint32_t RXFIFOINT                     : 1; // bit 2~2
    volatile uint32_t TXFIFOINT                     : 1; // bit 3~3
    volatile uint32_t ENDINT                        : 1; // bit 4~4
    volatile uint32_t SLVCMDINT                     : 1; // bit 5~5
    volatile uint32_t ERRINT                        : 1; // bit 6~6
    volatile uint32_t FRAME_START_INT               : 1; // bit 7~7
    volatile uint32_t FRAME_END_INT                 : 1; // bit 8~8
    volatile uint32_t LINE_END_INT                  : 1; // bit 9~9
    volatile uint32_t LINE_START_INT                : 1; // bit 10~10
    volatile uint32_t RESV_11_31                    : 21; // bit 11~31
};

union QSPI_SENSOR_IN_REG_INTRST {
    volatile uint32_t                               all;
    struct QSPI_SENSOR_IN_REG_INTRST_BITS           bit;
};

struct QSPI_SENSOR_IN_REG_TIMING_BITS
{
    volatile uint32_t SCLK_DIV                      : 8; // bit 0~7
    volatile uint32_t CSHT                          : 4; // bit 8~11
    volatile uint32_t CS2SCLK                       : 2; // bit 12~13
    volatile uint32_t RESV_14_31                    : 18; // bit 14~31
};

union QSPI_SENSOR_IN_REG_TIMING {
    volatile uint32_t                               all;
    struct QSPI_SENSOR_IN_REG_TIMING_BITS           bit;
};

struct QSPI_SENSOR_IN_REG_MEMCTRL_BITS
{
    volatile uint32_t MEMRDCMD                      : 4; // bit 0~3
    volatile uint32_t RESV_4_7                      : 4; // bit 4~7
    volatile uint32_t MEMCTRLCHG                    : 1; // bit 8~8
    volatile uint32_t RESV_9_31                     : 23; // bit 9~31
};

union QSPI_SENSOR_IN_REG_MEMCTRL {
    volatile uint32_t                               all;
    struct QSPI_SENSOR_IN_REG_MEMCTRL_BITS          bit;
};

struct QSPI_SENSOR_IN_REG_SLVST_BITS
{
    volatile uint32_t USR_STATUS                    : 16; // bit 0~15
    volatile uint32_t READY                         : 1; // bit 16~16
    volatile uint32_t OVERRUN                       : 1; // bit 17~17
    volatile uint32_t UNDERRUN                      : 1; // bit 18~18
    volatile uint32_t RESV_19_31                    : 13; // bit 19~31
};

union QSPI_SENSOR_IN_REG_SLVST {
    volatile uint32_t                               all;
    struct QSPI_SENSOR_IN_REG_SLVST_BITS            bit;
};

struct QSPI_SENSOR_IN_REG_SLVDATACNT_BITS
{
    volatile uint32_t RCNT                          : 31; // bit 0~30
    volatile uint32_t RCNT_CLR                      : 1; // bit 31~31
};

union QSPI_SENSOR_IN_REG_SLVDATACNT {
    volatile uint32_t                               all;
    struct QSPI_SENSOR_IN_REG_SLVDATACNT_BITS       bit;
};

struct QSPI_SENSOR_IN_REG_PACKET_ID_BITS
{
    volatile uint32_t FRAME_START                   : 8; // bit 0~7
    volatile uint32_t LINE_START                    : 8; // bit 8~15
    volatile uint32_t LINE_END                      : 8; // bit 16~23
    volatile uint32_t FRAME_END                     : 8; // bit 24~31
};

union QSPI_SENSOR_IN_REG_PACKET_ID {
    volatile uint32_t                               all;
    struct QSPI_SENSOR_IN_REG_PACKET_ID_BITS        bit;
};

struct QSPI_SENSOR_IN_REG_SYNC_CODE_BITS
{
    volatile uint32_t SYNC_CODE                     : 24; // bit 0~23
    volatile uint32_t RESV_24_31                    : 8; // bit 24~31
};

union QSPI_SENSOR_IN_REG_SYNC_CODE {
    volatile uint32_t                               all;
    struct QSPI_SENSOR_IN_REG_SYNC_CODE_BITS        bit;
};

struct QSPI_SENSOR_IN_REG_SPI_CAMERA_CTRL_BITS
{
    volatile uint32_t MTK                           : 1; // bit 0~0
    volatile uint32_t ERR_INT_EN                    : 1; // bit 1~1
    volatile uint32_t ALL_DATA_REC_EN               : 1; // bit 2~2
    volatile uint32_t FRAME_START_EN                : 1; // bit 3~3
    volatile uint32_t FRAME_END_EN                  : 1; // bit 4~4
    volatile uint32_t LINE_START_EN                 : 1; // bit 5~5
    volatile uint32_t LINE_END_EN                   : 1; // bit 6~6
    volatile uint32_t SYNC_CODE_LSB                 : 1; // bit 7~7
    volatile uint32_t DATA_ID_R                     : 8; // bit 8~15
    volatile uint32_t PK_SIZE_R                     : 16; // bit 16~31
};

union QSPI_SENSOR_IN_REG_SPI_CAMERA_CTRL {
    volatile uint32_t                               all;
    struct QSPI_SENSOR_IN_REG_SPI_CAMERA_CTRL_BITS    bit;
};

struct QSPI_SENSOR_IN_REG_IMAGE_SIZE_BITS
{
    volatile uint32_t IMAGE_HEIGHT_R                : 16; // bit 0~15
    volatile uint32_t IMAGE_WIDTH_R                 : 16; // bit 16~31
};

union QSPI_SENSOR_IN_REG_IMAGE_SIZE {
    volatile uint32_t                               all;
    struct QSPI_SENSOR_IN_REG_IMAGE_SIZE_BITS       bit;
};

struct QSPI_SENSOR_IN_REG_LINE_NUM_BITS
{
    volatile uint32_t LINE_NUM_R                    : 16; // bit 0~15
    volatile uint32_t RESV_16_31                    : 16; // bit 16~31
};

union QSPI_SENSOR_IN_REG_LINE_NUM {
    volatile uint32_t                               all;
    struct QSPI_SENSOR_IN_REG_LINE_NUM_BITS         bit;
};

struct QSPI_SENSOR_IN_REG_CONFIG_BITS
{
    volatile uint32_t RXFIFOSIZE                    : 2; // bit 0~1
    volatile uint32_t RESV_2_3                      : 2; // bit 2~3
    volatile uint32_t TXFIFOSIZE                    : 2; // bit 4~5
    volatile uint32_t RESV_6_7                      : 2; // bit 6~7
    volatile uint32_t DUALSPI                       : 1; // bit 8~8
    volatile uint32_t QUADSPI                       : 1; // bit 9~9
    volatile uint32_t RESV_10_10                    : 1; // bit 10~10
    volatile uint32_t DIRECTIO                      : 1; // bit 11~11
    volatile uint32_t AHBMEM                        : 1; // bit 12~12
    volatile uint32_t EILMMEM                       : 1; // bit 13~13
    volatile uint32_t SLAVE                         : 1; // bit 14~14
    volatile uint32_t RESV_15_31                    : 17; // bit 15~31
};

union QSPI_SENSOR_IN_REG_CONFIG {
    volatile uint32_t                               all;
    struct QSPI_SENSOR_IN_REG_CONFIG_BITS           bit;
};

typedef struct
{
    union QSPI_SENSOR_IN_REG_IDREV                  REG_IDREV;   // 0x000
    volatile uint32_t                               REG_RESV_0X4_0XC[3];
    union QSPI_SENSOR_IN_REG_TRANSFMT               REG_TRANSFMT; // 0x010
    union QSPI_SENSOR_IN_REG_DIRECTIO               REG_DIRECTIO; // 0x014
    volatile uint32_t                               REG_RESV_0X18_0X1C[2];
    union QSPI_SENSOR_IN_REG_TRANSCTRL              REG_TRANSCTRL; // 0x020
    union QSPI_SENSOR_IN_REG_CMD                    REG_CMD;     // 0x024
    union QSPI_SENSOR_IN_REG_ADDR                   REG_ADDR;    // 0x028
    union QSPI_SENSOR_IN_REG_DATA                   REG_DATA;    // 0x02C
    union QSPI_SENSOR_IN_REG_CTRL                   REG_CTRL;    // 0x030
    union QSPI_SENSOR_IN_REG_STATUS                 REG_STATUS;  // 0x034
    union QSPI_SENSOR_IN_REG_INTREN                 REG_INTREN;  // 0x038
    union QSPI_SENSOR_IN_REG_INTRST                 REG_INTRST;  // 0x03C
    union QSPI_SENSOR_IN_REG_TIMING                 REG_TIMING;  // 0x040
    volatile uint32_t                               REG_RESV_0X44_0X4C[3];
    union QSPI_SENSOR_IN_REG_MEMCTRL                REG_MEMCTRL; // 0x050
    volatile uint32_t                               REG_RESV_0X54_0X5C[3];
    union QSPI_SENSOR_IN_REG_SLVST                  REG_SLVST;   // 0x060
    union QSPI_SENSOR_IN_REG_SLVDATACNT             REG_SLVDATACNT; // 0x064
    union QSPI_SENSOR_IN_REG_PACKET_ID              REG_PACKET_ID; // 0x068
    union QSPI_SENSOR_IN_REG_SYNC_CODE              REG_SYNC_CODE; // 0x06C
    union QSPI_SENSOR_IN_REG_SPI_CAMERA_CTRL        REG_SPI_CAMERA_CTRL; // 0x070
    union QSPI_SENSOR_IN_REG_IMAGE_SIZE             REG_IMAGE_SIZE; // 0x074
    union QSPI_SENSOR_IN_REG_LINE_NUM               REG_LINE_NUM; // 0x078
    union QSPI_SENSOR_IN_REG_CONFIG                 REG_CONFIG;  // 0x07C
} QSPI_SENSOR_IN_RegDef;


#endif // __QSPI_SENSOR_IN_REGFILE_H__

