//  ----------------------------------------------------------------------
//  File Name   : GenCFold/wifi_intc_reg_arcs.h
//  Description : C header file generated by Python script.
//  Author      : klqi
//  Script Ver  : LS.AUTO_REG.2024.09.20
//  SVN Revision: Can't find <<ARCS-D_SoC_Memory_Mapping.xlsx>> SVN detail info,pls chk£¡£¡
//  Create Time : 2024-12-10 19:23:31
//  Comments    : 
//  ----------------------------------------------------------------------

#ifndef __WIFI_INTC_REGFILE_H__
#define __WIFI_INTC_REGFILE_H__

#include <stdint.h>

#define WIFI_INTC_IRQ_STATUS_OFFSET                 0x000
#define WIFI_INTC_IRQ_STATUS_IRQ_STATUS_Pos         0
#define WIFI_INTC_IRQ_STATUS_IRQ_STATUS_Msk         0xffffffff

#define WIFI_INTC_IRQ_RAW_STATUS_OFFSET             0x008
#define WIFI_INTC_IRQ_RAW_STATUS_IRQ_RAW_STATUS_Pos    0
#define WIFI_INTC_IRQ_RAW_STATUS_IRQ_RAW_STATUS_Msk    0xffffffff

#define WIFI_INTC_IRQ_UNMASK_SET_OFFSET             0x010
#define WIFI_INTC_IRQ_UNMASK_SET_IRQ_UNMASK_Pos     0
#define WIFI_INTC_IRQ_UNMASK_SET_IRQ_UNMASK_Msk     0xffffffff

#define WIFI_INTC_IRQ_UNMASK_CLEAR_OFFSET           0x018
#define WIFI_INTC_IRQ_UNMASK_CLEAR_IRQ_UNMASK_Pos    0
#define WIFI_INTC_IRQ_UNMASK_CLEAR_IRQ_UNMASK_Msk    0xffffffff

#define WIFI_INTC_IRQ_POLARITY_OFFSET               0x020
#define WIFI_INTC_IRQ_POLARITY_IRQ_POLARITY_Pos     0
#define WIFI_INTC_IRQ_POLARITY_IRQ_POLARITY_Msk     0xffffffff

#define WIFI_INTC_IRQ_INDEX_OFFSET                  0x040
#define WIFI_INTC_IRQ_INDEX_IRQ_INDEX_Pos           0
#define WIFI_INTC_IRQ_INDEX_IRQ_INDEX_Msk           0x3f

struct WIFI_INTC_REG_IRQ_STATUS_BITS
{
    volatile uint32_t IRQ_STATUS                    : 32; // bit 0~31
};

union WIFI_INTC_REG_IRQ_STATUS {
    volatile uint32_t                               all;
    struct WIFI_INTC_REG_IRQ_STATUS_BITS            bit;
};

struct WIFI_INTC_REG_IRQ_RAW_STATUS_BITS
{
    volatile uint32_t IRQ_RAW_STATUS                : 32; // bit 0~31
};

union WIFI_INTC_REG_IRQ_RAW_STATUS {
    volatile uint32_t                               all;
    struct WIFI_INTC_REG_IRQ_RAW_STATUS_BITS        bit;
};

struct WIFI_INTC_REG_IRQ_UNMASK_SET_BITS
{
    volatile uint32_t IRQ_UNMASK                    : 32; // bit 0~31
};

union WIFI_INTC_REG_IRQ_UNMASK_SET {
    volatile uint32_t                               all;
    struct WIFI_INTC_REG_IRQ_UNMASK_SET_BITS        bit;
};

struct WIFI_INTC_REG_IRQ_UNMASK_CLEAR_BITS
{
    volatile uint32_t IRQ_UNMASK                    : 32; // bit 0~31
};

union WIFI_INTC_REG_IRQ_UNMASK_CLEAR {
    volatile uint32_t                               all;
    struct WIFI_INTC_REG_IRQ_UNMASK_CLEAR_BITS      bit;
};

struct WIFI_INTC_REG_IRQ_POLARITY_BITS
{
    volatile uint32_t IRQ_POLARITY                  : 32; // bit 0~31
};

union WIFI_INTC_REG_IRQ_POLARITY {
    volatile uint32_t                               all;
    struct WIFI_INTC_REG_IRQ_POLARITY_BITS          bit;
};

struct WIFI_INTC_REG_IRQ_INDEX_BITS
{
    volatile uint32_t IRQ_INDEX                     : 6; // bit 0~5
    volatile uint32_t RESV_6_31                     : 26; // bit 6~31
};

union WIFI_INTC_REG_IRQ_INDEX {
    volatile uint32_t                               all;
    struct WIFI_INTC_REG_IRQ_INDEX_BITS             bit;
};

typedef struct
{
    union WIFI_INTC_REG_IRQ_STATUS                  REG_IRQ_STATUS; // 0x000
    volatile uint32_t                               REG_RESV_0X4_0X4[1];
    union WIFI_INTC_REG_IRQ_RAW_STATUS              REG_IRQ_RAW_STATUS; // 0x008
    volatile uint32_t                               REG_RESV_0XC_0XC[1];
    union WIFI_INTC_REG_IRQ_UNMASK_SET              REG_IRQ_UNMASK_SET; // 0x010
    volatile uint32_t                               REG_RESV_0X14_0X14[1];
    union WIFI_INTC_REG_IRQ_UNMASK_CLEAR            REG_IRQ_UNMASK_CLEAR; // 0x018
    volatile uint32_t                               REG_RESV_0X1C_0X1C[1];
    union WIFI_INTC_REG_IRQ_POLARITY                REG_IRQ_POLARITY; // 0x020
    volatile uint32_t                               REG_RESV_0X24_0X3C[7];
    union WIFI_INTC_REG_IRQ_INDEX                   REG_IRQ_INDEX; // 0x040
} WIFI_INTC_RegDef;


#endif // __WIFI_INTC_REGFILE_H__

