//  ----------------------------------------------------------------------
//  File Name   : GenCFold/wifi_macbypass_reg_arcs.h
//  Description : C header file generated by Python script.
//  Author      : klqi
//  Script Ver  : LS.AUTO_REG.2024.09.20
//  SVN Revision: Can't find <<ARCS-D_SoC_Memory_Mapping.xlsx>> SVN detail info,pls chk£¡£¡
//  Create Time : 2024-12-10 19:23:31
//  Comments    : 
//  ----------------------------------------------------------------------

#ifndef __WIFI_MACBYPASS_REGFILE_H__
#define __WIFI_MACBYPASS_REGFILE_H__

#include <stdint.h>

#define WIFI_MACBYPASS_CTRL_OFFSET                  0x000
#define WIFI_MACBYPASS_CTRL_TX_DONE_Pos             31
#define WIFI_MACBYPASS_CTRL_TX_DONE_Msk             0x80000000
#define WIFI_MACBYPASS_CTRL_MODE_Pos                8
#define WIFI_MACBYPASS_CTRL_MODE_Msk                0x300
#define WIFI_MACBYPASS_CTRL_CLEAR_STAT_Pos          4
#define WIFI_MACBYPASS_CTRL_CLEAR_STAT_Msk          0x10
#define WIFI_MACBYPASS_CTRL_DEFKEEPRFON_Pos         2
#define WIFI_MACBYPASS_CTRL_DEFKEEPRFON_Msk         0x4
#define WIFI_MACBYPASS_CTRL_DEFRXREQ_Pos            1
#define WIFI_MACBYPASS_CTRL_DEFRXREQ_Msk            0x2
#define WIFI_MACBYPASS_CTRL_BYPASS_Pos              0
#define WIFI_MACBYPASS_CTRL_BYPASS_Msk              0x1

#define WIFI_MACBYPASS_PAYLOAD_OFFSET               0x004
#define WIFI_MACBYPASS_PAYLOAD_PAYLOAD_TX_Pos       16
#define WIFI_MACBYPASS_PAYLOAD_PAYLOAD_TX_Msk       0xf0000
#define WIFI_MACBYPASS_PAYLOAD_PAYLOAD_RX_Pos       0
#define WIFI_MACBYPASS_PAYLOAD_PAYLOAD_RX_Msk       0xf

#define WIFI_MACBYPASS_TRIGGER_OFFSET               0x008
#define WIFI_MACBYPASS_TRIGGER_TRIGGER1_Pos         4
#define WIFI_MACBYPASS_TRIGGER_TRIGGER1_Msk         0xf0
#define WIFI_MACBYPASS_TRIGGER_TRIGGER0_Pos         0
#define WIFI_MACBYPASS_TRIGGER_TRIGGER0_Msk         0xf

#define WIFI_MACBYPASS_CLKEN_OFFSET                 0x00C
#define WIFI_MACBYPASS_CLKEN_CLKEN_Pos              0
#define WIFI_MACBYPASS_CLKEN_CLKEN_Msk              0x1

#define WIFI_MACBYPASS_FRAMEPERBURST_OFFSET         0x010
#define WIFI_MACBYPASS_FRAMEPERBURST_NFRAME_Pos     0
#define WIFI_MACBYPASS_FRAMEPERBURST_NFRAME_Msk     0xffff

#define WIFI_MACBYPASS_COEX_OFFSET                  0x014
#define WIFI_MACBYPASS_COEX_COEX_EN_Pos             4
#define WIFI_MACBYPASS_COEX_COEX_EN_Msk             0x10
#define WIFI_MACBYPASS_COEX_PTI_Pos                 0
#define WIFI_MACBYPASS_COEX_PTI_Msk                 0xf

#define WIFI_MACBYPASS_INTERFRAME_DELAY_OFFSET      0x048
#define WIFI_MACBYPASS_INTERFRAME_DELAY_INTERFRAME_DELAY_Pos    0
#define WIFI_MACBYPASS_INTERFRAME_DELAY_INTERFRAME_DELAY_Msk    0xfffff

#define WIFI_MACBYPASS_STAT_FRAME_OK_OFFSET         0x080
#define WIFI_MACBYPASS_STAT_FRAME_OK_STAT_FRAME_OK_Pos    0
#define WIFI_MACBYPASS_STAT_FRAME_OK_STAT_FRAME_OK_Msk    0xffffffff

#define WIFI_MACBYPASS_STAT_FRAME_BAD_OFFSET        0x084
#define WIFI_MACBYPASS_STAT_FRAME_BAD_STAT_FRAME_BAD_Pos    0
#define WIFI_MACBYPASS_STAT_FRAME_BAD_STAT_FRAME_BAD_Msk    0xffffffff

#define WIFI_MACBYPASS_STAT_RXEND_OFFSET            0x088
#define WIFI_MACBYPASS_STAT_RXEND_STAT_FRAME_RXEND_Pos    0
#define WIFI_MACBYPASS_STAT_RXEND_STAT_FRAME_RXEND_Msk    0xffffffff

#define WIFI_MACBYPASS_STAT_RXERROR_OFFSET          0x08C
#define WIFI_MACBYPASS_STAT_RXERROR_STAT_FRAME_RXERROR_Pos    0
#define WIFI_MACBYPASS_STAT_RXERROR_STAT_FRAME_RXERROR_Msk    0xffffffff

#define WIFI_MACBYPASS_STAT_EVM_OFFSET              0x090
#define WIFI_MACBYPASS_STAT_EVM_EVM3_Pos            24
#define WIFI_MACBYPASS_STAT_EVM_EVM3_Msk            0xff000000
#define WIFI_MACBYPASS_STAT_EVM_EVM2_Pos            16
#define WIFI_MACBYPASS_STAT_EVM_EVM2_Msk            0xff0000
#define WIFI_MACBYPASS_STAT_EVM_EVM1_Pos            8
#define WIFI_MACBYPASS_STAT_EVM_EVM1_Msk            0xff00
#define WIFI_MACBYPASS_STAT_EVM_EVM0_Pos            0
#define WIFI_MACBYPASS_STAT_EVM_EVM0_Msk            0xff

#define WIFI_MACBYPASS_STAT_RSSI_OFFSET             0x094
#define WIFI_MACBYPASS_STAT_RSSI_RSSI_Pos           8
#define WIFI_MACBYPASS_STAT_RSSI_RSSI_Msk           0xff00
#define WIFI_MACBYPASS_STAT_RSSI_LEG_RSSI_Pos       0
#define WIFI_MACBYPASS_STAT_RSSI_LEG_RSSI_Msk       0xff

#define WIFI_MACBYPASS_STAT_PHYERR_OFFSET           0x098
#define WIFI_MACBYPASS_STAT_PHYERR_STAT_PHYERR_Pos    0
#define WIFI_MACBYPASS_STAT_PHYERR_STAT_PHYERR_Msk    0xffffffff

#define WIFI_MACBYPASS_INT_CTRL_OFFSET              0x0A0
#define WIFI_MACBYPASS_INT_CTRL_RXV_LOCK_EN_Pos     16
#define WIFI_MACBYPASS_INT_CTRL_RXV_LOCK_EN_Msk     0x10000
#define WIFI_MACBYPASS_INT_CTRL_INTERRUPT3_EN_Pos    3
#define WIFI_MACBYPASS_INT_CTRL_INTERRUPT3_EN_Msk    0x8
#define WIFI_MACBYPASS_INT_CTRL_INTERRUPT2_EN_Pos    2
#define WIFI_MACBYPASS_INT_CTRL_INTERRUPT2_EN_Msk    0x4
#define WIFI_MACBYPASS_INT_CTRL_INTERRUPT1_EN_Pos    1
#define WIFI_MACBYPASS_INT_CTRL_INTERRUPT1_EN_Msk    0x2
#define WIFI_MACBYPASS_INT_CTRL_INTERRUPT0_EN_Pos    0
#define WIFI_MACBYPASS_INT_CTRL_INTERRUPT0_EN_Msk    0x1

#define WIFI_MACBYPASS_INT_GENERATION_OFFSET        0x0A4
#define WIFI_MACBYPASS_INT_GENERATION_INT3_GEN_Pos    24
#define WIFI_MACBYPASS_INT_GENERATION_INT3_GEN_Msk    0xff000000
#define WIFI_MACBYPASS_INT_GENERATION_INT2_GEN_Pos    16
#define WIFI_MACBYPASS_INT_GENERATION_INT2_GEN_Msk    0xff0000
#define WIFI_MACBYPASS_INT_GENERATION_INT1_GEN_Pos    8
#define WIFI_MACBYPASS_INT_GENERATION_INT1_GEN_Msk    0xff00
#define WIFI_MACBYPASS_INT_GENERATION_INT0_GEN_Pos    0
#define WIFI_MACBYPASS_INT_GENERATION_INT0_GEN_Msk    0xff

#define WIFI_MACBYPASS_INT_STAT_RAW_OFFSET          0x0A8
#define WIFI_MACBYPASS_INT_STAT_RAW_RXV_LOCK_STATE_Pos    16
#define WIFI_MACBYPASS_INT_STAT_RAW_RXV_LOCK_STATE_Msk    0x10000
#define WIFI_MACBYPASS_INT_STAT_RAW_INT3_STATE_Pos    3
#define WIFI_MACBYPASS_INT_STAT_RAW_INT3_STATE_Msk    0x8
#define WIFI_MACBYPASS_INT_STAT_RAW_INT2_STATE_Pos    2
#define WIFI_MACBYPASS_INT_STAT_RAW_INT2_STATE_Msk    0x4
#define WIFI_MACBYPASS_INT_STAT_RAW_INT1_STATE_Pos    1
#define WIFI_MACBYPASS_INT_STAT_RAW_INT1_STATE_Msk    0x2
#define WIFI_MACBYPASS_INT_STAT_RAW_INT0_STATE_Pos    0
#define WIFI_MACBYPASS_INT_STAT_RAW_INT0_STATE_Msk    0x1

#define WIFI_MACBYPASS_INT_STAT_ACK_OFFSET          0x0AC
#define WIFI_MACBYPASS_INT_STAT_ACK_RXV_LOCK_RELEASE_Pos    16
#define WIFI_MACBYPASS_INT_STAT_ACK_RXV_LOCK_RELEASE_Msk    0x10000
#define WIFI_MACBYPASS_INT_STAT_ACK_INT3_ACK_Pos    3
#define WIFI_MACBYPASS_INT_STAT_ACK_INT3_ACK_Msk    0x8
#define WIFI_MACBYPASS_INT_STAT_ACK_INT2_ACK_Pos    2
#define WIFI_MACBYPASS_INT_STAT_ACK_INT2_ACK_Msk    0x4
#define WIFI_MACBYPASS_INT_STAT_ACK_INT1_ACK_Pos    1
#define WIFI_MACBYPASS_INT_STAT_ACK_INT1_ACK_Msk    0x2
#define WIFI_MACBYPASS_INT_STAT_ACK_INT0_ACK_Pos    0
#define WIFI_MACBYPASS_INT_STAT_ACK_INT0_ACK_Msk    0x1

#define WIFI_MACBYPASS_INT_RXV0_OFFSET              0x0B0
#define WIFI_MACBYPASS_INT_RXV0_RXV3_Pos            24
#define WIFI_MACBYPASS_INT_RXV0_RXV3_Msk            0xff000000
#define WIFI_MACBYPASS_INT_RXV0_RXV2_Pos            16
#define WIFI_MACBYPASS_INT_RXV0_RXV2_Msk            0xff0000
#define WIFI_MACBYPASS_INT_RXV0_RXV1_Pos            8
#define WIFI_MACBYPASS_INT_RXV0_RXV1_Msk            0xff00
#define WIFI_MACBYPASS_INT_RXV0_RXV0_Pos            0
#define WIFI_MACBYPASS_INT_RXV0_RXV0_Msk            0xff

#define WIFI_MACBYPASS_INT_RXV4_OFFSET              0x0B4
#define WIFI_MACBYPASS_INT_RXV4_RXV7_Pos            24
#define WIFI_MACBYPASS_INT_RXV4_RXV7_Msk            0xff000000
#define WIFI_MACBYPASS_INT_RXV4_RXV6_Pos            16
#define WIFI_MACBYPASS_INT_RXV4_RXV6_Msk            0xff0000
#define WIFI_MACBYPASS_INT_RXV4_RXV5_Pos            8
#define WIFI_MACBYPASS_INT_RXV4_RXV5_Msk            0xff00
#define WIFI_MACBYPASS_INT_RXV4_RXV4_Pos            0
#define WIFI_MACBYPASS_INT_RXV4_RXV4_Msk            0xff

#define WIFI_MACBYPASS_INT_RXV8_OFFSET              0x0B8
#define WIFI_MACBYPASS_INT_RXV8_RXV11_Pos           24
#define WIFI_MACBYPASS_INT_RXV8_RXV11_Msk           0xff000000
#define WIFI_MACBYPASS_INT_RXV8_RXV10_Pos           16
#define WIFI_MACBYPASS_INT_RXV8_RXV10_Msk           0xff0000
#define WIFI_MACBYPASS_INT_RXV8_RXV9_Pos            8
#define WIFI_MACBYPASS_INT_RXV8_RXV9_Msk            0xff00
#define WIFI_MACBYPASS_INT_RXV8_RXV8_Pos            0
#define WIFI_MACBYPASS_INT_RXV8_RXV8_Msk            0xff

#define WIFI_MACBYPASS_RXV12_OFFSET                 0x0BC
#define WIFI_MACBYPASS_RXV12_RXV15_Pos              24
#define WIFI_MACBYPASS_RXV12_RXV15_Msk              0xff000000
#define WIFI_MACBYPASS_RXV12_RXV14_Pos              16
#define WIFI_MACBYPASS_RXV12_RXV14_Msk              0xff0000
#define WIFI_MACBYPASS_RXV12_RXV13_Pos              8
#define WIFI_MACBYPASS_RXV12_RXV13_Msk              0xff00
#define WIFI_MACBYPASS_RXV12_RXV12_Pos              0
#define WIFI_MACBYPASS_RXV12_RXV12_Msk              0xff

#define WIFI_MACBYPASS_TRIGFORMATMOD_OFFSET         0x100
#define WIFI_MACBYPASS_TRIGFORMATMOD_TRIG_FORMATMOD_EN_Pos    31
#define WIFI_MACBYPASS_TRIGFORMATMOD_TRIG_FORMATMOD_EN_Msk    0x80000000
#define WIFI_MACBYPASS_TRIGFORMATMOD_TRIG_FORMATMOD_Pos    0
#define WIFI_MACBYPASS_TRIGFORMATMOD_TRIG_FORMATMOD_Msk    0xf

#define WIFI_MACBYPASS_TRIGMCS_OFFSET               0x104
#define WIFI_MACBYPASS_TRIGMCS_TRIG_MCS_EN_Pos      31
#define WIFI_MACBYPASS_TRIGMCS_TRIG_MCS_EN_Msk      0x80000000
#define WIFI_MACBYPASS_TRIGMCS_TRIG_MCS_Pos         0
#define WIFI_MACBYPASS_TRIGMCS_TRIG_MCS_Msk         0x7f

#define WIFI_MACBYPASS_TRIGSGI_OFFSET               0x108
#define WIFI_MACBYPASS_TRIGSGI_TRIG_SGI_EN_Pos      31
#define WIFI_MACBYPASS_TRIGSGI_TRIG_SGI_EN_Msk      0x80000000
#define WIFI_MACBYPASS_TRIGSGI_TRIG_SGI_Pos         0
#define WIFI_MACBYPASS_TRIGSGI_TRIG_SGI_Msk         0x3

#define WIFI_MACBYPASS_TRIGFEC_OFFSET               0x10C
#define WIFI_MACBYPASS_TRIGFEC_TRIG_FEC_EN_Pos      31
#define WIFI_MACBYPASS_TRIGFEC_TRIG_FEC_EN_Msk      0x80000000
#define WIFI_MACBYPASS_TRIGFEC_TRIG_FEC_Pos         0
#define WIFI_MACBYPASS_TRIGFEC_TRIG_FEC_Msk         0x1

#define WIFI_MACBYPASS_TRIGSTBC_OFFSET              0x110
#define WIFI_MACBYPASS_TRIGSTBC_TRIG_STBC_EN_Pos    31
#define WIFI_MACBYPASS_TRIGSTBC_TRIG_STBC_EN_Msk    0x80000000
#define WIFI_MACBYPASS_TRIGSTBC_TRIG_STBC_Pos       0
#define WIFI_MACBYPASS_TRIGSTBC_TRIG_STBC_Msk       0x1

#define WIFI_MACBYPASS_TRIGCHBW_OFFSET              0x114
#define WIFI_MACBYPASS_TRIGCHBW_TRIG_CHBW_EN_Pos    31
#define WIFI_MACBYPASS_TRIGCHBW_TRIG_CHBW_EN_Msk    0x80000000
#define WIFI_MACBYPASS_TRIGCHBW_TRIG_CHBW_Pos       0
#define WIFI_MACBYPASS_TRIGCHBW_TRIG_CHBW_Msk       0x7

#define WIFI_MACBYPASS_TRIGNSTS_OFFSET              0x118
#define WIFI_MACBYPASS_TRIGNSTS_TRIG_NSTS_EN_Pos    31
#define WIFI_MACBYPASS_TRIGNSTS_TRIG_NSTS_EN_Msk    0x80000000
#define WIFI_MACBYPASS_TRIGNSTS_TRIG_NSTS_Pos       0
#define WIFI_MACBYPASS_TRIGNSTS_TRIG_NSTS_Msk       0x7

#define WIFI_MACBYPASS_TRIGSOUNDING_OFFSET          0x11C
#define WIFI_MACBYPASS_TRIGSOUNDING_TRIG_SOUNDING_EN_Pos    31
#define WIFI_MACBYPASS_TRIGSOUNDING_TRIG_SOUNDING_EN_Msk    0x80000000
#define WIFI_MACBYPASS_TRIGSOUNDING_TRIG_SOUNDING_Pos    0
#define WIFI_MACBYPASS_TRIGSOUNDING_TRIG_SOUNDING_Msk    0x1

#define WIFI_MACBYPASS_TRIGPARTIALAID_OFFSET        0x120
#define WIFI_MACBYPASS_TRIGPARTIALAID_TRIG_PARTIALAID_EN_Pos    31
#define WIFI_MACBYPASS_TRIGPARTIALAID_TRIG_PARTIALAID_EN_Msk    0x80000000
#define WIFI_MACBYPASS_TRIGPARTIALAID_TRIG_PARTIALAID_Pos    0
#define WIFI_MACBYPASS_TRIGPARTIALAID_TRIG_PARTIALAID_Msk    0x1ff

#define WIFI_MACBYPASS_TRIGGROUPID_OFFSET           0x124
#define WIFI_MACBYPASS_TRIGGROUPID_TRIG_GROUPID_EN_Pos    31
#define WIFI_MACBYPASS_TRIGGROUPID_TRIG_GROUPID_EN_Msk    0x80000000
#define WIFI_MACBYPASS_TRIGGROUPID_TRIG_GROUPID_Pos    0
#define WIFI_MACBYPASS_TRIGGROUPID_TRIG_GROUPID_Msk    0x3f

#define WIFI_MACBYPASS_TRIGSMOOTHING_OFFSET         0x128
#define WIFI_MACBYPASS_TRIGSMOOTHING_TRIG_SMOOTHING_EN_Pos    31
#define WIFI_MACBYPASS_TRIGSMOOTHING_TRIG_SMOOTHING_EN_Msk    0x80000000
#define WIFI_MACBYPASS_TRIGSMOOTHING_TRIG_SMOOTHING_Pos    0
#define WIFI_MACBYPASS_TRIGSMOOTHING_TRIG_SMOOTHING_Msk    0x1

#define WIFI_MACBYPASS_TXV_OFFSET                   0x200
#define WIFI_MACBYPASS_TXV_TXV_BYTE_Pos             0
#define WIFI_MACBYPASS_TXV_TXV_BYTE_Msk             0xff

struct WIFI_MACBYPASS_REG_CTRL_BITS
{
    volatile uint32_t BYPASS                        : 1; // bit 0~0
    volatile uint32_t DEFRXREQ                      : 1; // bit 1~1
    volatile uint32_t DEFKEEPRFON                   : 1; // bit 2~2
    volatile uint32_t RESV_3_3                      : 1; // bit 3~3
    volatile uint32_t CLEAR_STAT                    : 1; // bit 4~4
    volatile uint32_t RESV_5_7                      : 3; // bit 5~7
    volatile uint32_t MODE                          : 2; // bit 8~9
    volatile uint32_t RESV_10_30                    : 21; // bit 10~30
    volatile uint32_t TX_DONE                       : 1; // bit 31~31
};

union WIFI_MACBYPASS_REG_CTRL {
    volatile uint32_t                               all;
    struct WIFI_MACBYPASS_REG_CTRL_BITS             bit;
};

struct WIFI_MACBYPASS_REG_PAYLOAD_BITS
{
    volatile uint32_t PAYLOAD_RX                    : 4; // bit 0~3
    volatile uint32_t RESV_4_15                     : 12; // bit 4~15
    volatile uint32_t PAYLOAD_TX                    : 4; // bit 16~19
    volatile uint32_t RESV_20_31                    : 12; // bit 20~31
};

union WIFI_MACBYPASS_REG_PAYLOAD {
    volatile uint32_t                               all;
    struct WIFI_MACBYPASS_REG_PAYLOAD_BITS          bit;
};

struct WIFI_MACBYPASS_REG_TRIGGER_BITS
{
    volatile uint32_t TRIGGER0                      : 4; // bit 0~3
    volatile uint32_t TRIGGER1                      : 4; // bit 4~7
    volatile uint32_t RESV_8_31                     : 24; // bit 8~31
};

union WIFI_MACBYPASS_REG_TRIGGER {
    volatile uint32_t                               all;
    struct WIFI_MACBYPASS_REG_TRIGGER_BITS          bit;
};

struct WIFI_MACBYPASS_REG_CLKEN_BITS
{
    volatile uint32_t CLKEN                         : 1; // bit 0~0
    volatile uint32_t RESV_1_31                     : 31; // bit 1~31
};

union WIFI_MACBYPASS_REG_CLKEN {
    volatile uint32_t                               all;
    struct WIFI_MACBYPASS_REG_CLKEN_BITS            bit;
};

struct WIFI_MACBYPASS_REG_FRAMEPERBURST_BITS
{
    volatile uint32_t NFRAME                        : 16; // bit 0~15
    volatile uint32_t RESV_16_31                    : 16; // bit 16~31
};

union WIFI_MACBYPASS_REG_FRAMEPERBURST {
    volatile uint32_t                               all;
    struct WIFI_MACBYPASS_REG_FRAMEPERBURST_BITS    bit;
};

struct WIFI_MACBYPASS_REG_COEX_BITS
{
    volatile uint32_t PTI                           : 4; // bit 0~3
    volatile uint32_t COEX_EN                       : 1; // bit 4~4
    volatile uint32_t RESV_5_31                     : 27; // bit 5~31
};

union WIFI_MACBYPASS_REG_COEX {
    volatile uint32_t                               all;
    struct WIFI_MACBYPASS_REG_COEX_BITS             bit;
};

struct WIFI_MACBYPASS_REG_INTERFRAME_DELAY_BITS
{
    volatile uint32_t INTERFRAME_DELAY              : 20; // bit 0~19
    volatile uint32_t RESV_20_31                    : 12; // bit 20~31
};

union WIFI_MACBYPASS_REG_INTERFRAME_DELAY {
    volatile uint32_t                               all;
    struct WIFI_MACBYPASS_REG_INTERFRAME_DELAY_BITS    bit;
};

struct WIFI_MACBYPASS_REG_STAT_FRAME_OK_BITS
{
    volatile uint32_t STAT_FRAME_OK                 : 32; // bit 0~31
};

union WIFI_MACBYPASS_REG_STAT_FRAME_OK {
    volatile uint32_t                               all;
    struct WIFI_MACBYPASS_REG_STAT_FRAME_OK_BITS    bit;
};

struct WIFI_MACBYPASS_REG_STAT_FRAME_BAD_BITS
{
    volatile uint32_t STAT_FRAME_BAD                : 32; // bit 0~31
};

union WIFI_MACBYPASS_REG_STAT_FRAME_BAD {
    volatile uint32_t                               all;
    struct WIFI_MACBYPASS_REG_STAT_FRAME_BAD_BITS    bit;
};

struct WIFI_MACBYPASS_REG_STAT_RXEND_BITS
{
    volatile uint32_t STAT_FRAME_RXEND              : 32; // bit 0~31
};

union WIFI_MACBYPASS_REG_STAT_RXEND {
    volatile uint32_t                               all;
    struct WIFI_MACBYPASS_REG_STAT_RXEND_BITS       bit;
};

struct WIFI_MACBYPASS_REG_STAT_RXERROR_BITS
{
    volatile uint32_t STAT_FRAME_RXERROR            : 32; // bit 0~31
};

union WIFI_MACBYPASS_REG_STAT_RXERROR {
    volatile uint32_t                               all;
    struct WIFI_MACBYPASS_REG_STAT_RXERROR_BITS     bit;
};

struct WIFI_MACBYPASS_REG_STAT_EVM_BITS
{
    volatile uint32_t EVM0                          : 8; // bit 0~7
    volatile uint32_t EVM1                          : 8; // bit 8~15
    volatile uint32_t EVM2                          : 8; // bit 16~23
    volatile uint32_t EVM3                          : 8; // bit 24~31
};

union WIFI_MACBYPASS_REG_STAT_EVM {
    volatile uint32_t                               all;
    struct WIFI_MACBYPASS_REG_STAT_EVM_BITS         bit;
};

struct WIFI_MACBYPASS_REG_STAT_RSSI_BITS
{
    volatile uint32_t LEG_RSSI                      : 8; // bit 0~7
    volatile uint32_t RSSI                          : 8; // bit 8~15
    volatile uint32_t RESV_16_31                    : 16; // bit 16~31
};

union WIFI_MACBYPASS_REG_STAT_RSSI {
    volatile uint32_t                               all;
    struct WIFI_MACBYPASS_REG_STAT_RSSI_BITS        bit;
};

struct WIFI_MACBYPASS_REG_STAT_PHYERR_BITS
{
    volatile uint32_t STAT_PHYERR                   : 32; // bit 0~31
};

union WIFI_MACBYPASS_REG_STAT_PHYERR {
    volatile uint32_t                               all;
    struct WIFI_MACBYPASS_REG_STAT_PHYERR_BITS      bit;
};

struct WIFI_MACBYPASS_REG_INT_CTRL_BITS
{
    volatile uint32_t INTERRUPT0_EN                 : 1; // bit 0~0
    volatile uint32_t INTERRUPT1_EN                 : 1; // bit 1~1
    volatile uint32_t INTERRUPT2_EN                 : 1; // bit 2~2
    volatile uint32_t INTERRUPT3_EN                 : 1; // bit 3~3
    volatile uint32_t RESV_4_15                     : 12; // bit 4~15
    volatile uint32_t RXV_LOCK_EN                   : 1; // bit 16~16
    volatile uint32_t RESV_17_31                    : 15; // bit 17~31
};

union WIFI_MACBYPASS_REG_INT_CTRL {
    volatile uint32_t                               all;
    struct WIFI_MACBYPASS_REG_INT_CTRL_BITS         bit;
};

struct WIFI_MACBYPASS_REG_INT_GENERATION_BITS
{
    volatile uint32_t INT0_GEN                      : 8; // bit 0~7
    volatile uint32_t INT1_GEN                      : 8; // bit 8~15
    volatile uint32_t INT2_GEN                      : 8; // bit 16~23
    volatile uint32_t INT3_GEN                      : 8; // bit 24~31
};

union WIFI_MACBYPASS_REG_INT_GENERATION {
    volatile uint32_t                               all;
    struct WIFI_MACBYPASS_REG_INT_GENERATION_BITS    bit;
};

struct WIFI_MACBYPASS_REG_INT_STAT_RAW_BITS
{
    volatile uint32_t INT0_STATE                    : 1; // bit 0~0
    volatile uint32_t INT1_STATE                    : 1; // bit 1~1
    volatile uint32_t INT2_STATE                    : 1; // bit 2~2
    volatile uint32_t INT3_STATE                    : 1; // bit 3~3
    volatile uint32_t RESV_4_15                     : 12; // bit 4~15
    volatile uint32_t RXV_LOCK_STATE                : 1; // bit 16~16
    volatile uint32_t RESV_17_31                    : 15; // bit 17~31
};

union WIFI_MACBYPASS_REG_INT_STAT_RAW {
    volatile uint32_t                               all;
    struct WIFI_MACBYPASS_REG_INT_STAT_RAW_BITS     bit;
};

struct WIFI_MACBYPASS_REG_INT_STAT_ACK_BITS
{
    volatile uint32_t INT0_ACK                      : 1; // bit 0~0
    volatile uint32_t INT1_ACK                      : 1; // bit 1~1
    volatile uint32_t INT2_ACK                      : 1; // bit 2~2
    volatile uint32_t INT3_ACK                      : 1; // bit 3~3
    volatile uint32_t RESV_4_15                     : 12; // bit 4~15
    volatile uint32_t RXV_LOCK_RELEASE              : 1; // bit 16~16
    volatile uint32_t RESV_17_31                    : 15; // bit 17~31
};

union WIFI_MACBYPASS_REG_INT_STAT_ACK {
    volatile uint32_t                               all;
    struct WIFI_MACBYPASS_REG_INT_STAT_ACK_BITS     bit;
};

struct WIFI_MACBYPASS_REG_INT_RXV0_BITS
{
    volatile uint32_t RXV0                          : 8; // bit 0~7
    volatile uint32_t RXV1                          : 8; // bit 8~15
    volatile uint32_t RXV2                          : 8; // bit 16~23
    volatile uint32_t RXV3                          : 8; // bit 24~31
};

union WIFI_MACBYPASS_REG_INT_RXV0 {
    volatile uint32_t                               all;
    struct WIFI_MACBYPASS_REG_INT_RXV0_BITS         bit;
};

struct WIFI_MACBYPASS_REG_INT_RXV4_BITS
{
    volatile uint32_t RXV4                          : 8; // bit 0~7
    volatile uint32_t RXV5                          : 8; // bit 8~15
    volatile uint32_t RXV6                          : 8; // bit 16~23
    volatile uint32_t RXV7                          : 8; // bit 24~31
};

union WIFI_MACBYPASS_REG_INT_RXV4 {
    volatile uint32_t                               all;
    struct WIFI_MACBYPASS_REG_INT_RXV4_BITS         bit;
};

struct WIFI_MACBYPASS_REG_INT_RXV8_BITS
{
    volatile uint32_t RXV8                          : 8; // bit 0~7
    volatile uint32_t RXV9                          : 8; // bit 8~15
    volatile uint32_t RXV10                         : 8; // bit 16~23
    volatile uint32_t RXV11                         : 8; // bit 24~31
};

union WIFI_MACBYPASS_REG_INT_RXV8 {
    volatile uint32_t                               all;
    struct WIFI_MACBYPASS_REG_INT_RXV8_BITS         bit;
};

struct WIFI_MACBYPASS_REG_RXV12_BITS
{
    volatile uint32_t RXV12                         : 8; // bit 0~7
    volatile uint32_t RXV13                         : 8; // bit 8~15
    volatile uint32_t RXV14                         : 8; // bit 16~23
    volatile uint32_t RXV15                         : 8; // bit 24~31
};

union WIFI_MACBYPASS_REG_RXV12 {
    volatile uint32_t                               all;
    struct WIFI_MACBYPASS_REG_RXV12_BITS            bit;
};

struct WIFI_MACBYPASS_REG_TRIGFORMATMOD_BITS
{
    volatile uint32_t TRIG_FORMATMOD                : 4; // bit 0~3
    volatile uint32_t RESV_4_30                     : 27; // bit 4~30
    volatile uint32_t TRIG_FORMATMOD_EN             : 1; // bit 31~31
};

union WIFI_MACBYPASS_REG_TRIGFORMATMOD {
    volatile uint32_t                               all;
    struct WIFI_MACBYPASS_REG_TRIGFORMATMOD_BITS    bit;
};

struct WIFI_MACBYPASS_REG_TRIGMCS_BITS
{
    volatile uint32_t TRIG_MCS                      : 7; // bit 0~6
    volatile uint32_t RESV_7_30                     : 24; // bit 7~30
    volatile uint32_t TRIG_MCS_EN                   : 1; // bit 31~31
};

union WIFI_MACBYPASS_REG_TRIGMCS {
    volatile uint32_t                               all;
    struct WIFI_MACBYPASS_REG_TRIGMCS_BITS          bit;
};

struct WIFI_MACBYPASS_REG_TRIGSGI_BITS
{
    volatile uint32_t TRIG_SGI                      : 2; // bit 0~1
    volatile uint32_t RESV_2_30                     : 29; // bit 2~30
    volatile uint32_t TRIG_SGI_EN                   : 1; // bit 31~31
};

union WIFI_MACBYPASS_REG_TRIGSGI {
    volatile uint32_t                               all;
    struct WIFI_MACBYPASS_REG_TRIGSGI_BITS          bit;
};

struct WIFI_MACBYPASS_REG_TRIGFEC_BITS
{
    volatile uint32_t TRIG_FEC                      : 1; // bit 0~0
    volatile uint32_t RESV_1_30                     : 30; // bit 1~30
    volatile uint32_t TRIG_FEC_EN                   : 1; // bit 31~31
};

union WIFI_MACBYPASS_REG_TRIGFEC {
    volatile uint32_t                               all;
    struct WIFI_MACBYPASS_REG_TRIGFEC_BITS          bit;
};

struct WIFI_MACBYPASS_REG_TRIGSTBC_BITS
{
    volatile uint32_t TRIG_STBC                     : 1; // bit 0~0
    volatile uint32_t RESV_1_30                     : 30; // bit 1~30
    volatile uint32_t TRIG_STBC_EN                  : 1; // bit 31~31
};

union WIFI_MACBYPASS_REG_TRIGSTBC {
    volatile uint32_t                               all;
    struct WIFI_MACBYPASS_REG_TRIGSTBC_BITS         bit;
};

struct WIFI_MACBYPASS_REG_TRIGCHBW_BITS
{
    volatile uint32_t TRIG_CHBW                     : 3; // bit 0~2
    volatile uint32_t RESV_3_30                     : 28; // bit 3~30
    volatile uint32_t TRIG_CHBW_EN                  : 1; // bit 31~31
};

union WIFI_MACBYPASS_REG_TRIGCHBW {
    volatile uint32_t                               all;
    struct WIFI_MACBYPASS_REG_TRIGCHBW_BITS         bit;
};

struct WIFI_MACBYPASS_REG_TRIGNSTS_BITS
{
    volatile uint32_t TRIG_NSTS                     : 3; // bit 0~2
    volatile uint32_t RESV_3_30                     : 28; // bit 3~30
    volatile uint32_t TRIG_NSTS_EN                  : 1; // bit 31~31
};

union WIFI_MACBYPASS_REG_TRIGNSTS {
    volatile uint32_t                               all;
    struct WIFI_MACBYPASS_REG_TRIGNSTS_BITS         bit;
};

struct WIFI_MACBYPASS_REG_TRIGSOUNDING_BITS
{
    volatile uint32_t TRIG_SOUNDING                 : 1; // bit 0~0
    volatile uint32_t RESV_1_30                     : 30; // bit 1~30
    volatile uint32_t TRIG_SOUNDING_EN              : 1; // bit 31~31
};

union WIFI_MACBYPASS_REG_TRIGSOUNDING {
    volatile uint32_t                               all;
    struct WIFI_MACBYPASS_REG_TRIGSOUNDING_BITS     bit;
};

struct WIFI_MACBYPASS_REG_TRIGPARTIALAID_BITS
{
    volatile uint32_t TRIG_PARTIALAID               : 9; // bit 0~8
    volatile uint32_t RESV_9_30                     : 22; // bit 9~30
    volatile uint32_t TRIG_PARTIALAID_EN            : 1; // bit 31~31
};

union WIFI_MACBYPASS_REG_TRIGPARTIALAID {
    volatile uint32_t                               all;
    struct WIFI_MACBYPASS_REG_TRIGPARTIALAID_BITS    bit;
};

struct WIFI_MACBYPASS_REG_TRIGGROUPID_BITS
{
    volatile uint32_t TRIG_GROUPID                  : 6; // bit 0~5
    volatile uint32_t RESV_6_30                     : 25; // bit 6~30
    volatile uint32_t TRIG_GROUPID_EN               : 1; // bit 31~31
};

union WIFI_MACBYPASS_REG_TRIGGROUPID {
    volatile uint32_t                               all;
    struct WIFI_MACBYPASS_REG_TRIGGROUPID_BITS      bit;
};

struct WIFI_MACBYPASS_REG_TRIGSMOOTHING_BITS
{
    volatile uint32_t TRIG_SMOOTHING                : 1; // bit 0~0
    volatile uint32_t RESV_1_30                     : 30; // bit 1~30
    volatile uint32_t TRIG_SMOOTHING_EN             : 1; // bit 31~31
};

union WIFI_MACBYPASS_REG_TRIGSMOOTHING {
    volatile uint32_t                               all;
    struct WIFI_MACBYPASS_REG_TRIGSMOOTHING_BITS    bit;
};

struct WIFI_MACBYPASS_REG_TXV_BITS
{
    volatile uint32_t TXV_BYTE                      : 8; // bit 0~7
    volatile uint32_t RESV_8_31                     : 24; // bit 8~31
};

union WIFI_MACBYPASS_REG_TXV {
    volatile uint32_t                               all;
    struct WIFI_MACBYPASS_REG_TXV_BITS              bit;
};

typedef struct
{
    union WIFI_MACBYPASS_REG_CTRL                   REG_CTRL;    // 0x000
    union WIFI_MACBYPASS_REG_PAYLOAD                REG_PAYLOAD; // 0x004
    union WIFI_MACBYPASS_REG_TRIGGER                REG_TRIGGER; // 0x008
    union WIFI_MACBYPASS_REG_CLKEN                  REG_CLKEN;   // 0x00C
    union WIFI_MACBYPASS_REG_FRAMEPERBURST          REG_FRAMEPERBURST; // 0x010
    union WIFI_MACBYPASS_REG_COEX                   REG_COEX;    // 0x014
    volatile uint32_t                               REG_RESV_0X18_0X44[12];
    union WIFI_MACBYPASS_REG_INTERFRAME_DELAY       REG_INTERFRAME_DELAY; // 0x048
    volatile uint32_t                               REG_RESV_0X4C_0X7C[13];
    union WIFI_MACBYPASS_REG_STAT_FRAME_OK          REG_STAT_FRAME_OK; // 0x080
    union WIFI_MACBYPASS_REG_STAT_FRAME_BAD         REG_STAT_FRAME_BAD; // 0x084
    union WIFI_MACBYPASS_REG_STAT_RXEND             REG_STAT_RXEND; // 0x088
    union WIFI_MACBYPASS_REG_STAT_RXERROR           REG_STAT_RXERROR; // 0x08C
    union WIFI_MACBYPASS_REG_STAT_EVM               REG_STAT_EVM; // 0x090
    union WIFI_MACBYPASS_REG_STAT_RSSI              REG_STAT_RSSI; // 0x094
    union WIFI_MACBYPASS_REG_STAT_PHYERR            REG_STAT_PHYERR; // 0x098
    volatile uint32_t                               REG_RESV_0X9C_0X9C[1];
    union WIFI_MACBYPASS_REG_INT_CTRL               REG_INT_CTRL; // 0x0A0
    union WIFI_MACBYPASS_REG_INT_GENERATION         REG_INT_GENERATION; // 0x0A4
    union WIFI_MACBYPASS_REG_INT_STAT_RAW           REG_INT_STAT_RAW; // 0x0A8
    union WIFI_MACBYPASS_REG_INT_STAT_ACK           REG_INT_STAT_ACK; // 0x0AC
    union WIFI_MACBYPASS_REG_INT_RXV0               REG_INT_RXV0; // 0x0B0
    union WIFI_MACBYPASS_REG_INT_RXV4               REG_INT_RXV4; // 0x0B4
    union WIFI_MACBYPASS_REG_INT_RXV8               REG_INT_RXV8; // 0x0B8
    union WIFI_MACBYPASS_REG_RXV12                  REG_RXV12;   // 0x0BC
    volatile uint32_t                               REG_RESV_0XC0_0XFC[16];
    union WIFI_MACBYPASS_REG_TRIGFORMATMOD          REG_TRIGFORMATMOD; // 0x100
    union WIFI_MACBYPASS_REG_TRIGMCS                REG_TRIGMCS; // 0x104
    union WIFI_MACBYPASS_REG_TRIGSGI                REG_TRIGSGI; // 0x108
    union WIFI_MACBYPASS_REG_TRIGFEC                REG_TRIGFEC; // 0x10C
    union WIFI_MACBYPASS_REG_TRIGSTBC               REG_TRIGSTBC; // 0x110
    union WIFI_MACBYPASS_REG_TRIGCHBW               REG_TRIGCHBW; // 0x114
    union WIFI_MACBYPASS_REG_TRIGNSTS               REG_TRIGNSTS; // 0x118
    union WIFI_MACBYPASS_REG_TRIGSOUNDING           REG_TRIGSOUNDING; // 0x11C
    union WIFI_MACBYPASS_REG_TRIGPARTIALAID         REG_TRIGPARTIALAID; // 0x120
    union WIFI_MACBYPASS_REG_TRIGGROUPID            REG_TRIGGROUPID; // 0x124
    union WIFI_MACBYPASS_REG_TRIGSMOOTHING          REG_TRIGSMOOTHING; // 0x128
    volatile uint32_t                               REG_RESV_0X12C_0X1FC[53];
    union WIFI_MACBYPASS_REG_TXV                    REG_TXV;     // 0x200
} WIFI_MACBYPASS_RegDef;


#endif // __WIFI_MACBYPASS_REGFILE_H__

