/**
 ****************************************************************************************
 *
 * Don't modify this file. It is automatically generated by a script.
 *
 * Author: KeHuatao
 *
 * Copyright (C) ListenAI 2025
 *
 ****************************************************************************************
 */
#include <stdint.h>
#include <string.h>
#include "ls_err.h"
#include "ls_wifi_type.h"
#include "ipc.h"
#include "mrpc.h"
#include "mrpc_lwip_api_msg.h"
#include "mrpc_lwip_api_server.h"

ls_err_t lwip_pbuf_alloc(const struct pbuf ** pbuf, pbuf_layer layer, u16_t length, pbuf_type type)
{
    mrpc_lwip_pbuf_alloc_req_t req;
    mrpc_lwip_pbuf_alloc_resp_t resp;

    req.hdr.id = MRPC_MSG_ID_LWIP_PBUF_ALLOC;
    req.pbuf = (struct pbuf **)pbuf;
    req.layer = layer;
    req.length = length;
    req.type = type;
    if (mrpc_msg_send(&req, sizeof(mrpc_lwip_pbuf_alloc_req_t), &resp))
        return LS_FAIL;

    return (ls_err_t)resp.hdr.status;
}

ls_err_t lwip_pbuf_free(struct pbuf * p, uint8_t * count)
{
    mrpc_lwip_pbuf_free_req_t req;
    mrpc_lwip_pbuf_free_resp_t resp;

    req.hdr.id = MRPC_MSG_ID_LWIP_PBUF_FREE;
    req.p = p;
    req.count = count;
    if (mrpc_msg_send(&req, sizeof(mrpc_lwip_pbuf_free_req_t), &resp))
        return LS_FAIL;

    return (ls_err_t)resp.hdr.status;
}

