add_subdirectory(lisa_device)
add_subdirectory(lisa_adc)
add_subdirectory(lisa_audio)
add_subdirectory(lisa_gpio)
add_subdirectory(lisa_i2c)
add_subdirectory(lisa_pwm)
add_subdirectory(lisa_spi)
add_subdirectory(lisa_uart)
add_subdirectory(lisa_display)
add_subdirectory(lisa_touch)
add_subdirectory(lisa_wdt)
add_subdirectory(lisa_camera)
add_subdirectory(lisa_rtc)
add_subdirectory(lisa_flash)
add_subdirectory(lisa_hwtimer)
add_subdirectory(lisa_sdmmc)
add_subdirectory(lisa_qspilcd)
add_subdirectory(lisa_dvp)
add_subdirectory(lisa_rgb)
