/**
 ****************************************************************************************
 *
 * Don't modify this file. It is automatically generated by a script.
 *
 * Author: KeHuatao
 *
 * Copyright (C) ListenAI 2025
 *
 ****************************************************************************************
 */
#include <stdint.h>
#include <string.h>
#include "ls_err.h"
#include "ipc.h"
#include "mrpc.h"
#include "mrpc_luna_api_client.h"
#include "mrpc_luna_api_msg.h"
#include "mrpc_luna_api_server.h"

static void mrpc_luna_demo_get_version(void *msg, struct mrpc_resp_msg *resp_msg, uint32_t resp_buf_len)
{
    mrpc_luna_demo_get_version_req_t *req;
    mrpc_luna_demo_get_version_resp_t *resp;

    req = (mrpc_luna_demo_get_version_req_t*)msg;
    resp = (mrpc_luna_demo_get_version_resp_t*)resp_msg;
    memset(resp, 0, sizeof(mrpc_luna_demo_get_version_resp_t));
    resp_msg->len = sizeof(mrpc_luna_demo_get_version_resp_t);
    resp_msg->status = luna_demo_get_version(&resp->version);
}

static void mrpc_luna_demo_add(void *msg, struct mrpc_resp_msg *resp_msg, uint32_t resp_buf_len)
{
    mrpc_luna_demo_add_req_t *req;
    mrpc_luna_demo_add_resp_t *resp;

    req = (mrpc_luna_demo_add_req_t*)msg;
    resp = (mrpc_luna_demo_add_resp_t*)resp_msg;
    memset(resp, 0, sizeof(mrpc_luna_demo_add_resp_t));
    resp_msg->len = sizeof(mrpc_luna_demo_add_resp_t);
    resp_msg->status = luna_demo_add(req->a, req->b, &resp->result);
}


mrpc_msg_handler_t mrpc_msg_luna_handlers[MRPC_MSG_ID_LUNA_MAX - MRPC_MSG_ID_LUNA_START] =
{
    mrpc_luna_demo_get_version,  /*MRPC_MSG_ID_LUNA_DEMO_GET_VERSION*/
    mrpc_luna_demo_add,  /*MRPC_MSG_ID_LUNA_DEMO_ADD*/
    NULL
};