CONFIG_PSRAM_HEAP_SIZE=0x40000

CONFIG_ARCS_AP_CORE=y

CONFIG_LISA_WIFI=y
CONFIG_WIFI_LWIP_DIFF_CORE=y

# 双核WiFi要手动选择当前核心运行WIFI还是LWIP
CONFIG_WIFI=y

# 射频板型配置
CONFIG_ARCS_HAL_WCND_RF_BOARD_VER=1

CONFIG_SYSLOG_PRINTK_REDIRECT=y
CONFIG_SYSLOG_UART_DEVICE_UART1=y

