# 项目可根据需要在此文件中设置对应的配置

# TinyUSB 配置
CONFIG_TINY_USB=y
CONFIG_TINY_USB_USE_CUSTOM_CONFIG_FILE=y
CONFIG_TINY_USB_CONFIG_FILE="tusb_config.h"

# 日志配置
CONFIG_LOG=y
CONFIG_SYSLOG_PRINTK_REDIRECT=y

# 磁盘驱动配置
CONFIG_DISK_DRIVER=y
CONFIG_DISK_DRIVER_SDMMC=y

# 系统配置
CONFIG_LINK_OPTION_NOSYS_SPECS=y
