# 项目可根据需要在此文件中设置对应的配置
CONFIG_ARCS_HAL_WARNING_DISABLE=y

CONFIG_TINY_USB=y
CONFIG_TINY_USB_USE_CUSTOM_CONFIG_FILE=y
CONFIG_TINY_USB_CONFIG_FILE="tusb_config.h"

CONFIG_LOG=y
CONFIG_SYSLOG_PRINTK_REDIRECT=y

CONFIG_DISK_DRIVER=y
CONFIG_DISK_DRIVER_SDMMC=y

CONFIG_LINK_OPTION_NOSYS_SPECS=y

# CONFIG_BOARD_QFN52_ARCS_D_EVB=y
