# TinyUSB configuration
CONFIG_TINY_USB=y
CONFIG_TINY_USB_USE_CUSTOM_CONFIG_FILE=y
CONFIG_TINY_USB_CONFIG_FILE="tusb_config.h"

# File system configuration
CONFIG_FILE_SYSTEM=y
CONFIG_FATFS_FILESYSTEM=y
CONFIG_DISK_DRIVER=y
CONFIG_DISK_DRIVER_FLASH=y
CONFIG_DISK_DRIVER_SDMMC=y
CONFIG_DISK_FLASH_START_ADDR=0x100000
CONFIG_DISK_FLASH_MAX_RW_SIZE=4096
CONFIG_DISK_FLASH_ERASE_ALIGNMENT=4096
CONFIG_DISK_FLASH_ERASE_BLOCK_SIZE=4096
CONFIG_DISK_FLASH_SECTOR_SIZE=512
CONFIG_DISK_FLASH_VOLUME_SIZE=3145728

# LSFS configuration
CONFIG_LSFS=y
CONFIG_LSFS_FAT=y

# ADB configuration
CONFIG_TUSB_APP_CLASS=y
CONFIG_ADB_SYNC=y
CONFIG_ADB_PUSH_PULL_DEFAULT_ROOT="/NAND:/adb_bench/"
CONFIG_ADB_SHELL=y

# Shell configuration
CONFIG_SDK_MODULE_LETTER_SHELL=y
CONFIG_SDK_MODULE_LETTER_SHELL_CONFIG_FILE="shell_cfg_user.h"

# SDMMC public driver usage
CONFIG_LISA_DEVICE=y
CONFIG_LISA_SDMMC_DEVICE=y
CONFIG_LISA_SDMMC_CARD_TYPE_AUTO=y

# System configuration
CONFIG_LINK_OPTION_NOSYS_SPECS=y
CONFIG_DCACHE_ENABLE=y

# Memory configuration
CONFIG_PSRAM_HEAP_SIZE=0x300000
CONFIG_HEAP_SIZE=0x10000

# Logging configuration
CONFIG_EASYLOGGER_ASYNC_BUF_SIZE=102400
