/**
 ****************************************************************************************
 *
 * Don't modify this file. It is automatically generated by a script.
 *
 * Author: KeHuatao
 *
 * Copyright (C) ListenAI 2025
 *
 ****************************************************************************************
 */
#include <stdio.h>
#include <stdint.h>
#include <string.h>
#include "ls_err.h"
#include "ls_wifi_type.h"
#include "flash_if.h"
#include "ipc.h"
#include "mrpc.h"
#include "mrpc_flash_if_api_msg.h"
#include "mrpc_flash_if_api_server.h"

static void mrpc_flash_if_init(void *msg, struct mrpc_resp_msg *resp_msg)
{
    mrpc_flash_if_init_req_t *req;
    mrpc_flash_if_init_resp_t *resp;

    req = (mrpc_flash_if_init_req_t*)msg;
    resp = (mrpc_flash_if_init_resp_t*)resp_msg;
    memset(resp, 0, sizeof(mrpc_flash_if_init_resp_t));
    resp_msg->len = sizeof(mrpc_flash_if_init_resp_t);
    resp_msg->status = flash_if_init(&req->dev, req->ud0, req->ud1);
}

static void mrpc_flash_if_read(void *msg, struct mrpc_resp_msg *resp_msg)
{
    mrpc_flash_if_read_req_t *req;
    mrpc_flash_if_read_resp_t *resp;

    req = (mrpc_flash_if_read_req_t*)msg;
    resp = (mrpc_flash_if_read_resp_t*)resp_msg;
    memset(resp, 0, sizeof(mrpc_flash_if_read_resp_t));
    resp_msg->len = sizeof(mrpc_flash_if_read_resp_t);
    resp_msg->status = flash_if_read(req->offset, req->data, req->len);
}

static void mrpc_flash_if_write(void *msg, struct mrpc_resp_msg *resp_msg)
{
    mrpc_flash_if_write_req_t *req;
    mrpc_flash_if_write_resp_t *resp;

    req = (mrpc_flash_if_write_req_t*)msg;
    resp = (mrpc_flash_if_write_resp_t*)resp_msg;
    memset(resp, 0, sizeof(mrpc_flash_if_write_resp_t));
    resp_msg->len = sizeof(mrpc_flash_if_write_resp_t);
    resp_msg->status = flash_if_write(req->offset, (const void *)req->data, req->len);
}

static void mrpc_flash_if_erase(void *msg, struct mrpc_resp_msg *resp_msg)
{
    mrpc_flash_if_erase_req_t *req;
    mrpc_flash_if_erase_resp_t *resp;

    req = (mrpc_flash_if_erase_req_t*)msg;
    resp = (mrpc_flash_if_erase_resp_t*)resp_msg;
    memset(resp, 0, sizeof(mrpc_flash_if_erase_resp_t));
    resp_msg->len = sizeof(mrpc_flash_if_erase_resp_t);
    resp_msg->status = flash_if_erase(req->offset, req->size);
}

static void mrpc_flash_if_write_protection_set(void *msg, struct mrpc_resp_msg *resp_msg)
{
    mrpc_flash_if_write_protection_set_req_t *req;
    mrpc_flash_if_write_protection_set_resp_t *resp;

    req = (mrpc_flash_if_write_protection_set_req_t*)msg;
    resp = (mrpc_flash_if_write_protection_set_resp_t*)resp_msg;
    memset(resp, 0, sizeof(mrpc_flash_if_write_protection_set_resp_t));
    resp_msg->len = sizeof(mrpc_flash_if_write_protection_set_resp_t);
    resp_msg->status = flash_if_write_protection_set(req->enable);
}

static void mrpc_flash_if_security_read(void *msg, struct mrpc_resp_msg *resp_msg)
{
    mrpc_flash_if_security_read_req_t *req;
    mrpc_flash_if_security_read_resp_t *resp;

    req = (mrpc_flash_if_security_read_req_t*)msg;
    resp = (mrpc_flash_if_security_read_resp_t*)resp_msg;
    memset(resp, 0, sizeof(mrpc_flash_if_security_read_resp_t));
    resp_msg->len = sizeof(mrpc_flash_if_security_read_resp_t);
    resp_msg->status = flash_if_security_read(req->offset, req->data, req->len);
}

static void mrpc_flash_if_security_write(void *msg, struct mrpc_resp_msg *resp_msg)
{
    mrpc_flash_if_security_write_req_t *req;
    mrpc_flash_if_security_write_resp_t *resp;

    req = (mrpc_flash_if_security_write_req_t*)msg;
    resp = (mrpc_flash_if_security_write_resp_t*)resp_msg;
    memset(resp, 0, sizeof(mrpc_flash_if_security_write_resp_t));
    resp_msg->len = sizeof(mrpc_flash_if_security_write_resp_t);
    resp_msg->status = flash_if_security_write(req->offset, (const void *)req->data, req->len);
}

static void mrpc_flash_if_security_erase(void *msg, struct mrpc_resp_msg *resp_msg)
{
    mrpc_flash_if_security_erase_req_t *req;
    mrpc_flash_if_security_erase_resp_t *resp;

    req = (mrpc_flash_if_security_erase_req_t*)msg;
    resp = (mrpc_flash_if_security_erase_resp_t*)resp_msg;
    memset(resp, 0, sizeof(mrpc_flash_if_security_erase_resp_t));
    resp_msg->len = sizeof(mrpc_flash_if_security_erase_resp_t);
    resp_msg->status = flash_if_security_erase(req->offset);
}

static void mrpc_flash_if_check_security_support(void *msg, struct mrpc_resp_msg *resp_msg)
{
    mrpc_flash_if_check_security_support_req_t *req;
    mrpc_flash_if_check_security_support_resp_t *resp;

    req = (mrpc_flash_if_check_security_support_req_t*)msg;
    resp = (mrpc_flash_if_check_security_support_resp_t*)resp_msg;
    memset(resp, 0, sizeof(mrpc_flash_if_check_security_support_resp_t));
    resp_msg->len = sizeof(mrpc_flash_if_check_security_support_resp_t);
    resp_msg->status = flash_if_check_security_support();
}


mrpc_msg_handler_t mrpc_msg_flash_if_handlers[MRPC_MSG_ID_FLASH_IF_MAX - MRPC_MSG_ID_FLASH_IF_START] =
{
    mrpc_flash_if_init,  /*MRPC_MSG_ID_FLASH_IF_INIT*/
    mrpc_flash_if_read,  /*MRPC_MSG_ID_FLASH_IF_READ*/
    mrpc_flash_if_write,  /*MRPC_MSG_ID_FLASH_IF_WRITE*/
    mrpc_flash_if_erase,  /*MRPC_MSG_ID_FLASH_IF_ERASE*/
    mrpc_flash_if_write_protection_set,  /*MRPC_MSG_ID_FLASH_IF_WRITE_PROTECTION_SET*/
    mrpc_flash_if_security_read,  /*MRPC_MSG_ID_FLASH_IF_SECURITY_READ*/
    mrpc_flash_if_security_write,  /*MRPC_MSG_ID_FLASH_IF_SECURITY_WRITE*/
    mrpc_flash_if_security_erase,  /*MRPC_MSG_ID_FLASH_IF_SECURITY_ERASE*/
    mrpc_flash_if_check_security_support,  /*MRPC_MSG_ID_FLASH_IF_CHECK_SECURITY_SUPPORT*/
    NULL
};