#ifndef _ANIM_IMAGES_H_
#define _ANIM_IMAGES_H_

#include "assets/assets_res.h"

#define ANIM_ROLE_INDEX     (1)
#define ANIM_ROLE_DURATION  (1000)

static const void *battery_level_img[] = {
    &LISA_UI_ASSETS_IMG_DSC(img_png_power0),
    &LISA_UI_ASSETS_IMG_DSC(img_png_power1),
    &LISA_UI_ASSETS_IMG_DSC(img_png_power2),
    &LISA_UI_ASSETS_IMG_DSC(img_png_power3),
    &LISA_UI_ASSETS_IMG_DSC(img_png_power4),
    &LISA_UI_ASSETS_IMG_DSC(img_png_power5),
    &LISA_UI_ASSETS_IMG_DSC(img_png_power6),
    &LISA_UI_ASSETS_IMG_DSC(img_png_power7),
    &LISA_UI_ASSETS_IMG_DSC(img_png_power8),
    &LISA_UI_ASSETS_IMG_DSC(img_png_power9),
};
static const void *emoji_battery_frames[] = {
    &LISA_UI_ASSETS_IMG_DSC(img_png_battery_frame_000),
    &LISA_UI_ASSETS_IMG_DSC(img_png_battery_frame_001),
    &LISA_UI_ASSETS_IMG_DSC(img_png_battery_frame_002),
    &LISA_UI_ASSETS_IMG_DSC(img_png_battery_frame_003),
    &LISA_UI_ASSETS_IMG_DSC(img_png_battery_frame_004),
    &LISA_UI_ASSETS_IMG_DSC(img_png_battery_frame_005),
    &LISA_UI_ASSETS_IMG_DSC(img_png_battery_frame_006),
    &LISA_UI_ASSETS_IMG_DSC(img_png_battery_frame_007),
    &LISA_UI_ASSETS_IMG_DSC(img_png_battery_frame_008),
    &LISA_UI_ASSETS_IMG_DSC(img_png_battery_frame_009),
    &LISA_UI_ASSETS_IMG_DSC(img_png_battery_frame_010),
    &LISA_UI_ASSETS_IMG_DSC(img_png_battery_frame_011),
    &LISA_UI_ASSETS_IMG_DSC(img_png_battery_frame_012),
    &LISA_UI_ASSETS_IMG_DSC(img_png_battery_frame_013),
    &LISA_UI_ASSETS_IMG_DSC(img_png_battery_frame_014),
    &LISA_UI_ASSETS_IMG_DSC(img_png_battery_frame_015),
    &LISA_UI_ASSETS_IMG_DSC(img_png_battery_frame_016),
    &LISA_UI_ASSETS_IMG_DSC(img_png_battery_frame_017),
    &LISA_UI_ASSETS_IMG_DSC(img_png_battery_frame_018),
    &LISA_UI_ASSETS_IMG_DSC(img_png_battery_frame_019),
    &LISA_UI_ASSETS_IMG_DSC(img_png_battery_frame_020),
    &LISA_UI_ASSETS_IMG_DSC(img_png_battery_frame_021),
};

static const void *battery_charging_img[] = {
    &LISA_UI_ASSETS_IMG_DSC(img_png_charging0),
    &LISA_UI_ASSETS_IMG_DSC(img_png_charging1),
    &LISA_UI_ASSETS_IMG_DSC(img_png_charging2),
    &LISA_UI_ASSETS_IMG_DSC(img_png_charging3),
    &LISA_UI_ASSETS_IMG_DSC(img_png_charging4),
    &LISA_UI_ASSETS_IMG_DSC(img_png_charging5),
    &LISA_UI_ASSETS_IMG_DSC(img_png_charging6),
    &LISA_UI_ASSETS_IMG_DSC(img_png_charging7),
    &LISA_UI_ASSETS_IMG_DSC(img_png_charging8),
    &LISA_UI_ASSETS_IMG_DSC(img_png_charging9),
};

static const void *emoji_love[] = {
    &LISA_UI_ASSETS_IMG_DSC(img_png_love_000),
    &LISA_UI_ASSETS_IMG_DSC(img_png_love_001),
    &LISA_UI_ASSETS_IMG_DSC(img_png_love_002),
    &LISA_UI_ASSETS_IMG_DSC(img_png_love_003),
    &LISA_UI_ASSETS_IMG_DSC(img_png_love_004),
    &LISA_UI_ASSETS_IMG_DSC(img_png_love_005),
    &LISA_UI_ASSETS_IMG_DSC(img_png_love_006),
    &LISA_UI_ASSETS_IMG_DSC(img_png_love_007),
    &LISA_UI_ASSETS_IMG_DSC(img_png_love_008),
    &LISA_UI_ASSETS_IMG_DSC(img_png_love_009),
    &LISA_UI_ASSETS_IMG_DSC(img_png_love_010),
    &LISA_UI_ASSETS_IMG_DSC(img_png_love_011),
    &LISA_UI_ASSETS_IMG_DSC(img_png_love_012),
    &LISA_UI_ASSETS_IMG_DSC(img_png_love_013),
    &LISA_UI_ASSETS_IMG_DSC(img_png_love_014),
    &LISA_UI_ASSETS_IMG_DSC(img_png_love_015),
    &LISA_UI_ASSETS_IMG_DSC(img_png_love_016),
    &LISA_UI_ASSETS_IMG_DSC(img_png_love_017),
    &LISA_UI_ASSETS_IMG_DSC(img_png_love_018),
    &LISA_UI_ASSETS_IMG_DSC(img_png_love_019),
    &LISA_UI_ASSETS_IMG_DSC(img_png_love_020),
    &LISA_UI_ASSETS_IMG_DSC(img_png_love_021),
    &LISA_UI_ASSETS_IMG_DSC(img_png_love_022),
};

static const void *emoji_sad[] = {
    &LISA_UI_ASSETS_IMG_DSC(img_png_sad_000),
    &LISA_UI_ASSETS_IMG_DSC(img_png_sad_001),
    &LISA_UI_ASSETS_IMG_DSC(img_png_sad_002),
    &LISA_UI_ASSETS_IMG_DSC(img_png_sad_003),
    &LISA_UI_ASSETS_IMG_DSC(img_png_sad_004),
    &LISA_UI_ASSETS_IMG_DSC(img_png_sad_005),
    &LISA_UI_ASSETS_IMG_DSC(img_png_sad_006),
    &LISA_UI_ASSETS_IMG_DSC(img_png_sad_007),
    &LISA_UI_ASSETS_IMG_DSC(img_png_sad_008),
    &LISA_UI_ASSETS_IMG_DSC(img_png_sad_009),
    &LISA_UI_ASSETS_IMG_DSC(img_png_sad_010),
    &LISA_UI_ASSETS_IMG_DSC(img_png_sad_011),
    &LISA_UI_ASSETS_IMG_DSC(img_png_sad_012),
    &LISA_UI_ASSETS_IMG_DSC(img_png_sad_013),
    &LISA_UI_ASSETS_IMG_DSC(img_png_sad_014),
    &LISA_UI_ASSETS_IMG_DSC(img_png_sad_015),
    &LISA_UI_ASSETS_IMG_DSC(img_png_sad_016),
    &LISA_UI_ASSETS_IMG_DSC(img_png_sad_017),
    &LISA_UI_ASSETS_IMG_DSC(img_png_sad_018),
};

static const void *emoji_puzzled[] = {
    &LISA_UI_ASSETS_IMG_DSC(img_png_puzzled_000),
    &LISA_UI_ASSETS_IMG_DSC(img_png_puzzled_001),
    &LISA_UI_ASSETS_IMG_DSC(img_png_puzzled_002),
    &LISA_UI_ASSETS_IMG_DSC(img_png_puzzled_003),
    &LISA_UI_ASSETS_IMG_DSC(img_png_puzzled_004),
    &LISA_UI_ASSETS_IMG_DSC(img_png_puzzled_005),
    &LISA_UI_ASSETS_IMG_DSC(img_png_puzzled_006),
    &LISA_UI_ASSETS_IMG_DSC(img_png_puzzled_007),
    &LISA_UI_ASSETS_IMG_DSC(img_png_puzzled_008),
    &LISA_UI_ASSETS_IMG_DSC(img_png_puzzled_009),
    &LISA_UI_ASSETS_IMG_DSC(img_png_puzzled_010),
    &LISA_UI_ASSETS_IMG_DSC(img_png_puzzled_011),
    &LISA_UI_ASSETS_IMG_DSC(img_png_puzzled_012),
    &LISA_UI_ASSETS_IMG_DSC(img_png_puzzled_013),
    &LISA_UI_ASSETS_IMG_DSC(img_png_puzzled_014),
    &LISA_UI_ASSETS_IMG_DSC(img_png_puzzled_015),
    &LISA_UI_ASSETS_IMG_DSC(img_png_puzzled_016),
    &LISA_UI_ASSETS_IMG_DSC(img_png_puzzled_017),
    &LISA_UI_ASSETS_IMG_DSC(img_png_puzzled_018),
};

static const void *emoji_angry[] = {
    &LISA_UI_ASSETS_IMG_DSC(img_png_angry_000),
    &LISA_UI_ASSETS_IMG_DSC(img_png_angry_001),
    &LISA_UI_ASSETS_IMG_DSC(img_png_angry_002),
    &LISA_UI_ASSETS_IMG_DSC(img_png_angry_003),
    &LISA_UI_ASSETS_IMG_DSC(img_png_angry_004),
    &LISA_UI_ASSETS_IMG_DSC(img_png_angry_005),
    &LISA_UI_ASSETS_IMG_DSC(img_png_angry_006),
    &LISA_UI_ASSETS_IMG_DSC(img_png_angry_007),
    &LISA_UI_ASSETS_IMG_DSC(img_png_angry_008),
    &LISA_UI_ASSETS_IMG_DSC(img_png_angry_009),
    &LISA_UI_ASSETS_IMG_DSC(img_png_angry_010),
    &LISA_UI_ASSETS_IMG_DSC(img_png_angry_011),
    &LISA_UI_ASSETS_IMG_DSC(img_png_angry_012),
    &LISA_UI_ASSETS_IMG_DSC(img_png_angry_013),
    &LISA_UI_ASSETS_IMG_DSC(img_png_angry_014),
    &LISA_UI_ASSETS_IMG_DSC(img_png_angry_015),
};

static const void *emoji_blink[] = {
    &LISA_UI_ASSETS_IMG_DSC(img_png_blink_000),
    &LISA_UI_ASSETS_IMG_DSC(img_png_blink_001),
    &LISA_UI_ASSETS_IMG_DSC(img_png_blink_002),
    &LISA_UI_ASSETS_IMG_DSC(img_png_blink_003),
    &LISA_UI_ASSETS_IMG_DSC(img_png_blink_004),
};

static const void *emoji_eye[] = {
    &LISA_UI_ASSETS_IMG_DSC(img_png_eye_000),
    &LISA_UI_ASSETS_IMG_DSC(img_png_eye_001),
    &LISA_UI_ASSETS_IMG_DSC(img_png_eye_002),
    &LISA_UI_ASSETS_IMG_DSC(img_png_eye_003),
    &LISA_UI_ASSETS_IMG_DSC(img_png_eye_004),
    &LISA_UI_ASSETS_IMG_DSC(img_png_eye_005),
    &LISA_UI_ASSETS_IMG_DSC(img_png_eye_006),
    &LISA_UI_ASSETS_IMG_DSC(img_png_eye_007),
    &LISA_UI_ASSETS_IMG_DSC(img_png_eye_008),
    &LISA_UI_ASSETS_IMG_DSC(img_png_eye_009),
    &LISA_UI_ASSETS_IMG_DSC(img_png_eye_010),
    &LISA_UI_ASSETS_IMG_DSC(img_png_eye_011),
};

static const void *emoji_hug[] = {
    &LISA_UI_ASSETS_IMG_DSC(img_png_hug_000),
    &LISA_UI_ASSETS_IMG_DSC(img_png_hug_001),
    &LISA_UI_ASSETS_IMG_DSC(img_png_hug_002),
    &LISA_UI_ASSETS_IMG_DSC(img_png_hug_003),
    &LISA_UI_ASSETS_IMG_DSC(img_png_hug_004),
    &LISA_UI_ASSETS_IMG_DSC(img_png_hug_005),
    &LISA_UI_ASSETS_IMG_DSC(img_png_hug_006),
    &LISA_UI_ASSETS_IMG_DSC(img_png_hug_007),
    &LISA_UI_ASSETS_IMG_DSC(img_png_hug_008),
    &LISA_UI_ASSETS_IMG_DSC(img_png_hug_009),
    &LISA_UI_ASSETS_IMG_DSC(img_png_hug_010),
    &LISA_UI_ASSETS_IMG_DSC(img_png_hug_011),
    &LISA_UI_ASSETS_IMG_DSC(img_png_hug_012),
    &LISA_UI_ASSETS_IMG_DSC(img_png_hug_013),
    &LISA_UI_ASSETS_IMG_DSC(img_png_hug_014),
    &LISA_UI_ASSETS_IMG_DSC(img_png_hug_015),
    &LISA_UI_ASSETS_IMG_DSC(img_png_hug_016),
    &LISA_UI_ASSETS_IMG_DSC(img_png_hug_017),
    &LISA_UI_ASSETS_IMG_DSC(img_png_hug_018),
    &LISA_UI_ASSETS_IMG_DSC(img_png_hug_019),
    &LISA_UI_ASSETS_IMG_DSC(img_png_hug_020),
    &LISA_UI_ASSETS_IMG_DSC(img_png_hug_021),
    &LISA_UI_ASSETS_IMG_DSC(img_png_hug_022),
    &LISA_UI_ASSETS_IMG_DSC(img_png_hug_023),
    &LISA_UI_ASSETS_IMG_DSC(img_png_hug_024),
};

static const void *emoji_wakeup[] = {
    &LISA_UI_ASSETS_IMG_DSC(img_png_wakeup_000),
    &LISA_UI_ASSETS_IMG_DSC(img_png_wakeup_001),
    &LISA_UI_ASSETS_IMG_DSC(img_png_wakeup_002),
    &LISA_UI_ASSETS_IMG_DSC(img_png_wakeup_003),
    &LISA_UI_ASSETS_IMG_DSC(img_png_wakeup_004),
    &LISA_UI_ASSETS_IMG_DSC(img_png_wakeup_005),
    &LISA_UI_ASSETS_IMG_DSC(img_png_wakeup_006),
    &LISA_UI_ASSETS_IMG_DSC(img_png_wakeup_007),
    &LISA_UI_ASSETS_IMG_DSC(img_png_wakeup_008),
    &LISA_UI_ASSETS_IMG_DSC(img_png_wakeup_009),
    &LISA_UI_ASSETS_IMG_DSC(img_png_wakeup_010),
    &LISA_UI_ASSETS_IMG_DSC(img_png_wakeup_011),
    &LISA_UI_ASSETS_IMG_DSC(img_png_wakeup_012),
    &LISA_UI_ASSETS_IMG_DSC(img_png_wakeup_013),
    &LISA_UI_ASSETS_IMG_DSC(img_png_wakeup_014),
    &LISA_UI_ASSETS_IMG_DSC(img_png_wakeup_015),
    &LISA_UI_ASSETS_IMG_DSC(img_png_wakeup_016),
    &LISA_UI_ASSETS_IMG_DSC(img_png_wakeup_017),
    &LISA_UI_ASSETS_IMG_DSC(img_png_wakeup_018),
    &LISA_UI_ASSETS_IMG_DSC(img_png_wakeup_019),
    &LISA_UI_ASSETS_IMG_DSC(img_png_wakeup_020),
    &LISA_UI_ASSETS_IMG_DSC(img_png_wakeup_021),
    &LISA_UI_ASSETS_IMG_DSC(img_png_wakeup_022),
    &LISA_UI_ASSETS_IMG_DSC(img_png_wakeup_023),
    &LISA_UI_ASSETS_IMG_DSC(img_png_wakeup_024),
    &LISA_UI_ASSETS_IMG_DSC(img_png_wakeup_025),
    &LISA_UI_ASSETS_IMG_DSC(img_png_wakeup_026),
    &LISA_UI_ASSETS_IMG_DSC(img_png_wakeup_027),
};

static const void *emoji_sleepy[] = {
    &LISA_UI_ASSETS_IMG_DSC(img_png_sleepy_000),
    &LISA_UI_ASSETS_IMG_DSC(img_png_sleepy_001),
    &LISA_UI_ASSETS_IMG_DSC(img_png_sleepy_002),
    &LISA_UI_ASSETS_IMG_DSC(img_png_sleepy_003),
    &LISA_UI_ASSETS_IMG_DSC(img_png_sleepy_004),
    &LISA_UI_ASSETS_IMG_DSC(img_png_sleepy_005),
    &LISA_UI_ASSETS_IMG_DSC(img_png_sleepy_006),
    &LISA_UI_ASSETS_IMG_DSC(img_png_sleepy_007),
    &LISA_UI_ASSETS_IMG_DSC(img_png_sleepy_008),
    &LISA_UI_ASSETS_IMG_DSC(img_png_sleepy_009),
    &LISA_UI_ASSETS_IMG_DSC(img_png_sleepy_010),
    &LISA_UI_ASSETS_IMG_DSC(img_png_sleepy_011),
    &LISA_UI_ASSETS_IMG_DSC(img_png_sleepy_012),
    &LISA_UI_ASSETS_IMG_DSC(img_png_sleepy_013),
    &LISA_UI_ASSETS_IMG_DSC(img_png_sleepy_014),
    &LISA_UI_ASSETS_IMG_DSC(img_png_sleepy_015),
    &LISA_UI_ASSETS_IMG_DSC(img_png_sleepy_016),
    &LISA_UI_ASSETS_IMG_DSC(img_png_sleepy_017),
    &LISA_UI_ASSETS_IMG_DSC(img_png_sleepy_018),
    &LISA_UI_ASSETS_IMG_DSC(img_png_sleepy_019),
    &LISA_UI_ASSETS_IMG_DSC(img_png_sleepy_020),
    &LISA_UI_ASSETS_IMG_DSC(img_png_sleepy_021),
    &LISA_UI_ASSETS_IMG_DSC(img_png_sleepy_022),
    &LISA_UI_ASSETS_IMG_DSC(img_png_sleepy_023),
    &LISA_UI_ASSETS_IMG_DSC(img_png_sleepy_024),
    &LISA_UI_ASSETS_IMG_DSC(img_png_sleepy_025),
    &LISA_UI_ASSETS_IMG_DSC(img_png_sleepy_026),
    &LISA_UI_ASSETS_IMG_DSC(img_png_sleepy_027),
    &LISA_UI_ASSETS_IMG_DSC(img_png_sleepy_028),
    &LISA_UI_ASSETS_IMG_DSC(img_png_sleepy_029),
    &LISA_UI_ASSETS_IMG_DSC(img_png_sleepy_030),
    &LISA_UI_ASSETS_IMG_DSC(img_png_sleepy_031),
    &LISA_UI_ASSETS_IMG_DSC(img_png_sleepy_032),
    &LISA_UI_ASSETS_IMG_DSC(img_png_sleepy_033),
    &LISA_UI_ASSETS_IMG_DSC(img_png_sleepy_034),
    &LISA_UI_ASSETS_IMG_DSC(img_png_sleepy_035),
    &LISA_UI_ASSETS_IMG_DSC(img_png_sleepy_036),
    &LISA_UI_ASSETS_IMG_DSC(img_png_sleepy_037),
    &LISA_UI_ASSETS_IMG_DSC(img_png_sleepy_038),
    &LISA_UI_ASSETS_IMG_DSC(img_png_sleepy_039),
    &LISA_UI_ASSETS_IMG_DSC(img_png_sleepy_040),
};

static const void *emoji_wait[] = {
    &LISA_UI_ASSETS_IMG_DSC(img_png_wait_000),
    &LISA_UI_ASSETS_IMG_DSC(img_png_wait_001),
    &LISA_UI_ASSETS_IMG_DSC(img_png_wait_002),
    &LISA_UI_ASSETS_IMG_DSC(img_png_wait_003),
    &LISA_UI_ASSETS_IMG_DSC(img_png_wait_004),
    &LISA_UI_ASSETS_IMG_DSC(img_png_wait_005),
    &LISA_UI_ASSETS_IMG_DSC(img_png_wait_006),
    &LISA_UI_ASSETS_IMG_DSC(img_png_wait_007),
};

static const void *emoji_happy[] = {
    &LISA_UI_ASSETS_IMG_DSC(img_png_happy_frame_00),
    &LISA_UI_ASSETS_IMG_DSC(img_png_happy_frame_01),
    &LISA_UI_ASSETS_IMG_DSC(img_png_happy_frame_02),
    &LISA_UI_ASSETS_IMG_DSC(img_png_happy_frame_03),
    &LISA_UI_ASSETS_IMG_DSC(img_png_happy_frame_04),
    &LISA_UI_ASSETS_IMG_DSC(img_png_happy_frame_05),
    &LISA_UI_ASSETS_IMG_DSC(img_png_happy_frame_06),
    &LISA_UI_ASSETS_IMG_DSC(img_png_happy_frame_07),
    &LISA_UI_ASSETS_IMG_DSC(img_png_happy_frame_08),
    &LISA_UI_ASSETS_IMG_DSC(img_png_happy_frame_09),
    &LISA_UI_ASSETS_IMG_DSC(img_png_happy_frame_10),
    &LISA_UI_ASSETS_IMG_DSC(img_png_happy_frame_11),
    &LISA_UI_ASSETS_IMG_DSC(img_png_happy_frame_12),
    &LISA_UI_ASSETS_IMG_DSC(img_png_happy_frame_13),
    &LISA_UI_ASSETS_IMG_DSC(img_png_happy_frame_14),
    &LISA_UI_ASSETS_IMG_DSC(img_png_happy_frame_15),
    &LISA_UI_ASSETS_IMG_DSC(img_png_happy_frame_16),
    &LISA_UI_ASSETS_IMG_DSC(img_png_happy_frame_17),
    &LISA_UI_ASSETS_IMG_DSC(img_png_happy_frame_18),
    &LISA_UI_ASSETS_IMG_DSC(img_png_happy_frame_19),
    &LISA_UI_ASSETS_IMG_DSC(img_png_happy_frame_20),
};

static const void *emoji_cute[] = {
    &LISA_UI_ASSETS_IMG_DSC(img_png_cute_frame_00),
    &LISA_UI_ASSETS_IMG_DSC(img_png_cute_frame_01),
    &LISA_UI_ASSETS_IMG_DSC(img_png_cute_frame_02),
    &LISA_UI_ASSETS_IMG_DSC(img_png_cute_frame_03),
    &LISA_UI_ASSETS_IMG_DSC(img_png_cute_frame_04),
    &LISA_UI_ASSETS_IMG_DSC(img_png_cute_frame_05),
    &LISA_UI_ASSETS_IMG_DSC(img_png_cute_frame_06),
    &LISA_UI_ASSETS_IMG_DSC(img_png_cute_frame_07),
    &LISA_UI_ASSETS_IMG_DSC(img_png_cute_frame_08),
    &LISA_UI_ASSETS_IMG_DSC(img_png_cute_frame_09),
    &LISA_UI_ASSETS_IMG_DSC(img_png_cute_frame_10),
    &LISA_UI_ASSETS_IMG_DSC(img_png_cute_frame_11),
    &LISA_UI_ASSETS_IMG_DSC(img_png_cute_frame_12),
    &LISA_UI_ASSETS_IMG_DSC(img_png_cute_frame_13),
    &LISA_UI_ASSETS_IMG_DSC(img_png_cute_frame_14),
    &LISA_UI_ASSETS_IMG_DSC(img_png_cute_frame_15),
    &LISA_UI_ASSETS_IMG_DSC(img_png_cute_frame_16),
    &LISA_UI_ASSETS_IMG_DSC(img_png_cute_frame_17),
    &LISA_UI_ASSETS_IMG_DSC(img_png_cute_frame_18),
    &LISA_UI_ASSETS_IMG_DSC(img_png_cute_frame_19),
    &LISA_UI_ASSETS_IMG_DSC(img_png_cute_frame_20),
    &LISA_UI_ASSETS_IMG_DSC(img_png_cute_frame_21),
    &LISA_UI_ASSETS_IMG_DSC(img_png_cute_frame_22),
    &LISA_UI_ASSETS_IMG_DSC(img_png_cute_frame_23),
};


#endif
