# LISA I2S Master TX Sample Configuration

# I2S 驱动配置
CONFIG_LISA_DEVICE=y
CONFIG_LISA_I2S_DEVICE=y
CONFIG_LISA_I2S0=y

CONFIG_LISA_GPIO_DEVICE=y
CONFIG_LISA_GPIOA=y
CONFIG_LISA_GPIOB=y

# 系统配置
CONFIG_LINK_OPTION_NOSYS_SPECS=y

# HEAP
CONFIG_HEAP_SIZE=0x10000
CONFIG_PSRAM_HEAP_SIZE=0x680000

# Debug
CONFIG_BACK_TRACE=y

# freertos
CONFIG_FREERTOS_STATIC_ALLOCATION_ENABLE=y

# main task
CONFIG_MAIN_TASK_STACK_SIZE=8192
CONFIG_MAIN_TASK_PRIORITY=5

# GPDMA
CONFIG_ARCS_GPDMA_FULL_INIT=y

# watchdog
CONFIG_BOOT_WITH_WATCHDOG=y
CONFIG_WATCHDOG_ENABLE=n

# 日志配置
CONFIG_LOG=y
CONFIG_LOG_MODE_ASYNC=y  # 异步日志
