/**
 ****************************************************************************************
 *
 * Don't modify this file. It is automatically generated by a script.
 *
 * Author: KeHuatao
 *
 * Copyright (C) ListenAI 2025
 *
 ****************************************************************************************
 */
#include <stdio.h>
#include <stdint.h>
#include <string.h>
#include "ls_err.h"
#include "ls_wifi_type.h"
#include "net_al.h"
#include "ipc.h"
#include "mrpc.h"
#include "ipc_test_internal.h"
#include "mrpc_s2m_test_api_msg.h"
#include "mrpc_s2m_test_api_server.h"

static void mrpc_s2m_echo_req(void *msg, struct mrpc_resp_msg *resp_msg, uint32_t resp_buf_len)
{
    mrpc_s2m_echo_req_req_t *req;
    mrpc_s2m_echo_req_resp_t *resp;

    req = (mrpc_s2m_echo_req_req_t*)msg;
    resp = (mrpc_s2m_echo_req_resp_t*)resp_msg;
    resp_msg->len = sizeof(mrpc_s2m_echo_req_resp_t);
    resp_msg->status = s2m_echo_req(req->mrpc_ep, &req->echo_req, &resp->echo_resp);
}


mrpc_msg_handler_t mrpc_msg_s2m_test_handlers[MRPC_MSG_ID_S2M_TEST_MAX - MRPC_MSG_ID_S2M_TEST_START] =
{
    mrpc_s2m_echo_req,  /*MRPC_MSG_ID_S2M_ECHO_REQ*/
    NULL
};