#ifndef __VOICE_EVT_H__
#define __VOICE_EVT_H__

#include <stdint.h>

#include "voice_msg_structure.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Domain */
enum {
    VOICE_DOMAIN_APPLICATION = 0, /* 由应用程序自行定义 */
    VOICE_DOMAIN_SYSTEM,
    VOICE_DOMAIN_INVOKE,
    VOICE_DOMAIN_POWER,
    VOICE_DOMAIN_PLATFORM,
    VOICE_DOMAIN_WIFI,
    VOICE_DOMAIN_BLE,
    VOICE_DOMAIN_BUTTON,
    VOICE_DOMAIN_WAKEUP,
    VOICE_DOMAIN_CLOUD,
    VOICE_DOMAIN_PLAYER,
    VOICE_DOMAIN_RECORD,
    VOICE_DOMAIN_ALARM,
    VOICE_DOMAIN_RECOGNIZED,
    VOICE_DOMAIN_PLAY_CONTROL,
#ifdef CONFIG_OTA
    VOICE_DOMAIN_OTA,
#endif
    VOICE_DOMAIN_MAX,
};

#define VOICE_MSG_ID(domain, evt) (((domain) << 16) | (evt))
#define VOICE_MSG_DOMAIN(msg) ((msg) >> 16)
#define VOICE_MSG_EVT(msg)    ((msg) & 0xffff)

typedef enum {
    VOICE_MSG_BUTTON_ACTION_PRESS_DOWN = 0,
    VOICE_MSG_BUTTON_ACTION_CLICK,
    VOICE_MSG_BUTTON_ACTION_DOUBLE_CLICK,
    VOICE_MSG_BUTTON_ACTION_TRIPLE_CLICK,
    VOICE_MSG_BUTTON_ACTION_QUADRUPLE_CLICK,
    VOICE_MSG_BUTTON_ACTION_QUINTUPLE_CLICK,
    VOICE_MSG_BUTTON_ACTION_SEXTUPLE_CLICK,
    VOICE_MSG_BUTTON_ACTION_SEPTUPLE_CLICK,
    VOICE_MSG_BUTTON_ACTION_REPEAT_CLICK,
    VOICE_MSG_BUTTON_ACTION_SHORT_START,
    VOICE_MSG_BUTTON_ACTION_SHORT_UP,
    VOICE_MSG_BUTTON_ACTION_LONG_START,
    VOICE_MSG_BUTTON_ACTION_LONG_UP,
    VOICE_MSG_BUTTON_ACTION_LONG_HOLD,
    VOICE_MSG_BUTTON_ACTION_LONG_HOLD_UP,
    VOICE_MSG_BUTTON_ACTION_UNKNOWN,
} voice_msg_button_action_t;

typedef struct {
    uint8_t button_id;
    voice_msg_button_action_t action;
} voice_msg_button_evt_t;

struct voice_msg_audio_item {
    uint8_t playable;
    char id[32];
    char name[64];
} __attribute__((packed));

struct voice_msg_audio_items {
    uint32_t cnt;
    struct voice_msg_audio_item items[0];
} __attribute__((packed));

struct voice_invoke_rsp {
    int err;
    uint8_t data[0];
};

typedef void (*voice_invoke_worker_t)(void *, uint32_t);
typedef void (*voice_invoke_sync_worker_t)(void *, uint32_t, struct voice_invoke_rsp *);

enum {
    /* System事件 */
    VOICE_MSG_SYSTEM_START = VOICE_MSG_ID(VOICE_DOMAIN_SYSTEM, 0),
    VOICE_MSG_SYSTEM_NETWORK_PROBE_SUCCESS,
    VOICE_MSG_SYSTEM_NETWORK_PROBE_FAIL,
    VOICE_MSG_SYSTEM_MAX,

    /* WORKQ */
    VOICE_MSG_INVOKE_START = VOICE_MSG_ID(VOICE_DOMAIN_INVOKE, 0),
    /*
     * 注意: 应用层不要监听INVOKE相关
     * 如需要代理执行, 请调用voice_invoke接口
     */
    VOICE_MSG_INVOKE_SUBMIT,
    VOICE_MSG_INVOKE_SYNC_SUBMIT,

    /* Power事件 */
    VOICE_MSG_POWER_START = VOICE_MSG_ID(VOICE_DOMAIN_POWER, 0),
    VOICE_MSG_POWER_BATTERY_UPDATE,
    VOICE_MSG_POWER_MAX,

    /* Platform事件 */
    VOICE_MSG_PLATFORM_START = VOICE_MSG_ID(VOICE_DOMAIN_PLATFORM, 0),
    VOICE_MSG_PLATFORM_READY = VOICE_MSG_PLATFORM_START,
    VOICE_MSG_PLATFORM_MAX,

#ifdef CONFIG_OTA
    /* OTA事件 */
    VOICE_MSG_OTA_START = VOICE_MSG_ID(VOICE_DOMAIN_OTA, 0),
    VOICE_MSG_OTA_CHECKING,
    VOICE_MSG_OTA_UPDATING,
    VOICE_MSG_OTA_SUCCESSED,
    VOICE_MSG_OTA_FAILED,
    VOICE_MSG_OTA_UP_TO_DATE,
    VOICE_MSG_OTA_MAX,
#endif

    /* WIFI事件 */
    VOICE_MSG_WIFI_START = VOICE_MSG_ID(VOICE_DOMAIN_WIFI, 0),
    VOICE_MSG_WIFI_CONNECTED = VOICE_MSG_WIFI_START,
    VOICE_MSG_WIFI_DISCONNECTED,
    VOICE_MSG_WIFI_SCAN_DONE,
    VOICE_MSG_WIFI_IP_GOT,
    VOICE_MSG_WIFI_MAX,

    /* BLE事件 */
    VOICE_MSG_BLE_START = VOICE_MSG_ID(VOICE_DOMAIN_BLE, 0),
    VOICE_MSG_BLE_CONNECT_DONE = VOICE_MSG_BLE_START,
    VOICE_MSG_BLE_DISCONNECT_DONE,
    VOICE_MSG_BLE_SCAN_DONE,
    VOICE_MSG_BLE_MAX,

    VOICE_MSG_BUTTON_START = VOICE_MSG_ID(VOICE_DOMAIN_BUTTON, 0),
    VOICE_MSG_BUTTON_CHANGE = VOICE_MSG_BUTTON_START,
    VOICE_MSG_BUTTON_IMAGE_RECOGNITION,
    VOICE_MSG_BUTTON_MAX,
    /* WAKEUP事件 */
    VOICE_MSG_WAKEUP_START = VOICE_MSG_ID(VOICE_DOMAIN_WAKEUP, 0),
    VOICE_MSG_WAKEUP_KEYWORD = VOICE_MSG_WAKEUP_START,
    VOICE_MSG_WAKEUP_COMMAND,
    VOICE_MSG_WAKEUP_RECOGNIZED_START,
    VOICE_MSG_WAKEUP_RECOGNIZED_FINISH,
    VOICE_MSG_WAKEUP_BUTTON,
    VOICE_MSG_WAKEUP_BUTTON_START,
    VOICE_MSG_WAKEUP_BUTTON_STOP,
    VOICE_MSG_WAKEUP_MAX,

    /* LSChat事件 */
    VOICE_MSG_CLOUD_START = VOICE_MSG_ID(VOICE_DOMAIN_CLOUD, 0),
    VOICE_MSG_CLOUD_CONNECTING = VOICE_MSG_CLOUD_START,
    VOICE_MSG_CLOUD_CONNECTED,
    VOICE_MSG_CLOUD_DISCONNECTED,
    VOICE_MSG_CLOUD_RECONNECTING,
    VOICE_MSG_CLOUD_ERROR,
    VOICE_MSG_CLOUD_CLOUD_AUTH_FAILED,
    VOICE_MSG_CLOUD_CLOUD_AUTH_SUCCESS,
    VOICE_MSG_CLOUD_SESSION_STARTING,
    VOICE_MSG_CLOUD_SESSION_STARTED,
    VOICE_MSG_CLOUD_SESSION_FINISHED,
    VOICE_MSG_CLOUD_TTS_URL,
    VOICE_MSG_CLOUD_IAT_START,
    VOICE_MSG_CLOUD_IAT_UPDATE,
    VOICE_MSG_CLOUD_IAT_END,
    VOICE_MSG_CLOUD_TTS_TEXT_START,
    VOICE_MSG_CLOUD_TTS_TEXT_UPDATE,
    VOICE_MSG_CLOUD_TTS_TEXT_END,
    VOICE_MSG_CLOUD_MCP,
    VOICE_MSG_CLOUD_MCP_CALL_RESP, /* char * */
    VOICE_MSG_CLOUD_AUDIO_URL,     /* char * */
    VOICE_MSG_CLOUD_AUDIO_ITEM,    /* struct voice_msg_audio_items * */
    VOICE_MSG_CLOUD_RECOGNIZED_COMMAND,
    VOICE_MSG_CLOUD_RECOGNIZED_COMMAND_WITH_TIMER,/*定时控制命令*/
    VOICE_MSG_CLOUD_VAD,
    VOICE_MSG_CLOUD_EMOJI,
    VOICE_MSG_CLOUD_MCP_EMOJI,
    VOICE_MSG_CLOUD_MCP_LOADING,
    VOICE_MSG_CLOUD_MCP_CHAT_EXIT,
    VOICE_MSG_CLOUD_MCP_IMAGE_RECOGNITION, /* char * */
    VOICE_MSG_CLOUD_MCP_IMAGE_URL,         /* char * */
    VOICE_MSG_CLOUD_ROLE_SETTING_QRCODE,
    VOICE_MSG_CLOUD_VPR_INFO,
    VOICE_MSG_CLOUD_VPR_FEATURE,
    VOICE_MSG_CLOUD_STANDBY_TEXTS, /* char * banner json */
    VOICE_MSG_CLOUD_SHOW_QRCODE,   /* char * json with url, message, err_code */
    VOICE_MSG_CLOUD_OPEN_INFO,
    VOICE_MSG_CLOUD_MAX,

    /* Player事件 */
    VOICE_MSG_PLAYER_START = VOICE_MSG_ID(VOICE_DOMAIN_PLAYER, 0),
    VOICE_MSG_PLAYER_TTS_PLAYING,
    VOICE_MSG_PLAYER_TTS_PAUSED,
    VOICE_MSG_PLAYER_TTS_STOPED,
    VOICE_MSG_PLAYER_MAX,

    /* Record事件 */
    VOICE_MSG_RECORD_START = VOICE_MSG_ID(VOICE_DOMAIN_RECORD, 0),
    VOICE_MSG_RECORD_MAX,

    /* Alarm事件 */
    VOICE_MSG_ALARM_START = VOICE_MSG_ID(VOICE_DOMAIN_ALARM, 0),
    VOICE_MSG_ALARM_TRIGGER,
    VOICE_MSG_ALARM_CREATE,
    VOICE_MSG_ALARM_DELETE,
    VOICE_MSG_ALARM_QUERY,
    VOICE_MSG_ALARM_MAX,

    /*命令词处理事件*/
    VOICE_MSG_RECOGNIZED_START = VOICE_MSG_ID(VOICE_DOMAIN_RECOGNIZED, 0),
    VOICE_MSG_RECOGNIZED_ONLINE_COMMAND = VOICE_MSG_RECOGNIZED_START,
    VOICE_MSG_RECOGNIZED_OFFLINE_COMMAND,
    VOICE_MSG_RECOGNIZED_SESSION_FINISH,
    VOICE_MSG_RECOGNIZED_MAX,

    /* PlayControl事件 */
    VOICE_MSG_PLAY_CONTROL_START = VOICE_MSG_ID(VOICE_DOMAIN_PLAY_CONTROL, 0),
    VOICE_MSG_PLAY_CONTROL_PLAY,
    VOICE_MSG_PLAY_CONTROL_PAUSE,
    VOICE_MSG_PLAY_CONTROL_NEXT,
    VOICE_MSG_PLAY_CONTROL_PREVIOUS,
    VOICE_MSG_PLAY_CONTROL_REPLAY,
    VOICE_MSG_PLAY_CONTROL_MAX,
};

struct voice_msg_wakeup {
    char keyword[64];
};

typedef void (*voice_msg_cb_t)(void *unused, uint32_t msg_id, void *data, uint32_t len, void *user_data);

int voice_msg_init(void);
int voice_msg_pub(uint32_t msg_id, void *data, uint32_t len);
int voice_msg_sub(uint32_t msg_id, voice_msg_cb_t cb, void *user_data);
int voice_msg_unsub(uint32_t msg_id, voice_msg_cb_t cb);

int voice_invoke(voice_invoke_worker_t worker, void *data, uint32_t len);
int voice_invoke_sync(voice_invoke_sync_worker_t worker, void *data, uint32_t len, struct voice_invoke_rsp *rsp,
                      uint32_t timeout);
#ifdef __cplusplus
}
#endif

#endif
