# CherryUSB Host EC801E ECM Sample Configuration

CONFIG_MEM_IPC_ISOLATED=n
CONFIG_MEM_LUNA_SHARED_SIZE=0x0

# CherryUSB 配置
CONFIG_CHERRYUSB=y
CONFIG_CHERRYUSB_HOST=y
CONFIG_CHERRYUSB_HOST_MUSB_LISA=y
CONFIG_CHERRYUSB_HOST_CDC_ECM=y
CONFIG_CHERRYUSB_HOST_GSM=y

# lwIP
CONFIG_LWIP=y
CONFIG_LWIP_OPTION_LWIP_DNS=y
CONFIG_LWIP_OPTION_SO_REUSE=y

# 日志配置
CONFIG_LOG=y

# 系统配置
CONFIG_LINK_OPTION_NOSYS_SPECS=y

# Debug
CONFIG_BACK_TRACE=y
