/* AUTOGENERATED FILE. DO NOT EDIT. */

/*=======Test Runner Used To Run Each Test Below=====*/
#define RUN_TEST(TestFunc, TestLineNum)                                                                                \
    {                                                                                                                  \
        Unity.CurrentTestName = #TestFunc;                                                                             \
        Unity.CurrentTestLineNumber = TestLineNum;                                                                     \
        Unity.NumberOfTests++;                                                                                         \
        if (TEST_PROTECT()) {                                                                                          \
            setUp();                                                                                                   \
            TestFunc();                                                                                                \
        }                                                                                                              \
        if (TEST_PROTECT()) {                                                                                          \
            tearDown();                                                                                                \
        }                                                                                                              \
        UnityConcludeTest();                                                                                           \
    }

/*=======Automagically Detected Files To Include=====*/
#include "unity.h"
#include <setjmp.h>
#include <stdio.h>
#include <fcntl.h>
#include <unistd.h>

#include "lisa_device.h"
#include "lisa_sdmmc.h"
#include "IOMuxManager.h"
#include "lsfs.h"
#include "disk/disk_access.h"
#include "log_print.h"
#if CONFIG_LVFS
#include "lvfs.h"
#endif

#define SDMMC_CLK_PAD   CSK_IOMUX_PAD_A
#define SDMMC_CLK_PIN   6
#define SDMMC_CMD_PAD   CSK_IOMUX_PAD_A
#define SDMMC_CMD_PIN   7
#define SDMMC_DAT0_PAD  CSK_IOMUX_PAD_A
#define SDMMC_DAT0_PIN  5
#define SDMMC_DAT1_PAD  CSK_IOMUX_PAD_A
#define SDMMC_DAT1_PIN  4
#define SDMMC_DAT2_PAD  CSK_IOMUX_PAD_A
#define SDMMC_DAT2_PIN  9
#define SDMMC_DAT3_PAD  CSK_IOMUX_PAD_A
#define SDMMC_DAT3_PIN  8
#define SDMMC_FUNC      CSK_IOMUX_FUNC_ALTER15

#define DISK_MOUNT_POINT "/SD:"

static struct lsfs_mount_t s_lsfs_mnt = {
    .type = LSFS_FATFS,
    .mnt_point = DISK_MOUNT_POINT,
    .fs_data = NULL,
};

#ifdef CONFIG_BOARD_ARCS_EVB
static void lisa_sdio_pinmux(void)
{
    IOMuxManager_PinConfigure(SDMMC_CLK_PAD,  SDMMC_CLK_PIN,  SDMMC_FUNC);
    IOMuxManager_PinConfigure(SDMMC_CMD_PAD,  SDMMC_CMD_PIN,  SDMMC_FUNC);
    IOMuxManager_PinConfigure(SDMMC_DAT0_PAD, SDMMC_DAT0_PIN, SDMMC_FUNC);
    IOMuxManager_PinConfigure(SDMMC_DAT1_PAD, SDMMC_DAT1_PIN, SDMMC_FUNC);
    IOMuxManager_PinConfigure(SDMMC_DAT2_PAD, SDMMC_DAT2_PIN, SDMMC_FUNC);
    IOMuxManager_PinConfigure(SDMMC_DAT3_PAD, SDMMC_DAT3_PIN, SDMMC_FUNC);
}
#endif

void setUp(void)
{
}

void tearDown(void)
{
}

/*=======Test Reset Option=====*/
void resetTest(void);
void resetTest(void)
{
    tearDown();
    setUp();
}

#include <stdio.h>
#include <string.h>
#include <errno.h>

void test_rename_func(void)
{
    const char *old_name = "/SD:/testfile_rename.txt";
    const char *new_name = "/SD:/testfile_renamed.txt";
    FILE *fp = fopen(old_name, "w");
    TEST_ASSERT_NOT_NULL(fp);
    fputs("hello", fp);
    fclose(fp);
    // rename
    int rc = rename(old_name, new_name);
    TEST_ASSERT_EQUAL_INT_MESSAGE(0, rc, "rename failed");
    // old file should not exist
    fp = fopen(old_name, "r");
    TEST_ASSERT_NULL(fp);
    // new file should exist
    fp = fopen(new_name, "r");
    TEST_ASSERT_NOT_NULL(fp);
    char buf[16] = {0};
    fgets(buf, sizeof(buf), fp);
    TEST_ASSERT_EQUAL_STRING("hello", buf);
    fclose(fp);
    // cleanup
    remove(new_name);
}

void test_remove_func(void)
{
    const char *fname = "/SD:/testfile_remove.txt";
    FILE *fp = fopen(fname, "w");
    TEST_ASSERT_NOT_NULL(fp);
    fputs("bye", fp);
    fclose(fp);
    // remove
    int rc = remove(fname);
    TEST_ASSERT_EQUAL_INT_MESSAGE(0, rc, "remove failed");
    // file should not exist
    fp = fopen(fname, "r");
    TEST_ASSERT_NULL(fp);
}

void test_open_with_trunc_flag(void)
{
    const char *fname = "/SD:/testfile_trunc.txt";

    remove(fname);
    FILE *fp = fopen(fname, "w");
    const char *initial_content = "初始内容应该被截断";
    size_t written = fputs(initial_content, fp);
    fclose(fp);
    
    fp = fopen(fname, "r");
    char buf[50] = {0};
    fgets(buf, sizeof(buf), fp);
    fclose(fp);
    
    int fd = open(fname, O_WRONLY | O_TRUNC);
    TEST_ASSERT_MESSAGE(fd >= 0, "Failed to open file with O_TRUNC flag");
    close(fd);
    
    fp = fopen(fname, "r");
    TEST_ASSERT_NOT_NULL_MESSAGE(fp, "Failed to open truncated file");
    TEST_ASSERT_EQUAL_INT_MESSAGE(EOF, fgetc(fp), "File was not truncated");
    
    fclose(fp);
    remove(fname);
}

void test_ftell(void)
{
    const char *fname = "/SD:/testfile_ftell.txt";
    const char *test_content = "This is a ftell test";
    long position;

    remove(fname);
    FILE *fp = fopen(fname, "w");
    fputs(test_content, fp);

    position = ftell(fp);
    TEST_ASSERT_EQUAL(position, strlen(test_content));

    fseek(fp, -2, SEEK_CUR);
    position = ftell(fp);
    TEST_ASSERT_EQUAL(position, strlen(test_content) - 2);

    fseek(fp, 4, SEEK_SET);
    position = ftell(fp);
    TEST_ASSERT_EQUAL(position, 4);

    fclose(fp);
    remove(fname);
}

void test_ftell_then_fread(void)
{
    const char *fname = "/SD:/testfile_ftell.txt";
    const char *test_content = "This is a ftell test";
    const int seek_offset = 4;
    const char *expect_test_content = " is a ftell test";
    long position;
    
    remove(fname);
    FILE *fp = fopen(fname, "w");
    fputs(test_content, fp);
    
    fclose(fp);

    fp = fopen(fname, "r");

    fseek(fp, seek_offset, SEEK_SET);
    
    ftell(fp);
    
    char buffer[128] = {0};
    fread(buffer, 1, strlen(expect_test_content), fp);
    
    TEST_ASSERT_EQUAL_MEMORY(expect_test_content, buffer, strlen(expect_test_content));

    fclose(fp);
    remove(fname);
}

void test_chdir(void)
{
    int rc;
    const char *new_dir = "/SD:/test_chdir";
    remove(new_dir);
    
    mkdir(new_dir, 0777);

    rc = chdir(new_dir);
    TEST_ASSERT_EQUAL_INT_MESSAGE(0, rc, "chdir failed");

    remove(new_dir);
}

void test_getcwd(void)
{
    int rc;
    char *cwd_path;
    char buf[256] = {0};
    const char *new_dir = "/SD:/test_getcwd";

    remove(new_dir);
    mkdir(new_dir, 0777);
    rc = chdir(new_dir);
    TEST_ASSERT_EQUAL_INT_MESSAGE(0, rc, "chdir failed");

    cwd_path = getcwd(buf, sizeof(buf));
    TEST_ASSERT_EQUAL_STRING(new_dir, buf);
    TEST_ASSERT_EQUAL_STRING(new_dir, cwd_path);

    remove(new_dir);
}


static int fs_init(void)
{
    int ret;

#ifdef CONFIG_BOARD_ARCS_EVB
    lisa_sdio_pinmux();
#endif

    lisa_sdmmc_probe(lisa_device_get("sdmmc0"));
    disk_init(NULL);
#if CONFIG_LVFS
    lvfs_init();
#endif
    lsfs_init();

    /*
     * stdio_func uses the TF card as disposable test media. Reset the FAT
     * volume on every run so leftover state from earlier jobs does not affect
     * rename/remove assertions.
     */
    ret = lsfs_mkfs(s_lsfs_mnt.type, &s_lsfs_mnt.mnt_point[1], NULL, 0);
    if (ret != 0) {
        CLOG("Failed to format filesystem: %d", ret);
        return ret;
    }

    ret = lsfs_mount(&s_lsfs_mnt);
    if (ret != 0) {
        CLOG("Failed to mount filesystem after mkfs: %d", ret);
        return ret;
    }

#if CONFIG_LVFS
    lvfs_chdrive(DISK_MOUNT_POINT);
    lvfs_chdir(DISK_MOUNT_POINT);
#endif

    return 0;
}

/*=======MAIN=====*/
int main(void)
{
    fs_init();

    printf("user fs init complete\n");

    UnityBegin("test/stdio_func/test_stdio.c");
    RUN_TEST(test_rename_func, __LINE__);
    RUN_TEST(test_remove_func, __LINE__);
    RUN_TEST(test_open_with_trunc_flag, __LINE__);
    RUN_TEST(test_ftell, __LINE__);
    RUN_TEST(test_ftell_then_fread, __LINE__);
    RUN_TEST(test_chdir, __LINE__);
    RUN_TEST(test_getcwd, __LINE__);
    return (UnityEnd());
}
