# 项目可根据需要在此文件中设置对应的配置

# mbedtls
CONFIG_LWIP=n
CONFIG_SDK_MODULE_MBEDTLS=y
CONFIG_CUSTOM_MBEDTLS_CFG_FILE=y
CONFIG_MBEDTLS_CFG_FILE="config-tls-generic.h"

# mbedtls common configuration
CONFIG_MBEDTLS_TEST=y

# cipher
CONFIG_MBEDTLS_CIPHER_ALL_ENABLED=y

# hash
CONFIG_MBEDTLS_HASH_ALL_ENABLED=y

# message authentication
CONFIG_MBEDTLS_MAC_ALL_ENABLED=y

# rsa
CONFIG_MBEDTLS_KEY_EXCHANGE_RSA_ENABLED=y

# ecc
CONFIG_MBEDTLS_ECP_C=y
CONFIG_MBEDTLS_ECDSA_C=y
CONFIG_MBEDTLS_ECDH_C=y
CONFIG_MBEDTLS_KEY_EXCHANGE_ECDH_ECDSA_ENABLED=y
# Elliptic curve
CONFIG_MBEDTLS_ECP_ALL_ENABLED=y

# hardware acceleration
CONFIG_MBEDTLS_HARDWARE_ENTROPY=y

CONFIG_MBEDTLS_HARDWARE_AES=y
CONFIG_MBEDTLS_HARDWARE_AES_CCM=y
CONFIG_MBEDTLS_HARDWARE_AES_CMAC=y
CONFIG_MBEDTLS_HARDWARE_AES_GCM=y
CONFIG_MBEDTLS_HARDWARE_SHA_HMAC=y

CONFIG_MBEDTLS_HARDWARE_MPI_MODULAR_EXPONENTIATION=y
CONFIG_MBEDTLS_ATCA_HW_ECDSA_VERIFY=y
CONFIG_MBEDTLS_CMAC_C=y
