# 项目可根据需要在此文件中设置对应的配置

# 内存配置
CONFIG_PSRAM_HEAP_SIZE=0x700000

# LISA 设备配置
CONFIG_LISA_DEVICE=y
CONFIG_LISA_GPIO_DEVICE=y
CONFIG_LISA_GPIOA=y
CONFIG_LISA_GPIOB=y
CONFIG_LISA_I2C=y
CONFIG_LISA_I2C0=y
CONFIG_LISA_SPI_DEVICE=y
CONFIG_LISA_SPI0=y

# 摄像头配置
CONFIG_LISA_CAMERA_DEVICE=y
CONFIG_LISA_CAMERA_BUS_DVP=y
CONFIG_LISA_CAMERA_SENSOR_GC0328=y

# TinyUSB 配置
CONFIG_TINY_USB=y
CONFIG_TINY_USB_USE_CUSTOM_CONFIG_FILE=y
CONFIG_TINY_USB_CONFIG_FILE="tusb_config.h"

# 工作队列配置
CONFIG_WORK_QUEUE=y

# 日志配置
CONFIG_LOG=y
CONFIG_SYSLOG_PRINTK_REDIRECT=y

# 系统配置
CONFIG_LINK_OPTION_NOSYS_SPECS=y
