/*
 * Copyright (c) 2026, LISTENAI
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#pragma once

#include "usb_reg.h"

/* Keep the LS566X port compatible with USB register headers that use USB_* names. */
#ifndef USB_ARCS_COUNT0_MASK
#define USB_ARCS_COUNT0_MASK USB_COUNT0_MASK
#endif
#ifndef USB_ARCS_CSR0L_DATAEND
#define USB_ARCS_CSR0L_DATAEND USB_CSR0L_DATAEND
#endif
#ifndef USB_ARCS_CSR0L_RXPKTRDY
#define USB_ARCS_CSR0L_RXPKTRDY USB_CSR0L_RXPKTRDY
#endif
#ifndef USB_ARCS_CSR0L_SENDSTALL
#define USB_ARCS_CSR0L_SENDSTALL USB_CSR0L_SENDSTALL
#endif
#ifndef USB_ARCS_CSR0L_SENTSTALL
#define USB_ARCS_CSR0L_SENTSTALL USB_CSR0L_SENTSTALL
#endif
#ifndef USB_ARCS_CSR0L_SERVICEDRXPKTRDY
#define USB_ARCS_CSR0L_SERVICEDRXPKTRDY USB_CSR0L_SERVICEDRXPKTRDY
#endif
#ifndef USB_ARCS_CSR0L_SERVICEDSETUPEND
#define USB_ARCS_CSR0L_SERVICEDSETUPEND USB_CSR0L_SERVICEDSETUPEND
#endif
#ifndef USB_ARCS_CSR0L_SETUPEND
#define USB_ARCS_CSR0L_SETUPEND USB_CSR0L_SETUPEND
#endif
#ifndef USB_ARCS_CSR0L_TXPKTRDY
#define USB_ARCS_CSR0L_TXPKTRDY USB_CSR0L_TXPKTRDY
#endif
#ifndef USB_ARCS_DAINT_IN_EP_INT
#define USB_ARCS_DAINT_IN_EP_INT USB_DAINT_IN_EP_INT
#endif
#ifndef USB_ARCS_DAINT_OUT_EP_INT
#define USB_ARCS_DAINT_OUT_EP_INT USB_DAINT_OUT_EP_INT
#endif
#ifndef USB_ARCS_DMA_CHANNEL_NOT_ASSIGNED
#define USB_ARCS_DMA_CHANNEL_NOT_ASSIGNED USB_DMA_CHANNEL_NOT_ASSIGNED
#endif
#ifndef USB_ARCS_DMA_CNTL_DMAERR
#define USB_ARCS_DMA_CNTL_DMAERR USB_DMA_CNTL_DMAERR
#endif
#ifndef USB_ARCS_DMA_CNTL_DMAIE
#define USB_ARCS_DMA_CNTL_DMAIE USB_DMA_CNTL_DMAIE
#endif
#ifndef USB_ARCS_DMA_CNTL_DMAIE_POS
#define USB_ARCS_DMA_CNTL_DMAIE_POS USB_DMA_CNTL_DMAIE_POS
#endif
#ifndef USB_ARCS_DMA_CNTL_DMA_ENAB
#define USB_ARCS_DMA_CNTL_DMA_ENAB USB_DMA_CNTL_DMA_ENAB
#endif
#ifndef USB_ARCS_FADDR_ADDR_MASK
#define USB_ARCS_FADDR_ADDR_MASK USB_FADDR_ADDR_MASK
#endif
#ifndef USB_ARCS_FIFOSZ_DPB
#define USB_ARCS_FIFOSZ_DPB USB_FIFOSZ_DPB
#endif
#ifndef USB_ARCS_FIFOSZ_DPB_MASK
#define USB_ARCS_FIFOSZ_DPB_MASK USB_FIFOSZ_DPB_MASK
#endif
#ifndef USB_ARCS_FIFOSZ_SZ_MASK
#define USB_ARCS_FIFOSZ_SZ_MASK USB_FIFOSZ_SZ_MASK
#endif
#ifndef USB_ARCS_INTRRX_EP_MASK
#define USB_ARCS_INTRRX_EP_MASK USB_INTRRX_EP_MASK
#endif
#ifndef USB_ARCS_INTRRX_EP_POS
#define USB_ARCS_INTRRX_EP_POS USB_INTRRX_EP_POS
#endif
#ifndef USB_ARCS_INTRTX_EP0
#define USB_ARCS_INTRTX_EP0 USB_INTRTX_EP0
#endif
#ifndef USB_ARCS_INTRTX_EP0_MASK
#define USB_ARCS_INTRTX_EP0_MASK USB_INTRTX_EP0_MASK
#endif
#ifndef USB_ARCS_INTRTX_EP_MASK
#define USB_ARCS_INTRTX_EP_MASK USB_INTRTX_EP_MASK
#endif
#ifndef USB_ARCS_INTRTX_EP_POS
#define USB_ARCS_INTRTX_EP_POS USB_INTRTX_EP_POS
#endif
#ifndef USB_ARCS_INTRUSBE_CONN
#define USB_ARCS_INTRUSBE_CONN USB_INTRUSBE_CONN
#endif
#ifndef USB_ARCS_INTRUSBE_DISCON
#define USB_ARCS_INTRUSBE_DISCON USB_INTRUSBE_DISCON
#endif
#ifndef USB_ARCS_INTRUSBE_RESET
#define USB_ARCS_INTRUSBE_RESET USB_INTRUSBE_RESET
#endif
#ifndef USB_ARCS_INTRUSBE_RESUME
#define USB_ARCS_INTRUSBE_RESUME USB_INTRUSBE_RESUME
#endif
#ifndef USB_ARCS_INTRUSBE_SUSPEND
#define USB_ARCS_INTRUSBE_SUSPEND USB_INTRUSBE_SUSPEND
#endif
#ifndef USB_ARCS_INTRUSB_RESET
#define USB_ARCS_INTRUSB_RESET USB_INTRUSB_RESET
#endif
#ifndef USB_ARCS_INTRUSB_RESUME
#define USB_ARCS_INTRUSB_RESUME USB_INTRUSB_RESUME
#endif
#ifndef USB_ARCS_INTRUSB_SOF
#define USB_ARCS_INTRUSB_SOF USB_INTRUSB_SOF
#endif
#ifndef USB_ARCS_INTRUSB_SUSPEND
#define USB_ARCS_INTRUSB_SUSPEND USB_INTRUSB_SUSPEND
#endif
#ifndef USB_ARCS_IN_EP_NUM
#define USB_ARCS_IN_EP_NUM USB_IN_EP_NUM
#endif
#ifndef USB_ARCS_MAXP_MASK
#define USB_ARCS_MAXP_MASK USB_MAXP_MASK
#endif
#ifndef USB_ARCS_OUT_EP_NUM
#define USB_ARCS_OUT_EP_NUM USB_OUT_EP_NUM
#endif
#ifndef USB_ARCS_POWER_HSENABLE
#define USB_ARCS_POWER_HSENABLE USB_POWER_HSENABLE
#endif
#ifndef USB_ARCS_POWER_RESUME
#define USB_ARCS_POWER_RESUME USB_POWER_RESUME
#endif
#ifndef USB_ARCS_POWER_SOFTCONN
#define USB_ARCS_POWER_SOFTCONN USB_POWER_SOFTCONN
#endif
#ifndef USB_ARCS_RXCOUNT_MASK
#define USB_ARCS_RXCOUNT_MASK USB_RXCOUNT_MASK
#endif
#ifndef USB_ARCS_RXCSRH_AUTOCLEAR
#define USB_ARCS_RXCSRH_AUTOCLEAR USB_RXCSRH_AUTOCLEAR
#endif
#ifndef USB_ARCS_RXCSRH_DMAREQENAB
#define USB_ARCS_RXCSRH_DMAREQENAB USB_RXCSRH_DMAREQENAB
#endif
#ifndef USB_ARCS_RXCSRH_DMAREQENAB_MASK
#define USB_ARCS_RXCSRH_DMAREQENAB_MASK USB_RXCSRH_DMAREQENAB_MASK
#endif
#ifndef USB_ARCS_RXCSRH_DMAREQMODE_1
#define USB_ARCS_RXCSRH_DMAREQMODE_1 USB_RXCSRH_DMAREQMODE_1
#endif
#ifndef USB_ARCS_RXCSRH_DMAREQMODE_POS
#define USB_ARCS_RXCSRH_DMAREQMODE_POS USB_RXCSRH_DMAREQMODE_POS
#endif
#ifndef USB_ARCS_RXCSRH_ISO
#define USB_ARCS_RXCSRH_ISO USB_RXCSRH_ISO
#endif
#ifndef USB_ARCS_RXCSRH_ISO_MASK
#define USB_ARCS_RXCSRH_ISO_MASK USB_RXCSRH_ISO_MASK
#endif
#ifndef USB_ARCS_RXCSRL_CLRDATATOG
#define USB_ARCS_RXCSRL_CLRDATATOG USB_RXCSRL_CLRDATATOG
#endif
#ifndef USB_ARCS_RXCSRL_FLUSHFIFO
#define USB_ARCS_RXCSRL_FLUSHFIFO USB_RXCSRL_FLUSHFIFO
#endif
#ifndef USB_ARCS_RXCSRL_OVERRUN
#define USB_ARCS_RXCSRL_OVERRUN USB_RXCSRL_OVERRUN
#endif
#ifndef USB_ARCS_RXCSRL_RXPKTRDY
#define USB_ARCS_RXCSRL_RXPKTRDY USB_RXCSRL_RXPKTRDY
#endif
#ifndef USB_ARCS_RXCSRL_SENDSTALL
#define USB_ARCS_RXCSRL_SENDSTALL USB_RXCSRL_SENDSTALL
#endif
#ifndef USB_ARCS_RXCSRL_SENTSTALL
#define USB_ARCS_RXCSRL_SENTSTALL USB_RXCSRL_SENTSTALL
#endif
#ifndef USB_ARCS_RXCSRL_SENTSTALL_MASK
#define USB_ARCS_RXCSRL_SENTSTALL_MASK USB_RXCSRL_SENTSTALL_MASK
#endif
#ifndef USB_ARCS_SOFT_RST_NRST
#define USB_ARCS_SOFT_RST_NRST USB_SOFT_RST_NRST
#endif
#ifndef USB_ARCS_SOFT_RST_NRSTX
#define USB_ARCS_SOFT_RST_NRSTX USB_SOFT_RST_NRSTX
#endif
#ifndef USB_ARCS_STS_IN
#define USB_ARCS_STS_IN USB_STS_IN
#endif
#ifndef USB_ARCS_STS_OUT
#define USB_ARCS_STS_OUT USB_STS_OUT
#endif
#ifndef USB_ARCS_STS_SETUP
#define USB_ARCS_STS_SETUP USB_STS_SETUP
#endif
#ifndef USB_ARCS_STS_STATUS
#define USB_ARCS_STS_STATUS USB_STS_STATUS
#endif
#ifndef USB_ARCS_TXCSRH_AUTOSET
#define USB_ARCS_TXCSRH_AUTOSET USB_TXCSRH_AUTOSET
#endif
#ifndef USB_ARCS_TXCSRH_DMAREQENAB
#define USB_ARCS_TXCSRH_DMAREQENAB USB_TXCSRH_DMAREQENAB
#endif
#ifndef USB_ARCS_TXCSRH_DMAREQENAB_MASK
#define USB_ARCS_TXCSRH_DMAREQENAB_MASK USB_TXCSRH_DMAREQENAB_MASK
#endif
#ifndef USB_ARCS_TXCSRH_DMAREQMODE_0
#define USB_ARCS_TXCSRH_DMAREQMODE_0 USB_TXCSRH_DMAREQMODE_0
#endif
#ifndef USB_ARCS_TXCSRH_DMAREQMODE_1
#define USB_ARCS_TXCSRH_DMAREQMODE_1 USB_TXCSRH_DMAREQMODE_1
#endif
#ifndef USB_ARCS_TXCSRH_DMAREQMODE_POS
#define USB_ARCS_TXCSRH_DMAREQMODE_POS USB_TXCSRH_DMAREQMODE_POS
#endif
#ifndef USB_ARCS_TXCSRH_FRCDATATOG
#define USB_ARCS_TXCSRH_FRCDATATOG USB_TXCSRH_FRCDATATOG
#endif
#ifndef USB_ARCS_TXCSRH_ISO
#define USB_ARCS_TXCSRH_ISO USB_TXCSRH_ISO
#endif
#ifndef USB_ARCS_TXCSRH_ISO_MASK
#define USB_ARCS_TXCSRH_ISO_MASK USB_TXCSRH_ISO_MASK
#endif
#ifndef USB_ARCS_TXCSRL_FIFONOTEMPTY
#define USB_ARCS_TXCSRL_FIFONOTEMPTY USB_TXCSRL_FIFONOTEMPTY
#endif
#ifndef USB_ARCS_TXCSRL_FLUSHFIFO
#define USB_ARCS_TXCSRL_FLUSHFIFO USB_TXCSRL_FLUSHFIFO
#endif
#ifndef USB_ARCS_TXCSRL_SENDSTALL
#define USB_ARCS_TXCSRL_SENDSTALL USB_TXCSRL_SENDSTALL
#endif
#ifndef USB_ARCS_TXCSRL_SENTSTALL
#define USB_ARCS_TXCSRL_SENTSTALL USB_TXCSRL_SENTSTALL
#endif
#ifndef USB_ARCS_TXCSRL_SENTSTALL_MASK
#define USB_ARCS_TXCSRL_SENTSTALL_MASK USB_TXCSRL_SENTSTALL_MASK
#endif
#ifndef USB_ARCS_TXCSRL_TXPKTRDY
#define USB_ARCS_TXCSRL_TXPKTRDY USB_TXCSRL_TXPKTRDY
#endif
