CONFIG_LISA_DEVICE=y
CONFIG_LISA_GPIO_DEVICE=y
CONFIG_LISA_GPIOA=y
CONFIG_LISA_GPIOB=y
CONFIG_LISA_PWM=y

CONFIG_LISA_DISPLAY_DEVICE=y
CONFIG_LISA_RGB_DEVICE=y
CONFIG_LISA_DISPLAY_BUS_RGB=y

CONFIG_HEAP_SIZE=0x10000
CONFIG_PSRAM_HEAP_SIZE=0x500000
