add_subdirectory(alarm)
add_subdirectory(shell)
add_subdirectory(cmd)
add_subdirectory(usb)
add_subdirectory(sdemmc)
add_subdirectory(fs)
add_subdirectory(controller)
add_subdirectory(workqueue)
# add_subdirectory(ui)
add_subdirectory(kv)
add_subdirectory(battery)
add_subdirectory(button)
add_subdirectory(display)
# add_subdirectory(video)
add_subdirectory(config)
add_subdirectory(ble)
add_subdirectory(led)
add_subdirectory(power)