CONFIG_LOG=y
CONFIG_PRINTF_LOG_REDIRECT=y
CONFIG_BOOT=n
CONFIG_BOOT_HART=n
CONFIG_ARCS_CP_CORE=y
CONFIG_MEM_FLASH_BASE=0x08000000
CONFIG_MEM_FLASH_SIZE=0x00800000
CONFIG_MEM_PSRAM_BASE=0x28800000
CONFIG_MEM_PSRAM_SIZE=0x00100000
CONFIG_PSRAM_INIT=n

CONFIG_VADDR_REMAP_FW_VARIANT_NAME="CP"
CONFIG_VADDR_REMAP_FW_FLASH_OFFSET=0x20000
