# Components subdirectories
add_subdirectory(acomp)
add_subdirectory(core_spinlock)
add_subdirectory(dirent)
add_subdirectory(exclib)
add_subdirectory(ipclsf)
add_subdirectory(irq_proxy)
add_subdirectory(lis_algo)
add_subdirectory(lite_adc)
add_subdirectory(lite_dac)
add_subdirectory(ringbuf)
add_subdirectory(simple_box)
add_subdirectory(tinyusb-appclass)
add_subdirectory(lisa_evt_pub)
add_subdirectory(lisa_sntp)
add_subdirectory(lisa_shell)
add_subdirectory(sys_heap)
add_subdirectory(lisa_os)
add_subdirectory(lisa_kv)
add_subdirectory(lisa_http)
add_subdirectory(lisa_websocket)
add_subdirectory(lisa_log)
add_subdirectory(lisa_wifi)
add_subdirectory(lisa_bluetooth)
add_subdirectory(work_queue)
add_subdirectory(app_player)
