# Components subdirectories
add_subdirectory(acomp)
add_subdirectory(camera)
add_subdirectory(core_spinlock)
add_subdirectory(dirent)
add_subdirectory(display)
add_subdirectory(exclib)
add_subdirectory(flash)
add_subdirectory(ipclsf)
add_subdirectory(irq_proxy)
add_subdirectory(libs)
add_subdirectory(lis_algo)
add_subdirectory(lisa_evs)
add_subdirectory(lisa_porting)
add_subdirectory(lite_adc)
add_subdirectory(lite_dac)
add_subdirectory(ringbuf)
add_subdirectory(simple_box)
add_subdirectory(tinyusb-appclass)
add_subdirectory(touch)