//  File Name   : bt_modem_reg_venus.h
//  Description : C header file generated by Python script. Use C struct and union to define each 32-bit register.

#ifndef __BT_DRV_H__
#define __BT_DRV_H__


#include <stdbool.h>        // boolean definition
#include <stdint.h>

#include "bt_config.h"
#include "arcs_ap.h"
#include "ble_drv.h"

#include "bt_ctrl_top_reg.h"
#include "bt_modem_reg.h"
#include "bt_dm_reg.h"
#include "ble_reg.h"
#include "bt_reg.h"
/*
 * DEFINES
 *****************************************************************************************
 */

//#define IP_BT_CTRL                  ((BT_CTRL_TOP_RegDef *) BT_CTRL_BASE)
#define IP_BTMODEM                  ((BT_MODEM_RegDef *)BT_MODEM_BASE)
#define IP_BT_DM                    ((BT_DM_RegDef*) BASE_ADDR_BT_DM)
#define IP_BT                       ((BT_RegDef*) (BASE_ADDR_BT_BT))
#define IP_BLE                      ((BLE_RegDef*) (BASE_ADDR_BT_BLE))

#define CLK_SUB(clock_a, clock_b)     ((uint32_t)(((clock_a) - (clock_b)) & ((1L<<28) - 1)))

#define WRITE_REG_32(REG_ADDR, VAL)        (*(volatile uint32_t *)(REG_ADDR)) = (VAL)
#define READ_REG_32(REG_ADDR)              (*(volatile uint32_t *)(REG_ADDR))
#define CLEARMASK(START_POSTION, WIDTH)    (uint32_t)(((1<<WIDTH)-1)<<START_POSTION)
#define SETMASK(START_POSTION, VALUE)      (uint32_t)((VALUE)<<START_POSTION)

#define LS_SETF_REG(REG_ADDR, START_POSTION, WIDTH, VALUE)  \
        WRITE_REG_32((REG_ADDR), (((READ_REG_32(REG_ADDR)) & (~(CLEARMASK(START_POSTION, WIDTH)))) | (SETMASK(START_POSTION, VALUE))))

/*********************************MIDDLE FREQ********************************************/


#if (IC_BOARD==1)
#define MIDDLE_FREQ_1P5_M    0
#define MIDDLE_FREQ_1P25_M   0
#define MIDDLE_FREQ_750_K    1
#define ZERO_MIDDLE_FREQ     0
#else
#if (RF_ARCS_B0_SUPPORT)
#define MIDDLE_FREQ_1P5_M    0
#define MIDDLE_FREQ_1P25_M   0
#define MIDDLE_FREQ_750_K    1
#define ZERO_MIDDLE_FREQ     0
#elif (RF_MAX2830_SUPPORT)
#define MIDDLE_FREQ_1P5_M    1
#define MIDDLE_FREQ_1P25_M   0
#define MIDDLE_FREQ_750_K    0
#define ZERO_MIDDLE_FREQ     0
#endif
#endif

//#define ZERO_MIDDLE_FREQ     0

/*
dec2hex(2^17+2*(-freqShift)/fs)    clk:8MHZ
dec2hex(2^17+2*(-7.5e6)/8e6*2^16) = 0x1d000
*/
#define MIDDLE_FREQ_1MPHY_1P5_MHZ   0x1A000
#define MIDDLE_FREQ_1MPHY_1P25_MHZ  0x1D800
#define MIDDLE_FREQ_1MPHY_750_KHZ   0x1D000
#define MIDDLE_FREQ_1MPHY_0_KHZ     0x0
/*
dec2hex(2^17+2*(-freqShift)/fs)   clk:16MHZ
dec2hex(2^17+2*(-7.5e6)/16e6*2^16) = 0x1e800
*/

#define MIDDLE_FREQ_2MPHY_1P5_MHZ   0x1D000
#define MIDDLE_FREQ_2MPHY_1P25_MHZ  0x1D800
#define MIDDLE_FREQ_2MPHY_750_KHZ   0x1E800
#define MIDDLE_FREQ_2MPHY_0_KHZ     0x0
#define MIDDLE_FREQ_2MPHY_N1P25_MHZ  0x2800



// used to trx_en_isr
#define RXEN_OFF_STAT_BIT                   0x08
#define TXEN_OFF_STAT_BIT                   0x04
#define RXEN_ON_STAT_BIT                    0x02
#define TXEN_ON_STAT_BIT                    0x01


#define BLE_NORMAL_WIN_SIZE         (14)

#define MODEM_ALARM_LENGTH  5

#define HALF_SLOT_SIZE            625
#define TIME_TO_WRITE_MODEM_REG   240 // uint:half-us





/*
 * ENUMERATIONS DEFINITIONS
 ****************************************************************************************
 */

/// Rate information
enum
{
    /// 1 Mbits/s Rate
    BLE_RATE_1MBPS   = 0,
    /// 2 Mbits/s Rate
    BLE_RATE_2MBPS   = 1,
    /// 125 Kbits/s Rate
    BLE_RATE_125KBPS = 2,
    /// 500 Kbits/s Rate
    BLE_RATE_500KBPS = 3,

};

/// Mode
enum
{
    SCHEDULE_BLE,
    SCHEDULE_BT,
};

/// Reg config type
enum
{
    REG_TYPE_BT_MODEM = 0,
    REG_TYPE_BT_RF_IF = 1,
	REG_TYPE_BT_BLE   = 2,
	REG_TYPE_AON_CTRL = 3,
	REG_TYPE_BT_DM 	  = 4,
	REG_TYPE_BT_BT 	  = 5,
};

/*
 * STRUCTURE DEFINITIONS
 ****************************************************************************************
 */
#if (CHIP != vegap)
/// Alarm element structure
struct sch_alarm_tag
{
    /// List element for chaining in the Even Arbiter lists
    void *hdr;

    /// Timestamp of alarm expiry (in BT half-slots and half-us)
    struct
    {
        /// Integer part of the time (in half-slot)
        uint32_t hs;
        /// Fractional part of the time (in half-us) (range: 0-624)
        uint16_t hus;
    } time;

    /// Call back function invoked upon alarm expiry
    void (*cb_alarm)(struct sch_alarm_tag*);
};
#endif

struct BT_REG_INIT_ITEM
{
    uint16_t  reg_offset;
    uint8_t   start_bit_pos;
    uint8_t   bits_width;
    uint32_t  bits_value;
};
/*
 * GLOBAL VARIABLE DECLARATIONS
 *****************************************************************************************
 */
extern volatile CMN_BUSCFG_RegDef *CMN_SYS_NODFT_P;
extern volatile BT_CTRL_TOP_RegDef *BT_CNTL_P;
extern volatile AON_IOMUX_RegDef *AON_IOMUX_P;
extern volatile BT_MODEM_RegDef *BT_MODEM_P;
extern volatile CMN_SYSCFG_RegDef *CMN_SYS_P;
extern volatile BT_DM_RegDef *BT_DM_P;
extern volatile RFIF_RegDef *RFIF_P;
extern volatile BLE_RegDef *BT_BLE_P;
extern volatile BT_RegDef *BT_BT_P;


/*
 * FUNCTIONS DECLARATION
 ****************************************************************************************
 */
void lsip_modem_env_init(void);

void sleep_wakeup_reg_init(void);

void bt_drv_reg_init(uint8_t reset_state);

void modem_dac_clk_init(void);

void Bt_BootClock_Init();

void modem_reset(void);

void modem_cfg_phy_prog_cbk(uint8_t mode, uint8_t tx_rate, uint8_t rx_rate, uint8_t aux_rate, uint8_t edr, lsip_time_t time, uint8_t et_idx);

void extra_cfg(void);

void debug_diag_config(void);



#endif // __BT_MODEM_DRVFILE_H__


